README.md

This installs the Timber Library plugin into the plugins directory

Add composer install to setup instructions

---

composer.json
composer.lock

CMB2 is a dependency which needs to be pulled in with Composer.

Add the CMB2 dependency

---

src/css/style.css
style.css

For now I have updated both the style.css files in the project.

Updated stylesheets

---

classes/class-p4-taxonomy-campaign.php
tag.php
templates/tag.twig

Initial version of the new Tag Template. Use of new tag.twig template with custom markup.

Feature/1364 Tag page template

---

tag.php

Now that we use a const for the BLOCK_NAME we can retrieve them easier dynamically.

Get block names dynamically.

---

assets/js/main.js

Only the last 10 lines are new. Added tab indentation that's why whole file appears changed

Added load more click event for content four column load more button

---

tag.php

It does not have as many changes as it looks. Looks like that because I added some of the code inside and  if statement

Add footer menu items.

---

page.php
templates/blocks/header.twig
templates/tag.twig

Do not include the Header block's markup at all if the header_title is not set (e.g. in Front Page). Small possible bug fix. Markup fixes.

Presentation templates disparities

---

classes/class-p4-settings.php
functions.php

Added admin settings option for ACT, EXPLORE PAGE and ISSUE CATEGORY

PLANET-1411 Added settings for ACT, EXPLORE PAGE and ISSUE CATEGORY

---

.travis.yml

Discussed in hm slack Nov 28th.

Removed check for compatibility with php 5.6

---

functions.php

Add filters to dequeue devicepx and jitm jetpack scripts that are not needed by photon module.

Add filters to dequeue devicepx and jitm jetpack scripts.

---

single.php
templates/blocks/author_profile.twig
templates/comment_form/author_field.twig
templates/comment_form/comment_field.twig
templates/comment_form/email_field.twig
templates/comment_form/submit_button.twig
templates/comments_section.twig
templates/single.twig

Changed single post template according to latest markup.
Changed comment form elements according to latest markup.
Top background image is disabled for the moment.

Applied latest markup to post template.

---

functions.php

Remove jetpack related functions that became obsolete, since we are not going to use jetpack

Remove jetpack related functions.

---

templates/comment.twig
templates/single.twig

Latest markup for single post template.

---

classes/class-p4-settings.php

Issue fixed in Admin >> planet4 settings, copyright content html tags were not saving properly.

bugfix - copyright text with html was not inserting with html tags

---

page-templates/evergreen.php
templates/evergreen.twig

Intial version of the evergreen page template.

First version of evergreen page template

---

assets/js/main.js
assets/js/search.js
templates/search.twig

Changed css class names for load more buttons to be more self explanatory.

Changed css class names for load more buttons.

---

search.php

Enqueue search js file before page rendering.

Fix search page js to be enqueued correctly.

---

404.php
templates/404.twig

Enable search form input to use site's search functionality.

New content for 404 page. 

---

assets/js/custom.js

Removed old carousel header code from custom.js. 
Added new js implementation for carousel header in custom.js.

Added new implementation for carousel header js.

---

assets/js/main.js

Removed unnecessary code for publications slider that exists in custom js

Remove unnecessary code from main js (exists in custom js).

---

assets/js/main.js
functions.php

Fix Load more button not loading more rows in Content Four Column block. Fix Load more button not hiding as soon as it loads the last available row in Covers block.

Load more button fixes - Spreadsheet issues 

---

classes/class-p4-search.php
functions.php

Do not include attached photos to search results as separate results.… Currently, search for PDFs only. This also requires a change in the search plugin settings page under Media.

1575 search fixes - Spreadsheet issue 83

---

templates/404.twig

Improve 404 page presentation. 
Issue 88 from feedback spreadsheet.
Changes to 404 page template related to this [PR](https://github.com/greenpeace/planet4-presentation-layer/pull/159)

Removed some break lines from 404 page template to improve presentation.

---

tag.php

Small changes for issues noticed during changes for issue 140 in feedback spreadsheet.
Change css class for body in tag template to match other templates.
Add check for posts variable.

Change css class for body in tag template.

---

assets/js/search.js
functions.php

Fix clickability of thumbnail image and teaser text on the Search result items.

1575 search fixes - Spreadsheet issue 75

---

templates/404.twig

For issue 88 in feedback spreadsheet.

Small markup changes to 404 page.

---

templates/tease-search.twig

This fixes issue 132 from the sheet.

Add background gradient to actions search results

---

templates/search.twig

Have filter options show 0 results when no results were found.

1575 search fixes - Spreadsheet issue 162

---

page-templates/evergreen.php

Update Evergreen page template to include Issue/Campaigns on top as breadcrumb navigation.

Evergreen page update - Spreadsheet issue 166

---

templates/blocks/author_profile.twig
templates/single.twig

Issue [1641](https://jira.greenpeace.org/browse/PLANET-1641)

Remove author links from post template.

---

classes/class-p4-search.php

Lower Search page results limit to prevent big delays. This should not be a problem later on after we optimize Search page code and queries.

Search limit

---

assets/js/main.js

Separated logic for load more button click events in covers block.
Related to [Issue 1633](https://jira.greenpeace.org/browse/PLANET-1633)

Load more button functionality for covers block

---

templates/comment_form/submit_button.twig
templates/comments_section.twig

Based on the recent design changes at greenpeace/planet4-presentation-layer#197

Minor Posts design changes

---

single.php
templates/single.twig

Removed paragraph splitting in single post template. 
Updated markup in single post template.
Changes made regarding the below PR
[PR presentation layer](https://github.com/greenpeace/planet4-presentation-layer/pull/204)

Post template changes for take action boxout block

---

templates/tease-search.twig

Use thumbnail size for post's featured image in search results.

Search results posts' thumbnails

---

templates/tease-search.twig

according to https://github.com/greenpeace/planet4-presentation-layer/pull/210

markup changes

---

templates/single.twig

Markup changes from greenpeace/planet4-presentation-layer#213

Remove bootstrap grid from Post content

---

templates/page.twig

Markup changes from greenpeace/planet4-presentation-layer#216

Add default page template

---

templates/page.twig

Based on changes from greenpeace/planet4-presentation-layer#217

Remove unused container from page template

---

functions.php

Corrected the query to pick up correct pages

---

assets/js/custom.js
assets/scss/common/_carousel-header.scss
assets/scss/common/_happy-point-block.scss
assets/scss/pages/_page.scss
assets/scss/partials/_mixins.scss
assets/scss/partials/_variables.scss
functions.php

* Fixes x-large, to follow bootstrap's grid breakpoints.
* Adds support for wide blocks (eg. carousel-headers on page templates).

Fix wide blocks

---

functions.php

Fingerprinting the css and js files according to: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#invalidating_and_updating_cached_responses

Dynamically create version of css and js for handling cached files

---

functions.php

Sort the take action pages within the drop down selector by menu order.
Related to https://github.com/greenpeace/planet4-plugin-blocks/pull/204

1720 take action selector 2

---

classes/class-p4-search.php

Increase limit of search results to better test the search optimization and to have more accurate Filter counters.

1649 search optimize

---

assets/scss/common/_page-header.scss
assets/scss/pages/_evergreen.scss
assets/scss/pages/post/_article-content.scss

Related issue: [PLANET-1718](https://jira.greenpeace.org/browse/PLANET-1718)

Make evergreen page-header font tweaks global

---

assets/admin/js/edit_post.js
functions.php

Revert previous p4-page-type functionality in edit post page.
Reverts PR #246

Revert p4-page-type in edit post page

---

assets/scss/style.scss

Small fix to make sure the home background-image is expanding on large screens.

[Fixes PLANET-1780] Repeat home background for large screens

---

assets/scss/common/_covers.scss
assets/scss/pages/post/_article-content.scss

Based on [comment](https://jira.greenpeace.org/browse/PLANET-1581?focusedCommentId=61352&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-61352) at the relevant ticket.

Let cover cards adjust height dynamically on mobile

---

classes/class-p4-search.php

Issue [1752](https://jira.greenpeace.org/browse/PLANET-1752)

[PLANET-1752] Use only published posts/pages for searching in all cases.

---

assets/js/custom.js

Bug fix and some refactoring 🍰

Fix for the carousel header issue

---

classes/class-p4-search.php

Added also inherit status to include documents in search results.
Issue 1752

[PLANET-1752] Use only published posts/pages for searching in all cases 2

---

assets/js/custom.js

Scope for carousel function was not available in global context.

Bug Fix for 1594

---

assets/scss/pages/post/_article-content.scss

Adjust the post iframe heights. Especially the mobile one to be more dynamic and avoid scrolling.

[PLANET-1722] Adjust post iframes height to be more dynamic

---

assets/scss/pages/_take-action.scss

* Increase line-height proportionally

[PLANET-1659] Fix description font at Tasks block

---

assets/scss/pages/post/_author-block.scss

Fixed the issue of author block on safari 10 (by default it was working on safari 11).

Bug fix PLANET-1785

---

assets/scss/common/_tags-list.scss

[Issue 1697](https://jira.greenpeace.org/browse/PLANET-1697)

[PLANET-1697] Remove dot after last tag

---

templates/tease-search.twig

Handle long Document names to avoid misalignment in search results.

1648 handle long document names

---

templates/blocks/header.twig
templates/blocks/share_buttons.twig
templates/html-header.twig
templates/single.twig

I also moved share-buttons to a new block to avoid duplication of markup code.

[PLANET-1818] Add tracking code for Share buttons

---

assets/scss/common/_covers.scss

This is related to [this PR](https://github.com/greenpeace/planet4-plugin-blocks/pull/215)
[Issue 1633](https://jira.greenpeace.org/browse/PLANET-1633?focusedCommentId=60846&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-60846)

[PLANET-1633] Add css class for 3 covers option in covers block

---

functions.php

and raise the quality of resized images

PLANET-1820 Force wp to use imageMagick

---

assets/scss/common/_happy-point-block.scss

replaced background url for image with img tag.

Bug fix for PLANET-1586

---

assets/scss/pages/_take-action.scss
assets/scss/partials/_variables.scss

Reverts greenpeace/planet4-master-theme#300

Revert "[PLANET-1749] Adjust opacity and colors on Tasks blocks"

---

classes/class-p4-search.php
functions.php

Fix search weight not being applied in some cases (when sorting by most recent).

1831 fix search weight

---

classes/class-p4-search.php

Fix bug due to ignored stemming when searching for a word and we filter by Content Type.

1859 fix ignored stemming

---

assets/scss/common/_happy-point-block.scss

Position of iframe made absolute and stick to bottom of happy point container for mobile screen sizes.

PLANET-1797 Iframe positioning

---

assets/scss/pages/_take-action.scss

Based on design comment, to make the hover state darker.

Make numbers hover state more dark

---

assets/js/search.js

Use also in js the new name of checkbox class which does not collide with bootstrap class.

PLANET4-1881

---

assets/admin/js/edit_post.js

Fix bug in edit post page if p4 page types and categories mapping is not set.

PLANET-1877 Fix bug in edit post js for p4_page_type_mapping parsing

---

assets/js/custom.js

Fixing happy point on Tag Page for Large/XL,Medium and Small screen sizes.

PLANET-1878 Fixing broken happy point on Tag page

---

functions.php
page.php
single.php
tag.php
templates/html-header.twig

Add Facebook Open Graph and Twitter meta info for better sharing of Posts/Pages
(In the 1st commit had added info also for Campaign pages but removed it as it is not in the requirements).

PLANET-1888 open graph markup

---

assets/scss/common/_happy-point-block.scss

removed absolute positioning from happy point block wrap

PLANET-1878 Amendment in fixing broken happy point on Tag page

---

assets/js/custom.js
assets/js/search.js
assets/scss/common/_article-listing.scss
assets/scss/common/_content-four-column.scss
assets/scss/pages/search/_search-results.scss

* Adjust Articles block
* Adjust four column block
* Adjust Search block
* Fix search css indentation

[PLANET-1883] Make links behaviour consistent

---

assets/scss/pages/_page.scss

I did this change on the [Handbook](https://github.com/greenpeace/planet4-child-theme-handbook/pull/3) as requested instead.

Revert font change on pages

---

templates/search.twig

Apply translation for Sort options in search page.

PLANET-1891 search sort options translations

---

assets/js/custom.js

Setting the expiry string to 1 year in create cookie function.

PLANET 1858 Including expiry time in document cookie

---

assets/js/partials/carousel.js
assets/js/partials/post_action.js

These two changes were accidentally removed at a recent rebase:
* Carousel swipe
* Posts titles width
These have already been review at #343 and #339

Fix missing js code

---

assets/scss/pages/_take-action.scss

This is the css part of greenpeace/planet4-plugin-blocks#240

PLANET-1769 - Make mobile header on Tasks blocks clickable

---

404.php
classes/class-p4-settings.php
templates/404.twig

PLANET-1961 Added Planet4 setting option for 404 page

---

assets/js/partials/pubslider.js

Required for greenpeace/planet4-plugin-blocks#243

PLANET-1868 - Make 4 column blocks responsive

---

templates/html-header.twig

This reverts commit 8230972dc4689f9c43044073f9bd10e634a89c50.

Revert "Fix for PLANET-1956"

---

assets/js/search.js
classes/class-p4-search.php

[Issue 1983](https://jira.greenpeace.org/browse/PLANET-1983)

PLANET-1983 Hide search appended checkboxes

---

assets/js/main.js
assets/js/partials/comments_anchor.js
templates/comments_section.twig

The initial code was targeting the wrong element.

PLANET-1964 - Fix comments link anchoring

---

single.php
templates/single.twig

Issued fixed for -
1. As per post settings show/hide comments anchor link
2. On click of anchor scroll down to comment section

PLANET-1973 Bugfix/1973 number of comments in anchor

---

assets/scss/common/_footer.scss

Changed the copyright text color from #999999 to #e5e5e5 as per @tolen's suggestions.

PLANET-1995 Changing the copyright-text color.

---

assets/scss/modules/_buttons.scss
assets/scss/partials/_variables.scss

This reverts commit 5d632aa05db7ac0d7f5817a8b91a2431f98390fe.

Revert "PLANET 1702 CTA button: change orange background color"

---

assets/js/main.js
assets/js/partials/pubslider.js
assets/scss/common/_content-four-column.scss
functions.php

Small change to js in order to work with the updated custom rows functionality for Block:Content Four Column.
Related to https://github.com/greenpeace/planet4-plugin-blocks/pull/249

PLANET-1916 contentfourcolumn update

---

assets/js/partials/can_do_steps.js
assets/scss/pages/_take-action.scss

This is mostly css changes needed for greenpeace/planet4-plugin-blocks#259

PLANET-1998 - Vertical align action tasks

---

assets/scss/common/_happy-point-block.scss

Minor css change to force happy-point background image to adapt on all devices.

PLANET-2029 - Make Happy Point background image responsive

---

assets/js/search.js
classes/class-p4-search.php
templates/navigation-bar.twig

Adjust sort by date to work with ES. Adjust js code to make sure we get filtered and/or sorted results from ES when the initial search was performed via right-click. Same goes for when clearing filters.

PLANET-2027 search adjustments

---

classes/class-p4-sitemap.php
page-templates/sitemap.php
templates/sitemap.twig

Implement Sitemap page. Add Sitemap page in theme so that it can be accessed on /sitemap.

PLANET-1941 Feature/1941 sitemap

---

classes/class-p4-settings.php

Add wpml plugin hook to make planet4 settings multilingual.

PLANET-2067 Wpml - planet4 settings multilingual

---

assets/scss/common/_submenu.scss

These are the frontend changes needed for greenpeace/planet4-plugin-blocks#267

PLANET-2051 - Frontend implementation of Submenu variations

---

classes/class-p4-search.php
classes/class-p4-settings.php
templates/tease-search.twig

[Issue 2095](https://jira.greenpeace.org/browse/PLANET-2095)

PLANET-2095 Use planet4 settings for take action card button text in search results

---

assets/scss/common/_submenu.scss
assets/scss/pages/_sitemap.scss
assets/scss/partials/_variables.scss

* Change list items arrow
* Adapt color to design

PLANET-2051 - Submenu minor styling changes

---

functions.php

[Task 2125](https://jira.greenpeace.org/browse/PLANET-2125)

PLANET-2125 Append Credit to image caption for embedded images

---

templates/blocks/share_buttons.twig
templates/footer.twig

`sr-only` class hides the text while being accessible to screen readers.

PLANET-1506 - Add link text for screen readers on social media icons

---

assets/scss/common/_skip-links.scss
assets/scss/style.scss
templates/base.twig
templates/footer.twig

* Only visible on keyboard focus
* Implement Nav, Content and Footer links

PLANET-1505 - Add navigation skip links

---

tag.php

Show one row of publications (content four column block) in a tag page.

PLANET-2133 Show one row of publications in a tag page

---

assets/js/posts_report.js
classes/class-p4-post-report-controller.php
functions.php
posts_report.php
templates/posts_report.twig
underscore_templates/posts_reports.tpl.php

[Issue 1661](https://jira.greenpeace.org/browse/PLANET-1661)

PLANET-1661 First version of posts report page.

---

classes/class-p4-post-report-controller.php

Fix rest endpoints url for post report page

PLANET-1661 Use wordpress base url for rest endpoints.

---

classes/class-p4-search.php
functions.php

Complete adjustments for search page filtering via EP/ES. Fixed ambiguous column name error for post_mime_type in MySQL query. Increased http request timeout from 5 (default) to 10 seconds. Couple more checks+bug fixes that affected filtered search results.

PLANET-2028 adjust search filtering

---

assets/js/posts_report.js
classes/class-p4-post-report-controller.php

Fix spinner display in posts report page

Spinner in posts report page

---

classes/class-p4-sitemap.php
templates/sitemap.twig

Fix sitemap class methods returning null values.
[Issue 2191](https://jira.greenpeace.org/browse/PLANET-2191)

PLANET-2191 Sitemap fix

---

functions.php

Fixing the if statement, to check if the text field is empty, not the array

PLANET-2223 add copyright symbol if not exists

---

classes/class-p4-post.php
classes/class-p4-sitemap.php
tag.php

Consider current language when selecting content in theme functionality

PLANET-2229 consider language

---

classes/class-p4-post.php
page.php
single.php
templates/blocks/share_buttons.twig

Add functionality for having more information on pages/posts that have social media links. Twitter link now has updated 'text' and 'related' url parameters.

PLANET-2192 social share update

---

classes/class-p4-image-compression.php
functions.php

Extend the WP_Image_Editor_Imagick class that WP uses.

PLANET-2230 extend imagick

---

classes/class-p4-image-compression.php

Override imagick's thumbnail_image method.

PLANET-2231 override imagick method

---

assets/scss/common/_carousel.scss

A small adjustment to the changes already did in previous PR, just to make sure the the images inside the carousel are always responsive.

PLANET-2182 - Make Carousel image height responsive

---

assets/js/partials/app.js
assets/js/partials/cookies.js

PLANET-2240 Move cookies functions

---

assets/js/partials/happy_point.js

Regarding this PR https://github.com/greenpeace/planet4-plugin-blocks/pull/285

PLANET-2224 Decode iframe url passed to happy point block

---

functions.php

Generate images with unmodified code (using WP_Image_Editor_Imagick.

PLANET-2232 images unmodified code

---

functions.php

Generate images with modified code (using P4_Image_Compression).

PLANET-2233 images modified code

---

functions.php

Fix the automatically set featured-image functionality.

PLANET-2207 fix autofeatured image

---

classes/class-p4-cookies.php

Corrected function name for google login cookie hook.

Fix google login cookie hook

---

assets/scss/pages/_take-action.scss

A minor adjustment after Will's feedback

PLANET-2261 - Fix Task numbers positioning

---

assets/scss/style.scss

A small fix to restore Search results default font

PLANET-2377 - Use Roboto on Search results

---

functions.php

Add security hotfix to prevent file deletion when deleting an attachment and it's thumbnail.

PLANET-2408 security hotfix

---

assets/js/partials/carousel.js

[Issue 2390](https://jira.greenpeace.org/browse/PLANET-2390)

PLANET-2390 Carousel header js error when using single image

---

assets/js/partials/app.js

Reintroduce app js. 
Keep global assignment of jQuery to $

PLANET-2318 Global assignment of jQuery to $

---

templates/countries.twig

Add option for MENA office in the country selector.
* Needs https://jira.greenpeace.org/browse/PLANET-2464

PLANET-2456 add mena country selector

---

assets/scss/partials/_page-header.scss

This was one frontend change that happened after the cleanup and was lost on rebase. I'm re-adding it.

Fix breadcrumbs on Posts

---

assets/scss/partials/_footer.scss

Similar to greenpeace/planet4-plugin-blocks#321

Fix @supports nesting

---

templates/tease-search.twig

Escape alt attribute of img tags in search results

PLANET-2532 Escape alt attribute of img tags

---

functions.php
templates/navigation-bar.twig

because loco-translate was not picking the string from inside the aria-label parameter

Moved translatable string from twig to functions

---

classes/class-p4-post.php

Refactor get_social_accounts function in P4_Post to prevent php warnings

PLANET-2581 Fix php warnings in P4_Post

---

classes/class-p4-campaigns.php

After talking with requestor, we are switching to a row wide explanation for this setting

PLANET-2430 Changing way label appears

---

assets/scss/pages/_author.scss
assets/scss/pages/post/_author-block.scss
assets/scss/pages/search/_search-results.scss
backstop.js
templates/author.twig

* Fix colors on links
* Fix photo size
* Make author bio responsive
* Add authot url to regression tests
* Move bullets to tags

PLANET-2368 - Author: Design adjustments

---

assets/scss/pages/_author.scss
templates/author.twig

A small fix, not to stretch avatars on mobile.

PLANET-2368 - Fix author avatar for mobile

---

templates/single.twig

This should be fixed along with greenpeace/planet4-plugin-blocks#350

PLANET-2441 - Disable Author link on override

---

composer.json

Tested it locally and it seems to work fine

PLANET-2729 - Timber v1.8.1

---

classes/class-p4-search.php

Check sort_options parameter in search validation function

PLANET-2737 Search validation warning

---

templates/single.twig

Fixing a wrong var in the `single` Twig template.

PLANET-2614: Refined results page - URL fix.

---

templates/author.twig

Add support for HTML in Author's bio.

PLANET-2636: User Profile: allow for HTML in bio

---

functions.php

Fixed issue that prevented searching the WP Media Library in List view mode from returning results.

PLANET-2193 media search list

---

templates/404.twig

"Search" string was not translated.
Ref: https://jira.greenpeace.org/browse/PLANET-2505?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

PLANET-2505: Add translation for Search placeholder in 404 page.

---

classes/class-p4-post.php

Add more functionality in P4_Post class to make it easier to present data for those posts.

PLANET-2559

---

classes/class-p4-post.php

Reverts greenpeace/planet4-master-theme#624

Revert "PLANET-2559"

---

assets/scss/partials/_navbar.scss

Make that statement more explicit to avoid overrides.

PLANET-2903 - RTL: Make lang switcher padding more explicit

---

author.php
templates/tease-author.twig

Filtering out overridden posts in the query.

PLANET 2637: Author page

---

assets/scss/style.scss

Just found that while reading the code.
Nothing so serious.

minor comment typo 

---

author.php
classes/class-p4-user.php
templates/author.twig

Fix method-property name collision for author description which gets Timber confused.

PLANET-2944 hotfix author bio

---

classes/class-p4-control-panel.php

Ref: https://jira.greenpeace.org/browse/PLANET-2963
Adding Flush Cache & Check Cache options for Editor roles.
WP experts, please check if you think this can cause any side effects.

PLANET-2963: Explore how to give P4 editors the "flush cache" command

---

templates/blocks/author_profile.twig

Render html in author description for author profile template.

PLANET-2858 Render html in author description

---

templates/author.twig

- Added specificity to remove floats from share buttons.
- Removed unnecessary markup.
- Removed duplicated user info block.
Still need to check that fits design. Is there a guide where I can get designs for layouts?
In this case, in desktop the share buttons are top right, alone and away from the main content while description is below the picture.  I moved the buttons top of description under author photo, but need to be sure is that way and not the description that needs to be top right too.

PLANET-2857 User Profile: HTML not appearing correctly on mobile devices (M,S)

---

functions.php

Add source tag in wp_kses filter function

PLANET-2990 Audio player not working in posts

---

assets/js/search.js
classes/class-p4-master-site.php
classes/class-p4-search.php
templates/navigation-bar.twig
templates/search.twig

First commit for applying custom weight to search results depending on their Content Type (Action, Document, Page, Post).

PLANET-2058 es apply weight

---

classes/class-p4-campaigns.php

As per @kirdia's [comment](https://github.com/greenpeace/planet4-master-theme/pull/709#discussion_r254691296).

PLANET-3172 - Fix validation for tag redirection page

---

classes/class-p4-sitemap.php

Ref: https://jira.greenpeace.org/browse/PLANET-3211

PLANET-3211: Sitemap: About Greenpeace section shows up only 5 pages

---

classes/class-p4-master-site.php

See: https://jira.greenpeace.org/browse/PLANET-1068

PLANET-1068: Help button in admin that leads to GP specific content documentation

---

.circleci/config.yml

Adapt changes to docker-compose makefile done here https://github.com/greenpeace/planet4-docker-compose/commit/ee9ba1c1cba917f8f5bc671c03d55c9a5dceeaf0

Adapt docker compose make targets change

---

tests/test-category-page.php

Use real user before using posts factory for category page test
Fix for failing category page phpunit test
https://circleci.com/gh/greenpeace/planet4-master-theme/1404

Fix category page test

---

tests/test-open-graph.php

Use a real wordpress user before using posts factory for opengraph page test

Fix opengraph unit tests

---

assets/js/search.js
classes/class-p4-master-site.php
classes/class-p4-search.php
templates/navigation-bar.twig
templates/search.twig
templates/tease-search.twig

- Apply Lazy-loading on all cases to improve Search page loading time.
- Prevent unnecessary last ajax request from happening when all results have already loaded.
- Remove SearchWP methods from P4_Master_Site and move another one to P4_Search.

PLANET-3265 optimize search

---

.circleci/config.yml
phpunit.xml.dist

Change unit test ci jobs to use gcr.io/planet-4-151612/p4-unit-tests image

PLANET 3305 Use p4-unit-tests image for unit tests ci jobs 

---

classes/class-p4-campaign-exporter.php
exporter.php
functions.php

This is a repost of @mehulkaklotar's previous branch/PR: #683 . I rebased from the updated branch `planet-2561`. See below:
====
Ref: https://jira.greenpeace.org/browse/PLANET-2656
Import & Export Campaigns
Note: Wordpress Importer plugin is used for importing the xml file

Added Campagin post export functionality.

---

classes/class-p4-master-site.php
languages/planet4-master-theme-backend.pot
package-lock.json
page-templates/evergreen.php
page.php
templates/blocks/header.twig

Checkbox added to header to choose whether to open header link in new tab or not.
Ticket requested to add checkbox alongside Header Button Title but that wasn't feasible so it was added below.
Ref: https://jira.greenpeace.org/browse/PLANET-3256

Planet-3256: Add "Open in a new tab" for Page Header Link fields

---

templates/countries.json

Fix typo in Indonesia url. Add slash to urls to skip unnecessary redirection http requests.

PLANET-3332 countries json 2

---

classes/class-p4-search.php
templates/tease-search.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3311

PLANET-3311: Improve twig rendering times in search results

---

single-campaign.php

This has a matching PR in the blocks plugin: https://github.com/greenpeace/planet4-plugin-blocks/pull/529
Ref: https://jira.greenpeace.org/browse/PLANET-3398

PLANET-3398: CPP - Fix Secondary button colors across all blocks

---

.circleci/config.yml

Following changes in plugin block similar PR for php 7.3
https://github.com/greenpeace/planet4-plugin-blocks/pull/527

Add testing in php 7.3

---

single-campaign.php

Related [PR](https://github.com/greenpeace/planet4-plugin-blocks/pull/528)

PLANET-3387 CPP - Fix Take action block button color

---

single-campaign.php

https://jira.greenpeace.org/browse/PLANET-3394

PLANET-3394: CPP - Default template is using the Antarctica styleguide template

---

classes/class-p4-post-campaign.php

Ref: https://jira.greenpeace.org/browse/PLANET-3391

PLANET-3391: CPP - "Default template" missing from campaign template options dropdown

---

templates/countries.json

PLANET-3430: Fixed Slovenia spelling mistake in country selector

---

single-campaign.php

Ref: https://jira.greenpeace.org/browse/PLANET-3424

PLANET-3424: CPP - Logo color selector should update footer element colors too

---

classes/class-p4-dev-report.php

Improve report by linking to the branch history.

PLANET-3498 link to branch history

---

page.php
templates/single-page.twig

Ref: https://jira.greenpeace.org/browse/PLANET-2717

PLANET-2717 - Add support for password protected pages

---

templates/single-password.twig

Ref: https://jira.greenpeace.org/browse/PLANET-2715
Add some basic markup, copied from single template to make the form display properly. Also added some default classes to the form in order to follow p4 design.

PLANET-2715 - Wrap password protected Posts to template markup

---

classes/class-p4-post-campaign.php
single-campaign.php

Ref: https://jira.greenpeace.org/browse/PLANET-3393

PLANET-3393: CPP - Review color swatch options for the customizer

---

assets/js/search.js
classes/class-p4-search.php
templates/tease-search.twig

Change behavior of page type button in each search result item so that it leads to the respective page-type page instead of the relevant search result page (+ minor js code/comment fixes).

PLANET-2954 page type link

---

single-campaign.php

[JIRA 3420](https://jira.greenpeace.org/browse/PLANET-3420)

PLANET-3420 CPP - Fix "Open in a new tab" Page Header Link

---

classes/class-p4-metabox-register.php
page.php
single-campaign.php
templates/html-header.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3320

PLANET-3320: Add a new dataLayer field (Goal) on Form Block backend

---

exporter.php

Dynamic SQL construction in exporter.php replaced with prepared statement.

PLANET-3581 Code cleanup: Dynamic SQL Query

---

exporter.php

Fixed the prepared statement that was just added as it would only produce one result row even if more were expected.

PLANET-3518 Code cleanup: Dynamic SQL Query

---

classes/class-p4-elasticsearch.php

Customize out-of-the-box EP behavior to limit results down to full-text matches so that we do not get results that do not contain any of the search terms. When there is a phrase then we will get results that include all of the terms of the phrase (not only those who include the phrase as it is).
Reference https://www.elasticpress.io/blog/2019/02/custom-search-with-elasticpress-how-to-limit-results-to-full-text-matches/

PLANET-3507 full text search

---

classes/class-p4-settings.php
languages/planet4-master-theme-backend.pot

- Settings field descriptions renamed.
- .pot file updated and .po files synced
- Relating id's and variables changed to be consistent with field descriptions.

PLANET-1884 Rename description of settings fields

---

classes/class-p4-master-site.php

[JIRA 3551](https://jira.greenpeace.org/browse/PLANET-3551)

PLANET-3551 Fix GDPR consent tickbox issue on comment form

---

assets/scss/vendors/_usabilla.scss

Ref: https://jira.greenpeace.org/browse/PLANET-3595

PLANET-3595: Usabilla mobile buttons not "Sticky" on mobile screens - remove CSS

---

exporter-helper.php

[JIRA 3584](https://jira.greenpeace.org/browse/PLANET-3584)

PLANET-3584 Fix campaign exporter SQL creation

---

templates/tease-search.twig

Date removed from post teasers in search results.

PLANET-2723 date removed from search results

---

style-login.css

So you don't have to aim precisely for the text

Make the whole 'Login with Google' button clickable.

---

classes/class-p4-custom-taxonomy.php

The filter works with multiple languages and only shows the post types of the current language (tested with WPML only)

PLANET-3611 - Added a filter for post types in the admin post list

---

templates/html-header.twig

[Jira issue](https://jira.greenpeace.org/browse/PLANET-3615)
Adds meta name="title" to pages and posts

PLANET-3615 Add meta name="title" to pages and posts

---

classes/class-p4-master-site.php

Ref: https://jira.greenpeace.org/browse/PLANET-3593

PLANET-3593: Allow blocks in posts

---

templates/html-header.twig

[JIRA 3618](https://jira.greenpeace.org/browse/PLANET-3618)

PLANET-3618 Fix datalayer values encoding issue

---

classes/class-p4-master-site.php

[JIRA 3718](https://jira.greenpeace.org/browse/PLANET-3718)

PLANET-3718 Fix deprecated wp function(login_headertitle) notice error

---

assets/js/dashboard.js
classes/class-p4-control-panel.php
classes/class-p4-loader.php

Fix broken P4 Control Panel links. Ajax was failing. Update Check EN link to work once again after ENS API code was updated. Add check Elasticsearch connectivity link. Add Sync ES link. Remove old Check SearchWP indexer link.

PLANET-3726 fix control panel

---

classes/class-p4-metabox-register.php

Ref: https://jira.greenpeace.org/browse/PLANET-3744
This is a small counterpart for greenpeace/planet4-plugin-blocks#599

PLANET-3744 - Hide CTA links from page header on admin

---

templates/html-header.twig

Use post's excerpt for meta 'description' tag if it is populated.

PLANET-3801 Use post's excerpt for meta tag description

---

classes/class-p4-post-campaign.php

[JIRA 3824](https://jira.greenpeace.org/browse/PLANET-3824)

PLANET-3824 CPP - Rename elements in customizer

---

classes/class-p4-post-campaign.php

[JIRA 3817](https://jira.greenpeace.org/browse/PLANET-3817)

PLANET-3817 CPP - Add white color to CPP customiser

---

page-templates/evergreen.php

[JIRA 3808](https://jira.greenpeace.org/browse/PLANET-3808)

PLANET-3808 Fix password-protected content issue on evergreen page template

---

templates/html-header.twig

[JIRA 3809](https://jira.greenpeace.org/browse/PLANET-3809)

PLANET-3809 Hide meta fields for password protected content

---

templates/countries.json

Ticket: https://jira.greenpeace.org/browse/PLANET-3865

PLANET-3865 Landing Page: Minor text changes

---

admin/js/cmb2_form_validation.js
admin/js/posts_report.js
assets/js/cookies.js
assets/js/search.js
assets/js/single.js

There were some leftovers in the previous pass for the same task.
https://jira.greenpeace.org/browse/PLANET-3901

PLANET-3901: JS: Unify closure method on remaing js code

---

classes/class-p4-metabox-register.php

[JIRA 3868](https://jira.greenpeace.org/browse/PLANET-3868)

PLANET-3868 Fix campaign datalayer value reset issue

---

classes/class-p4-settings.php

A small text change after Julia's feedback.

PLANET-3864 - Minor text change for Google Optimize

---

templates/countries.json

Ref: https://jira.greenpeace.org/browse/PLANET-3873

PLANET-3873 Update countries URL for less redirections

---

classes/class-p4-post-campaign.php
composer.lock
single-campaign.php
templates/footer.twig
templates/footer_min.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3908

PLANET-3893: Investigate: Customize footer for CPP pages

---

.circleci/config.yml

Switch CI images to docker hub

Dockerhub repositories

---

templates/blocks/header.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3881

PLANET-3881: Password-Protected pages have header fields appearing

---

classes/class-p4-master-site.php

Temporarily remove master-theme's `parent style` to fix a couple of issues found in the admin.

(No ticket): Remove parent-style from admin side.

---

classes/class-p4-metabox-register.php

Ref: https://jira.greenpeace.org/browse/PLANET-3874

PLANET-3874 Enable Opengraph box on Campaign post type

---

classes/class-p4-post-campaign.php
single-campaign.php
templates/footer.twig
templates/footer_min.twig

[JIRA 4034](https://jira.greenpeace.org/browse/PLANET-4034)
**Note:** The existing campaigns need to edit once we release the new footer item option, else the campaign footer will display blank due to old footer social urls fields.

PLANET-4034 CPP - Add full configuration options for social media icons

---

classes/class-p4-post-campaign.php

Ref: https://jira.greenpeace.org/browse/PLANET-4036
Note: in Gabor's list, there is a missing field, `Footer theme`, I placed it before the footer social links, I'll ask Gabor in the ticket.

PLANET-4036: CPP - Reorder customizer options in the backend

---

classes/class-p4-campaign-importer.php
exporter-helper.php
exporter.php

Escape table names in various sql queries / Fix rips warnings

PLANET-4004 Fix rips warnings

---

single-campaign.php

[Issue](https://jira.greenpeace.org/browse/PLANET-4025)

PLANET-4025 Fix password protected campaigns

---

classes/class-p4-post-campaign.php

Ref: https://jira.greenpeace.org/browse/PLANET-4041
We got the confirmation to enable Campaigns on the backend menu.

PLANET-4041 Show Campaigns menu on backend

---

classes/class-p4-metabox-register.php
page.php
templates/blocks/header.twig

The default 'Hide page title' checkbox will be unchecked. All existing pages title will be default visible. 
[JIRA 3875](https://jira.greenpeace.org/browse/PLANET-3875)

PLANET-3875 Allow user to hide page title on post type 'Page'

---

single.php

- Strip the take action boxout block from the post content and add it to where the current shortcode would be added.

PLANET-4023 Allow "Take Action" boxout in Posts 

---

classes/class-p4-metabox-register.php

- change the order to post_title for the dropdown to select a take action boxout page in posts

PLANET-4024 order act page select dropdown by post title

---

classes/class-p4-post.php
templates/author.twig
templates/blocks/header.twig
templates/blocks/share_buttons.twig
templates/html-header.twig
templates/single.twig

Ref: https://jira.greenpeace.org/browse/PLANET-3992
Add a function for constructing all share button metadata.

PLANET-3992 Use opengraph metadata for share buttons

---

classes/class-p4-post-campaign.php

[JIRA 4084](https://jira.greenpeace.org/browse/PLANET-4084)

PLANET-4084 CPP - Add campaign import capability to Campaigner role

---

templates/countries.json

PLANET-4112 Add GP Peru site to global navigation

---

classes/class-p4-activator.php
classes/class-p4-campaigner.php
classes/class-p4-loader.php
classes/class-p4-post-campaign.php

Extract campaigner role functions to a new class - P4_Campaigner
Add P4_Activator class to run actions on theme activation/deactivation hooks
Load P4_Activator when theme is switched

PLANET-4050 Refactor campaigner role and capabilities

---

classes/class-p4-post-campaign.php

- arg added in order for gutenberg to work in campaigns post type.

PLANET-4131 add show_in_res arg to allow block editor in campaigns

---

classes/class-p4-post-campaign.php
single-campaign.php

Ref: https://jira.greenpeace.org/browse/PLANET-4061

PLANET-4061: Campaign Page: Accessibility of Climate Emergency theme

---

classes/class-p4-campaigns.php
classes/class-p4-taxonomy-campaign.php
single.php
tag.php
templates/single.twig
templates/tag.twig

[JIRA 4070](https://jira.greenpeace.org/browse/PLANET-4070)
Convert autogenerated shortcake shortcodes into new Gutenberg blocks.

PLANET-4070 Convert auto-generated shortcakes to Gutenberg

---

templates/blocks/header.twig

Ref: https://jira.greenpeace.org/browse/PLANET-4357
This the counterpart of greenpeace/planet4-plugin-blocks#665

PLANET-4357 Enable skewed header background for the plastic campaign

---

classes/class-p4-metabox-register.php

https://jira.greenpeace.org/browse/PLANET-4289

PLANET-4289 add new datalayer campaign and basket values

---

templates/countries.json

Ref: https://jira.greenpeace.org/browse/PLANET-4365
- 中文简体 (link to China mainland: https://www.greenpeace.org.cn/)
- 繁體 (link to Hong Kong: https://www.greenpeace.org/hongkong/)
- 正體 (link to Taiwan: https://www.greenpeace.org/taiwan/)
- 한국어 (link to Korea: https://www.greenpeace.org/korea/ )
- English (link to GPEA English
website:https://www.greenpeace.org/eastasia/)

Country list: Consolidate East Asia entries

---

templates/html-header.twig

See https://yoast.com/robots-meta-changes-for-google/

Add robots meta tag

---

classes/class-p4-master-site.php

Ref: https://jira.greenpeace.org/browse/PLANET-4371

PLANET-4371: Cookie notice background image is not displayed

---

classes/class-p4-control-panel.php
classes/class-p4-master-site.php

[JIRA 4408](https://jira.greenpeace.org/browse/PLANET-4408)

PLANET-4408 Fix WP-Dashboard 'Check Engaging Networks' option

---

templates/countries.json

[JIRA 4411](https://jira.greenpeace.org/browse/PLANET-4411)

PLANET-4411 Fix country selection url for Austria

---

classes/class-p4-campaign-importer.php
exporter-helper.php

[JIRA 4402](https://jira.greenpeace.org/browse/PLANET-4402)
The bug/planet-4402 is pinned on `sagardev` instance.
You can test it [here](https://k8s.p4.greenpeace.org/sagardev/wp-admin/edit.php?post_type=campaign). 
Campaign post created on `sagardev` instance -
https://k8s.p4.greenpeace.org/sagardev/campaign/image-gallery-test/
Exported above campaign and imported on GPI staging -
https://release.k8s.p4.greenpeace.org/international/?post_type=campaign&p=958&preview=true

PLANET-4402 Fix CPP image export issue

---

author.php
classes/class-p4-post.php
templates/author.twig
templates/blocks/meta_fields.twig
templates/html-header.twig

[JIRA 4113](https://jira.greenpeace.org/browse/PLANET-4113)
- Updated open graph data on author profile page
- Fix social share button links on author profile page

PLANET-4113 Added open graph meta fields on author profile page

---

assets/src/scss/pages/search/_search-results.scss
templates/tease-search.twig

- Changed styling for campaign search.
- Applied the same styling to Archive search.
Ref: https://jira.greenpeace.org/browse/PLANET-4432

PLANET-4432 Search results: Add label to P3 Archives and Campaign pages

---

assets/src/scss/pages/search/_search-results.scss

Ref: https://jira.greenpeace.org/browse/PLANET-4552

PLANET-4552 Search: CTA buttons are broken

---

classes/class-p4-master-site.php
templates/html-header.twig

[JIRA 4591](https://jira.greenpeace.org/browse/PLANET-4591)

PLANET-4591 Add dataLayer param - signedIn and visitorType

---

templates/countries.json

[JIRA 4607](https://jira.greenpeace.org/browse/PLANET-4607)

PLANET-4607 Country Selector - remove trailing slash in GPAP address

---

single.php

[JIRA 4597](https://jira.greenpeace.org/browse/PLANET-4597)

PLANET-4597 Fix campaign dataLayer script on P4 Posts

---

templates/countries.json

[JIRA 4644](https://jira.greenpeace.org/browse/PLANET-4644)

Fix GP Slovakia url

---

assets/src/js/search.js
classes/class-p4-search.php

* ... as a way to determine which archives to show next.
* hide show more controls if less than results per page is returned.

PLANET-4523 Send url of last seen archive from frontend

---

assets/src/scss/pages/_page.scss
templates/single-campaign.twig

Ref: https://jira.greenpeace.org/browse/PLANET-4524

PLANET-4524: CPP: Rogue space at top of page

---

assets/src/scss/pages/_page.scss
assets/src/scss/pages/post/_article-content.scss

Needed to make change in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/195
work.

PLANET-4441 Fix image alignment

---

classes/class-p4-settings.php

[JIRA 4508 ](https://jira.greenpeace.org/browse/PLANET-4508)

PLANET-4508 Add 'More info' link in Archive result control setting text

---

classes/class-p4-campaign-importer.php

Code refactor in import campaign functionality.

PLANET-4659 CPP import - Replace regex with parse_block()

---

classes/class-p4-campaign-importer.php
exporter-helper.php

Code refactor in export campaign functionality.

PLANET-4456 CPP export - Replace regex with parse_block()

---

templates/cookies.twig

Ref: https://jira.greenpeace.org/browse/PLANET-4486
Related styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/35

PLANET-4486: MENA: Cookies text and buttons are not aligned or resized properly (Tablet and Desktop)

---

templates/countries.json

Ref: https://jira.greenpeace.org/browse/PLANET-4690

PLANET-4690 Change Turkey language to Türkçe in Coutry selector

---

assets/src/js/app.js
assets/src/js/lazyload.js
classes/class-p4-master-site.php
templates/tease-post.twig
templates/tease-search.twig
templates/tease-taxonomy-post.twig
tests/test-category-page.php

Ref: https://jira.greenpeace.org/browse/PLANET-4532
More details in the blocks counterpart: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/186

PLANET-4532: Perf: Investigate lazy-loading solution across P4 (incl. all browsers)

---

campaign_themes/antarctic.json
campaign_themes/arctic.json
campaign_themes/climate.json
campaign_themes/default.json
campaign_themes/forest.json
campaign_themes/oceans.json
campaign_themes/oil.json
campaign_themes/plastic.json
classes/class-p4-post-campaign.php

* Change all hex codes to lowercase.
* Add some colors that are used in live campaigns

PLANET-4603 Fixes after testing

---

classes/class-p4-search.php

- Replaced OpenSearch retrieval of archived data with ElasticSearch.
- Docs to set up ElasticSearch index and documents: https://documenter.getpostman.com/view/7448731/SzKN12Ha

PLANET-4722 Integrate Elastic Search database with search code

---

classes/class-p4-post-campaign.php

[JIRA 4775](https://jira.greenpeace.org/browse/PLANET-4775)
eg. https://k8s.p4.greenpeace.org/test-atlas/campaign/test-campaign-footer-link-color-green/

PLANET-4775 P4CG - Fix wrong green color on footer links

---

single-campaign.php
templates/base.twig
templates/single-campaign.twig

Was more in there for demo purposes, maybe we'll add them again later.
https://jira.greenpeace.org/browse/PLANET-4712

PLANET-4712 Remove breadcrumbs

---

exporter-helper.php
exporter.php

[JIRA 4751](https://jira.greenpeace.org/browse/PLANET-4751)

PLANET-4751 Refactor campaign exporter module

---

assets/src/js/app.js
assets/src/js/cssvarsponyfill.js
classes/class-p4-master-site.php
classes/class-p4-post-campaign.php
templates/css-variables.twig

This is the minimum needed to close the mentioned ticket, I engaged in a few more refactors that might be out of scope, so I moved them to a separate branch, so we can close this ticket in this sprint and keep working on refactoring the campaigns code with proper testing for the next sprint.
Ref: https://jira.greenpeace.org/browse/PLANET-4745
This also needs:
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/218
https://github.com/greenpeace/planet4-plugin-gutenberg-engagingnetworks/pull/42

PLANET-4745: Campaigns CSS: EN form block title and CTA style

---

classes/class-p4-master-site.php

Ref: https://jira.greenpeace.org/browse/PLANET-4821

PLANET-4821: Gallery block: only first image is being displayed

---

single-campaign.php

I had changed accessing the post meta from `$post->custom` to `get_post_meta` but didn't transform the array in all cases.

PLANET-4840 Fix campaign meta

---

exporter-helper.php

[JIRA 4860](https://jira.greenpeace.org/browse/PLANET-4860)
Sentry Issue: [908](https://sentry.greenpeace.org/greenpeace/planet4/issues/908/)

PLANET-4860 Fix a bug catch by Sentry Issue: 908

---

classes/class-p4-metabox-register.php
classes/class-p4-post.php

Ref: https://jira.greenpeace.org/browse/PLANET-4844

PLANET-4844: Pages: Open Graph/Social fields not pulled

---

templates/html-header.twig

This is needed in for Optimize to load properly
Ref: https://jira.greenpeace.org/browse/PLANET-4880

PLANET-4880 Increase GTM timeout to 4000

---

templates/navigation-bar_min.twig

Ref: https://jira.greenpeace.org/browse/PLANET-4833
This depends on the styleguide PR: 
https://github.com/greenpeace/planet4-styleguide/pull/41

PLANET-4833: P4CG - Add language selector to minimal navigation

---

campaign_themes/default.json

[No issue]: Fix JSON file for the Default campaign theme

---

classes/class-p4-metabox-register.php

[PLANET-4889](https://jira.greenpeace.org/browse/PLANET-4889)

PLANET-4889 Added new value to campaign dataLayer dropdown (Covid-19)

---

templates/html-header.twig

Ref: https://jira.greenpeace.org/browse/PLANET-4858

PLANET-4858 Add gPlatform var to dataLayer to track platform source

---

templates/blocks/share_buttons.twig

Ref: https://jira.greenpeace.org/browse/PLANET-4906
Styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/43

PLANET-4906: Create UI for Whatsapp share button

---

classes/class-p4-post-campaign.php
single-campaign.php
templates/blocks/site_logo.twig

Note: despite of the issue description, I'm fixing other defaults and rules in this PR.
Ref: https://jira.greenpeace.org/browse/PLANET-4820
Styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/42
Blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/247

PLANET-4820: P4CG - Footer color should not be applied when "Main website navigation" is selected

---

classes/class-p4-context-controller.php
page-templates/evergreen.php
page.php
single-campaign.php
single.php

- Made common class to remove duplicate code for setting context
- Added the fallback field setting to evergreen pages
Ref: https://jira.greenpeace.org/browse/PLANET-4920

PLANET-4920 Evergreen Pages: Some Opengraph metadata are empty

---

classes/class-p4-analytics-values.php
classes/class-p4-loader.php
classes/class-p4-metabox-register.php
classes/class-p4-settings.php
classes/class-p4-smartsheet-client.php
classes/class-p4-smartsheet.php
page.php
single-campaign.php
single.php
templates/html-header.twig

* Add client for SmartSheet API.
* Get API key from config, if it's not there from environment variable
`SMARTSHEET_API_KEY`.
* Get global standards values from the API response (sheet ID still
hardcoded).
* Cache the global standards values for 5 minutes.
* Fall back to the hardcoded values if the API request fails.

PLANET-4855 Get Global Standards values from a SmartSheet

---

classes/class-p4-analytics-values.php
classes/class-p4-metabox-register.php
classes/class-p4-settings.php
page.php
single-campaign.php
single.php
templates/html-header.twig

[JIRA 4859](https://jira.greenpeace.org/browse/PLANET-4859)
- Get local project smartsheet id from Planet4 settings, if it's not there from environment variable
`ANALYTICS_LOCAL_SMARTSHEET_ID`.
The change are available for testing at [here](https://k8s.p4.greenpeace.org/test-pluto/test-local-project-id-analytics-tracking-field/)

PLANET-4859 Pull "Local Project" values from each NRO smartsheet and pass it to DataLayer

---

classes/class-p4-search.php
search.php

[JIRA 4738](https://jira.greenpeace.org/browse/PLANET-4738)

PLANET-4738 Fix Sentry Issue: PLANET4-2J

---

classes/class-p4-analytics-values.php

This one slipped through, had made this change while testing and forgot
to remove it before committing.

PLANET-4855 Fix wrong hardcoded value

---

classes/class-p4-user.php
templates/single.twig

[JIRA 4953](https://jira.greenpeace.org/browse/PLANET-4953)

PLANET-4953 Fix Sentry Issue: PLANET4-D0

---

classes/class-p4-smartsheet-client.php

Catch invalid api responses so that this doens't crash the editor

PLANET-4967 Catch invalid Smartsheet credentials

---

assets/src/scss/pages/search/_search-results.scss

- Show the excerpt not only from small and up, but always in search results.
Ref: https://jira.greenpeace.org/browse/PLANET-4163

PLANET-4163 Include excerpt in mobile search results

---

classes/class-p4-context.php
classes/class-p4-metabox-register.php

[JIRA 4968](https://jira.greenpeace.org/browse/PLANET-4968)

PLANET-4968 Hide Scope dropdown from Analytics & Tracking fields

---

assets/src/scss/pages/_404.scss
assets/src/scss/pages/_evergreen.scss
assets/src/scss/pages/post/_comments-block.scss
assets/src/scss/pages/post/_post.scss
assets/src/scss/pages/search/_filter-modal.scss
assets/src/scss/pages/search/_filter-sidebar.scss
assets/src/scss/pages/search/_search-bar.scss
campaign_themes/antarctic.json
campaign_themes/arctic.json
campaign_themes/climate.json
campaign_themes/default.json
campaign_themes/forest.json
campaign_themes/oceans.json
campaign_themes/oil.json
campaign_themes/plastic.json

Ref: https://jira.greenpeace.org/browse/PLANET-4919
Blocks counterpart: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/249

PLANET-4919: Ensure all variables & rules work as expected in the Sidebar.

---

templates/footer.twig

[JIRA 4971](https://jira.greenpeace.org/browse/PLANET-4971)

PLANET-4971 Add data-attributes on footer link

---

classes/class-p4-master-site.php

- Changed auto excerpt generator to first look for a paragraph to get excerpt from, and then the rest of the content.
Ref: https://jira.greenpeace.org/browse/PLANET-4700

PLANET-4700 TA boxout excerpt is copied to post excerpt

---

assets/src/js/header.js
author.php
classes/class-p4-master-site.php
templates/blocks/site_logo.twig
templates/navigation-bar.twig

[JIRA 4970](https://jira.greenpeace.org/browse/PLANET-4970)

PLANET-4970 Add GTM tracking data attributes on navigation bar

---

classes/class-p4-analytics-values.php
classes/class-p4-settings.php

PLANET-4967 Read Smartsheet API key from config file

---

classes/class-p4-master-site.php

- modified regex and added null coalesce for excerpt

planet-4700-fix fixed null error excerpt preg match

---

templates/search.twig
templates/tease-search.twig

[JIRA 4969](https://jira.greenpeace.org/browse/PLANET-4969)

PLANET-4969 Add GTM tracking data attributes on search page

---

campaign_themes/antarctic.json
campaign_themes/arctic.json
campaign_themes/climate.json
campaign_themes/default.json
campaign_themes/forest.json
campaign_themes/oceans.json
campaign_themes/oil.json
campaign_themes/plastic.json
classes/class-p4-master-site.php

See https://jira.greenpeace.org/browse/PLANET-5037
- Removed campaigns custom spreadsheet colors
- Added css variables to allowed properties

PLANET-5037 Spreadsheet colors

---

classes/class-p4-settings.php

- Re-arrange options in p4 settings.

PLANET-4641 P4 settings: reorder options

---

assets/src/scss/pages/post/_author-block.scss

See https://jira.greenpeace.org/browse/PLANET-5035

PLANET-5035 Fix post author block image width in medium screens

---

assets/src/scss/pages/_evergreen.scss

See https://jira.greenpeace.org/browse/PLANET-4511
There is also a PR for this in gutenberg-blocks repo: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/281

PLANET-4511 Update separator block styles for evergreen template

---

composer.json

[JIRA 4868](https://jira.greenpeace.org/browse/PLANET-4868)

PLANET-4868 Remove duplicate Timber requirement

---

classes/class-p4-search.php

* If a term was deleted but ElasticSearch still had the old tag, then
this would cause a fatal error because the term was fetched and then
assumed it existed, causing a WP_Error to be used as a string.
* Return early if there are no posts.

PLANET-5145 Fix deleted terms crashing search

---

assets/src/js/app.js
assets/src/js/enhancedDonateButton.js
classes/class-p4-master-site.php
classes/class-p4-settings.php
templates/navigation-bar.twig

[JIRA 5081](https://jira.greenpeace.org/browse/PLANET-5081)

PLANET-5081 Add option for enhanced mobile Donate button in settings

---

classes/class-p4-master-site.php

Added filter to check if user has greenpeace email, and warns them to login with google

PLANET-4891 Enforce Google Login for users with greenpeace.org email

---

tag.php

PLANET-5215 Add action hook to allow custom tag page behavior

---

classes/class-p4-master-site.php

- Added check for aliases
- Don't enforce google login if this check is successful

PLANET-5233 Don't enforce Google login on aliases

---

assets/src/scss/pages/_404.scss
assets/src/scss/pages/_evergreen.scss
assets/src/scss/pages/post/_article-content.scss
assets/src/scss/pages/post/_comments-block.scss
assets/src/scss/pages/post/_comments-form.scss
assets/src/scss/pages/post/_post.scss
assets/src/scss/pages/search/_filter-modal.scss
assets/src/scss/pages/search/_filter-sidebar.scss
assets/src/scss/pages/search/_search-bar.scss
assets/src/scss/pages/search/_search-results.scss

Just changing some grey shades.
Ref: https://jira.greenpeace.org/browse/PLANET-5082
Related PRs:
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/312

PLANET-5082: Accessibility change red based greys to blue based ones.

---

templates/search.twig
templates/tease-search.twig

Related to [JIRA 5202](https://jira.greenpeace.org/browse/PLANET-5202)
Task -
- Updated the `data-ga-action` values on the Search Page as below
Category Filter > Post Type Filter
Issue Filter > Category Filter
Category Tag > Post Type Tag
Testing -
- Check the `data-ga-action` data attributes values at [here](`data-ga-action`), it should be as per the above

PLANET-5202 Update the data-ga-action on the Search Page

---

assets/src/scss/pages/_page.scss
assets/src/scss/pages/post/_article-content.scss
assets/src/scss/pages/post/_author-block.scss

See https://jira.greenpeace.org/browse/PLANET-5116 (UAT already passed)
- Corresponding styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/61
- Corresponding plugin-gutenberg-blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/299

Planet 5116 - Fix block vertical spacing

---

assets/src/js/external_links.js

- Added a check in external_links.js to not add external link icon if href ends in .pdf

PLANET-5231 On links with PDF icon change colour and remove Leaving Site icon

---

admin/js/posts_report.js
src/PostReportController.php
templates/posts_report.twig
underscore_templates/posts_reports.tpl.php

Related to [JIRA 4795](https://jira.greenpeace.org/browse/PLANET-4795)
Task 
- Add campaign post type in post report page.
- Add string translations to texts
- change the `To` value's appending time value from `'T00:00:00'` => `'T23:59:59'` (This will show records falling on `To` date )

PLANET-4795 Add 'Campaign' Page types to posts report

---

assets/src/js/cookies.js

Just a slightly more sane value than 1 year :D

Decrease cookie expiration value for last visited NRO

---

templates/single.twig

Ref. https://jira.greenpeace.org/browse/PLANET-5351

PLANET-5351 Add "Post Type Tag" data attribute on post header

---

src/MasterSite.php

Ref. [JIRA #5296](https://jira.greenpeace.org/browse/PLANET-5296)
**Issue :**
- The TAB is no longer visible only when the viewer is logged in to P4.
- When not logged in to P4 and viewing the Post incognito the TAB is still present.
- It isn't until the cache is purged that the TAB disappears.
**Fix :**
- On change of act page status purge the cache of related posts which uses act page in TAB block
**Testing :**
- Add a [new TA page](https://k8s.p4.greenpeace.org/test-venus/wp-admin/post-new.php?post_type=page)
- Add/edit post and select newly added TA page from "Take Action Page Selector" dropdown at bottom of post or add a "Take Action Boxout" block from P4 blocks with new TA page
- Check the new post on frontend, the TAB is visible as intended
- Now change the status of TA page to …

PLANET-5296 Flush TAB posts cache if act page status changes

---

assets/src/js/country_select.js

ref. [JIRA 5206](https://jira.greenpeace.org/browse/PLANET-5206)
eg. https://k8s.p4.greenpeace.org/test-titan/

PLANET-5206 Add data attributes on Country Selector

---

templates/author.twig
templates/taxonomy.twig
templates/tease-author.twig
templates/tease-taxonomy-post.twig

Ref. [JIRA 5414](https://jira.greenpeace.org/browse/PLANET-5414)

PLANET-5414 Add data attributes on post type page Articles Lists

---

assets/src/js/cookies.js

Added secure and SameSite attributes to cookie depending on site protocol

PLANET-5320 P4 Cookies should implement the 'Secure' attribute

---

src/Settings.php

Added to enforce cookies textbox description

PLANET-5450 Add a note to the "Cookies Text" section (Planet 4 Backend)

---

templates/blocks/header.twig
templates/single.twig
templates/sitemap.twig
templates/tag.twig
templates/tease-author.twig
templates/tease-search.twig
templates/tease-taxonomy-post.twig
tests/test-category-page.php

Added span with aria label for improved hashtag accessibility in master theme
Fixes greenpeace/planet4#71

PLANET-5229 Hashtags Accessibility

---

templates/blocks/meta_fields.twig
templates/blocks/share_buttons.twig

Contributor PR #1216  
- Squash the commits into one commit
- Rename the commit message

PLANET-5441 Fix hashtag cuts off text for social media sharing

---

assets/src/js/country_select.js
templates/base.twig
templates/navigation-bar.twig

Improved accessibility of Country List, Search Bar and Skip To Links.

PLANET-5211 Home page Accessibility: Navigation bar and "Skip to..." links

---

assets/src/scss/pages/_author.scss
templates/author.twig

Improved accessibility of the author bio page

PLANET-5254 Author page accessibility

---

templates/footer.twig
templates/footer_min.twig

Added role="text" to parts of the footer.

PLANET-5253 Footer Accessibility

---

assets/src/scss/pages/_404.scss
assets/src/scss/pages/post/_comments-form.scss
assets/src/scss/pages/search/_search-bar.scss
assets/src/scss/pages/search/_sort-filter.scss

See https://jira.greenpeace.org/browse/PLANET-5613
- [styleguide](https://github.com/greenpeace/planet4-styleguide/pull/82)
- [gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/433)

PLANET-5613 Add border-radius to all form fields

---

package-lock.json
package.json
webpack.config.js

Plugin to transform CSS variables shorthand syntax. Same changes as in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/410/files

Include dash dash plugin in webpack

---

page.php
single-campaign.php
single.php
templates/base.twig
templates/blocks/header.twig
templates/html-header.twig
templates/single-page.twig
templates/single-password.twig

[JIRA 5286](https://jira.greenpeace.org/browse/PLANET-5286)
**Task -**
- Hide all details on password protected post/page/campaigns
**Testing -**
- Create new page, post, Campaign
- Make it password protected and check on frontend, the page should only display the add password form and submit button
- Check the page source and page meta tags (page title, open graph fields etc)
- Test with adding page header fields and changing the page template

PLANET-5286 Hide all details on password protected post/page/campaigns

---

languages/planet4-master-theme.pot
templates/search.twig

Removed Search archive translation and option from search page template

PLANET-5453 Remove the "Search the archive" string from LoCo

---

templates/blocks/title.twig
templates/html-header.twig

That would make it easier for child themes that just want to override that part only.

Split title into a new template block

---

.circleci/config.yml
composer.json
composer.lock

Ref: https://jira.greenpeace.org/browse/PLANET-5434
Similar to greenpeace/planet4-plugin-gutenberg-blocks#476
---
Unit tests are failing, so I'll open a follow-up ticket for that.

PLANET-5434 Split frontend linters and update composer dependencies

---

composer.json
composer.lock

To accommodate composer 1. Need to be merged after greenpeace/planet4-circleci-unit-tests#6

Switch to github-archive-installer 1.1

---

assets/src/scss/pages/_404.scss
assets/src/scss/pages/post/_comments-form.scss
assets/src/scss/pages/search/_sort-filter.scss
templates/comment_form/author_field.twig
templates/comment_form/comment_field.twig
templates/comment_form/email_field.twig
templates/search.twig

- [PLANET-5705](https://jira.greenpeace.org/browse/PLANET-5705): update form input styles (border, fonts, colors)
- [PLANET-5512](https://jira.greenpeace.org/browse/PLANET-5512): add label/placeholder animation
- styleguide: https://github.com/greenpeace/planet4-styleguide/pull/87
- gutenberg-blocks: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/454

Planet 5705 - Update form inputs UI

---

.circleci/config.yml

Ref: https://jira.greenpeace.org/browse/PLANET-5883

PLANET-5883 Pass actual url

---

assets/src/scss/pages/post/_post.scss
single-attachment.php
templates/single-attachment.twig

Ref: [JIRA 5816](https://jira.greenpeace.org/browse/PLANET-5816)
---
- Add a dedicated page for view attachment
- Its also fixes [PLANET-5908](https://jira.greenpeace.org/browse/PLANET-5908)
Eg.
Image: https://www-dev.greenpeace.org/test-venus/117234958_3412660455445704_8842025374363290911_o/
Document: https://www-dev.greenpeace.org/test-venus/21980e69-green-gadgets/
Video: https://www-dev.greenpeace.org/test-venus/big_buck_bunny_720p_1mb/
Audio: https://www-dev.greenpeace.org/test-venus/impact-moderato/
Reference:
https://developer.wordpress.org/themes/template-files-section/attachment-template-files/

PLANET-5816 Add P4 attachment page

---

phpunit.xml.dist
tests/test-custom-taxonomy.php

Ref: https://jira.greenpeace.org/browse/PLANET-5449
---
Also did a small fix for `@covers` otherwise it fails

PLANET-5449 Fix coverage path

---

src/MasterSite.php

Ref: [JIRA #5509](https://jira.greenpeace.org/browse/PLANET-5509)
---

PLANET-5509 Disable xmlrpc

---

assets/src/scss/pages/post/_post.scss

Ref: [JIRA 5817](https://jira.greenpeace.org/browse/PLANET-5817)
---

PLANET-5817 Fix comments img on handbook idea page

---

src/Settings.php

Ref: [JIRA 5840](https://jira.greenpeace.org/browse/PLANET-5840)
---
Task :
- Add "Facebook App Access Token" setting in Planet4 >> Social setting

PLANET-5840 Add "Facebook App Access Token" setting in Planet4 setting

---

templates/countries.json

Ref: https://jira.greenpeace.org/browse/PLANET-5928
---
Renaming the NRO name on the country list.

PLANET-5928 GPNZ > GPAo

---

.circleci/config.yml

Next-gen circleci image has python3

Switch to pip3

---

assets/src/js/cookies.js

See https://jira.greenpeace.org/browse/PLANET-5755
- gutenberg-blocks: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/506
- styleguide: https://github.com/greenpeace/planet4-styleguide/pull/99

PLANET-5755 Remove jQuery from cookies

---

templates/countries.json

Ref: https://jira.greenpeace.org/browse/PLANET-5928
---
I did the change but forgot to put in the right letter group 🤦🏻‍♂️

PLANET-5928 Fix GPAo order

---

.circleci/config.yml
src/MasterSite.php

Ref: [JIRA 5871](https://jira.greenpeace.org/browse/PLANET-5871)
---

PLANET-5871 Disable wp5.5 Block Patterns feature

---

assets/src/js/cookies.js

See https://jira.greenpeace.org/browse/PLANET-5969
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/514

Fix cookies functions when no cookie banner

---

src/MasterSite.php

PLANET-5964 Only depend on blocks plugin if present

---

admin/css/campaign.css
package-lock.json
package.json
src/Features.php
webpack.config.js

This adds the build script to make the CSS variables file used for the theme editor, as well as a toggle which will be used by https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/495

Collect vars and add beta toggles for theme editor

---

page-templates/evergreen.php

Ref: [JIRA 5979](https://jira.greenpeace.org/browse/PLANET-5979)
---

PLANET-5979 Fix Twitter share button on evergreen page template

---

admin/css/login.css
assets/src/scss/pages/_evergreen.scss
assets/src/scss/pages/_sitemap.scss
assets/src/scss/pages/post/_article-content.scss
assets/src/scss/pages/post/_author-block.scss
assets/src/scss/pages/search/_filter-sidebar.scss
assets/src/scss/pages/search/_search-bar.scss
assets/src/scss/pages/search/_search-results.scss
assets/src/scss/pages/search/_search.scss
images/down-arrow-blue.svg

See https://jira.greenpeace.org/browse/PLANET-5843
**Black / Grey colors:**
- ~~#000000 = $black -> replace by #020202 = $grey-80~~
- ~~#030403 = $header-footer-bg -> replace by #020202 = $grey-80~~
- ~~#1a1a1a = none -> replace by #020202 = $grey-80~~
- ~~#052a30 = $dark-tiber -> replace by #020202 = $grey-80~~
- ~~#242424 = none -> replace by #23292d = $grey~~
- #a7a7a7 = $step-number -> unused, was removed with https://jira.greenpeace.org/browse/PLANET-5842
- #aaaaaa = none -> replace by #a3a5a7 = $grey-20 -> couldn't find it, seems unused
**Blue colors:**
- ~~#0a3351 = $med-blue -> replace by #074365 = $dark-blue~~
- ~~#094464 = $cookie-blue -> replace by #074365 = $dark-blue~~
- ~~#014c8c = $menu-blue ->replace by #020202 = $grey-80~~
- ~~#0058cc = $link-hover-color -> replace by …

PLANET-5843 Replace some colors to align with the design system

---

src/MasterSite.php

Ref: https://jira.greenpeace.org/browse/PLANET-4590
Linked to: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/461
> In the editor, when an Image is added to post, the caption is there but the credit/copyright text is missing.
> It's visible though in the frontend. That can be confusing for editors.
- Adding a `_credit_text` property to the rest API response.
- Limiting potential duplication of credit text on the frontend.
- Another PR on gutenberg-blocks adds the hook to use this property in the editor.
Test with https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/461

PLANET-4590: add credit text to the rest api response

---

composer.json
composer.lock

Ref: [JIRA 5519](https://jira.greenpeace.org/browse/PLANET-5519)
---

PLANET-5519 Update Timber plugin to v1.18.*

---

.circleci/config.yml
bin/install-wp-tests.sh
src/ImageArchive/Rest.php
src/MasterSite.php

See https://jira.greenpeace.org/browse/PLANET-5458 & https://jira.greenpeace.org/browse/PLANET-5459

WordPress 5.6 preparation

---

assets/src/scss/pages/_page.scss
templates/single-page.twig
templates/single-password.twig

Ref: [JIRA 5748](https://jira.greenpeace.org/browse/PLANET-5748)
---
eg.
Page: https://www-dev.greenpeace.org/sagardev/test-password-protected-page/
Post: https://www-dev.greenpeace.org/sagardev/test-password-protected-post/
Campaign: https://www-dev.greenpeace.org/sagardev/campaign/test-password-protected-campaign/

PLANET-5748 Update password form UI as per design system

---

composer.json
composer.lock

Ref: https://jira.greenpeace.org/browse/PLANET-6020

Upgrade github-archive-installer to support composer 2

---

assets/src/scss/pages/search/_filter-sidebar.scss

See https://jira.greenpeace.org/browse/PLANET-5951
- [Broken version](https://www-dev.greenpeace.org/test-jupiter/?s=&orderby=_score)
- [Fixed version](https://www-dev.greenpeace.org/test-saturn/?s=&orderby=_score)

PLANET-5951 Fix search filter checkboxes font size

---

src/PostCampaign.php

---
This removes some dead code, and adds the new name of variables that will be added in https://github.com/greenpeace/planet4-master-theme/pull/1325 . It can be merged already since it preserves the old variables too.

PLANET-5983 Prepare old campaign code

---

src/HttpHeaders.php
src/Loader.php

Just creating this draft PR for the pulled branch, since CircleCI does pick up it's the same commit as the fork, but it doesn't recognize the PR of that fork as being on the commit. It needs to if we want to run the test instance deploy.
Maybe we can fix this in the request instance job by "manually" looking for an open PR that has the same commits?

PLANET-5897: Feature/csp http headers

---

.circleci/config.yml

Follow up PR from: https://github.com/greenpeace/planet4-circleci/pull/46

Add a job for posting a PR comment when test instance is ready

---

assets/src/scss/components/_buttons.scss

See https://jira.greenpeace.org/browse/PLANET-6037
Add a Button block with secondary or donate style and a PDF url (for example [GP annual report](https://www.greenpeace.org/static/planet4-international-stateless/2018/11/f4b36653-greenpeace_international_annualreport2006.pdf)) and make sure it looks good on hover.

PLANET-6037 Add color transition to button PDF icons

---

.circleci/config.yml
commitlint.config.js
package-lock.json
package.json

Ref: https://jira.greenpeace.org/browse/PLANET-6114
---
Added some very basic rules based on what we [already do](https://support.greenpeace.org/planet4/development/git-guidelines).
[Documentation](https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md)

PLANET-6114 Add commitlint CI job

---

templates/head/hubspot.twig

See https://jira.greenpeace.org/browse/PLANET-6146

PLANET-6146 Add Hubspot event callback script to track signups

---

composer.json
composer.lock

This should be merged along with https://github.com/greenpeace/planet4-builder/pull/83

Remove Github Archive Downloader plugin

---

src/CustomTaxonomy.php
src/Settings.php

Change the condition(wpml plugin is installed and activated) with is_plugin_active( 'sitepress-multilingual-cms/sitepress.php' ) function
Ref: [JIRA 6150](https://jira.greenpeace.org/browse/PLANET-6150)
---

PLANET-6150 Update WPML deprecated function [icl_object_id()]

---

src/MasterSite.php

Ref: https://jira.greenpeace.org/browse/PLANET-6127

Add P4 trainings to message board

---

.circleci/config.yml

Testing if https://github.com/greenpeace/planet4-master-theme/pull/1429 would work. It should reset it to master even for other target branches.

Add quotes, message contains spaces

---

templates/footer.twig
templates/footer_social_media.twig

------
The logic does not change, it's just a refactor for an easy maintenance. 
Please validate and check that the UI is not broken.
This PR is Blocked by https://github.com/greenpeace/planet4-master-theme/pull/1458
**Demo page**
------
https://www-dev.greenpeace.org/test-uranus/campaign/campaign-for-climate-emergency/
Ref: https://jira.greenpeace.org/browse/PLANET-6189
---

Move the Footer social media nav logic from the Footer to a new template

---

assets/src/scss/layout/_footer-social-media.scss
assets/src/scss/layout/_footer.scss
assets/src/scss/style.scss

This file was being moved by https://github.com/greenpeace/planet4-master-theme/pull/1467, and the PR also makes changes to the content. Because of this move, almost nothing in the PR is lining up with the previous changes, making it hard to review.
Ref: https://jira.greenpeace.org/browse/PLANET-6189

Move footer social media to own template

---

src/Features.php

Ref: https://jira.greenpeace.org/browse/PLANET-6495
* This prevented saving the features page.

Check for possible bool return value from CMB2_Field before calling value()

---

assets/src/js/external_links.js

Ref: https://jira.greenpeace.org/browse/PLANET-6501
See https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/744

Class selector as multiple blocks will be allowed

---

assets/src/js/header.js
assets/src/scss/layout/_navbar.scss
assets/src/scss/layout/navbar/languages.scss

Ref: https://jira.greenpeace.org/browse/PLANET-6256
For now I only unvariablized some properties. Also included a small syntax improvement in the JS.

Reduce amount of variable properties, some fixes

---

composer.json
composer.lock

* Done separately because an issue prevents using a lib in the same PR
that adds it.

Add Google API client lib

---

src/AnalyticsValues.php
src/Features.php
src/GoogleDocsClient.php
src/Settings.php
src/Smartsheet.php
src/SmartsheetClient.php

Ref: https://jira.greenpeace.org/browse/PLANET-6451
* Add Google Docs API client lib.
* Add option to choose between Smartsheet and Google for the
integration.
* Add settings field for the local Google Sheet.
* hardcode the global doc ID for now. Maybe later env var but it's on the Jira ticket anyway so it can be public.
* I'll set up the authentication in CircleCI context.
Before we initiate the release we need to verify the key is functional. I had some issues while testing because it requires a specific format of base64.

Support Analytics values using Google Sheet

---

functions.php
src/Loader.php

* Posts are updated somehow without the last revision being updated as
well. This filter should allow us to see when that happens by throwing a
warning.

Check every updated post for non CDN URLs

---

tests/acceptance/HomePageCept.php

Add a try/catch to test the new country selector, if the old one is not found.

Fix country selector acceptance test

---

assets/src/js/search.js
src/Search.php
templates/search.twig

I removed everything that could easily be determined is not used. We should be able to merge this without affecting any live code.
Easier to verify [with whitespace ignored](https://github.com/greenpeace/planet4-master-theme/pull/1562/files?diff=split&w=1).
There surely is more dead code so expect a part II :grin:

Clean up (some) search dead code

---

assets/src/js/app.js
assets/src/js/header.js

See [PLANET-5758](https://jira.greenpeace.org/browse/PLANET-5758)
I've removed quite a big chunk of the file, these parts did not seem to be used anymore as I couldn't find any use of the classes in our code.
You can test everything either on local or on the [test instance](https://www-dev.greenpeace.org/test-deimos), making sure that everything behaves as expected. You should check both the old and new navigation bar and menu, since both should still be working!

PLANET-5758 Remove jQuery from header.js

---

src/Settings.php

See https://jira.greenpeace.org/browse/PLANET-6496
---
Added the "embed code" options to 'Planet 4 > Defaults Content -

PLANET-6496 Happy Point: add option for code snippet embed

---

src/Post.php

* Calculating reading time takes some computation especially in large
posts. And the resulting data is really small, so caching makes sense
here.
* I trust that each post will have a modified time and that it will
reliably change. In this case at worst it's off by a few minutes for a
short amount of time.

Cache the reading time using ID and date as key

---

assets/src/scss/base/_mixins.scss
assets/src/scss/layout/_navbar.scss
assets/src/scss/layout/navbar/_search.scss

Ticket: https://jira.greenpeace.org/browse/PLANET-6606
The issue basically related of `Safari` by versions `< 13`, and initially reported by some iOS devices that have installed the OS version about < 12. _It's good to mention that the version of Safari, is the same as the OS_. It's been reported in iPhone and iPad.
**What is fixed?**
There are some properties that work only on versions higher than `14`. 
Se an example about `inset-inline-start`, which is available only on versions higher than 14.
Checked if the `property` is supported through this code
```
@supports not (property: value) {}
```
The `X` is hidden. The problem was about that the main navigation has been set to 400px of width, but smallest screens are about 320px. 
For smallest screens, the width has been set to `100vw`
All …

Planet 6606 fix navbar issue

---

src/Campaigns.php

I started this as a "quick PR" to make it easier to see the redirect pages.
While testing I found out how buggy the auto page creation is, the hard way, after trying to make a page in the list have no redirect page.

Show redirect_page in tag list

---

single-campaign.php
single-p4_action.php
src/ActionPage.php
src/Context.php

Ref: https://jira.greenpeace.org/browse/PLANET-6592
Goes with: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/800
Test with https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/800 on [Sinope](https://www-dev.greenpeace.org/test-sinope/)
See https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/800 for instructions

PLANET-6592: Add minimal navigation option to Action page type

---

assets/src/scss/editorStyle.scss
assets/src/scss/layout/_forms.scss
assets/src/scss/layout/_gravity-forms.scss
assets/src/scss/style.scss

See [PLANET-6555](https://jira.greenpeace.org/browse/PLANET-6555)
This includes the following form fields: textarea, input, checkbox, radio, select.
You can test a form example on [this page](https://www-dev.greenpeace.org/test-nix/gravity-forms-tests/), you can also play around in the backend with editing the existing GF form or creating a new one! Please make sure to also test the validation messages when submitting an invalid form.

PLANET-6555 Style Gravity Forms

---

assets/src/scss/components/_buttons.scss
assets/src/scss/pages/post/_post.scss
templates/blocks/author_profile.twig
templates/single-attachment.twig
templates/single-password.twig
templates/single.twig

See [PLANET-6513](https://jira.greenpeace.org/browse/PLANET-6513)
These new tags look more like buttons and are positioned at the end of the post content, before the author block
You can check the new post tags on local in any post, or on the test instance also on any post, for example [this one](https://www-dev.greenpeace.org/test-phobos/story/51526/animations-we-loved-this-year-7-short-films-that-inspire-action/).

PLANET-6513 Implement the new post tags

---

templates/countries.json

Ref: https://jira.greenpeace.org/browse/PLANET-6721

Remove Greenland from countries list

---

assets/src/js/header.js
assets/src/js/menu_editor.js
assets/src/scss/base/_mixins.scss
assets/src/scss/layout/_navbar.scss
assets/src/scss/layout/navbar/_burger-menu.scss
assets/src/scss/layout/navbar/_search.scss
assets/src/scss/layout/navbar/languages.scss
assets/src/scss/partials/navigation-bar-light.scss
src/AdminAssets.php
src/Features/DropdownMenu.php
src/MasterSite.php
src/Settings.php
src/Settings/InformationArchitecture.php
templates/burger-menu-items.twig
templates/burger-menu.twig
templates/navigation-bar-new.twig
templates/navigation-submenu.twig

Ref: [Ticket](https://jira.greenpeace.org/browse/PLANET-6673)
🎨 [Figma Design](https://www.figma.com/file/Gn8wyqgto7608rlESePXZE/Foundations-%26-Components?node-id=1126%3A1834) 
Fully implementation of drop down menus (already approved). It will work as a final review before merging into the `master` branch.
Go to the [Demo page](https://www-dev.greenpeace.org/test-nix) and play around the main navigation.
**Please be sure that the feature is enabled**, if not then go to Planet 4 > Information architecture > Enable dropdown menu
**Tickets**
- ~Desktop version~ ✅ : [PLANET-6509](https://jira.greenpeace.org/browse/PLANET-6509)  
- ~Mobile version~ ✅ [PLANET-6511](https://jira.greenpeace.org/browse/PLANET-6511)
- ~Donate Button~ ✅: [PLANET-6579](https://jira.greenpeace.org/browse/PLANET-6579) …

PLANET-6673: Navigation bar drop down menus

---

assets/src/scss/layout/navbar/mobile.scss

Remove unused import of base/color. it is already imported in navigation-bar-{dark,light}.scss.

Remove unused scss import

---

templates/burger-menu.twig
templates/desktop-menu.twig
templates/language-switcher.twig

* The only differences between both were because changes that should
have been applied in both places previously were not.

Move duplicated language switcher code to separate file

---

assets/src/images/icons/share.svg

This is part of our Figma mockup already. Adding it here, so NROs can use it.

Add share icon

---

src/Features/Dev/DisableDataSync.php
src/Settings/Features.php

Ref: https://jira.greenpeace.org/browse/PLANET-6772
---
This is the first required step. Adding the flag to be used by the sync CI pipeline.

Add feature flag to disable automated data sync

---

templates/burger-menu.twig
templates/navigation-bar-new.twig

Ref: https://jira.greenpeace.org/browse/PLANET-6776
Show only when the site has more than one languages already set.

PLANET-6776: Change languages dropdown menu condition

---

assets/src/scss/layout/_page-header.scss

Ref: https://jira.greenpeace.org/browse/PLANET-6800
Change to absolute units instead of relative units

PLANET-6800: Fix title and intro text width

---

page.php
src/Features/RedirectRedirectPages.php
src/Settings/Features.php

https://jira.greenpeace.org/browse/PLANET-6619

PLANET-6619 Ensure "redirect page" has no duplicate URL by redirecting to the tag URL it's overriding

---

theme.json

That allows auto-completion on many code editors.

Add schema link to theme.json

---

functions.php

Trying to import content through WP Importer with wp-stateless > 3 will fail at the import content step.
On step 1, the importer takes the file and wp-stateless saves it on GCS
On step 2, the importer looks for the file in the local /uploads folder, instead of GCS
The main cause of this issue is that the `sm_cloud` metadata for the imported file is never created.
WP Importer has no hook to attach actions on, so this fix heavily checks its context to run only when necessary.
Once the import file is uploaded, we trigger an update of metadatas so that wp-stateless hooks can do their job.
wp-stateless updates its `sm_cloud` metadata in `wpCloud\StatelessMedia\Utility::add_media`, this method is triggered on the filter `wp_update_attachment_metadata`.
WP importer follows this sequence for …

Fix WP importer error with wp-stateless 3.2

---

assets/src/scss/pages/post/_article-content.scss

Ticket: https://jira.greenpeace.org/browse/PLANET-6723
According to this Slack thread, we need to apply new styles only when the Article is included into a post.
This PR is blocked this other [PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/870). More info there!
IMPORTANT: We don't need to use the Ieda's instance for a demo page.

Allow articles block in posts

---

src/Activator.php
src/GravityFormsSettings.php
src/Role/GravityForms.php

Ref: https://jira.greenpeace.org/browse/PLANET-6803
Run `docker-compose exec php-fpm wp p4-run-activator` on your local and check if it's works.
**If you don't have already created a user with an editor role then create it.**

PLANET-6803: Add Gravity Forms Capabilities for Editors

---

src/MasterSite.php

Ref: https://jira.greenpeace.org/browse/PLANET-6671
Previous log content was filtered by Sentry :panda_face: 
This modification logs the list of cookies, and their respective size.
It also raises the trigger to 6M.
This [event in Sentry](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/433/events/8aa8672ceaa44460b98a73f0a0d81001/) show how it looks like.

PLANET-6671: Log cookies size

---

theme.json

New feature applied to `core/heading`.

Implement new spacing values

---

theme.json

The Issues patterns needs this from [here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/914/files#diff-48b8904c9490414ea5f81b24352f93cd7ebc7c65369ba952fbfebaa35f0d5f5fR32-R33) but other patterns will potentially needed it too.

Add border radius feature to theme

---

src/MasterSite.php

Related to: https://jira.greenpeace.org/browse/PLANET-6671
We have enough data in Sentry to reach a conclusion on this matter
Cf. https://sentry.greenpeace.org/organizations/greenpeace-org/issues/694/events/?project=2

Remove large cookie log

---

README.md

This is needed for applying in the Open Source Sponsorship program.

Add BrowserStack notice

---

author.php

See [PLANET-6912](https://jira.greenpeace.org/browse/PLANET-6912)
This issue was previously fixed for other templates but not the author one
You can compare the fixed version [here](https://www-dev.greenpeace.org/test-telesto/author/admin/) with the broken version for example [here](https://www-dev.greenpeace.org/test-mars/author/admin/)!

PLANET-6912 Fix site name appearing twice in author page title

---

src/GravityFormsExtensions.php

There must have been a mix up while rebasing PRs 😬

Fix Gravity Forms settings function name

---

src/MetaboxRegister.php

ref. https://jira.greenpeace.org/browse/PLANET-6891

PLANET-6891 Action post type enable the Opengraph metabox

---

assets/src/scss/layout/_navbar.scss
assets/src/scss/partials/navigation-bar-light.scss

Based on this [comment](https://github.com/greenpeace/planet4-master-theme/pull/1827#pullrequestreview-1164626339) from #1827 
Issued on Webkit only (Chrome and Safari)
**Demo page** 👉 https://www-dev.greenpeace.org/greece/epirease/receptionist-secretarial-assistant-on-site/

FIx navlink hover color

---

src/ActionPage.php

Allow admin to localize action slug from permalinks setting page
Ref. https://jira.greenpeace.org/browse/PLANET-6892
**eg.**
[Permalinks setting page](https://www-dev.greenpeace.org/test-phoebe/wp-admin/options-permalink.php)
[Action page](https://www-dev.greenpeace.org/test-phoebe/custom-slug/lorem-ipsum/)
**Testing:**
- Go to actions [listing page](https://www-dev.greenpeace.org/test-phoebe/wp-admin/edit.php?post_type=p4_action)
- Add new action page, view it on frontend, also please check the URL slug
- Now change the custom action slug from [permalinks settings page](https://www-dev.greenpeace.org/test-phoebe/wp-admin/options-permalink.php)
- Go to [actions listing page ](https://www-dev.greenpeace.org/test-phoebe/wp-admin/edit.php?post_type=p4_action) , check different action by …

PLANET-6892 Add localize action slug option

---

templates/countries.json

To avoid one extra redirect and potential certificate issues

Switch Poland to the proper url

---

src/ActionPage.php

Ref 
https://jira.greenpeace.org/browse/PLANET-6957
https://jira.greenpeace.org/browse/PLANET-6956
**Task:**
- Remove action-type string from Action Type permalink url ([PLANET-6957](https://jira.greenpeace.org/browse/PLANET-6957))
- Actions should use the Action Type slug as part of their permalink structure [/<action_type>/<action_slug>/]. ([PLANET-6956](https://jira.greenpeace.org/browse/PLANET-6956))
- Add a "Default Action Type" setting field on Writing settings page
**Testing:**
**PLANET-6957**
- Check the Action type permalink URL, it should not have a 'action-type' slug.
eg. 
https://www-dev.greenpeace.org/test-leda/oceans/
https://www-dev.greenpeace.org/test-leda/plastics/
**PLANET-6956**
- The action post type permalink structure should be - `/<action_type>/<action_slug>/`
eg. …

PLANET-6957 Remove action-type string from Action Type permalink url & Use Action Type slug on Actions permalink url

---

theme.json

This allows us to easily customise these values, either for child themes or campaigns

Add CSS variables for typography settings in theme file

---

assets/src/scss/components/_buttons.scss

It shouldn't be purple like other links.

Fix donate button visited color

---

src/GravityFormsExtensions.php

Cf. https://github.com/greenpeace/planet4-master-theme/pull/1937/files#r1116872091
Fix return type :grimacing:

Fix return type on GF custom confirmation function

---

src/PublicAssets.php

See [PLANET-7012](https://jira.greenpeace.org/browse/PLANET-7012)
We want to merge this towards the end of the sprint, but we can already start testing it!
There should be no issues in the frontend, everything should still work as expected.

PLANET-7012 Completely remove jQuery from frontend

---

page-templates/evergreen.php
page.php
single-campaign.php
single-p4_action.php
single.php
src/Context.php
templates/blocks/google_tag_manager.twig

Ref: https://jira.greenpeace.org/browse/PLANET-7075
Create a new datalayer value to track Planet4 blocks and Gravity forms
Create a new page with p4 or gravity form blocks and preview it.
Then, open de browser console and type `datalayer` through the terminal. Expand the `zero` index and check the value of `p4_blocks`. All the blocks should be separated by commas.

Add new datalayer value to track blocks

---

.eslintrc.json
assets/src/js/Components/ArchivePicker.js
assets/src/js/Components/archivePicker/ArchivePickerList.js
assets/src/js/Components/archivePicker/MultiSidebar.js
assets/src/js/Components/archivePicker/SingleSidebar.js
assets/src/js/Components/archivePicker/sizeFunctions.js
assets/src/js/Components/archivePicker/useImages.js
assets/src/js/app.js
assets/src/js/archive_picker.js
assets/src/js/cookies.js
assets/src/js/external_links.js
assets/src/js/gravityforms-client-side.js
assets/src/js/header.js
assets/src/js/load_more.js
assets/src/js/menu_editor.js
assets/src/js/pdf_icon.js
assets/src/js/search.js
package-lock.json
package.json

**Description: [PLANET-7106](https://jira.greenpeace.org/browse/PLANET-7106)**
Updated ESLint config to match plugin repo

PLANET-7106 Implement ESLint config in Master Theme

---

assets/src/scss/base/_tokens.scss

**New version of Design Tokens**<br> https://github.com/greenpeace/planet4-design-tokens/compare/v0.10.0...v0.11.1

Design Tokens: New release [v0.11.1]

---

src/MasterSite.php

Ref. https://jira.greenpeace.org/browse/PLANET-6975

PLANET-6975 Disable Background updates check in Site health.

---

assets/src/scss/new-identity/style.scss
assets/src/scss/pages/post/_comments-block.scss
assets/src/scss/pages/post/_comments-form.scss

Ref: https://jira.greenpeace.org/browse/PLANET-6998
Apply the new layout regarding the new identity project.
<!-- Ref: Please add a url to the ticket this change is addressing.

PLANET-6998: Apply new colors to comments block

---

assets/src/scss/base/_tokens.scss

**New version of Design Tokens**<br> https://github.com/greenpeace/planet4-design-tokens/compare/v0.11.1...v0.12.0

Design Tokens: New release [v0.12.0]

---

.circleci/config.yml

Ref: https://github.com/greenpeace/planet4-circleci/pull/69

Adjust test user trigger to new instance parameter

---

src/GravityFormsExtensions.php

Ref: https://jira.greenpeace.org/browse/PLANET-7154
The current implementation comes from [PLANET-7053](https://jira.greenpeace.org/browse/PLANET-7053) and its [related PR](https://github.com/greenpeace/planet4-master-theme/pull/2006).

PLANET-7154: Duplicate Feeds on form duplication

---

tests/e2e/comments.spec.js

**Description: [PLANET-7058](https://jira.greenpeace.org/browse/PLANET-7058)**
**Testing:**
Navigate to this branch locally and run `npx playwright test` and you should see the tests run and pass.

PLANET-7058 Re-write the Comments test in Playwright

---

tests/e2e/special-pages.spec.js

Otherwise we end up with no Act and Explore pages on test instances

Reset Act and Explore pages after special pages test

---

.eslintrc.json
tests/e2e/search.spec.js

**Description: [PLANET-7163](https://jira.greenpeace.org/browse/PLANET-7163)**
Testing:
Run `npx playwright test tests/e2e/search.spec.js` on this branch to see test output.

PLANET-7163 Re-write the Search test in Playwright

---

src/Search.php

These also impacted the Media Library

Revert Search ElasticPress fixes

---

assets/src/scss/base/_tokens.scss

**New version of Design Tokens**<br> https://github.com/greenpeace/planet4-design-tokens/compare/v0.13.0...v0.13.1

Design Tokens: New release [v0.13.1]

---

assets/src/scss/new-identity/_fonts.scss

Changed in bfa322e4181c7b7580606c2fa95aa13df65d8e8b

Rename fonts variable names

---

tests/e2e/404.spec.js
tests/e2e/comments.spec.js
tests/e2e/footer.spec.js
tests/e2e/special-pages.spec.js
tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
tests/e2e/tools/lib/login.js
tests/e2e/tools/lib/nonce.js
tests/e2e/tools/lib/rest.js

This includes removing some unnecessary await statements, and ESLint fixes
All tests should still pass

Improve Playwright tests

---

.circleci/config.yml
admin/js/dashboard.js
admin/js/post_tag.js
admin/js/posts_report.js
tests/e2e/tickets/PLANET-7064/PLANET-7064.test.js
tests/e2e/tools/php-errors.test.js

- Include tests and admin scripts
- Use double quotes to properly interpret glob patterns
- Fixed remaining eslint issues

Expand eslint check on all js code

---

assets/src/scss/base/_tokens.scss

**New version of Design Tokens**<br> https://github.com/greenpeace/planet4-design-tokens/compare/v0.14.0...v0.15.0

Design Tokens: New release [v0.15.0]

---

tests/e2e/password-protected-content.spec.js

See [PLANET-5284](https://jira.greenpeace.org/browse/PLANET-5284)

PLANET-5284 Add Playwright test for password protected content

---

assets/src/scss/components/_buttons.scss
assets/src/scss/layout/_cookies-settings.scss
assets/src/scss/layout/_country-selector.scss
assets/src/scss/layout/_navbar.scss
assets/src/scss/layout/navbar/_burger-menu.scss
assets/src/scss/new-identity/style.scss

Ref: https://jira.greenpeace.org/browse/PLANET-7194
Major updates 👇 
- Update the main nav
- Update the burger menu
- Update texts and buttons
- Update the country selector
Using the [Umbriel's instance](https://github.com/greenpeace/planet4-test-umbriel/blob/main/composer-local.json#L6-L7) as a demo page.

Follow up design tokens's  feedback

---

src/MasterSite.php

Fix notices when act_page is not defined

Fix act_page notices

---

assets/src/js/menu_editor.js

See [PLANET-7203](https://jira.greenpeace.org/browse/PLANET-7203)
This would happen whenever we would toggle some of the menu settings

PLANET-7203 Fix menu notice showing multiple times

---

package-lock.json

Update Browserslist DB
Cf. https://github.com/browserslist/update-db#readme

Update Browserslist DB

---

package-lock.json
package.json
tests/e2e/navigation-bar.spec.js

See [PLANET-6646](https://jira.greenpeace.org/browse/PLANET-6646)
On local you can run the new test via `npx playwright test tests/e2e/navigation-bar.spec.js` or using VSCode

PLANET-6646 Write an e2e test for the navigation bar

---

src/CustomTaxonomy.php
src/Loader.php
src/Migrations/M019MigrateReadingTime.php
src/Post.php
src/Post/ReadingTimeCalculator.php
src/Settings.php
src/Settings/ReadingTime.php

Ref: https://jira.greenpeace.org/browse/PLANET-7209
The Reading time WPM option should now be in `Settings > Reading`.

PLANET-7209: Move Reading Time option to Reading settings

---

assets/src/scss/pages/_sitemap.scss
page-templates/sitemap.php
templates/sitemap.twig

Ref: https://jira.greenpeace.org/browse/PLANET-6793
Following: https://github.com/greenpeace/planet4-master-theme/pull/2085
- fix post links
- fix category links
- move up empty condition to avoid empty category
- fix font-family for list content

Fix Sitemap links

---

.circleci/config.yml
package-lock.json
package.json

- Update Playwright
- Update e2e tools
- Fix licence
E2E tests should [still run properly](https://app.circleci.com/pipelines/gh/greenpeace/planet4-master-theme/8447/workflows/2f30cffc-c53e-4532-b81b-23cf954b6bc6/jobs/60468/tests).

Update Playwright version

---

assets/src/scss/new-identity/style.scss

Ref: https://jira.greenpeace.org/browse/PLANET-7242
Related to: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1111

PLANET-7242: Fix title text covered by background

---

assets/src/scss/components/_buttons.scss
assets/src/scss/new-identity/style.scss

See [PLANET-7243](https://jira.greenpeace.org/browse/PLANET-7243)

PLANET-7243 Fix new identity secondary buttons active styles

---

.circleci/config.yml

Pin versions to avoid mismatch between local and CI version

Pin E2E test packages versions

---

package-lock.json
package.json

Use @playwright/test, it contains playwright package [as a dependency](https://www.npmjs.com/package/@playwright/test?activeTab=dependencies)
Stops [CI from complaining](https://app.circleci.com/pipelines/github/greenpeace/planet4-develop/375/workflows/7405b8ff-e732-42d5-8086-722979a1c456/jobs/1237) about the wrong package being installed
[Tested on dev env CI](https://github.com/greenpeace/planet4-develop/pull/26)

Fix Playwright package

---

assets/src/scss/new-identity/style.scss
assets/src/scss/pages/_listing-page.scss

See [PLANET-7240](https://jira.greenpeace.org/browse/PLANET-7240)
You can check the new styles on the [Press listing page](https://www-dev.greenpeace.org/test-nix/press/) for example.

PLANET-7240 Update new identity listing pages fonts

---

src/GravityFormsExtensions.php

[No ticket]
Changes to the lifecycle stage in forms. Here is the [snippet code](https://share.gravityfor.ms/n/g5gsYQ) they suggest to implement.
https://developers.hubspot.com/changelog/changes-to-the-lifecycle-stage-in-forms

Add code GravityForms Hubspot snippet

---

admin/css/login.css

See [PLANET-7275](https://jira.greenpeace.org/browse/PLANET-7275)

PLANET-7275 Update login button color to reflect new visual identity

---

src/Search.php

Ref. https://jira.greenpeace.org/browse/PLANET-7363

PLANET-7363 Fix admin media library search issue

---

assets/src/scss/pages/_page.scss

Ref: https://jira.greenpeace.org/browse/PLANET-6795
Based on [this comment](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1108#discussion_r1309904756)
👉  [Demo page](https://www-dev.greenpeace.org/test-saturn/1425-2/)

PLANET-6795: Fix top spacing of Media and Text

---

admin/css/archive-picker.css
assets/src/js/Components/ArchivePicker/MultiSearchOption.js
assets/src/js/Components/ArchivePicker/SingleSidebar.js
assets/src/scss/editorOverrides.scss
images/arrow-right.svg

Include the new variant of close button but also refactor a small piece of code.
---
Please provide a brief summary of the change introduced to make review process easier.
Ideally this should also be part of the commit summary.
-->

Media Archive: include new close button

---

src/Blocks/GuestBook.php

No ticket needed
We do not need to use P4GBKS to blocks into the theme

Guestbook: Change package name of class

---

assets/src/block-editor/ColorPaletteControl/ColorPaletteControl.js
assets/src/blocks/Spreadsheet/ArrowIcon.js
assets/src/blocks/Spreadsheet/HighlightMatches.js
assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
assets/src/blocks/Spreadsheet/SpreadsheetEditorScript.js
assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
assets/src/blocks/Spreadsheet/SpreadsheetScript.js
assets/src/scss/blocks.scss
assets/src/scss/blocks/CarouselHeader/CarouselHeaderStyle.scss
assets/src/scss/blocks/Spreadsheet.scss
src/Blocks/Spreadsheet.php
src/Loader.php
webpack.config.js

**Ref:[ PLANET-7303](https://jira.greenpeace.org/browse/PLANET-7303)**
**Testing:**
On the assigned test-instance or locally, you can disable the blocks plugin, make sure the _Planet 4 Blocks_ feature is enabled and you should see the Spreadsheet block in the editor.

PLANET-7303 Move Spreadsheet block into master theme

---

assets/src/blocks/Submenu/SubmenuBlock.js
assets/src/blocks/Submenu/SubmenuEditor.js
assets/src/blocks/Submenu/SubmenuFrontend.js
assets/src/blocks/Submenu/SubmenuItems.js
assets/src/blocks/Submenu/SubmenuLevel.js
assets/src/blocks/Submenu/example.js
assets/src/blocks/Submenu/generateAnchor.js
assets/src/blocks/Submenu/getHeadingsFromBlocks.js
assets/src/blocks/Submenu/getHeadingsFromDom.js
assets/src/blocks/Submenu/getSubmenuStyle.js
assets/src/blocks/Submenu/makeHierarchical.js
assets/src/blocks/editorIndex.js
assets/src/blocks/frontendIndex.js
assets/src/functions/deepClone.js
assets/src/functions/unescape.js
assets/src/scss/blocks.scss
assets/src/scss/blocks/Submenu/SubmenuEditorStyle.scss
assets/src/scss/blocks/Submenu/SubmenuStyle.scss
assets/src/scss/editorStyle.scss
src/Blocks/Submenu.php
src/Loader.php

**Ref: [PLANET-7382](https://jira.greenpeace.org/browse/PLANET-7382)**
Testing: 
Submenu block now exist in Master theme, disabling the Blocks Plugin, you should still have access to the Submenu Block.

PLANET-7382 Move Submenu block into master theme

---

.circleci/config.yml
composer.json
composer.lock
src/MasterSite.php
src/Migrations/M025CreateDefaultPostsPage.php

Ref: https://jira.greenpeace.org/browse/PLANET-7388
- Update package to match planet4-base declaration
- Remove php7.4 tests

PLANET-7388: Update google/apiclient package

---

src/Post.php

See [PLANET-7343](https://jira.greenpeace.org/browse/PLANET-7343)
Following up from [PLANET-6747](https://jira.greenpeace.org/browse/PLANET-6747) that we implemented during the IA MVP phase, we can unify the logic of the Posts breadcrumb regardless of the "New IA" feature flag status.
- Taxonomy breadcrumbs should follow the new IA logic: `Post Type > Category | Category`
- Simplify any involved template code _(seems this wasn't needed?)_
- Simplify Post class code accordingly
You can make sure that the breadcrumbs behave as expected on [this post](https://www-dev.greenpeace.org/test-pandora/press/1113/duis-posuere-6/) for example, with or without enabling the new IA!

PLANET-7343 Unify Post breadcrumbs structure

---

tests/e2e/gravity-forms.spec.js

They are flaky sometimes, hopefully these changes will help

Fix Gravity Forms tests

---

src/MasterSite.php

Ref: https://jira.greenpeace.org/browse/PLANET-7428

PLANET-7428: Add survey to WP Dashboard

---

src/Exporter.php

Ref. https://jira.greenpeace.org/browse/PLANET-7413

PLANET-7413 Redirect Import button to Greenpeace Media

---

src/MediaArchive/UiIntegration.php

**Description:**
Changed name from _Image Archive_ to _Greenpeace Media_ in `Dashboard > Media > Greenpeace Media Settings`

Update Image Archive name to Greenpeace Media

---

assets/src/blocks/Media/MediaBlock.js
assets/src/blocks/Media/MediaEditor.js
assets/src/blocks/Media/MediaElementVideo.js
assets/src/blocks/Media/MediaFrontend.js
assets/src/blocks/Media/deprecated/mediaV1.js
assets/src/blocks/Media/setupMediaElementJS.js
assets/src/editorIndex.js
assets/src/frontendIndex.js
assets/src/hooks/useStylesheet/addLinkTag.js
assets/src/hooks/useStylesheet/useStylesheet.js
assets/src/scss/blocks.scss
assets/src/scss/blocks/Media.scss
src/Blocks/Media.php
src/Loader.php

**Ref: [PLANET-7402](https://jira.greenpeace.org/browse/PLANET-7402)**
**Testing:**
Media Block should still work as normal when Blocks plugin is disabled.

PLANET-7402 Move Media block into master theme

---

src/ElasticSearch.php
src/Search.php

Ref: https://jira.greenpeace.org/browse/PLANET-7430
- Wrongly applied sanitize+decode on query string to obtain sort field
Taking the filter first and then sanitizing it works.
- Ajax requests go through `admin-ajax.php`, which triggers a different behavior from ElasticPress
Setting filter [`ep_is_integrated_request`](https://10up.github.io/ElasticPress/ep_is_integrated_request.html) to `true` fixes most behaviors, including the usual double nested `query.function_score.query.function_score`.
Use the query log page of ElasticPress to debug queries (`wp-admin/admin.php?page=ep-query-log`)
"Search, public" query body and "Search, ajax" query body should have the same structure (apart from aggregation data).
Using `international` DB:
- searching for "waste colonialism", the article …

PLANET-7430: Elastic search not returning correct results

---

assets/src/js/actions_list_clickable_cards.js
assets/src/js/app.js
assets/src/js/query_loop_carousel.js
assets/src/scss/blocks/ActionsList.scss

**Ref: [PLANET-7420](https://jira.greenpeace.org/browse/PLANET-7420)**
**Testing:** 
Actions List cards are now clickable and redirect to page/post

PLANET-7420 Actions List: make the whole card clickable

---

admin/js/enforms.js
assets/src/blocks/ENForm/ENFormFrontend.js
assets/src/scss/blocks/ENForm/components/_enform-side-style.scss
src/Loader.php

Ref: https://jira.greenpeace.org/browse/PLANET-7462
Following: https://jira.greenpeace.org/browse/PLANET-7323
Following: https://jira.greenpeace.org/browse/PLANET-7304
Requires: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1197
- Replace `_.template` functionality with js template literals.
- Fix missing API endpoint
- Fix side style background image path

PLANET-7462: Remove Lodash dependency from enforms.js

---

templates/evergreen.twig
templates/listing-page.twig
templates/page.twig
templates/single-attachment.twig
templates/single-page.twig
templates/single-password.twig
templates/single.twig

Added `id="content"` for post and page content

Add id for page-content and post-content

---

assets/src/blocks/Columns/ColumnConstants.js
assets/src/blocks/Columns/Columns.js
assets/src/blocks/Columns/ColumnsBlock.js
assets/src/blocks/Columns/ColumnsEditor.js
assets/src/blocks/Columns/ColumnsFrontend.js
assets/src/blocks/Columns/ColumnsImagePlaceholder.js
assets/src/blocks/Columns/ColumnsTasks.js
assets/src/blocks/Columns/EditableColumns.js
assets/src/blocks/Columns/example.js
assets/src/blocks/Columns/imageSizes.js
assets/src/editorIndex.js
assets/src/frontendIndex.js
assets/src/scss/blocks.scss
assets/src/scss/blocks/Columns/ColumnsEditorStyle.scss
assets/src/scss/blocks/Columns/ColumnsStyle.scss
assets/src/scss/components/_image-hover-buttons.scss
assets/src/scss/editorStyle.scss
src/Blocks/Columns.php
src/Loader.php
src/MasterBlocks.php

See [PLANET-7442](https://jira.greenpeace.org/browse/PLANET-7442)
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1201
The Columns block should still behave as expected even if our plugin is deactivated. Make sure to test both new blocks and old ones!

PLANET-7442 Move P4 Columns block to the theme

---

src/GravityFormsExtensions.php

New 'userEmail' Datalayer variable added in Gravity forms form_submission event.
Ref https://jira.greenpeace.org/browse/PLANET-7453
**Testing:**
- On form submission GF, 'formSubmission' dataLayer event should send a new variable 'userEmail' along with existing data
- This change should work for both redirect & text confirmation pages
eg.
https://www-dev.greenpeace.org/test-neptune/newsletter-redirect/

PLANET-7453 Add new DL variable for email in Gravity Forms

---

assets/src/blocks/Cookies/CookiesFrontend.js
assets/src/js/cookies.js
templates/blocks/google_tag_manager.twig

Ref. https://jira.greenpeace.org/browse/PLANET-7410
The consent default & update should work as per the requirements mentioned in the JIRA ticket.
eg. 
https://www-dev.greenpeace.org/test-saturn/
https://www-dev.greenpeace.org/test-saturn/privacy-and-cookies/

PLANET-7410 Update the default and update consent mode scripts

---

assets/src/block-styles/index.js
assets/src/editorIndex.js
assets/src/scss/base/_mixins.scss
assets/src/scss/core-overrides/_heading.scss
assets/src/scss/core-overrides/_image.scss
assets/src/scss/editorStyle.scss
assets/src/scss/style.scss

_No ticket needed_
[Demo page](https://www-dev.greenpeace.org/test-nix/register-block-styles/)
- https://github.com/greenpeace/planet4-master-theme/pull/2258
- https://github.com/greenpeace/planet4-master-theme/pull/2259
Copied from [editor.js](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/admin/js/editor.js#L5C3-L86C6)

Include custom block styles from plugin

---

tests/e2e/tools/lib/editor.js

No ticket needed
Previously
Now

Fix gallery spec 

---

src/GravityFormsExtensions.php

Adds a filter hook in both places the formSubmission event is pushed to dataLayer. The filter enables the modification of the data that's sent with the event.
Ref: https://github.com/greenpeace/planet4/issues/188
For testing, make sure the formSubmission event is still correctly sent when a form is submitted.

Add filter hook to allow changing the formSubmission event parameters

---

assets/src/block-templates/take-action/block.json
assets/src/block-templates/take-action/index.js
assets/src/block-templates/take-action/template.js
assets/src/block-templates/template-list.js
src/Patterns/BlockPattern.php
src/Patterns/TakeAction.php

See [PLANET-7554](https://jira.greenpeace.org/browse/PLANET-7554)
We remove it from the plugin in [this PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1216)

PLANET-7554 Move Take Action block pattern layout into master theme

---

theme.json

This is the latest version. From what I've read in the [migration guide](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-migrations/), we don't need any other changes.

Update theme file version from 2 to 3

---

assets/src/block-templates/page-header/block.json
assets/src/block-templates/page-header/index.js
assets/src/block-templates/page-header/template.js
assets/src/block-templates/template-list.js
assets/src/scss/blocks.scss
assets/src/scss/blocks/PageHeader.scss
src/Loader.php
src/Patterns/BlockPattern.php
src/Patterns/PageHeader.php
src/Patterns/PageHeaderImgLeft.php

Ref. https://jira.greenpeace.org/browse/PLANET-7401
**Testing**
- Create a new page
- Click on "+" and click on "Patterns" tab
- The Page Header block pattern should be visible on that list

PLANET-7401 Move Page Header block pattern into master theme

---

assets/src/js/query-no-posts.js

Otherwise we get a console error that it is undefined:
On any page, on `main` branch you should see the above error, whereas with the changes on this branch it should be gone.

Make sure 'no post text' exists before manipulating it

---

assets/src/block-templates/deep-dive-topic/block.json
assets/src/block-templates/deep-dive-topic/index.js
assets/src/block-templates/deep-dive-topic/template.js
assets/src/block-templates/template-list.js
src/Patterns/BlockPattern.php
src/Patterns/DeepDiveTopic.php

**Ref:** https://jira.greenpeace.org/browse/PLANET-7550
**Description:** This PR adds the "Deep Dive Topic" pattern block to the master theme.
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1228

PLANET-7550: Move Deep Dive Topic pattern block to theme

---

.circleci/config.yml
composer.json
composer.lock
exporter-helper.php
src/Loader.php

See [PLANET-7389](https://jira.greenpeace.org/browse/PLANET-7389)
**Issues fixed:**
- MissingNativeTypeHint at Loader.php
- Function utf8_encode() has [been deprecated](https://mixable.blog/php-function-utf8_decode-and-utf8_encode-have-been-deprecated/)
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1229

PLANET-7389 Add PHP8.3 tests job

---

src/GravityFormsExtensions.php

**Ref: https://jira.greenpeace.org/browse/PLANET-7556**
Ticket also contains changes for **https://jira.greenpeace.org/browse/PLANET-7479**

PLANET-7556 Implement purchase dataLayer event for forms without redirect

---

src/GravityFormsExtensions.php

Ref: https://jira.greenpeace.org/browse/PLANET-7596

PLANET-7596 Gravity forms won't send thank you pages

---

assets/src/scss/base/_body.scss

Ref: https://jira.greenpeace.org/browse/PLANET-7602
Currently is using the one provided by bootstrap
Check it out the assigned instance

PLANET-7602: Fix link hover color

---

assets/src/blocks/Counter/CounterScript.js

This PR fixes [the following error](https://greenpeace.slack.com/archives/C0151L0KKNX/p1725647132531729) in the Counter block, based on the solution discovered [here](https://github.com/greenpeace/planet4-master-theme/pull/2369):

Fix error in the Counter block

---

assets/src/blocks/Cookies/CookiesBlock.js
assets/src/blocks/Cookies/CookiesEditor.js
assets/src/blocks/Cookies/CookiesFrontend.js
assets/src/blocks/Cookies/CookiesScript.js

See [PLANET-7606](https://jira.greenpeace.org/browse/PLANET-7606)
In this PR I also try separating the backend and frontend files, I feel it's less confusing that way and more consistent with what we do with other blocks, but let me know what you think 🙂 
- [Broken version](https://www-dev.greenpeace.org/test-pluto/privacy-and-cookies/)
- [Fixed version](https://www-dev.greenpeace.org/test-nix/privacy-and-cookies/)

 PLANET-7606 Fix Cookies block crashing in the frontend

---

assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
assets/src/scss/pages/post/_article-content.scss

Added a margin bottom for the take action boxout and button block on posts.

Bug fix: Take Action Boxout spacing below missing

---

assets/src/scss/core-overrides/embed.scss

**Ref: https://jira.greenpeace.org/browse/PLANET-7631**

PLANET-7631 Twitter embed doesn't work in the frontend

---

assets/src/js/Components/ArchivePicker/ArchivePicker.js
assets/src/js/Components/ArchivePicker/SingleSidebar.js
assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
assets/src/js/media_archive.js
assets/src/js/media_archive_editor_view.js

**Ref: https://jira.greenpeace.org/browse/PLANET-7525**
**Testing:**
Adding Featured Image should now work with Greenpeace Media.

PLANET-7525 Media Import does not work with Featured Image

---

assets/src/scss/blocks/CarouselHeader/CarouselHeaderStyle.scss

In preparation of #2188 we need to split fixes and improvents in small PRs, and then easy to review and merge.
Is not currently possible to click on controls. That's why the related spec is failing.

Fix Carousel Header layout

---

single-campaign.php
src/CustomTaxonomy.php
src/DevReport.php
tag.php
taxonomy.php

This PR fixes the following warnings and errors reported by Sentry:
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/954
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/955
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/956
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/957
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/1885
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/109
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/160
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/202
- https://sentry.greenpeace.org/organizations/greenpeace-org/issues/452

Fix warnings and errors reported by Sentry

---

assets/src/js/listing_pages.js
assets/src/scss/layout/_forms.scss
assets/src/scss/pages/_listing-page.scss
functions.php
src/ListingPage.php
templates/listing-page-filters.twig
templates/listing-page.twig

See [PLANET-7614](https://jira.greenpeace.org/browse/PLANET-7614)
You can check the [News & Stories page](https://www-dev.greenpeace.org/test-oberon/news-stories/) on the oberon instance. Please also make sure that the other listing pages (tag, category, author...) are not affected!

PLANET-7614 Add categories filter to News & Stories page

---

templates/search.twig

Fix tiny search page typo

---

functions.php

**URL for see all posts link was hard coded, now it has been updated to render dynamically.**

Fix Related Posts URL for see all posts

---

assets/src/scss/blocks/core-overrides/MediaText.scss

See [PLANET-7651](https://jira.greenpeace.org/browse/PLANET-7651)
Make sure that all screen sizes look good, also for the "normal" Media & Text block.
- [Broken version](https://www-dev.greenpeace.org/test-rhea/test-page/)
- [Fixed version](https://www-dev.greenpeace.org/test-pluto/test-page/)

PLANET-7651 Fix PageHeader for tablets

---

.github/pull_request_template.md

- Add certain sections, instead of just hiding everything in comments
- Add help texts as comments
- Add Testing section

Expand PR template

---

src/MasterBlocks.php
src/Post.php

This was reported by Sentry, see [here](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/3088/?alert_rule_id=4&alert_type=issue&notification_uuid=85a83776-6955-4ed4-add8-df27293a1b7a&project=2&referrer=slack), hopefully this will solve it. I also took this opportunity to update some variable names that were not making sense.

Fix undefined act_page warning

---

assets/src/js/query_loop_carousel.js

See [PLANET-7697](https://jira.greenpeace.org/browse/PLANET-7697)
This is for the carousel style
Here is an [example page](https://www-dev.greenpeace.org/test-deimos/carousels/) with the different possibilities!

PLANET-7697 Add Posts/Actions List indicators only when needed

---

assets/src/js/query_loop_carousel.js
assets/src/scss/layout/_query-loop-overrides.scss

Follow up #2501.
Remove interval prop and reset ordered list style from posts list.
Ref: No ticket needed.
Go to the assigned [demo page](https://www-dev.greenpeace.org/test-saturn/test-carousel/), the carousel should work as expected.

Follow up Carousel issues

---

src/Migrations/M037MigrateCoversContentBlockToPostsListBlock.php
src/Migrations/Utils/Functions.php

Ref: 
- https://jira.greenpeace.org/browse/PLANET-7578
- https://github.com/greenpeace/planet4-master-theme/pull/2461
---
This PR improves the migration script M037 (Content Covers blocks to Posts Lists) by covering cases that have not been considered so far:
- The usage of multiple rows in the Content Covers block ([example](https://www.greenpeace.org/international/about/annual-report/)).
- The usage of the target block as an inner block ([example](https://www.greenpeace.org/usa/climate/)).
- The inline margin for the paragraph block (this adds a separation between the "See all stories" button and the posts when there is no title or description, as [here](https://www-dev.greenpeace.org/international/about/annual-report/))
---
1. Run this PR in your local environment (keep in mind this PR …

PLANET-7578: Improve Migration Script M037

---

src/MasterBlocks.php

Ref. https://jira.greenpeace.org/browse/PLANET-7731
Move javascript files strings translation logic for blocks plugin to master theme.
The JSON files are generated in the handbook and pushed to the master theme's [language](https://github.com/greenpeace/planet4-master-theme/tree/main/languages/blocks) folder.
Ref: 
[Related PR](https://github.com/greenpeace/planet4-handbook/pull/18)
For testing purposes, I installed and activated the pt_BR language on the [test-deimos](https://www-dev.greenpeace.org/test-deimos/story/2094/test-articles-block/) instance.
You can search for a translated JS string in the [language file](https://github.com/greenpeace/planet4-master-theme/tree/main/languages/blocks) and check it on both the frontend and backend of the test instance.
For example, when adding a …

PLANET-7731 Add JS strings translation support for blocks plugin strings

---

assets/src/block-editor/QueryLoopBlockExtension/index.js

See [PLANET-7514](https://jira.greenpeace.org/browse/PLANET-7514)
This is for the Actions/Posts List blocks

PLANET-7514 Update manual override text

---

assets/src/scss/pages/post/_author-block.scss

---
Ref: https://jira.greenpeace.org/browse/PLANET-7711
1. On post page, author block at the bottom should have updated color for author name
2. This [post](https://www-dev.greenpeace.org/test-venus/story/5109/test-author-block/) on the test-instance shows the changes

PLANET-7711 Updated Author link text

---

functions.php

---
Ref: https://jira.greenpeace.org/browse/PLANET-7764
1. Overriding the Author name in posts, the right author name is now picked up in the Posts List block.

PLANET-7764 Fixed Author override update

---

src/Post.php

---
Ref: https://jira.greenpeace.org/browse/PLANET-7741
1. Should fix sentry error linked in ticket

PLANET-7741 Fixed ErrorException

---

tests/e2e/blocks/audio-video.spec.js

This PR fixes the failing Audio & Video e2e tests.
The solution is fairly simple: as the tests tended to run out of time before completion, I split them into multiple ones. Each test creates a new page and examines a particular variant of the blocks. 
---
Ref: https://jira.greenpeace.org/browse/PLANET-7786

PLANET-7786: Fix failing Audio & Video e2e test

---

src/MediaReplacer.php
src/Post.php
src/Sitemap.php
tag.php

This PR fixes the following issues notified by Sentry:
- https://greenpeace-international.sentry.io/issues/6356341865/?project=4508408819417088&query=master-theme&referrer=issue-stream&sort=freq&stream_index=0
- https://greenpeace-international.sentry.io/issues/6352233572/?project=4508408819417088&query=master-theme&referrer=issue-stream&sort=freq&stream_index=2
- https://greenpeace-international.sentry.io/issues/6421613375/?project=4508408819417088&query=master-theme&referrer=issue-stream&sort=freq&stream_index=4
- https://greenpeace-international.sentry.io/issues/6334098596/?project=4508408819417088&query=master-theme&referrer=issue-stream&sort=freq&stream_index=6
Additionally, it fixes the following [issue notified by Grafana](https://greenpeace.slack.com/archives/C014UMRC4AJ/p174246530 …

Fix issues notified by Sentry

---

assets/src/scss/blocks/Counter/CounterStyle.scss

- Update font families, backgorund and text colors
---
Ref: [PLANET-7790](https://jira.greenpeace.org/browse/PLANET-7790)
1. Create a new page
2. Instert a counter block
3. Validate through [Figma](https://www.figma.com/design/9NtbY8n3at8uOEJTsLrETb/P4-Design-System?node-id=1969-53366&t=81Tnp8v0IZ1Z8OEb-1)

Update Counter block layout

---

assets/src/scss/components/_buttons.scss
assets/src/scss/layout/_forms.scss
assets/src/scss/layout/_gravity-forms.scss
src/GravityFormsExtensions.php

This PR fixes the broken links of the files uploaded via Gravity Forms. 
Additionally, it fixes the focus styles of the File fields.
---
In the email body:
In the entries page:
In the single-entry pages:
---
**PART 1:**
1. Go to the [Gutenberg instance](https://www-dev.greenpeace.org/gutenberg/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=notification&id=20&nid=681c6c2adb7ab) and replace the "Send To Email" field in the form with your email address.
2. Go to [this page](https://www-dev.greenpeace.org/gutenberg/form-test-page/), complete the form, and submit it.
3. Check the [form entries](https://www-dev.greenpeace.org/gutenberg/wp-admin/admin.php?page=gf_entries&id=20). The link to the uploaded files should be broken (both in the entries list and the single entry).
4. Check …

PLANET-7460: Fix uploaded file links in Gravity Forms

---

assets/src/scss/base/_mixins.scss
assets/src/scss/editorOverrides.scss
assets/src/scss/pages/_page.scss
assets/src/scss/pages/post/_article-content.scss

See [PLANET-7456](https://jira.greenpeace.org/browse/PLANET-7456). We fixed this a while ago, but limited it to direct children. This fix should be more generic.
You can check this [Post](https://www-dev.greenpeace.org/test-mars/story/1295/list-tests/), this [Action](https://www-dev.greenpeace.org/test-mars/petitions/lists-test/), and this [Page](https://www-dev.greenpeace.org/test-mars/list-tests/), in the frontend and in the editor.

PLANET-7456 Apply link styles in lists

---

src/Blocks/QueryLoopExtension.php

This PR refactors the `QueryLoopExtension` class in order to improve its readability, maintainability, and modularity.
It also adds comments and documentation.
IMPORTANT: The logic is still intact; no changes were introduced to it.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7832
1. Check that the Posts List block properly handles the items added using the Manual Override feature.
2. Check that the Actions List block properly handles the items added using the Manual Override feature.
3. Check that the Actions List block only shows pages when the new IA is disabled.
4. Check that the Actions List block shows pages and actions when the new IA is enabled.

PLANET-7832: Refactor `QueryLoopExtension` class

---

assets/src/scss/blocks/PostsList/PostsListStyle.scss
src/Post.php

Ref: [PLANET-7812 ](https://jira.greenpeace.org/browse/PLANET-7812)
Please check out both possible scenarios:
- [Posts List block](https://www-dev.greenpeace.org/test-pluto/)
- [Related Posts block](https://www-dev.greenpeace.org/test-pluto/press/1109/duis-posuere-4/)

PLANET-7812 Move See All Posts link under the list

---

assets/src/js/Components/ArchivePicker/ArchivePicker.js
assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js

---
**Ref: https://jira.greenpeace.org/browse/PLANET-7698**
1. Create a new Post
2. Add the Topic Link block
3. To add a new background Image, the GP media now works for this block

PLANET-7698 GP Media works in Topic Link block

---

assets/src/js/header.js

Remove mentions of navbar-search-toggle class

---

src/Search/Search.php
templates/comment.twig

This ticket is part of the investigation about Reflected Cross-Site Scripting, or in other words, XSS atack.
After the investigation, I can share a quick solution which is crucial to us. Currently, the users can inject any code through 's' query parameter, for example [here](https://www.greenpeace.org/international/?s=<script>alert(1)<script/>) or a more visual [here](https://www.greenpeace.org/international/?s=%3Cstyle%3Ebody{background:yellow%20!important;}%3C/style%3E).
The solution I provide is to prevent that undesired functionality removing and escaping special characters of the query string.
✅ Storing session or login tokens (though secure systems usually use `[HttpOnly](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies)` cookies, which JS can’t access).
⚠️ Exposing …

PLANET-7820: Research and shared solution(s) of XSS atack

---

src/Search/ElasticSearch.php
templates/tease-search.twig

Add elasticsearch failed query logs to sentry
Ref. https://greenpeace-planet4.atlassian.net/browse/PLANET-7821

PLANET-7821 Fix elasticpress post_date type mapping issue

---

assets/src/js/header.js
assets/src/js/header/setupNavMenu.js

This PR refactors the `header.js` file to make it more modular and easier to maintain. Specifically:
- It moves functions related to navigation toggling from the `header.js` file into the ` setupNavMenu.js` file
- It adds some extra constant values.
---
Ref: https://greenpeace-planet4.atlassian.net/browse/PLANET-7849

PLANET-7849: Refactor `header.js` file I

---

assets/src/js/hide_weak_pw_checkbox.js
src/EnqueueController.php
src/MasterSite.php
webpack.config.js

---
Ref: https://greenpeace-planet4.atlassian.net/browse/PLANET-7907
1.  Creating a new user should trigger an error if password does not validate conditions
2. Also triggers errors on user update and password reset.
3. On user creation/update the `Confirm Weak password` checkbox is no longer visible, passwords must meet certain standards to be acceptable.

PLANET-7907 Strengthen Account Password Policy

---

assets/src/blocks/ActionsList/index.js
assets/src/blocks/PostsList/index.js
src/Migrations/M059AddMissingTypeToButtons.php
src/Migrator.php

When we use the `button` tagName, we also need to set the type in the HTML, otherwise the editor throws an error
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2741
1. Run `npm run db:reset`.
2. Temporarily remove `type="button"` from [this line](https://github.com/greenpeace/planet4-master-theme/blob/main/src/Migrations/Utils/Functions.php#L406) (this is to recreate the previous migration that caused the error in the first place, affecting existing blocks).
3. Run `npx wp-env run cli wp p4-run-activator`
4. You should see the buttons (arrows and "load more") working correctly in the frontend and not throw errors in the editor.
You can also use the following "defect" code to reproduce the error:
```
<div class="wp-block-query actions-list p4-query-loop …
```

Add migration for missing button type

---

src/Blocks/QueryLoopExtension.php

Ref: [PLANET-7919](https://greenpeace-planet4.atlassian.net/browse/PLANET-7919)
[PLANET-7919]: https://greenpeace-planet4.atlassian.net/browse/PLANET-7919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLANET-7919 Fix Sentry warning about undefined post__in

---

assets/src/js/header/setupNavInteractions.js

This is a left over from [PLANET-6577](https://greenpeace-planet4.atlassian.net/browse/PLANET-6577). We don't actively use that anymore, and it's triggering [an exception](https://greenpeace-international.sentry.io/issues/6887931233/?project=4508408819417088) in certain sites.
[PLANET-6577]: https://greenpeace-planet4.atlassian.net/browse/PLANET-6577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove Hotjar tracking event
