greenpeace/planet4-master-theme

- src/Campaigns.php
- src/Features/HideListingPagesBackground.php
- src/Settings/InformationArchitecture.php
- tag.php
- templates/blocks/header.twig
- templates/tag.twig
See [PLANET-6725](https://jira.greenpeace.org/browse/PLANET-6725)
In order to test this behaviour, you need to toggle the new `Planet 4 > Information Architecture > Listing pages background` feature. Then you should no longer see the background and skewed overlay in the tag pages (it seems other listing pages such as author, category/issue and post type don't support adding a background image). You can check this on the pluto test instance, for example with this [tag page](https://www-dev.greenpeace.org/test-pluto/tag/health/).
Please make sure you also test the tag page with the new paginated list enabled (`Planet 4 > Features > Use a paginated list of posts`), both versions should no longer have the background!
> PLANET-6725 Remove listing pages background and overlay

- assets/src/scss/layout/_gravity-forms.scss
See [PLANET-6755](https://jira.greenpeace.org/browse/PLANET-6755)
We move it from the inputs to the form wrapper, to make sure fields are aligned even if side by side
You can test the new GF forms' max width in all screen sizes on this [page](https://www-dev.greenpeace.org/test-saturn/new-gravity-forms-width/) I created for UAT 🙂
> PLANET-6755 Update GF forms max width specification

- assets/src/scss/layout/navbar/languages.scss
- assets/src/scss/partials/navigation-bar-light.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6775
Mena's dev instance: https://www-dev.greenpeace.org/mena
Follow up a design issue.
The chevron icon was not added previously to the [navigation bar mockup](https://www.figma.com/file/Gn8wyqgto7608rlESePXZE/Foundations-%26-Components?node-id=0%3A103) and that was the reason we removed that. We noticed the inconsistent design, because the [search form mockup](https://www.figma.com/file/Gn8wyqgto7608rlESePXZE/Foundations-%26-Components?node-id=665%3A2301) had the chevron, after we merged the code.
> PLANET-6775: Add chevron icon to the languages nav

- assets/src/scss/components/_buttons.scss
- assets/src/scss/editorOverrides.scss
See [PLANET-6712](https://jira.greenpeace.org/browse/PLANET-6712)
This is needed for some block patterns, for now only the Highlighted CTA
**Related PR**: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/849
You can test both the Highlighted CTA pattern and regular buttons on this [page](https://www-dev.greenpeace.org/test-titan/transparent-buttons/) I made for UAT, with several background colors from our palette.
> PLANET-6712 Add transparent style to core Button block

- admin/css/dashboard.css
- src/ControlPanel.php
Ref: https://jira.greenpeace.org/browse/PLANET-6767
> Icons on dashboard (flush part) are so big, I can't flush the cache anymore.
WP 5.9 background image is displayed over our links and prevent clicks. It is because we use the `.welcome-panel` class, that WP uses to display its "welcome new 5.9 version" background.
<table>
<tr><td>Before fix</td><td>After fix</td></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/617346/168778839-90e680e9-7087-4f57-8c5a-48fbe29d4ebb.png" /></td>
<td><img src="https://user-images.githubusercontent.com/617346/168778366-bef766a7-5eea-479a-b86a-d4be93ab5dfb.png" /></td>
</tr></table>
- Removing this class fixes the issue
- Changing markup a bit to fit other panel boxes 
On the admin dashboard, check the Planet4 Control Panel.
- Links should …
> PLANET-6767: Remove control panel overlay blocking clicks

- assets/src/scss/base/_palette.scss
This is needed for some block patterns, for their background color, for example the [Deep Dive](https://jira.greenpeace.org/browse/PLANET-6534) or the [Quick Links](https://jira.greenpeace.org/browse/PLANET-6520).
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/856
You can see the new color used in both text color and background color on [this page](https://www-dev.greenpeace.org/test-iocaste/new-grey-5-color/) for example!
> Add Grey 5% to our color palette

- theme.json
See [PLANET-6788](https://jira.greenpeace.org/browse/PLANET-6788)
This used to be defined in the blocks repo.
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/859
Either on local or on the rhea test instance ([example page](https://www-dev.greenpeace.org/test-rhea/color-tests/)), you can test the new palette in both the editor and the frontend. It should look exactly the same as before, be available for all core blocks (except the Table block for which we have custom background colors), and the colors should be the same in the backend and frontend!
> PLANET-6788 Define color palette in theme.json

- assets/src/scss/base/_palette.scss
- theme.json
See [PLANET-6784](https://jira.greenpeace.org/browse/PLANET-6784) & [PLANET-6787](https://jira.greenpeace.org/browse/PLANET-6787)
In this PR we also add the `white` color to our theme palette, since it will now be the only palette available to editors and that color might be useful to them.
There is also a small commit to update the file version number to 2, since it's the [version number that fits our current WordPress version](https://developer.wordpress.org/themes/advanced-topics/theme-json/#what-is-theme-json). Following this change we had to change the Button block border radius setting removal, from `customRadius` to just `radius`.
Either on local or on the [titan test instance](https://www-dev.greenpeace.org/test-titan/), you can add any core block in the editor and the only color …
> PLANET-6784 Remove WP default color palette

- src/AnalyticsValues.php
Ref: https://jira.greenpeace.org/browse/PLANET-6749
Return a hard-coded list of Global Projects when the sheet is present but its content is invalid
- Move list to constant
- Return hard-coded list if global projects list is empty
- Change handling of [ambiguous](https://github.com/WordPress/wordpress-develop/blob/cd8e14638effe2e4857038b739da56e6d2305040/src/wp-includes/cache.php#L147-L148) cache found
You need  a proper api json key in a `GOOGLE_SHEETS_KEY` constant or `/app/source/sheets-service-account.json` file, and access to the [global projects sheet](https://docs.google.com/spreadsheets/d/1pDAj0jR7WWzUOzBwviFeMGjV8-ocyrE21HYB75oVfOc/edit#gid=0). Without those, the sheet request will fail (unauthorized access) and the Global Project field will be filled by the hard-coded projects …
> PLANET-6749: Display hard-coded list when Global projects sheet fails

- theme.json
See [PLANET-6784](https://jira.greenpeace.org/browse/PLANET-6784)
This allowed editors to add colored filters to certain core blocks:
We should remove this functionality as part of our WP core color palette removal. 
Either on local or on the [titan test instance](https://www-dev.greenpeace.org/test-titan/), when adding certain core blocks (such as Image) in the editor you should no longer see the controls associated to this duotone functionality.
> PLANET-6784 Remove color duotone functionality

- exporter-helper.php
- src/Importer.php
Ref: https://jira.greenpeace.org/browse/PLANET-6773
Taken from the ticket:
> From the recent experience of Brasil migration, we noticed that the imported posts in production kept their dev-site media url.
**In the above image you see that the page is on `www-stage` and the image is taken from `www-dev`.**
_Since we haven't changed a lot of part of the code, the solutions seems to be an easy fix. However, the hardest and tedious part was the analysis and the way of testing it._
The page would render correctly the `<img>` with all the correct values and don't render anything related to the previous exported instance. For example, if you create a post from `-dev` and export it and then import it to `-stage` you wouldn't see any URL related to `-dev` and vice-versa.
I used the Argentina dev's …
> PLANET-6773: Fix WP importer fetches media along with posts

- src/MasterSite.php
Replicated from https://github.com/greenpeace/planet4-master-theme/pull/1727
Closes https://github.com/greenpeace/planet4/issues/179
Applies a filter to the parameters used to load an embedded Youtube video. Enables child themes to modify the functionality of the embedded Youtube player [using the supported parameters](https://developers.google.com/youtube/player_parameters#Parameters).
One relevant use case is to enable the JS API in order to get better video data in Google Analytics.
[Slack thread](https://greenpeace.slack.com/archives/C0151L0KKNX/p1654089635150519)
> Apply filter to youtube embed parameters

- src/MasterSite.php
- templates/burger-menu.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6805
Use the default provided from Planet4 > Donate button instead the "Make a donation" text. It avoids to use a duplicated donate button into the burger menu.
**New Logic**
- If the Donate button has not been created, then use the default one through the `navbar` and burger menu.
- If the donate button has been created, then show on the `navbar`. And if it has at least one item, then show it also in the burger menu.
- The "Make a donation" button is now replaced by the default settings.
Play around within the donate dropdown menu (Appearance > Menu) and the default donate button (Planet4 > Donate Button).
> PLANET-6805: Change donate button text through the burger menu

- assets/src/scss/editorOverrides.scss
See [PLANET-6687](https://jira.greenpeace.org/browse/PLANET-6687)
Without this fix, the placeholder is white regardless of the actual text color.
On local, you can test the fix with any empty Button block (without text) by changing the style (esp. `secondary` since it doesn't have white text color) or by picking a new text color from the palette. On this branch you should see the text color always being applied to the placeholder, whereas on `master` branch it would remain white.
> PLANET-6887 Fix placeholder color for Button block

- assets/src/scss/layout/_navbar.scss
- assets/src/scss/layout/navbar/_desktop-menu.scss
This change it's very helpful to understand the styles related to the desktop menu template, all of those [are currently added within the navbar](https://github.com/greenpeace/planet4-master-theme/blob/master/assets/src/scss/layout/_navbar.scss#L94-L99) and doesn't seem to be helpful.
We should do the same as we did with the burger menu. (template + styles). 
This is also a preparation of this [ticket](https://jira.greenpeace.org/browse/PLANET-6794)
> Move desktop styles to a file

- assets/src/scss/layout/_forms.scss
See [PLANET-6789](https://jira.greenpeace.org/browse/PLANET-6789)
Without this, the label sometimes blocks clicking on the field to start typing.
You can test the fix with any EN form block.
> PLANET-6789 Add pointer-events none to animated form field labels

- src/Settings/InformationArchitecture.php
A PHP Notice appears when an IA option is not yet set
https://output.circle-artifacts.com/output/job/7c8a73d8-065a-4632-aa3b-b8f29ac061a3/artifacts/0/artifacts/codeception/report.html
> Fix php notice when IA option unavailable

- src/ElasticSearch.php
- src/Search.php
- src/Search/Filters/ActionTypes.php
- src/Search/Filters/Categories.php
- src/Search/Filters/ContentTypes.php
- src/Search/Filters/PostTypes.php
- src/Search/Filters/Tags.php
- templates/search.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6652
Ref: https://jira.greenpeace.org/browse/PLANET-6797
Ref/ https://jira.greenpeace.org/browse/PLANET-6578
Clarify search code by matching native taxonomy with class structure 
- Extract search filters to their own classes
- Rename page_types to post_types
- Hide tags search
- Add p4_action type to search
> PLANET-6652: Extract search filters

- theme.json
Ref: https://jira.greenpeace.org/browse/PLANET-6811
Ref: https://github.com/WordPress/gutenberg/issues/40383
---
Our current `theme.json` option doesn't work in 6.0. You will probably see a validation error in your editor, because `null`
is not yet reflected in the official schema, but it does seem to work without issues.
1. You need to be running Wordpress 6.0
2. While on `master` branch in the theme, add an image block. You should be seeing the Duotones button in the formatting toolbar.
3. `git checkout -t origin/duotone-false`
4. `make flush` (just in case)
5. No duotone button anymore.
I haven't tested this with 5.9 yet, but if it creates issues we can hold merging it till the actual upgrade.
> PLANET-6811 Remove default duotones

- assets/src/scss/pages/search/_search-results.scss
See [PLANET-6744](https://jira.greenpeace.org/browse/PLANET-6744)
This is to comply with the new designs.
On local, you can check any post type listing page (such as [Story](http://www.planet4.test/story/) or [Publication](http://www.planet4.test/publication/)) and compare both versions: on `master` branch you'll see the author name is not bold, whereas on this branch it should be.
Or you can see the fix on the test instance, on the [Story](https://www-dev.greenpeace.org/test-pluto/story/) or [Publication](https://www-dev.greenpeace.org/test-pluto/publication/) listing pages for example.
> PLANET-6744 Make listing pages author name bold

- assets/src/scss/pages/_page.scss
- templates/page.twig
See [PLANET-6325](https://jira.greenpeace.org/browse/PLANET-6325)
Without this fix the navbar overlaps the page content if there is no title
You can compare both versions on these pages I set up without title:
- [Broken](https://www-dev.greenpeace.org/test-mars/no-page-title/)
- [Fixed](https://www-dev.greenpeace.org/test-umbriel/no-page-title/)
> PLANET-6325 Add padding top to pages with no title

- assets/src/scss/pages/post/_author-block.scss
See [PLANET-6822](https://jira.greenpeace.org/browse/PLANET-6822)
Without this fix, if the bio info is too short the image takes more space and the block looks weird.
On local, you can add a short bio (such as "Morbi ac congue ipsum.") to one of your users, then go to a post written by this user. On `master` branch, in screen sizes medium and up you should see the image take too much space in the author block, whereas on this branch it should show aligned to the start as expected.
You can also compare the [broken version](https://www-dev.greenpeace.org/test-oberon/story/51096/post-title-goes-here-it-can-be-this-long/) with the [fixed version](https://www-dev.greenpeace.org/test-deimos/blog/36520/por-que-precisamos-de-um-tratado-global-dos-oceanos/) in test instances.
> PLANET-6822 Fix author block image margins

- assets/src/js/menu_editor.js
- assets/src/scss/layout/_navbar.scss
- assets/src/scss/layout/navbar/languages.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6794
- ~Add a new XXL screen value (1400px), based on [Bootstrap breakpoints](https://getbootstrap.com/docs/5.0/layout/breakpoints/#available-breakpoints), and don't use the [XXL P4's breakpoint](https://github.com/greenpeace/planet4-master-theme/blob/master/assets/src/scss/base/_variables.scss#L11).~
- ~Remove Bootstrap's inline classes.~
- Add a Notice info message.
Demo page: Using the [Belgium's dev instance](https://www-dev.greenpeace.org/belgium/fr/) not only because they reported the issue but also because they have a Multi language site.
Please take a look all the comments I left about to changed files explaining about some of their changes.
> PLANET-6794: Fix languges switcher through the navigation bar

- functions.php
Ref: https://jira.greenpeace.org/browse/PLANET-6831
WP stateless plugin short-circuits the [image_downsize()](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/media.php#L191) process with [wpCloud\StatelessMedia\Bootstrap::image_downsize()](https://github.com/udx/wp-stateless/blob/b685a67f2961d1459874da461586b4ae1bde853d/lib/classes/class-bootstrap.php#L1322).
Contrary to [the native function](https://github.com/WordPress/wordpress-develop/blob/0abc2b2a5bbc6737a7c31d28456037be91a0bfa7/src/wp-includes/media.php#L222-L229), it will return attachment data [even if the attachment is not an image](https://github.com/udx/wp-stateless/blob/b685a67f2961d1459874da461586b4ae1bde853d/lib/classes/class-bootstrap.php#L1385-L1390).
The attachment is then treated as an image by …
> PLANET-6831: Fix PDF attachment links missing in attachment pages

- .stylelintrc
- assets/src/js/menu_editor.js
Making `stylelint` happy, since this property is needed for `line-clamp`.
And adding a missing semicolon to make `eslint` also happy.
Frontend tests are [currently failing](https://app.circleci.com/pipelines/github/greenpeace/planet4-master-theme/5942/workflows/688bf238-d345-4785-8d11-e8377d154e08/jobs/37372/parallel-runs/0/steps/0-102) because of [-webkit-box-orient](https://github.com/greenpeace/planet4-master-theme/blob/61ba0e0f6e32c1a40fdebe8ce2d33689ad313b93/assets/src/scss/pages/post/_article-content.scss#L255).
> Allow box-orient to be vendor prefixed

- src/AdminAssets.php
Ref: https://jira.greenpeace.org/browse/PLANET-6845
> Houssam and I noticed that WPML sites, such as Belgium or MENA, has the Menu restrictions not working as expected.
Because of a mistake in a condition, if the Donate menu location doesn't exist on the instance, the menu configuration limitations are not applied to the editor.
Fixing the condition to work if at least one of the menus location exists.
> PLANET-6845: Fix menu config loading

- templates/blocks/google_antiflicker.twig
- templates/blocks/google_tag_manager.twig
- templates/html-header.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6844
> Check relevant discussions [here](https://greenpeace-gpi.slack.com/archives/C0151L0KKNX/p1656962941586809) and [here](https://greenpeace-gpi.slack.com/archives/C0151L0KKNX/p1656510365584269).
> Google Optimize reports (see screenshot) that the snippet is not installed in the right place or not installed at all.
- Re order scripts
- Extract anti-flicker to its own template, to make it easier to modify/edit/remove
- Change anti-flicker last parameter to make it appear "non-standard" and avoid installation check error in Optimize
- Add anti-flicker duration log to check for good run or timeout
- Include anti-flicker only if an a/b selector is configured
Optimize installation check now reports only a Warning, instead of various errors. …
> PLANET-6844: Anti-flicker snippet does not load properly

- assets/src/scss/editorOverrides.scss
The intention is to show the pattern description above the pattern preview for a better readability. 
This change has been suggested by Suzi, here is the [Slack's thread](https://greenpeace-gpi.slack.com/archives/G014JEXDUHJ/p1657303099711689?thread_ts=1657291502.321389&cid=G014JEXDUHJ).
Ref: https://jira.greenpeace.org/browse/PLANET-6847
**Test**
1. create a new page
2. Then see how the modal looks like. The title must be above the pattern preview
> PLANET-6847: Improve the Page Create Patterns modal layout 

- composer.json
Ref: https://jira.greenpeace.org/browse/PLANET-6850
Ref: https://getcomposer.org/doc/06-config.md#allow-plugins
---
This is required by newer composer versions.
Main PR: https://github.com/greenpeace/planet4-docker/pull/101
> PLANET-6850 Add allow-plugns config to composer

- assets/src/scss/base/_colors.scss
- assets/src/scss/components/_buttons.scss
- assets/src/scss/editorOverrides.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6698
> - Remove the Donate button style's associated CSS (class name "is-style-donate").
> - Remove the "aquamarine" color from our codebase (including theme.json) since it's used nowhere else.
> - Check existing content and maybe warn NROs that still use this style.
[`$aquamarine`](https://github.com/search?q=org%3Agreenpeace+aquamarine&type=code) and [`is-style-donate`](https://github.com/search?q=org%3Agreenpeace+is-style-donate&type=Code) are locally copied in the child-theme where they're used.
> PLANET-6698: Remove the Donate button styles and classes

- theme.json
This feature is going to be used by the [issues pattern](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/914/files#diff-48b8904c9490414ea5f81b24352f93cd7ebc7c65369ba952fbfebaa35f0d5f5fR32) among others.
Related PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/914
- Create a new page and add a `core/group`. You'll be able to see the below settings
- More info about the [Wodrpress's Dimension feature](https://wordpress.com/support/wordpress-editor/blocks/row-block/)
- [Code reference](https://developer.wordpress.org/reference/classes/wp_theme_json/get_settings/)
> Add spacing feature to theme

- src/GravityFormsExtensions.php
- src/Loader.php
Added a new section named "Planet 4 Options" in form settings and added formtype in it
[JIRA 6569](https://jira.greenpeace.org/browse/PLANET-6569)
**Testing:**
- Create a [new Gravity form](https://www-dev.greenpeace.org/test-nix/wp-admin/admin.php?page=gf_new_form)
- Go to "Form Settings" , update the form type field, the default value should be 'Other'
> PLANET-6569 Add form type field in Gravity form settings

- src/PublicAssets.php
Variable `$filename` generates a Notice because it's not defined
Typo on filename -> file
> Fix notice on undefined $filename variable

- src/Commands.php
- src/Commands/GFAddonsDisconnect.php
Ref: https://jira.greenpeace.org/browse/PLANET-6854
Used by: https://github.com/greenpeace/planet4-builder/pull/102
Add a command to disconnect Gravity forms addons.
```console
> wp p4-gf-addons disconnect
```
To be used in sql sync scripts, cf https://github.com/greenpeace/planet4-builder/pull/102/files
> PLANET-6854: Disconnect GF addons authentication

- assets/src/scss/layout/_footer.scss
Ref: [PLANET-6873](https://jira.greenpeace.org/browse/)
The color must be always in white in all its states (active, hover, etc).
Demo page: Just visit the [current instance](https://www-dev.greenpeace.org/test-janus)
> PLANET-6873: Fix the color of links from footer

- templates/blocks/title.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6895
> If Opengraph title has been set, [we use](https://github.com/greenpeace/planet4-master-theme/blob/aa58c884132cbe4cfe8a01194a1953ceb06d38ff/templates/blocks/meta_fields.twig#L18-L24) that to override the meta title tag (same for description).
We should do the same for the actual [title tag](https://github.com/greenpeace/planet4-master-theme/blob/aa58c884132cbe4cfe8a01194a1953ceb06d38ff/templates/blocks/title.twig). That would allow editors to have a more SEO-friendly title for search bots while using a slightly different/bigger for the actual content.
Prioritize Open graph title if it exists as `<title>` tag.
- create a page with a specific title
- add a different title in the _Open Graph > Title_ field, at the bottom of the editor
- …
> PLANET-6895: Use open graph title for title tag

- src/GravityFormsExtensions.php
See [PLANET-6861](https://jira.greenpeace.org/browse/PLANET-6861)
This is to clarify what this setting is for.
You can check out this new tooltip in any Gravity Forms form's settings (or on the [test instance](https://www-dev.greenpeace.org/test-umbriel/wp-admin/admin.php?page=gf_edit_forms&view=settings&id=1)!)
> PLANET-6861 Add tooltip to P4 form type setting for Gravity Forms

- assets/src/scss/layout/_gravity-forms.scss
- functions.php
- src/GravityFormsExtensions.php
- templates/gravity_forms_confirmation.twig
See [PLANET-6808](https://jira.greenpeace.org/browse/PLANET-6808)
You can test the new confirmation message either on this [page](https://www-dev.greenpeace.org/test-neptune/33089-2/) that I created for UAT, or on your local using any GF form. I also added a Planet 4 option to Gravity Forms to allow editors to choose whether or not they want to use our message or create a custom one! I've added a tooltip to explain that it's not possible to see or edit it via the Confirmations tab if they select the P4 one. You can test that new setting [here](https://www-dev.greenpeace.org/test-neptune/wp-admin/admin.php?page=gf_edit_forms&view=settings&id=1) for example 🙂
> PLANET-6808 Update Gravity Forms thank you message

- assets/src/scss/base/_mixins.scss
Cf. https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/934
Used to extend columns scrolling behavior to screens < 1200px
> Add mixin for screen < 1200px

- src/ActionPage.php
See [PLANET-6890](https://jira.greenpeace.org/browse/PLANET-6890)
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/937
You can test the new checkbox either on local on any Action page, or on [this one](https://www-dev.greenpeace.org/test-telesto/action/the-first-action-page/) that I created for UAT. Note that just like the corresponding meta option available in pages/posts, you need to update (and not just preview) the page before you see the change applied!
> PLANET-6890 Add meta field to hide page title in Actions

- assets/src/js/pdf_icon.js
- src/Search.php
- templates/tease-search.twig
See [PLANET-6405](https://jira.greenpeace.org/browse/PLANET-6405)
This PR also includes a small refactoring to get rid of some unnecessary/unused variables.
On the pluto test instance, you can [search for documents](https://www-dev.greenpeace.org/test-pluto/?s=&orderby=_score&f%5Bctype%5D%5BDocument%5D=1) and make sure that the download buttons with PDF icons are shown for all the corresponding results (even the ones after clicking the "show more" button)
> PLANET-6405 Fix download icon not showing in later search results

- assets/src/js/load_more.js
- functions.php
- index.php
- src/Search.php
- templates/all-posts.twig
Ref: [PLANET-6527](https://jira.greenpeace.org/browse/PLANET-6527)
Demo page: https://www-dev.greenpeace.org/test-tavros/news-stories/
This is the new default listing page when the "Posts page" setting From Reading Settings is changed.
The UI should be similar to the [Category page](https://www-dev.greenpeace.org/test-rhea/category/issues/energy/) but without the description.
Other features that we would have to include: (taken from the ticket's description)
- Check if we can disable the ability to add blocks/content on the page that is set as 'posts page', to minimize editor confusion.
- Check if we can update the warning text that shows up in the yellow box at the top. If we can, I (suzi) will provide text for it.
This is how the editor looks like 👇 and there is no possibility to add …
> PLANET-6527: Style the default 'all posts' listing page

- assets/src/js/header.js
- assets/src/scss/layout/_navbar.scss
See [PLANET-6897](https://jira.greenpeace.org/browse/PLANET-6897)
We don't want the page to scroll back to top when toggling the burger menu
Either on local or on the [oberon test instance](https://www-dev.greenpeace.org/test-oberon/), when opening the side menu on mobile/tablet devices after scrolling down the page a bit, the page should no longer scroll back to top. On tablets make sure that you also cannot scroll through the page when the side menu is open!
> PLANET-6897 Fix scroll to top bug when opening side menu

- src/GravityFormsExtensions.php
Ref. https://jira.greenpeace.org/browse/PLANET-6867
The default gravity form uploaded files path gives error.
eg. 
https://www.greenpeace.org/static/planet4-test-titan-stateless-develop/gravity_forms/8-23c5dc88bb5af48eb293c4c780a5ed0a/2022/09/e26f3fe9-2022_08_gravity_forms_3-1b36ac6eddacf20087d29746b297b384_2022_08_99ef18e1-predator.jpg
By updating a part[/year/month/] of file path('/gravity_forms/' => '/2022/09/gravity_forms/') fix the issue.
(**Note:** I also tested the `WP_STATELESS_COMPATIBILITY_GF` [flag](https://wp-stateless.github.io/docs/constants/) but it won't make any change in the current issue though it's good to have [enabled](https://github.com/greenpeace/planet4-docker/pull/103). )
**Testing:**
- Add form details with file upload at [test-rhea …
> PLANET-6867 Fix Gravity form file path before output

- src/GravityFormsExtensions.php
See [PLANET-6907](https://jira.greenpeace.org/browse/PLANET-6907)
By default we want the sub-label and description to be above inputs instead of below
I've created a new form on the test instance for UAT, in its [settings](https://www-dev.greenpeace.org/test-phoebe/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=settings&id=1) you can see that now by default both fields are set to "Above inputs". On local or on the instance, you can also add a new form yourself and make sure that the initial values are properly set.
> PLANET-6907 Update Gravity Forms settings initial values

- templates/single.twig
See [PLANET-6915](https://jira.greenpeace.org/browse/PLANET-6915)
This filter was messing up Gravity Forms forms on posts.
> PLANET-6915 Remove wp_kses_post filter from post content

- assets/src/scss/layout/_cookies.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6908
---
To avoid Cookie Box contributing to CLS metrics, we remove the slide animation
and instead show the Cookie Box directly in its final position.
> PLANET-6908 Remove Cookies box slide animation

- src/GravityFormsExtensions.php
Without this check, if editors didn't manually save the confirmation message then the buttons don't show in the frontend (and you see some warnings on local). If not defined, we set them to true since we want to show them by default. 
You can test this behaviour on local by creating a new form and not editing/saving the confirmation message. On this branch the share buttons should then show in the confirmation message, whereas on `master` they won't. Another option to fix this issue would maybe be to set the share buttons values for new forms in [this after save function](https://github.com/greenpeace/planet4-master-theme/blob/master/src/GravityFormsExtensions.php#L167), but that wouldn't solve the problem for existing forms which is the reason why I've gone for this fix instead!
> Check if share platforms are set for GF confirmation message

- assets/src/scss/pages/search/_search-results.scss
- templates/tease-search.twig
See [PLANET-6913](https://jira.greenpeace.org/browse/PLANET-6913)
This PR also includes small design fixes for search results that have buttons (PDF documents and now Actions)
You can test the changes on [this page](https://www-dev.greenpeace.org/test-pluto/?s=greenpeace&orderby=_score) for example where the search parameters show you both an Action page and a Document. Make sure to test in all screen sizes 🙂
> PLANET-6913 Show button in search results for Actions

- assets/src/scss/components/_buttons.scss
- assets/src/scss/editorOverrides.scss
See [PLANET-6780](https://jira.greenpeace.org/browse/PLANET-6780)
This was previously used in block patterns until we added the transparent style to Buttons
> PLANET-6780 Remove unused transparent-button class

- src/GravityFormsExtensions.php
Since we check for the message string it's possible that if the string is too complicated (seems the problem is when there's a line break) then the corresponding object is not found.
I think this would solve the issue [GP Brazil is having at the moment](https://greenpeace.slack.com/archives/C0151L0KKNX/p1664374752896649?thread_ts=1663783124.723999&cid=C0151L0KKNX).
**Note:** I'm checking for the message in order to find the right confirmation object, because editors can add several confirmation messages and also add share buttons there. However, depending on how often this happens, maybe it would make sense to only allow the share buttons for the default confirmation, in that case we could check for `isDefault` which would always return something since it's mandatory... Maybe we could …
> Return current GF confirmation if no corresponding one is found

- src/GravityFormsExtensions.php
We need to strip all HTML tags from the confirmation messages for the comparison to work properly.
You can test these changes on [this page](https://www-dev.greenpeace.org/test-janus/gravity-forms-confirmation-tests/?) for example! For this form I've created a new confirmation message, which shows only if the input contains the `a` character. If the input doesn't contain this letter then you will see the default confirmation message. Both of these confirmation messages have different share buttons, and one of them has some bold HTML tags, to make sure that the comparison works as expected.
> Fix Gravity Forms confirmations filtering

- .circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5872
---
Re-enables a11y tests, but instead of spawning a full docker-compose setup, move the job a bit further in the pipeline and use the test instance that's already deployed.
For now the job passes in any case. Once we refine a11y tickets and fix the issues we can account for the errors and make it fail.
---
Using the container images from https://github.com/greenpeace/planet4-circleci-unit-tests/pull/12
[Example a11y report](https://output.circle-artifacts.com/output/job/62efab4e-faad-4c26-9979-96c0ccb98e18/artifacts/0/home/circleci/pa11y-ci-report/index.html)
> PLANET-5872 Run a11y against test instances

- src/Loader.php
- src/MetaboxRegister.php
- src/Page.php
- src/PostCampaign.php
See [PLANET-6901](https://jira.greenpeace.org/browse/PLANET-6901)
These fields will now be in the sidebar (see [related PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/942))
You can test the changes in any page or campaign, either on local or on the tavros test instance!
> PLANET-6901 Remove Page Header metabox fields

- src/ActionPage.php
- src/Search.php
- templates/tease-search.twig
See [PLANET-4444](https://jira.greenpeace.org/browse/PLANET-4444)
This text will be shown in the Covers block, the Take Action boxout and in search results.
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/957
You can test the 3 possibilities (no button text, default button text, and custom button text)
- in the Covers block on [this page](https://www-dev.greenpeace.org/test-titan/text-actions-button-texts/) for example
- in the Search page [here](https://www-dev.greenpeace.org/test-titan/?s=button+text&orderby=_score) for example
You can also test changing the default text in the [P4 settings](https://www-dev.greenpeace.org/test-titan/wp-admin/admin.php?page=planet4_settings_defaults_content) to see how the block and search results are impacted!
> PLANET-4444 Add meta field for Action button text

- functions.php
See [PLANET-6678](https://jira.greenpeace.org/browse/PLANET-6678)
This PR adds a filter to alphabetically sort the Planet 4 settings menu.
> PLANET-6678 Alphabetically order Planet 4 settings menu

- src/ActionPage.php
- src/Loader.php
- src/MetaboxRegister.php
- src/PageMeta.php
- src/PostCampaign.php
- src/PostMeta.php
See [PLANET-6900](https://jira.greenpeace.org/browse/PLANET-6900)
These fields are now moved to the sidebar (see [related PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/954))
On your local or on the [mars test instance](https://www-dev.greenpeace.org/test-mars/), you can add the Open Graph meta fields from the sidebar to any post/campaign/page/action and update the page. On reload in the editor you should still see the data that you entered, and when inspecting the page in the frontend you should see the correct meta fields added to the `head`:
You can also test the fields using this tool: https://www.opengraph.xyz/
> PLANET-6900 Remove Open Graph metabox

- assets/src/scss/layout/_navbar.scss
- assets/src/scss/partials/navigation-bar-light.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6950
Fix the visited color and set to the default one. Now it's set to purple.
Example of issues:
- [GPI Take Action page](https://www.greenpeace.org/international/act/stop-deep-sea-mining/)
- [GPGR Take Action page](https://www.greenpeace.org/greece/epirease/receptionist-secretarial-assistant-on-site/)
[The Greece dev site is using this branch](https://github.com/greenpeace/planet4-greece/commit/e094426189c9fc80bb34244665250f14f10bde51), don't test through the current instance (Phobos).
Remember to test the light and dark mode too ⚠️ 
**Demo page** 👉  https://www-dev.greenpeace.org/greece/epirease/receptionist-secretarial-assistant-on-site/
> PLANET-6950: Add new visited pseudo class style

- assets/src/scss/layout/_navbar.scss
- src/AdminAssets.php
See [PLANET-6948](https://jira.greenpeace.org/browse/PLANET-6948)
With this change we also allow dropdown menu items to be up to 32 characters long.
In the backend, in `Appearance > Menus`, you should now see a warning appear only when a dropdown menu item's name is longer than 32 characters. For the main menu items however the limit remains 18 characters. 
In the frontend, you should see that the dropdown menu is now `240px` wide (instead of previously `193px`).
> PLANET-6948 Increase the size of the navigation bar drop-down menu

- src/GravityFormsExtensions.php
Ref https://jira.greenpeace.org/browse/PLANET-6929
Use a `confirmation` param instead of `confirmations` from $form [Form Object](https://docs.gravityforms.com/form-object).
The `confirmation` param returns the [Confirmation Object](https://docs.gravityforms.com/confirmations-object/#confirmation-properties) being used for the current form submission.
Reference:
https://docs.gravityforms.com/form-object/
> PLANET-6929 Fixed GF confirmation message share button issue

- src/GravityFormsExtensions.php
Ref https://jira.greenpeace.org/browse/PLANET-6930
- Pass the `social_accounts` & `utm_medium` params to twig file.
- Conditionally pass the `share_text` & `share_url` params to twig file
eg. https://www-dev.greenpeace.org/test-venus/test-gravity-form-share-buttons-text/
> PLANET-6930 Fix Gravity Forms share text issues

- functions.php
PLANET-6955 ErrorException: Warning: uasort() expects parameter 1 to be array, null given
- Added a condition to check if planet 4 settings array returns a value before sorting, to avoid sentry error.
Ticket [here](https://jira.greenpeace.org/browse/PLANET-6955)
> PLANET-6955 ErrorException: Warning: uasort() expects parameter 1 to be array, null given

- .circleci/config.yml
- [Remove lighthouse job](https://github.com/greenpeace/planet4-master-theme/pull/1828/commits/566d0a09959922738182b802d761604475355fec) 
As discussed, removing it from app repos. Instead we should focus on providing performance data on live production sites.
- [Add workflow definitions to simplify pipelines](https://github.com/greenpeace/planet4-master-theme/pull/1828/commits/a87f00f62cb022b87056145b1a047558cd0cae43) 
Removed most of the tests from main branch, since we practically only need/use them in PRs. Instead added a new simplified `reset-instance` job to just reset the test instances on merge. Simplified also `request-instance` job, since now it will only run on PR branches. Potentially we can now simplify the scripts used there but these are in a different repo.
> Simplify Ci config

- assets/src/scss/pages/_listing-page.scss
- assets/src/scss/style.scss
Ref: [PLANET-6928](https://jira.greenpeace.org/browse/PLANET-6928)
Since we're having a couple of listing pages (default, category, action, among others), the idea is to standardize their styles by using the same style sheet.
This pull request it's blocked by https://github.com/greenpeace/planet4-master-theme/pull/1812
> PLANET-6928: Create a new listing page stylesheet

- archive-p4_action.php
- archive.php
- parts/action/query-grid.html
- parts/action/query-list.html
- src/Features/ListingPagePagination.php
- src/Post.php
- templates/all-actions.twig
- templates/blocks/image.twig
- templates/tease-taxonomy-action.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6918
New UI applied to the default Actions listing page. We should take action listing pages as a reference with the other listing pages. 
I've also left some comments (for more description) in files changed.
Navigate to the [actions page](https://www-dev.greenpeace.org/test-sinope/action/) and compare previous layout against the [unstyled Neptune's instance](https://www-dev.greenpeace.org/test-neptune/action/). Also compare against the one reported by [Nordics](https://www-dev.greenpeace.org/denmark/action/).
Don't forget to `enable|disable` the `Listing page pagination` feature from `Planet 4 > Information architecture`
> PLANET-6918: Implement actions listing page

- src/Post.php
I've noticed this issue after we merged [this code](https://github.com/greenpeace/planet4-master-theme/pull/1812/files#diff-5568aa3d3d5790f0967a994f11836016ec5d67d74c37cc62dc84ea56b39a8181R516). It's never been detected since the Action pages doesn't have already implemented the `Reading time` feature.
[Check it out the default listing pages](https://www-dev.greenpeace.org/test-pandora/default-listing-page/) 
Before
After
> Fix reading time value

- taxonomy.php
Ref: https://jira.greenpeace.org/browse/PLANET-6961
Queries ending up in the `taxonomy.php` template are the [Custom taxonomy](https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/#custom-taxonomy) ones.
We have 2 different custom taxonomies,
- `p4-page-type` (cf. `/edit-tags.php?taxonomy=p4-page-type`) 
- `action-type` (cf. `/edit-tags.php?taxonomy=action-type`).
- Change query args to fetch any valid post type, not only `post`
- Rebase query on taxonomy query instead of static  `p4-page-type` taxonomy
- Force `tax-p4-page-type` class [used for font-family](https://github.com/greenpeace/planet4-master-theme/blob/1dc9c0714f32112fc5a05ee433541cdc5c9e29ac/assets/src/scss/pages/_page_type.scss#L1)
- Activate option `Action post type` in _Planet 4 > Information …
> PLANET-6961: Action Type listing page empty when no pagination

- assets/src/scss/base/_typography.scss
- assets/src/scss/editorOverrides.scss
- theme.json
See [PLANET-6914](https://jira.greenpeace.org/browse/PLANET-6914)
Some small fixes were needed before the upgrade:
- remove the new `text-transform` added to labels in the editor
- force `0 1rem` padding in the editor block area
- move the `text-decoration` changes for links to `theme.json`
I've created 2 follow-up tickets that would require more work and/or some investigation:
- [PLANET-6958](https://jira.greenpeace.org/browse/PLANET-6958) to look into our RichText components that currently use the deprecated `multiline` prop, since it's probably gonna require quite a lot of changes and it's less urgent because we have until WP 6.3 before that prop is completely removed
- [PLANET-6965](https://jira.greenpeace.org/browse/PLANET-6965) to adapt the page creation modal to all post types
[The …
> PLANET-6914 Prepare to upgrade to Wordpress 6.1.1

- phpcs.xml.dist
- single.php
- Follow up fix from https://github.com/greenpeace/planet4-master-theme/pull/1804 PR
- By using the same text domain no need to add a translation twice
eg.
...
> PLANET-6676 Fix articles block strings text-domain

- src/Context.php
Since the meta data title is set to an empty string when cleared, the declaration was no longer working as expected because `$page_meta_data['p4_title'] ?? $post_title` would return an empty string instead of the actual title.
On your local, reproduce the following steps:
1. Go to any page
2. Add a meta data header in the sidebar fields, update the page and see the meta data header show in the frontend
3. Remove the meta data header field, and update the page again
4. On `main` branch you'll see the page in the frontend show no title, whereas on this branch it should again show the actual title that is set in the editor
> Fix post title declaration

- assets/src/scss/layout/_navbar.scss
- assets/src/scss/layout/navbar/_burger-menu.scss
**Description**: 
[See PLANET-6931](https://jira.greenpeace.org/browse/PLANET-6931)
Changed behaviour of submenu links with the **_active_** class to allow pointer-events.
**Testing**:
- Make sure menu items with dropdown for submenus it active, create a menu item and add submenus. 
- On the frontend, inspect the submenu items and use the style panel to add the **_active_** class to the _li_ element.
- The item should now have a font bold, but also allow you to click the link. Previously the link was not clickable, (Test [here](https://www-dev.greenpeace.org/denmark/about-greenpeace/) under the About Us menu).
> PLANET-6931 Navigation submenu items that are anchors are not clickable

- templates/navigation-submenu.twig
**Description** [here](https://jira.greenpeace.org/browse/PLANET-6954?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D)
**TESTING:**
Implementation before:
- Go to the admin dashboard and create a menu item.
- Add a submenu item under the menu item you created.
- Enable _CSS classes_ under the _screen options_ tab and add a custom CSS to your submenu.
- Save the page and got to the frontend of the webpage.
- Inspect the submenu element and you will not see the class added to the `li` element.
_After this change is implemented you can test now and the submenu links should have the custom CSS added to it now._
> PLANET-6954 Adding a custom CSS class through the admin panel is not reflected in the frontend when inspecting the page

- admin/js/dashboard.js
- src/ControlPanel.php
This is to eventually completely stop using jQuery
These functionalities in the dashboard should still work as expected:
> PLANET-6981 Remove jQuery from dashboard.js

- .circleci/config.yml
- composer.json
- composer.lock
- page.php
- phpcs.xml.dist
- single.php
- src/Settings/Features.php
- src/Settings/InformationArchitecture.php
- tests/MarkupAssertionsTrait.php
- tests/bootstrap.php
- tests/p4-testcase.php
- tests/test-category-page.php
- tests/test-open-graph.php
- tests/test-p4-master-theme.php
Ref: https://jira.greenpeace.org/browse/PLANET-5434
Adding a PHP8.1 job to this repo to ensure everything runs on this PHP version.
- Hide deprecated error from WPCS using `-d error_reporting` option
- Should stay until v3, cf. https://github.com/WordPress/WordPress-Coding-Standards/issues/2035
- Exclusion of some snifffs that can't read numbers for numberposts, post_per_page
- Remove coverage option
- Coverage doesn't seem to work here, coverage driver is not included
- Update Timber package to a version supporting php8
- from 1.18 to 1.22, reading [Releases messages](https://github.com/timber/timber/releases) is easier than [reading diffs](https://github.com/timber/timber/compare/1.18.2...1.22.1)
- Removal of phpunit-markup-assertions
- package is still not updated, but we can replicate …
> PLANET-5434: Add PHP 8.1 job

- src/Commands.php
- src/Migrations/M004UpdateMissingMediaPath.php
Adding this command to be able to re-run the media path fix migration after WPML activation on site the migration has already run.
I couldn't reproduce Aotearoa's issue locally even with their latest production db. So the command does run properly locally but didn't see any visible changes.
I'll deploy this branch in Aotearoa's dev site, so we can test it before merge.
> Add command for WPML media path migration

- assets/src/js/menu_editor.js
The functionality looks a bit different now, but it's more consistent with the other possible errors. We could also look into adding `pointer-events: none;` to the save button when there are errors, to make sure that editors cannot submit the new menu.
In the backend in the Menus section, when editing the main navigation you should now see an error message show if you try to add menu items at a depth of more than 1.
> PLANET-6981 Remove jQuery from menu_editor.js

- admin/js/posts_report.js
- src/PostReportController.php
See [PLANET-6981](https://jira.greenpeace.org/browse/PLANET-6981)
Ideally we want to avoid using jQuery
You can test the posts report either on local or on [this page](https://www-dev.greenpeace.org/test-pandora/wp-admin/edit.php?page=posts-report) from the pandora test instance, and it should behave as expected.
**Note:** the spinner image doesn't work on the test instance (and also on production sites) because the image url computes to the following:
However this is not related to these changes, so if we want to fix it we could do it in a separate PR 🙂 I've created a [follow-up ticket](https://jira.greenpeace.org/browse/PLANET-7000) for it!
> PLANET-6981 Remove jQuery from posts_report.js

- src/Feature.php
- src/Migrations/M013RemoveDuplicatedOptions.php
- src/Migrator.php
- src/Settings/Features.php
Ref: https://jira.greenpeace.org/browse/PLANET-6852
Removed features fallback and deduplicate options. Also created new Migration to clean up code
Ideally and easy to check, I'd suggest to run the full version of `docker-compose` to compare against the table `wp_options` from the [Database](/sql.php?db=planet4_dev&table=wp_options&token=08db792cbdf739020c6f613c43dcc251). 
1. Comment the rest of migrations except the one you want to run.
2. `make php-shell`
3. `wp p4-run-activator`
> PLANET-6852: Remove features fallback and deduplicate p4 features in options

- assets/src/scss/editorOverrides.scss
This is used in the editor in some blocks such as Articles, it should have the same styles as the other labels.
In the editor, add an Articles block and check the sidebar. On the `main` branch you should see some labels in uppercase:
On this branch it should be fixed 🙂
> Fix form token field label text transform

- assets/src/scss/base/_body.scss
- assets/src/scss/base/_typography.scss
- functions.php
- theme.json
See [PLANET-6968](https://jira.greenpeace.org/browse/PLANET-6968)
This is to simplify our code and follow WP guidelines. Options moved include:
- link colors
- heading font family and font weight
- body text/background color and font family
You can make sure (on local or on the [sinope test instance](https://www-dev.greenpeace.org/test-sinope/)) that links and headings still look as expected. Note that you need WordPress 6.1 or up for the changes to work!
> PLANET-6968 Move some typography settings to theme.json

- functions.php
- src/ActionPage.php
- src/PageMeta.php
- src/Post.php
- src/PostCampaign.php
- src/PostMeta.php
See [PLANET-6960](https://jira.greenpeace.org/browse/PLANET-6960)
Associated [PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/986)
On your local or [Umbriel Test Instance](https://www-dev.greenpeace.org/test-umbriel/), you can add the Canonical link from the sidebar (_Search Engine Optimizations_ section), to any post type and update the page. On reload in the editor you should still see the data that you entered, and when inspecting the page in the frontend you should see the correct link tag added to the head.
> PLANET-6960 Add sidebar option to define canonical link

- theme.json
This is a follow up from 24cc5ec49fe0cec09289deb9680e186274423104
It was breaking theme.json scheme validation. This change is how duotone feature is supposed to be disabled.
This also includes a fist commit to re-indent `theme.json` for removing tabs.
Image block should not have the [duotone button](https://wordpress.com/go/tutorials/how-to-use-the-duotone-image-filter-with-wordpress-com/) in its toolbar
> Remove duotone feature the proper way

- single-p4_action.php
Ref: [PLANET-6983](https://jira.greenpeace.org/browse/PLANET-6983)
This the [Slack thread](https://greenpeace-gpi.slack.com/archives/G015K63081W/p1667920973170169) with more information.
Go to this [demo page](https://www-dev.greenpeace.org/test-titan/action/the-second-action-custom-button-text/) and you wouldn't see any link, categories or tags, at the top of the page. Even you've already set them (1) and enabled the **Category links on Posts** feature from [Planet 4 > Information architecture](https://www-dev.greenpeace.org/test-titan/wp-admin/admin.php?page=planet4_settings_ia) (2).  Also compare with the [current behavior](https://www-dev.greenpeace.org/international/action/action-demo-page/)
(1)
(2)
> Remove Campaign tags from Action Pages

- package-lock.json
- package.json
- src/PublicAssets.php
See [PLANET-6936](https://jira.greenpeace.org/browse/PLANET-6936)
This should not cause any issues.
I've opened some follow-up PRs to stop using jQuery in a few other places in the admin area (so not totally related to this ticket):
- [dashboard.js](https://github.com/greenpeace/planet4-master-theme/pull/1853)
- [addButtonLinkPasteWarning.js](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/977)
- [menu_editor.js](https://github.com/greenpeace/planet4-master-theme/pull/1851)
All should still work as expected in the site (blocks, admin code, plugins, etc)
> PLANET-6936 Remove jQuery from frontend

- src/ActionPage.php
- tests/p4-testcase.php
- tests/test-action-type-custom-taxonomy.php
Ref. https://jira.greenpeace.org/browse/PLANET-7011
- When editor add a new action, by default assign a default action type* to it. 
- If user manually select multiple action type while add/edit of action, assign only first action type
- Same above behaviour should work in case of quick edit of action from admin action listing page.
The Default Action Type setting is available in WP admin >> Writing Settings page (wp-admin/options-writing.php)
**Testing:**
- Add new action, the default action type should assign to action post type
- Select multiple action type while add/edit of action, on save of action only one action type should save.
- Also check the action quick edit from admin action listing page
**Note:**
- I tried to use a `save_post` hook for both (save action …
> PLANET-7011 Select one action type on action add/edit

- admin/css/post_tag.css
- admin/js/post_tag.js
- src/Campaigns.php
See [PLANET-6981](https://jira.greenpeace.org/browse/PLANET-6981)
Ideally we want to avoid using jQuery. In this PR I've also included a small CSS fix for the tags image thumbnail size.
Adding a post tag (for example [here](https://www-dev.greenpeace.org/test-pandora/wp-admin/edit-tags.php?taxonomy=post_tag)) or editing a post tag (for example [here](https://www-dev.greenpeace.org/test-pandora/wp-admin/term.php?taxonomy=post_tag&tag_ID=79&post_type=post&wp_http_referer=%2Ftest-pandora%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dpost_tag)) should still work as expected.
> PLANET-6981 Remove jQuery from post_tag.js

- assets/src/scss/base/_body.scss
- assets/src/scss/base/_variables.scss
- assets/src/scss/components/_blockquote.scss
- assets/src/scss/components/_buttons.scss
- assets/src/scss/editorOverrides.scss
- assets/src/scss/layout/_breadcrumbs.scss
- assets/src/scss/layout/_cookies.scss
- assets/src/scss/layout/_footer.scss
- assets/src/scss/layout/_forms.scss
- assets/src/scss/layout/_gravity-forms.scss
- assets/src/scss/layout/_navbar.scss
- assets/src/scss/layout/_page-header.scss
- assets/src/scss/layout/_page-section.scss
- assets/src/scss/layout/_tables.scss
- assets/src/scss/layout/navbar/_burger-menu.scss
- assets/src/scss/pages/_author.scss
- assets/src/scss/pages/_category.scss
- assets/src/scss/pages/_listing-page.scss
- assets/src/scss/pages/_page_type.scss
- assets/src/scss/pages/_sitemap.scss
- assets/src/scss/pages/post/_article-content.scss
- assets/src/scss/pages/post/_comments-block.scss
- assets/src/scss/pages/post/_comments-form.scss
- assets/src/scss/pages/post/_post.scss
- assets/src/scss/pages/search/_filtered-tags.scss
- assets/src/scss/pages/search/_search-results.scss
Switching to css variables from scss will help us to replace those fonts easier in child themes by just overriding the variable. Same as we do for campaign themes.
I left the scss variables untouched since they may be used in other places (eg. landing page).
Just running `make assets` on local env with these branches should have no visual diff in the frontend.
> Add font-family css variables

- src/ImageArchive/ApiClient.php
- src/ImageArchive/Image.php
As a part of [#49](https://github.com/greenpeace/planet4-plugin-medialibrary/pull/49)
> Fix copyright values from Media Library

- tag.php
Ref: https://jira.greenpeace.org/browse/PLANET-7027
This issue has been reported by Greenpeace Denmark.
Here is a very useful description taken from the ticket:
> Sup! It seems I need your help debugging the
> listing pages. We may lack to do something for them to work, but I can’t
> tell what. We are redirecting the tags for FI and NO right now, but I’d
> prefer implementing/piloting the listing pages.
> 
> What I did so far:
> I enabled the “Use the new paginated tag, category, author, post & action
> type listing pages.” option.
> Randomly selected the Fiskeri (37) tag to test with. Initially it only
> showed the title/description.
> Toggled the IA setting off/on again like proper IT. It then started
> showing the <li> elements, but they remain empty of content.
> Reproduced the issue …
> PLANET-7027: Fix tag listing page

- templates/footer_social_media.twig
This is being used by some social media platforms to verify website url.
Just verify that all links for footer social media icons now also contain `rel="me"` as part of the `href` tag.
Already deployed on eu-unit website since they were eager to test it out. And the website link looks verified now in their [Mastodon profile page](https://eupolicy.social/@GreenpeaceEU).
> Add rel="me" on footer social icon links

- languages/planet4-master-theme-backend.pot
- tag.php
- templates/blocks/meta_fields.twig
This adds metadata tags on Tag auto-generated listing pages. Adjusted also the relevant context variables to get [proper values](https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/) for url and size.
- While on `main` branch, remove the redirection page from any tag and then check the frontend source code. Opengraph metadata are completely missing so the image selected on Tag edit is not being used anywhere.
- Switch to this branch and refresh. Now you should be seing proper `og:image` meta tag on the frontend source code.
> Enable Opengraph metadata for tag listing pages

- src/ActionPage.php
- src/Migrations/M016CreateDefaultActionType.php
- src/Migrator.php
Ref. https://jira.greenpeace.org/browse/PLANET-7029
**Testing:** 
- Ensure the action post type is action on local, and No action type terms.
- To run the migration script on local env. connect to PHP container
`make php-shell`
- Run migration script - `wp p4-run-activator`
-  Check action type terms - The "Petitions" action term is added and set as default.
The migration script tested on [test-umbriel](https://www-dev.greenpeace.org/test-umbriel/wp-admin/edit-tags.php?taxonomy=action-type&post_type=p4_action) instance. (The test-oberon instance was updated in first commit of PR)
> PLANET-7029 Add default action type, if no action type added

- src/GravityFormsExtensions.php
Ref: https://jira.greenpeace.org/browse/PLANET-7056
Ref: https://docs.gravityforms.com/gform_form_args/
---
Using `gform_form_args` to enforce Ajax submission.
Leaving the filter introduced at [this commit](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/commit/121f22428c1c457d3482a8e048b4237fe233370b) intact, since it's needed for visually changing the toggle option in the editor.
This can be tested by adding a form to a page and submitting it while having he Network tab in the Browser Web Console open. Looking at the requests on submission before and after the change, it should be obcious that before this fix the page is being reloaded on submission.
> PLANET-7056 Change form attributes to enforce Ajax submission

- src/Campaigns.php
- src/CustomTaxonomy.php
Ref: https://jira.greenpeace.org/browse/PLANET-6967
Following [PHP coding standards](https://github.com/greenpeace/planet4-master-theme/pull/1880) PR
PHP error on `add_taxonomy_form_fields()` with `$term` type when adding new taxonomy (Posts Types, Page Tags, Action tags).
> Fix PHP error on custom taxonomy

- .gitignore
- package-lock.json
- package.json
- playwright.config.js
- tests/e2e/404.spec.js
- tests/e2e/cookies-banner.spec.js
See [PLANET-7055](https://jira.greenpeace.org/browse/PLANET-7055)
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1001
On local, run `npm install` to install Playwright and its needed dependencies, and then to run the tests you can use the following commands:
- `npx playwright test` for all tests
- `npx playwright test tests/e2e/404.spec.js` for individual tests
> PLANET-7055 Setup Playwright

- page.php
- src/PostReportController.php
Fix error on pages rest endpoint
-  Fix type hint on second parameter for hook `rest_page_query`
Cf. Sentry issue https://sentry.greenpeace.org/organizations/greenpeace-org/issues/1323/?project=2&query=is%3Aunresolved
Fix error exception on page  
- Fix type hint on Request object
Cf. https://sentry.greenpeace.org/organizations/greenpeace-org/issues/1126/?project=2&query=is%3Aunresolved
> Fix PHP error on pages rest endpoint

- src/CustomTaxonomy.php
Ref: https://jira.greenpeace.org/browse/PLANET-7073
> Posts listing page pagination redirects to an article that has a title which starts with the same number
Pagination handling is missing from the rewrite rule for Custom taxonomy.  
Adding pagination to rewrite rules fixes the issue.
Locally, using the `query-monitor` plugin simplifies debugging the matching rules
```
wp install --activate query-monitor
```
On [Oberon](https://www-dev.greenpeace.org/test-oberon/press-release/page/3/), check Posts Types listing pages and their pagination.
> PLANET-7073: Fix custom taxonomy pagination

- author.php
- single-attachment.php
Cf. https://sentry.greenpeace.org/organizations/greenpeace-org/issues/1381/?project=2&query=is%3Aunresolved Generates an error on some author pages like https://www-dev.gcef.ca/en/author/admin/ if no `footer_social_menu` is defined
> Fix type error on author page

- assets/src/scss/pages/_sitemap.scss
- assets/src/scss/pages/post/_post.scss
These should always be the same color regardless of their state (I double-checked with the design team)
You can see the broken versions on the GPI site:
- [Sitemap](https://www.greenpeace.org/international/sitemap/)
- [Post](https://www.greenpeace.org/international/press-release/58205/after-13-days-and-nearly-4000km-greenpeace-occupation-of-shell-oil-platform-ends-with-no-arrests/)
On local you can test the fixed versions in the Sitemap page and in any post.
> Fix some links hover/visited/active color

- src/Post.php
Ref: https://jira.greenpeace.org/browse/PLANET-7077
> On some posts the set featured image is not picked up and missing when sharing on socials
The loop going through post images can return an empty result in some cases.
A request in DB `select * from wp_postmeta where meta_key = 'p4_og_image_id'` will return some rows with empty `meta_value`; in the current loop, `isset` will return true and `get_og_image()` will return nothing, even if a featured image (thumbnail_id) is set.
> PLANET-7077: Featured img not picked up/ missing when sharing on socials

- assets/src/scss/editorOverrides.scss
- src/ActionPage.php
- src/AnalyticsValues.php
- src/MetaboxRegister.php
- src/PageMeta.php
- src/PostCampaign.php
- src/PostMeta.php
Ref: https://jira.greenpeace.org/browse/PLANET-7005
Requires: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1005
> As we recently moved Opengraph and Page Header option on the sidebar, it's a good opportunity to refactor Analytics section too to match the same UI.
This PR :
- removes the Metabox for Analytics & tracking
- adds relevant fields to meta fields declaration, so that they are readable/editable through the REST API used by our Sidebar system
> PLANET-7005: Analytics sidebar in native UI

- admin/css/login.css
This was probably caused by a recent plugin upgrade.
> Decrease Google login font-size to fix overflow

- assets/src/scss/layout/_forms.scss
See [PLANET-6473](https://jira.greenpeace.org/browse/PLANET-6473)
**Note:** I've noticed that the Gravity Forms radio buttons are not working properly with the keyboard, I've opened a [bug ticket](https://jira.greenpeace.org/browse/PLANET-7085) to investigate that since it's not related to these style changes
You can test the new focus styles on [this page](https://www-dev.greenpeace.org/test-rhea/new-focus-styles/), where I've added a Gravity Forms block and an EN form block with checkboxes and/or radio buttons. They should appear only for `:focus-visible`, for example when navigating with tabs.
> PLANET-6473 Add focus state to checkboxes and radio buttons

- src/GravityFormsExtensions.php
Every time a Gravity Form is updated in wordpress, this will search all posts that contain the form and purge the page caches. It also works for posts that include the forms in a resuable block.
Some additional comments on the code choices:
- I added a filter to cutomize the post types searched for forms. That enables NROs to search custom post types they use in their child themes
- Updating the post is the most reliable way I could find to clear all caches, including Cloudflare. I couldn't find any side effects.
- I'm not sure if the functions are in the right place, mainly if `find_nested_blocks` should be in the `GravityFormsExtensions` class. It could be used in more general use cases, but for now isn't. Let me know if I should move it.
- I tried @lithrel's suggestion to use the block …
> Purge caches for posts that contain a form

- src/MasterSite.php
As the WP-v5.8 resolved the core issue(https://core.trac.wordpress.org/ticket/52050), no need of this patch.
Ref: [PLANET-6060](https://jira.greenpeace.org/browse/PLANET-6060)
[Old PR](https://github.com/greenpeace/planet4-master-theme/pull/1396)
> Revert fix added in Planet-6060

- src/GravityFormsExtensions.php
- src/MasterSite.php
Fix 2 type errors coming up in Sentry
Fix https://sentry.greenpeace.org/organizations/greenpeace-org/issues/1438/?project=2&query=is%3Aunresolved
Cf. https://docs.gravityforms.com/gform_confirmation/#parameters
Fix https://sentry.greenpeace.org/organizations/greenpeace-org/issues/1443/?project=2&query=is%3Aunresolved
Cf. https://developer.wordpress.org/reference/hooks/attachment_fields_to_save/#parameters
> Fix PHP type errors

- assets/src/scss/base/_colors.scss
- assets/src/scss/components/_share-buttons.scss
This PR is meant to update the share buttons to match the new visual identity.
**Testing**
If you checkout out a post page on the associated test instance, you should see the updated share button styles.
> PLANET-6989 Apply the new UI for the share buttons

- assets/src/scss/pages/post/_comments-block.scss
See [PLANET-6959](https://jira.greenpeace.org/browse/PLANET-6959)
We need this in case comments contain a really long word or URL
You can compare the broken version [here](https://www.greenpeace.org/international/story/55533/amazon-rainforest-fires-2022-brazil-causes-climate/) to the fixed version [here](https://www-dev.greenpeace.org/test-pandora/story/52154/africa-waste-colonialism-plastic-treaty/#comment-33844).
> PLANET-6959 Fix possible overflow in comment text

- assets/src/scss/base/_css-variables.scss
- assets/src/scss/base/_variables.scss
- assets/src/scss/editorOverrides.scss
- assets/src/scss/editorStyle.scss
- assets/src/scss/new-identity/style.scss
- assets/src/scss/style.scss
- src/MasterSite.php
- src/PublicAssets.php
- src/Settings.php
- webpack.config.js
See [PLANET-7020](https://jira.greenpeace.org/browse/PLANET-7020) & [PLANET-6984](https://jira.greenpeace.org/browse/PLANET-6984)
When checking the new site identity toggle in `Appearance > Customize > Site identity`, you should see in the frontend and in the editor that the new value of `--body--color` is applied (#1c1c1c instead of #020202). You'll need to also use [this branch](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1014) from the blocks plugin to see the change applied properly.
> PLANET-7020 Add new site identity feature toggle

- src/Campaigns.php
This was crashing, my guess is that it is due to a [recent refactor of the validate function](https://github.com/greenpeace/planet4-master-theme/commit/d8303237ece741dc19c773c4f2c2ec25e3f6c73f#diff-09f0c1569665b6a290f7d056be1cabce24a3834d7940a7c16da9817bbd0de723R353). Maybe this is a partial fix for [PLANET-7099](https://jira.greenpeace.org/browse/PLANET-7099).
If you try creating a tag on the `main` branch without selecting a redirect page or an image, it will crash (even though on reload the tag will be there). On this branch it should work as expected.
> Fix tag creation when certain fields are missing

- admin/css/wpml.css
- assets/src/scss/style.scss
- src/ControlPanel.php
See [PLANET-6977](https://jira.greenpeace.org/browse/PLANET-6977)
We use CSS for this since it seems there's no available hook to do it
You'll need WPML to test this, so it's probably easier to use the [rhea test instance](https://www-dev.greenpeace.org/test-rhea). There, make sure that the footer language switcher option is hidden in the backend, and even if it was checked make sure that the footer switcher doesn't show in the frontend!
> PLANET-6977 Hide WPML footer language switcher

- admin/css/wpml.css
**Description: [PLANET-6970](https://jira.greenpeace.org/browse/PLANET-6970)**
**Testing:** 
If you got to this [test instance](https://www-dev.greenpeace.org/test-rhea/wp-admin/) and look through the WPML Settings, you should not see the option for _Login and Registration pages_
> PLANET-6970 WPML option disabling access to WordPress admin panel

- assets/src/scss/layout/_country-selector.scss
- assets/src/scss/new-identity/style.scss
See [PLANET-6992](https://jira.greenpeace.org/browse/PLANET-6992)
For now these are only visible when the new identity styles setting is checked
Make sure that the new identity styles setting is enabled (`Appearance > Customize > Site identity > Enable new Greenpeace visual identity`) and then you should see the new footer background colors. Note that on local you will probably need to rebuild the theme to see the changes. You can also test the changes on the [neptune test instance](https://www-dev.greenpeace.org/test-neptune/) where I already toggled the new identity styles.
> PLANET-6992 Update footer background colors for new identity

- assets/src/scss/new-identity/style.scss
See [PLANET-7015](https://jira.greenpeace.org/browse/PLANET-7015)
These are only applied if the new identity styles are enabled
Make sure that the new identity styles setting is enabled (`Appearance > Customize > Site identity > Enable new Greenpeace visual identity`) and then when adding a Planet 4 Columns block to a page, you should see it with the new colors in all screen sizes. You can also use the [neptune test instance](https://www-dev.greenpeace.org/test-neptune/) where the setting has already been enabled, specifically [this page](https://www-dev.greenpeace.org/test-neptune/simple-tasks/) where the block has been added for UAT.
> PLANET-7015 Apply new identity colors to Columns Tasks block

- assets/src/scss/components/_buttons.scss
- assets/src/scss/editorOverrides.scss
- assets/src/scss/new-identity/style.scss
- assets/src/scss/pages/search/_filter-sidebar.scss
- templates/search.twig
See [PLANET-6985](https://jira.greenpeace.org/browse/PLANET-6985)
These are only applied when the new identity styles are enabled
Related PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1019 to make sure that these changes are also applied to the Take Action boxout button
Make sure that the new identity styles setting is enabled (`Appearance > Customize > Site identity > Enable new Greenpeace visual identity`) and then you should see the new primary buttons colors. Note that on local you will probably need to rebuild the theme to see the changes. You can also test the changes on the [pandora test instance](https://www-dev.greenpeace.org/test-pandora/) where I already toggled the new identity styles (I've added more detailed instructions for UAT in the ticket's …
> PLANET-6985 Update primary buttons colors for new identity

- assets/src/scss/base/_typography.scss
- assets/src/scss/components/_buttons.scss
- assets/src/scss/new-identity/style.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6988
New layout applied to Tag links as a part of the new identity project.
Navigate any page with tags, for example the [forest category page](https://www-dev.greenpeace.org/test-nix/tag/forests/).
Remember to enable the new layout from the appearance section
> PLANET-6988: New layout applied to tag links

- assets/src/scss/new-identity/style.scss
See [PLANET-6987](https://jira.greenpeace.org/browse/PLANET-6987)
These changes are only visible when the new identity styles are enabled
Make sure that the new identity styles setting is enabled (`Appearance > Customize > Site identity > Enable new Greenpeace visual identity`) and then you should see the new Donate button colors, both in the top navigation bar and in the side menu on mobile. Note that on local you will probably need to rebuild the theme to see the changes. You can also test the changes on the [rhea test instance](https://www-dev.greenpeace.org/test-rhea/) where I already toggled the new identity styles.
> PLANET-6987 Update Donate button colors for new identity

- admin/css/login.css
- assets/src/scss/components/_buttons.scss
- assets/src/scss/editorOverrides.scss
- assets/src/scss/layout/_navbar.scss
I've checked with the design team and we can already make this change regardless of the new identity.
All buttons should no longer have a `box-shadow`.
> Remove buttons box-shadow

- assets/src/scss/new-identity/style.scss
- assets/src/scss/pages/_listing-page.scss
See [PLANET-6991](https://jira.greenpeace.org/browse/PLANET-6991)
This change is only visible if the new identity styles are enabled
Make sure that the new identity styles setting is enabled (`Appearance > Customize > Site identity > Enable new Greenpeace visual identity`) and then you should see the new contextual link colors. Note that on local you will probably need to rebuild the theme to see the changes. You can also test the changes on the [leda test instance](https://www-dev.greenpeace.org/test-leda/) where I already toggled the new identity styles (I've added more detailed instructions for UAT in the ticket's comments).  Please make sure that the old links still look as expected (when the new identity styles are not enabled).
> PLANET-6991 Apply the new dark green color to contextual links

- assets/src/scss/new-identity/style.scss
See [PLANET-6986](https://jira.greenpeace.org/browse/PLANET-6986)
These are only applied when the new identity styles are enabled
Make sure that the new identity styles setting is enabled (`Appearance > Customize > Site identity > Enable new Greenpeace visual identity`) and then you should see the new primary buttons colors. Note that on local you will probably need to rebuild the theme to see the changes. You can also test the changes on the [nix test instance](https://www-dev.greenpeace.org/test-nix/) where I already toggled the new identity styles (I've added more detailed instructions for UAT in the ticket's comments)
> PLANET-6986 Update secondary buttons colors for new identity

- src/GravityFormsExtensions.php
Ref. https://jira.greenpeace.org/browse/PLANET-7028
**Testing:**
- Create a new GF form, the default feed called "Google Analytics" is created with value's specified in JIRA ticket
- On form submission, the 'formSubmission' dataLayer event will trigger (please check all 3 use case's, Confirmation type - Text, Page, Redirect)  - [example](https://www-dev.greenpeace.org/test-saturn/story/46528/test-page-redirect-dlv/)
> PLANET-7028 Add analytics feed meta on new GF form add

- assets/src/js/gravityforms-client-side.js
- src/GravityFormsExtensions.php
Hidden fields in GF are now dynamically populated on the frontend with the value passed in the URL params.
> PLANET-7003 Implement client-side dynamic population on form fields

- functions.php
These new colors were suggested by Houssam for the new palette, of course we can always add/remove some in the future if needed.
You can check the new color palette with any block that offers color customisations, such as the Paragraph. Make sure they are applied as expected, both in the backend and frontend. You can use [this page](https://www-dev.greenpeace.org/test-pandora/new-color-palette/) I made for UAT. Please also make sure that the rest of the theme settings are not impacted, and that the "old" palette still shows as expected if the new identity styles are not enabled 🙂
> Add new identity colors to our color palette

- assets/src/scss/base/_palette.scss
- assets/src/scss/new-identity/style.scss
This is needed for the Highlighted CTA pattern (see [PLANET-7022](https://jira.greenpeace.org/browse/PLANET-7022))
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1030
Either on local (make sure the new identity styles are enabled!) or on the janus test instance, you can check the new available colors for the pattern. You can also use [this page](https://www-dev.greenpeace.org/test-janus/highlighted-ctas/) that I made for UAT.
> PLANET-7022 Apply new identity colors to transparent buttons

- assets/src/scss/base/_css-variables.scss
- assets/src/scss/layout/_navbar.scss
- assets/src/scss/layout/navbar/_search.scss
- assets/src/scss/layout/navbar/_site-logo.scss
- assets/src/scss/layout/navbar/languages.scss
- assets/src/scss/pages/_page.scss
As a part of https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/969 I'd suggest also to re implement the Navigation variables. 
By doing this will be more easier to maintain afterwards and to migrate to design tokens since we're are start using `CSS Variables`.
Here is the [demo page](https://www-dev.greenpeace.org/test-pluto/page-header-demo-page)
> Convert navbar variables to CSS variables

- assets/src/scss/layout/_navbar.scss
You can see the issue on the [nix instance](https://www-dev.greenpeace.org/test-nix/).
With the new identity, the color is now no longer white but grey. To simplify the code we can just always set it to `currentColor`.
> Fix Donate button dropdown arrow color

- src/GravityFormsExtensions.php
Ref: https://jira.greenpeace.org/browse/PLANET-7125
Fix the warning issue 
```
Warning: filemtime(): stat failed for /app/source/public/wp-content/themes/planet4-master-theme-international/assets/src/js/gravityforms-client-side.js in /app/source/public/wp-content/themes/planet4-master-theme/src/GravityFormsExtensions.php on line 481
```
Which happens when any Gravity Forms is rendered into a page.
> PLANET-7125: Fix filemtime() warning issue on GF Client Side file

- src/GravityFormsExtensions.php
That would make it easier for editors to translate since it would appear as one line in Loco. This also gives them the option to completely blank the text if they don't wish to appear at all. 
I had to remove formatting too from the translatable part (except from `href`) to make it easier for editors.
> Adjust GF redirection message

- assets/src/scss/base/_colors.scss
- assets/src/scss/layout/_tables.scss
- assets/src/scss/new-identity/style.scss
- functions.php
**Testing**
You can use this [page](https://www-dev.greenpeace.org/test-umbriel/test-new-identity-colors/) on the Umbriel instance to test the new changes for the Table block. Switching between the new identity styles and old ones should be reflected on the table.
Ref PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1029
> PLANET-7016 Apply the new colors to the Table block

- src/PublicAssets.php
- src/Settings.php
See [PLANET-7019](https://jira.greenpeace.org/browse/PLANET-7019)
This will only be applied if the new identity styles are enabled. Once we merge the new identity, we'll need to run a migration to properly remove this setting from existing data.
Either on local or on the [telesto test instance](https://www-dev.greenpeace.org/test-telesto/), make sure that the Planet 4 `Navigation > Website Navigation Style` setting is now only available in the backend when the new identity styles are disabled. When they are enabled, the light style should always be applied in the frontend.
> PLANET-7019 Remove navigation bar dark style for new identity

- assets/src/scss/new-identity/style.scss
See [PLANET-7014](https://jira.greenpeace.org/browse/PLANET-7014)
These will only be applied if the new identity styles are enabled
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1031
You can add an Accordion block on local or on the janus test instance, making sure you enabled the new identity styles, and test out the various styles. You can also check [this page](https://www-dev.greenpeace.org/test-janus/all-the-accordions/) that I made for UAT. Make sure the block also still looks fine with the "old" styles, if the new identity is not enabled.
> PLANET-7014 Apply new identity colors to Accordion block

- assets/src/scss/layout/navbar/_burger-menu.scss
- assets/src/scss/layout/navbar/_search.scss
- assets/src/scss/layout/navbar/languages.scss
- assets/src/scss/new-identity/style.scss
- assets/src/scss/partials/navigation-bar-light.scss
See [PLANET-6996](https://jira.greenpeace.org/browse/PLANET-6996)
These will only be applied if the new identity styles are enabled. This should only be merged after [this PR](https://github.com/greenpeace/planet4-master-theme/pull/1978), to make sure it's always the light style that is used, because with the dark style it looks weird 😅
Make sure that the new identity styles setting is enabled (`Appearance > Customize > Site identity > Enable new Greenpeace visual identity`) and then you should see the new navigation bar colors. You can also test the changes on the [deimos test instance](https://www-dev.greenpeace.org/test-deimos/) where I already toggled the new identity styles.
> PLANET-6996 Apply new identity colors to the navigation bar

- assets/src/scss/new-identity/style.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6994
As a part of the new identity, It's Including the new `hover` effect to some links (not all).
**IMPORTANT NOTE**
I was trying to find the best CSS pure way to define the `offset-y` (as `-22px`) through the `drop-shadow` property, without using Javascript, but I haven't find it yet. 
The problem there is that `22px`  is applied to ALL links with `font-sizes` higher than `22px` and lower. Thus, doesn't matter which is the `font-size`, the `inset` drop shadow will be always `22px` and I disagree with that 🙃. 
Of course we can do it directly with Vainilla JS, but the performance will be impacted.
> PLANET-6994: Implement new identity colors to standalone links

- tests/e2e/cookies-banner.spec.js
If the P4 settings cookies text is empty then the notice will not show. We should include this case in our test.
On local, you can run `npx playwright test tests/e2e/cookies-banner.spec.js` with and without a cookies text defined in the P4 settings, and the test should pass in both cases.
> Add empty text case to cookie notice e2e test

- assets/src/scss/new-identity/style.scss
- tests/e2e/404.spec.js
We forgot this case when working on this 😬 
You can either manually add the `disabled` attribute to a secondary button, or you can see this state when loading more articles in the Articles block for example. On this branch if the new identity styles are enabled, the color should be green, whereas on the `main` branch it will still be blue.
> Update secondary button disabled color for new identity

- src/GravityFormsExtensions.php
Ref. https://jira.greenpeace.org/browse/PLANET-7109
eg. https://www-dev.greenpeace.org/test-telesto/lorem-ipsum/
**Testing:**
- On GF form submission, 'GFTrackEvennt' should not trigger
> PLANET-7109 Disable GFTrackEvent

- assets/src/scss/new-identity/style.scss
- tests/e2e/404.spec.js
**Testing**
Check this [post](https://www-dev.greenpeace.org/test-tavros/story/29458/peak-oil-decline-coronavirus-economy/) on the tavros instance. Because the _New Site Identity_ has been enabled, it reflects the new changes for body copy links.
> PLANET-6990 Apply the new style to body copy links

- src/Post.php
We forgot to add the possibility to translate this string here, it was reported on Slack! You can find an example page of the issue [here](https://www.greenpeace.org/brasil/blog/)
> Fix reading time translation in listing pages

- assets/src/scss/new-identity/style.scss
See [PLANET-6997](https://jira.greenpeace.org/browse/PLANET-6997)
We only need to make sure that links follow the body links styles
When the new identity styles are enabled, the cookies box should have the new identity colors. Make sure to test it with links within the texts. Also, make sure that the "old" cookies box still looks fine!
> PLANET-6997 Apply new identity colors to cookies box

- assets/src/scss/components/_buttons.scss
See [PLANET-7149](https://jira.greenpeace.org/browse/PLANET-7149)
GP Luxembourg for some reason [replaced](https://github.com/greenpeace/planet4-child-theme-luxembourg/blob/bc79f742169b60d619ccfcbbd961264235fb2389/plugins/gravityforms-gpf/src/Plugin.php#L113-L114) the `input` tag by a `button` so our previous selector doesn't work for them. By using the `id` instead the problem should be solved, and it should still work for other sites too.
Either on local or on the telesto test instance, if you add a Gravity Forms the submit button should be styled as expected (with our primary buttons styles).
> PLANET-7149 Fix Gravity Forms submit button styles

- assets/src/scss/pages/_listing-page.scss
See [PLANET-7143](https://jira.greenpeace.org/browse/PLANET-7143)
On bigger screens some padding was missing between the image and text
On local, make sure you have the paginated lists enabled (`Planet 4 > Navigation > New Information Architecture` setting) and go to any listing page (such as `/press`). You can then manually change the direction to `rtl` on the `html` element and see that the padding is now correct. Please test all screen sizes and also the `ltr` version!
Alternatively, you can check out [this listing page](https://www-dev.greenpeace.org/test-neptune/story/) from the neptune test instance.
> PLANET-7143 Fix spacing in RTL paginated listing pages

- assets/src/scss/new-identity/style.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7132
Used the [SASS variables recently merged](https://github.com/greenpeace/planet4-design-tokens/pull/8).
You can compare the [new changes](https://www-dev.greenpeace.org/test-pandora/new-identity-layouts-links/) versus the [current behavior](https://www-dev.greenpeace.org/test-nix/explore-2/).
> PLANET-7132: Apply new identity colors to Split Two Columns block

- assets/src/scss/new-identity/style.scss
As a part of [#1044](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1044) we will need to standardize the yellow color to the Split Two Columns block and to the Campaign Cover block, by using always the `yellow-500` color.
> Implement new yellow CSS variables to links

- assets/src/scss/layout/navbar/_search.scss
- assets/src/scss/new-identity/style.scss
- assets/src/scss/pages/search/_search-bar.scss
- templates/search.twig
See [PLANET-7157](https://jira.greenpeace.org/browse/PLANET-7157)
The old clear search button from the search page looks weird and not consistent with the navbar one
Either on local or on the [telesto test instance](https://www-dev.greenpeace.org/test-telesto/?s=forest&orderby=_score), you can check the new "clear input" button on the Search page and make sure that it looks and behaves the same as the one from the navbar.
> PLANET-7157 Harmonise search input clear buttons

- src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-6235
Conditional class usage so that ElasticPress plugin can be safely disabled locally, without triggering a Fatal error
- Locally, disable the ElasticPress plugin
- your instance should give an error on Search page
- with this branch, it runs without error
> PLANET-6235: Fix ElasticSearch class usage

- src/GravityFormsExtensions.php
**Description: [PLANET-7146](https://jira.greenpeace.org/browse/PLANET-7146)**
**Testing:**
On local, go to Gravity Forms and create a new form, for the current behaviour, the toggle to _Prevent the storage of IP addresses during form submission_  is disabled. 
Having this changes locally or on the associated branch, all newly created forms should have this toggle enabled by default.
> PLANET-7146 Form Builder: Disable IP address retention during submission

- assets/src/scss/layout/_breadcrumbs.scss
- assets/src/scss/layout/_cookies-settings.scss
- assets/src/scss/layout/_cookies.scss
- assets/src/scss/layout/_footer.scss
- assets/src/scss/layout/_forms.scss
- assets/src/scss/layout/_gravity-forms.scss
- assets/src/scss/new-identity/_fonts.scss
- assets/src/scss/new-identity/style.scss
- assets/src/scss/pages/post/_author-block.scss
- assets/src/scss/pages/post/_comments-block.scss
- assets/src/scss/pages/post/_comments-form.scss
- assets/src/scss/pages/post/_post.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7128
Include regular and bold variants of fonts from [this bucket](https://storage.googleapis.com/planet4-assets/) also apply typography tokens. 
In cases where the `font-weight`, `font-size` and `font-family` are not set to any `selector`, we will override the selector and the new properties and don't edit the current behavior since are probably used by some NROs.
```
.selector {
// new properties
}
```
If not, then add the prefix `_--` add define the new CSS Variables. For instance, `--selector--property: value`.
- Links (contextual navigation links, footer links, breadcrumbs)
- Forms (inputs, small paragraphs, checkbox label)
- Comments block (inputs, short paragraphs, checkbox label, replies)
- Card text description
- Footer copyright …
> PLANET-7128: Apply the new Source Sans 3 typeface

- src/GravityFormsExtensions.php
Description: [PLANET-7146](https://jira.greenpeace.org/browse/PLANET-7146)
Testing:
On local, go to Gravity Forms and create a new form, for the current behaviour, the _Retention Policy_ should have _`Retain entries indefinitely`_ as the default.
Having this changes locally or on the associated branch, all newly created forms should have _`Delete entries permanently automatically`_ as the default with a `90days` period.
> PLANET-7148 Form Builder: Enforce data retention policy

- src/GravityFormsExtensions.php
**Description: [PLANET-7147](https://jira.greenpeace.org/browse/PLANET-7147)**
**Testing:**
On local, go to Gravity Forms and create a new form, for the current behaviour, _Exporting and Erasing Data_ toggle should be off by default.
Having this changes locally or on the associated test instance, all newly created forms should have this toggle switched to on by default.
> PLANET-7147 Form Builder: Enable integration with native export tool

- templates/countries.json
Ref: https://jira.greenpeace.org/browse/PLANET-7176
---
Add link to website and relevany locale codes.
Skipped Indian since it has a dedicated website already.
1. Check that the country list is properly rendered
2. There is an entry for South Asia
3. It points to the correct website
> Add GPSA into the footer country list

- src/AnalyticsValues.php
- src/GoogleDocsClient.php
Ref. https://jira.greenpeace.org/browse/PLANET-7131
- Updated the fallback hardcoded list of Global Projects in codebase
- Sync Global Project Standards from "Global Projects Standards" tab of Google sheet
**Testing:**
- To test these changes on local, you need a `GOOGLE_SHEETS_KEY`(Contact me or Nikos, if you don't have it)
- Add new page/post/campaign, check the "Analytics & Tracking" fields in sidebar
- It's hard to identify the change because data is cache after first API call to Google sheet, you may comment the [cache check point code](https://github.com/greenpeace/planet4-master-theme/blob/main/src/AnalyticsValues.php#L188) and check the API request response.
> PLANET-7131 Sync Global Project Standards using sheet tab name

- src/Search.php
See [PLANET-7183](https://jira.greenpeace.org/browse/PLANET-7183) (in the comments)
We should only show PDF files but before this fix images showed too. It seems to be due to the use of `ep_post_query_db_args` filter that no longer works as expected.
Before this fix you'll see images in search results, after they should no longer be there (but PDF files should still show as expected)
> PLANET-7183 Fix search unwanted attachments

- src/Search.php
Related to [PLANET-7183](https://jira.greenpeace.org/browse/PLANET-7183)
We don't want to show password protected content in the search results
Password protected content should no longer show in the search results. You can test it on the [pandora instance search page](https://www-dev.greenpeace.org/test-pandora/?s=duis&orderby=_score) for example, where [this post](https://www-dev.greenpeace.org/test-pandora/press/1105/duis-posuere-2/?ch=2y10XhjRarKqS7U6uFeJZf7GIOfM1z7SMKKNDlafeJ8.8oyjqKpIPaVX6) should not appear.
> PLANET-7183 Fix search password protected content

- assets/src/scss/new-identity/_fonts.scss
In preparation of [PLANET-7126](https://jira.greenpeace.org/browse/PLANET-7126) and [PLANET-7127](https://jira.greenpeace.org/browse/PLANET-7127)
Currently, all the new font families has included its variants, then, we don't need to have `bold` and `semi bold` font families anymore.
Includes:
- Greenpeace Sans
- Source Sans Pro
> Add new fonts

- src/PostReportController.php
See [PLANET-5789](https://jira.greenpeace.org/browse/PLANET-5789)
I couldn't find a way to specifically target subscribers, but I think it makes sense that users who can't edit posts shouldn't see the posts report?
Actually, it turns out only subscribers cannot edit posts so that's a good solution 😄
> PLANET-5789 Make sure posts report is only visible to some users

- admin/js/options.js
- src/Settings.php
To reduce the amount of excessive requests to Akismet API, since we are exceeding our current rate limit. Comments are already being scanned through Akismet on submission.
1. Add a new comment (without being logged in)
2. Login and go to Comments. This new comment should be pending.
- Before this change a "Check for Spam" button should be visible on top. It's only visible when there is a pending comment.
- After this change the button should be hidden in all cases.
> Disable Akismet admin spam button

- assets/src/scss/pages/post/_comments-form.scss
See [PLANET-7103](https://jira.greenpeace.org/browse/PLANET-7103)
If the user name is too long then before this fix the logged in text would overlap with comment form title
Log in and check the comment form on any post. If your username is not long enough, you can manually change the string when inspecting the element.
> PLANET-7103 Fix comment form logged in text overlap

- admin/css/picker.css
See [PLANET-7113](https://jira.greenpeace.org/browse/PLANET-7113)
This is part of the Media Archive redesign
Enable the Media Archive feature and then check the image list in all screen sizes, it should look like the [designs](https://www.figma.com/file/cnd1hDu5MnXD2kmGxfwH4N/Media-Archive-Wireframes-(Final-Beta)?node-id=220%3A7218&mode=dev) (`Additional photo columns` section). You can test this either on local or on the [janus test instance](https://www-dev.greenpeace.org/test-janus/wp-admin/admin.php?page=media-picker).
> PLANET-7113 Add more space and columns to Media Archive list

- package-lock.json
- package.json
The latest `v1.2.1` version includes the possibility to work with prefix and multi-selectors.
The below error was being returned before the new [dash-dash version](https://github.com/greenpeace/planet4-dashdash/releases/tag/v1.2.1)
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot generate prefix when using multiple selectors. .nav-item _--,.nav-donate _--
at /home/circleci/project/assets/src/scss/partials/navigation-bar-dark.scss:1:4161
at /home/circleci/project/node_modules/@greenpeace/dashdash/index.js:59:19
at /home/circleci/project/node_modules/postcss/lib/container.js:243:18
at /home/circleci/project/node_modules/postcss/lib/container.js:139:18 …
```
> Update dashdash dependency

- assets/src/scss/base/_typography.scss
- assets/src/scss/components/_buttons.scss
- assets/src/scss/layout/_cookies.scss
- assets/src/scss/layout/_navbar.scss
- assets/src/scss/new-identity/style.scss
- assets/src/scss/pages/post/_comments-form.scss
Ref: [PLANET-7127](https://jira.greenpeace.org/browse/PLANET-7127)
Apply the new Greenpeace Sans (primary) typeface to:
- Headings
- Buttons
- Navigation menu items
Related to
- #2008 
- #2051
- #2052
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1078
> PLANET-7127: Apply the new Greenpeace sans typeface

- assets/src/scss/new-identity/style.scss
Ref: [PLANET-7126](https://jira.greenpeace.org/browse/PLANET-7126)
Apply the new Source Sans Pro (secondary typeface to:
- Body texts
- Carousel Header texts
Related to
- #2008 
- #2051 
- #2023 
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1078
> PLANET-7126: Apply the new source sans pro typeface

- templates/author.twig
- templates/blocks/author_profile.twig
Google profile avatars plugins seems to add a suffix string that fetches smaller images than what we want in certain cases.
This is a hotfix till we have a response from them for a better way to handle this.
Unfortunately we can't test this easily locally, since we don't have Google login.
But here is how it looks currently in production: https://www.greenpeace.org/international/author/nikos-roussos/
vs
How it looks fixed in the test instance: https://www-dev.greenpeace.org/test-mars/author/nroussos/
_(inspect the img src)_
> Small fix to get bigger avatars on certain pages

- assets/src/js/media_archive.js
- src/Features/MediaArchive.php
- src/MediaArchive/UiIntegration.php
- src/Settings.php
Ref: https://jira.greenpeace.org/browse/PLANET-6840
- Move "Media Archive" under "Media" right after "Library" and rename it to "-
- Create a new option menu under "Media" named "Archive Settings".
- Show section description text: "Please enter your Image Archive username and password. Please note that you will need to ask from the Image Archive administrators to enable API access for your account."
- Add Fields labels: "Username" and "Password".
1. Go to `Media > Archive Settings`
2. Edit any input and try to type a wrong value.
3. These values of `Media > Archive Settings`  might be the same of `Planet 4 > GPI Media Library`
> PLANET-6840: Rename admin panel configuration options from Media Archive

- src/MasterSite.php
This is needed to make sure the `og:url` is identical to canonical url which ends with a forward slash. Flagged from Google Search Console as an issue.
- Before this fix, view source of any post and check `og:url`. It shouldn't have forward slash. But `link rel="canonical"` does.
- After this fix, both tags should end with a forward slash.
> Add trailing slash on Opengraph url

- src/AnalyticsValues.php
- src/Loader.php
- src/MasterSite.php
- src/MetaboxRegister.php
Ref [PLANET-7169](https://jira.greenpeace.org/browse/PLANET-7169)
- Update tracking ID(i.e projectID) value as per Global project standard value changes
- If the global/local project unapproved/removed from spreadsheet, still keep selection with [deprecated] label in P4
**Testing:**
- Add new page/post select analytics fields, save & publish page 
- View page on frontend and check page source
- In page source check datalayer params(gCampaign, gLocalProject, projectID) value
- To test the deprecated label use case - edit the page, change the Global & Local project dropdown value using browser console, save the page and check on frontend datalayer params
eg. 
https://www-dev.greenpeace.org/test-mars/wp-admin/post.php?post=1137&action=edit
> PLANET-7169 Fix analytics Field tracking ID(i.e projectID) bug

- assets/src/scss/new-identity/style.scss
Links styles don't apply if a link is included in an inline tag like `<em>` or `<strong>`.
This is due to a child combinator `p > a` that doesn't allow for `p > em > a`. The declaration also misses `.post-content > article` selector for lists.
Example: https://planet4.greenpeace.org/story/16394/v2-105-106/
> Fix link style rule

- src/MasterSite.php
- src/Settings.php
- templates/base.twig
- templates/hubspot_tracking_code.twig
Ref. https://jira.greenpeace.org/browse/PLANET-7186
**Task:**
- Added a `Hubspot tracking code` settings option under: Planet 4 > Analytics
- This option should be visible only if the GF Hubspot add-on is activated
- The `Hubspot tracking code` snippet will be added only if,  
- The user has accepted "Marketing" cookies
- The snippet script will be loaded in the end of the page
eg.
https://www-dev.greenpeace.org/test-leda/wp-admin/admin.php?page=planet4_settings_analytics
> PLANET-7186 Add setting for Hubspot tracking code

- admin/css/options.css
- admin/js/options.js
- src/Post.php
- src/Settings.php
- tests/e2e/special-pages.spec.js
See [PLANET-7045](https://jira.greenpeace.org/browse/PLANET-7045)
With the new IA we no longer need the old special pages (`Act`, `Explore` and `Issues Parent Category`) but we want to add new ones to the Analytics section (`Get Informed`, `About Us`, and `Take Action`)
Either on local or on the jupiter test instance,
- go to `Planet 4 > Navigation`
- disable the new IA and save, making sure that the `Act`, `Explore` and `Issues Parent Category` dropdowns are shown
- go to `Planet 4 > Analytics` and make sure the new `Get Informed`, `About Us`, and `Take Action` dropdowns are hidden
- go back to `Planet 4 > Navigation` and enable the new IA, making sure that the `Act`, `Explore` and `Issues Parent Category` dropdowns are now hidden
- go back to `Planet 4 > Analytics` and select pages for …
> PLANET-7045 Create settings options for new IA pages

- author.php
- category.php
- page.php
- tag.php
- taxonomy.php
- templates/base.twig
- templates/html-header.twig
- tests/test-category-page.php
See [PLANET-7198](https://jira.greenpeace.org/browse/PLANET-7198)
You can check that the canonical links are now present on the neptune test instance:
- [author page](https://www-dev.greenpeace.org/test-neptune/author/ltiralon/)
- tag page [with redirect](https://www-dev.greenpeace.org/test-neptune/tag/climate/) and [without](https://www-dev.greenpeace.org/test-neptune/tag/renewables/) (on this one you can also make sure that the pagination is added to the canonical link as expected)
- [post type](https://www-dev.greenpeace.org/test-neptune/press/)
- [category](https://www-dev.greenpeace.org/test-neptune/category/issues/energy/)
Please test the changes with both the list and grid styles (`Listing page grid view` setting in [Planet 4 > …
> PLANET-7198 Add self-reference canonical urls to listing pages

- src/MasterSite.php
- src/Migrations/M018MigrateDonateButtonSetting.php
- src/Migrator.php
- src/Settings.php
- templates/burger-menu.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7047
Create a new `nav_menu` (AKA `wp_term`) as `donate-menu` in cases where this `term` is not already created. 
Also remove the Donate Button settings page.
In addition to that:
- Unset from `planet4_options` all the `donate settings`
- Remove default values from `$context` 
By default we provide the `donate-menu` as `Theme location` with unassigned term.
After running `wp-env run cli wp p4-run-activator` you'll get
> PLANET-7047: Migrate Donate button setting to a menu

- tag.php
- templates/tag.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7046
- on Deimos, check [Renewables tag page](https://www-dev.greenpeace.org/test-deimos/tag/renewables/) (I unselected the redirect page to display a regular tag page)
- check that [Redirected page](https://www-dev.greenpeace.org/test-deimos/tag/climate/) still works
> PLANET-7046: Align tag listing page with new design

- page.php
- single-campaign.php
- single-p4_action.php
- single.php
- templates/blocks/google_tag_manager.twig
See [PLANET-7102](https://jira.greenpeace.org/browse/PLANET-7102)
This is to make it easier to track High Level topics. Since all post types can have categories, I've added this new DLV to all of them (similar to the `post_tags`)
On local or on the [atlas test instance](https://www-dev.greenpeace.org/test-atlas/), any post/page/action should now have the `post_categories` DLV which you can check by typing `dataLayer` in the console.
> PLANET-7102 Add categories DLV on Posts

- src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-7137
---
Simple description text to inform admins about phasing out the feature flag.
> PLANET-7137: Add and EOL date on new identity feature flag

- src/MasterSite.php
- tests/e2e/search.spec.js
Ref: https://jira.greenpeace.org/browse/PLANET-7210
Rewrite search test to create its own content.
- creates a page for tag redirect
- creates a tag with redirect_page
- creates a post associated with tag
- search for redirect tag page and post
See [test run on CI](https://output.circle-artifacts.com/output/job/2f6cf6bc-18c0-4617-a9df-9b1dd34fba62/artifacts/0/usr/artifacts/playwright/report/index.html)
On local you need Elasticsearch activated:
```
npm run elastic:activate
```
if this fails, run
```console
> wp-env run cli wp  elasticpress index --setup
> wp-env run cli wp cache flush
> PLANET-7210: Rewrite search test independent of content

- tag.php
Ref: https://jira.greenpeace.org/browse/PLANET-7216
Fix instance of Post on tag page being WP_Post in some cases.
On local, load a Mena instance
- `npm run nro:install mena`
- check a tag page like `/en/tag/aboutus/`
- on _main_ it crashes
- on this branch the page displays properly
> PLANET-7216: Fix error on tag page

- assets/src/scss/layout/navbar/_burger-menu.scss
Otherwise it just uses the `--body--color` variable, this change makes it easier for NROs to override (see this [Slack thread](https://greenpeace.slack.com/archives/C014UMRC4AJ/p1691482547865659?thread_ts=1691478418.696729&cid=C014UMRC4AJ) for example)
The burger menu should still look as expected.
> Add CSS variable for the burger menu color

- admin/css/picker.css
- assets/src/js/Components/ArchivePicker.js
See [PLANET-7159](https://jira.greenpeace.org/browse/PLANET-7159)
You can test the changes by going to the Media Archive either on local or on the [telesto test instance](https://www-dev.greenpeace.org/test-telesto/wp-admin/upload.php?page=media-picker), and make sure the help tooltip looks and behaves as expected in all screen sizes.
> PLANET-7159 Add help tooltip to Media Archive

- assets/src/scss/layout/_navbar.scss
See [PLANET-7222](https://jira.greenpeace.org/browse/PLANET-7222)
Either on local or on the [leda test instance](https://www-dev.greenpeace.org/test-leda/), the Donate button menu dropdown should look good in all screen sizes
> PLANET-7222 Fix Donate button menu dropdown alignment

- src/CustomTaxonomy.php
- src/Loader.php
- src/Migrations/M021MigrateDefaultPostType.php
- src/Migrator.php
- src/Settings.php
- src/Settings/DefaultPostType.php
See [PLANET-7177](https://jira.greenpeace.org/browse/PLANET-7177)
The `Default P4 Post Type` setting should now be in `Settings > Writing`, you can make sure it still works as expected by creating a new post without any post type.
> PLANET-7177 Move Default P4 Post Type setting under Settings > Writing

- assets/src/scss/base/_css-variables.scss
- assets/src/scss/base/_variables.scss
- assets/src/scss/new-identity/style.scss
This allows to NROs to override font families when the new identity is being released.
Related PRs
- https://github.com/greenpeace/planet4-design-tokens/pull/13
> Implement CSS variables to font families

- templates/html-header.twig
This will allow adding child theme custom scripts without overriding the whole header template.
We have a use case by MENA to add a fundraising script in the head section. Since we don't offer a way to do that in the Admin Panel, this would help them do that with minimal future maintenance burden.
> Add template include for custom scripts

- assets/src/scss/new-identity/style.scss
See [PLANET-7215](https://jira.greenpeace.org/browse/PLANET-7215)
Related PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1096
Either on local or on the [oberon test instance](https://www-dev.greenpeace.org/test-oberon/), you can add a Submenu block to a page and make sure it looks as expected both with and without the new identity. Please make sure to test several styles and options of the block (links, etc), also in all different screen sizes!
> PLANET-7215 Apply the new design to the Submenu block

- assets/src/js/external_links.js
- assets/src/scss/new-identity/style.scss
See [PLANET-7219](https://jira.greenpeace.org/browse/PLANET-7219)
This PR includes several fixes:
- apply the new identity link styles to the Author block/page
- add the external link icon to the author page, to be consistent with the author block
- apply the new identity link styles to the 404 page content
You can test the new identity link styles in this [Author page](https://www-dev.greenpeace.org/test-atlas/author/ltiralon/), and for the Author block you can see it on [this post](https://www-dev.greenpeace.org/test-atlas/press/1113/duis-posuere-6/). You can test the 404 page [here](https://www-dev.greenpeace.org/test-atlas/404/) for example.
> PLANET-7219 Apply new identity link styles to the author block/page and 404 page

- assets/src/scss/base/_css-variables.scss
Ref: [PLANET-7225](https://jira.greenpeace.org/browse/PLANET-7225)
- Change the `--body--font-family` as the secondary font family.
- Change the `--headings--font-family` as the primary font family.
Disable the new identity and then the `Roboto` should be applied to `headings`, `links`, `navigation bar`, among other elements.
[Demo page](https://www-dev.greenpeace.org/test-atlas/)
> PLANET-7225: Fix font family for headings, links and body text

- assets/src/scss/pages/_sitemap.scss
- page-templates/sitemap.php
- templates/sitemap.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6793
> Follow up from [PLANET-6497](https://jira.greenpeace.org/browse/PLANET-6497), we need to change our Sitemap logic to just display categories and pages.
Display Categories and pages associated to those categories in a list as Sitemap, when new IA is activated.
- check [mars sitemap](https://www-dev.greenpeace.org/test-mars/sitemap/)
- locally, activate new IA and check that categories are all there (except Uncategorized) and toggle some categories association for pages
> PLANET-6793: Sitemap native taxonomies

- assets/src/scss/layout/_navbar.scss
No ticket needed
As a part of the maintenance, we should Force the nav donate content to align to middle
Unexpected behavior
Expected behavior
> Modify the children alignment within the donate nav

- author.php
- category.php
- index.php
- single-p4_action.php
- src/Post.php
- taxonomy.php
Ref: https://jira.greenpeace.org/browse/PLANET-7035
Implement new page types to DLV. It's applied to News, Listing and Action pages.
Navigate to any of these pages, open the console and log `window.dataLayer`. In theory the value should be at the index 2, so, `window.dataLayer[2].pageType` should print the right value.
Expected values:
- `News` for the page picked as the "Posts page" in Settings > Reading.
- `Listing Page` for all the auto-generated listing pages (categories, tags, author, post types, etc).
- `Actions` for all the Action pages.
> PLANET-7035: Add new Page Types to the Data Layer values

- templates/search.twig
- tests/e2e/tickets/PLANET-7191/PLANET-7191.test.js
Ref: https://jira.greenpeace.org/browse/PLANET-7191
> Search "Action type" or "Content type" filters toggle the same section
Locally, run (with elastic activated)
```
> TICKET=PLANET-7191 npx playwright test --ui tests/e2e/tickets/PLANET-7191/PLANET-7191.test.js
```
On test instance, click on Content Type and Action Type toggles, they should act independently.
> PLANET-7191: Fix search action and content toggles

- tag.php
Ref: https://jira.greenpeace.org/browse/PLANET-7247
Cf. https://github.com/WordPress/gutenberg/issues/53593
Cf. https://github.com/WordPress/gutenberg/pull/49904
With new IA activated, tag listing pages are missing the first post of the list, for each page, and showing only 9 instead of 10.
This is a known bug in Gutenberg. The fix consists in rewinding the main query  before entering the loop so that we don't miss the first post.
Locally, use International `npm run nro:install international`
or on [test instance Atlas](https://www-dev.greenpeace.org/test-atlas/tag/renewables/)
- check that default tag listing pages can show 10 posts per page
> PLANET-7247: Fix tag listing page not listing all posts

- src/Post.php
Ref https://jira.greenpeace.org/browse/PLANET-7072
**Testing:**
Either on local or on the [phoebe](https://www-dev.greenpeace.org/test-phoebe/wp-admin/index.php) test instance, -
- Ensure the `Select "Get Informed" page` is selected(Planet4 >> Analytics >> Select "Get Informed" page)
- Add first level & second child pages under "Get Informed" page"
- Check the DLV of 'PageType' field in page source,
- First level children pages: High Level Topic" [eg.](https://www-dev.greenpeace.org/test-phoebe/test-get-informed-page/first-child-of-get-informed-page/)
- Second level children pages: "Deep Dive Topic" [eg.](https://www-dev.greenpeace.org/test-phoebe/test-get-informed-page/first-child-of-get-informed-page/second-level-child-of-get-informed-page/)
> PLANET-7072 Set PageType DLV for High Level & Deep Dive Topic pages

- assets/src/scss/new-identity/style.scss
See [PLANET-7267](https://jira.greenpeace.org/browse/PLANET-7267)
Before this change they were not visible
Related PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1122
You can test the fix either on local or on [this page](https://www-dev.greenpeace.org/test-atlas/wp-admin/post.php?post=1168&action=edit) I created on the atlas test instance.
> PLANET-7267 Make sure editor links are styled with the new identity

- src/Migrations/M022UpdatePostRevisions.php
After the merge of #1945 we noticed that the query is returning always `0` posts to delete, which seems to be weird since too many posts has more that `20` revisions.
We detected that the problem is because we need to ORDER not only by `post_date` but also by `post_parent`, if not, we have an inconsistency with `@rownumber` counter since the counter is reseted whenever the `post_parent` is looped through a query.
```sql
@rownumber:=(IF(@postparent=post_parent, @rownumber:=@rownumber+1, 1)) as rwn,
@postparent:=post_parent
```
and the unexpected result
```
+-------------+------+-------+
| post_parent | rwn  | ID    |
+-------------+------+-------+
|         936 |    1 | 43693 |
|         936 |    2 | 43692 |
|         936 |    3 | 43691 |
|         936 |    4 | 43690 |
|         936 |    5 …
```
> Fix limit post revisions query

- functions.php
- src/Api/Settings.php
- src/Loader.php
- src/Settings/Features.php
Ref: https://jira.greenpeace.org/browse/PLANET-7264
```
GET /wp-json/planet4/v1/settings/
```
Log as admin on [test instance](https://www-dev.greenpeace.org/test-atlas/wp-admin/), then on the admin dashboard open your browser console and run
```
wp.apiRequest({path: '/planet4/v1/settings/'})
```
For API use, include a header `X-Auth-Token` matching the `PLANET4_API_KEY` constant.
```console
> curl -H 'X-Auth-Token: foo' 'http://www.planet4.test/wp-json/planet4/v1/settings' | jq
```
> PLANET-7264: Endpoint for listing options and plugins

- admin/css/archive-picker.css
- assets/src/js/Components/ArchivePicker/ArchivePicker.js
- assets/src/js/Components/ArchivePicker/ArchivePickerList.js
- assets/src/js/Components/ArchivePicker/SingleSidebar.js
- assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
- assets/src/js/media_archive.js
- assets/src/js/media_archive_editor_view.js
- assets/src/scss/editorOverrides.scss
- package-lock.json
- package.json
- src/AdminAssets.php
- src/MediaArchive/UiIntegration.php
- webpack.config.js
**Ref: [PLANET-7158](https://jira.greenpeace.org/browse/PLANET-7158)**
New implementation for the Media Archive on the editor.
**Testing:**
- Locally, run `npm run build` when you have pulled in the changes for this branch.
- The functionality should still be the same, but slight changes in the UI.
You can also test on the assigned test instance.
_So far this implementation works for just the **Image and Happy Point blocks**. In the Editor, you can add a new image using the new Media Archive implementation or even replace the existing image with a new one. At the moment changes are not saved, so make sure to update or publish your changes to a post/page._
> PLANET-7158 Editor Version of Media Archive

- src/Settings.php
See [PLANET-7178](https://jira.greenpeace.org/browse/PLANET-7178)
This is to simplify our P4 settings. This PR also removes some old code related to the Donate button settings, that we no longer need there since [we moved them](https://github.com/greenpeace/planet4-master-theme/commit/0547c5e7fe88565e6294a1352d0d8748ed32f33d#diff-eb1710f64250974d6d1550d421a31054e6079592ae3a8428cd9530bc086bdd94).
The Copyright settings should now be under `Planet 4 > Navigation`. Make sure that the previous Copyright settings values have been preserved.
> PLANET-7178 Move Copyright settings to Navigation settings

- author.php
- category.php
- src/Post.php
- tag.php
- taxonomy.php
- templates/base.twig
- templates/blocks/meta_fields.twig
See [PLANET-7268](https://jira.greenpeace.org/browse/PLANET-7268)
**Requirements:**
- All listing pages
- Categories, Tags, Post Types, Action Types
- Author page
- News & Stories
You can inspect pages to make sure the relevant tags are present, you can also use https://opengraph.xyz/ for validation.
- [Tag listing page](https://www-dev.greenpeace.org/test-rhea/tag/renewables/)
- [Post type listing page](https://www-dev.greenpeace.org/test-rhea/press/)
- [Category listing page](https://www-dev.greenpeace.org/test-rhea/category/energy/)
- [Action type listing page](https://www-dev.greenpeace.org/test-rhea/petitions/)
- [Author page](https://www-dev.greenpeace.org/test-rhea/author/tgarcia/)
- [News & stories page](https://www-dev.greenpeace.org/test-rhea/news-stories/)
> PLANET-7268 Add meta and opengraph html tags on listing pages

- package-lock.json
- package.json
Related to [PLANET-5973](https://jira.greenpeace.org/browse/PLANET-5973)
We're now using the [recent released version (0.3.0)](https://github.com/paulirish/lite-youtube-embed/releases/tag/v0.3.0).
> Maintenance: Upgrade the lite-youtube-embed npm library

- templates/author.twig
- templates/blocks/author_profile.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7333
Replace `trim()` function with `replace()` to avoid removing legitimate characters in avatar URL.
To test locally, you can edit `author.twig` and change the avatar url function with a static link to check if the URL ends up truncated:
```diff
-                     src="{{ fn('get_avatar_url', author.id, {'size' : 300}) | trim('=s96-c') }}"
+                     src="{{ "https://lh3.googleusercontent.com/a/ACg8ocJQbijyyfXduAZ9es8nsKGgelZZUctDai9y7RoDSqfkcoc"  | trim('=s96-c') }}"
````
> PLANET-7333: Fix author avatar URL trimmed

- assets/src/scss/pages/_page.scss
This is for pages without a title. Only the first `.wp-block-group` child of the page should have the margin top removed, not every direct child.
> Add missing first-child selector to remove margin top

- src/MasterSite.php
The previous regex didn't work with shorts. I found this new regex on the same [StackOverflow thread](https://stackoverflow.com/questions/3392993/php-regex-to-get-youtube-video-id) that is linked in our comment.
On local, add 2 Embed blocks to a page, one with a YouTube short and one with a regular YouTube video. On `main` branch the embed with a short will be broken in the frontend, whereas on this branch both should work as expected.
> Fix regex to get YouTube video id for shorts

- src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-7238
Cf. https://make.wordpress.org/core/2023/10/17/replacing-hard-coded-style-tags-with-wp_add_inline_style/
> PLANET-7238: Modify deprecated action

- src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-7340
Requires: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1164
> Do a pre-publish check so that Post title is not empty
> Enforce the rule for publishing or updating a Post
> This should be applied in all post types
On test instance [Pluto](https://www-dev.greenpeace.org/test-pluto/), try to:
- Publish a post/page with and without a title
- Quick edit a post/page with and without a title
> PLANET-7340: Make Post title mandatory for publishing

- src/Search.php
Ref. https://jira.greenpeace.org/browse/PLANET-7192
**Issue:**
- The new version of elasticpress plugin, list the images, password protected posts in search result, the searched post also has wrong links.
- This PR fixes issues listeding in [PLANET-7183](https://jira.greenpeace.org/browse/PLANET-7183) 
The elasticpress(v4.7.2) plugin by default won't filter data with admin ajax queries. with the help of `ep_ajax_wp_query_integration` filter add support for admin ajax search request.
**Testing:**
The fix is available for testing on [GP Sweden development instance](https://www-dev.greenpeace.org/sweden/?s=&orderby=_score). You can check the search result on click of "Show more 5 results" button.
> PLANET-7192 Enable elasticpress search query on admin ajax request

- assets/src/scss/layout/_featured-action.scss
- assets/src/scss/style.scss
- category.php
- tag.php
- templates/featured-action.twig
- templates/tag.twig
- templates/taxonomy.twig
**Ref: [PLANET-7277](https://jira.greenpeace.org/browse/PLANET-7277)**
**Testing:**
On test instance or locally, if you have Actions and visit a Category or Tag Listing Page and the taxonomy matches the Action, you should see a featured action section.
[Example Page](https://www-dev.greenpeace.org/test-venus/tag/forests/)
> PLANET-7277 Listing pages: add a featured Action section

- tests/e2e/gravity-forms.spec.js
The generic name previously used was sometimes considered spam and therefore would not behave as expected
> Fix Gravity Forms confirmation text test

- src/AnalyticsValues.php
- src/GoogleDocsClient.php
Ref: https://sentry.greenpeace.org/organizations/greenpeace-org/issues/230/
Capture errors on Google libs usage to avoid crashing instance and blocking post editing.
This is currently deployed on Japan instance and handles error properly.
https://sentry.greenpeace.org/organizations/greenpeace-org/discover/results/?field=title&field=event.type&field=timestamp&field=url&field=handled&name=All+Events&query=undefined+method&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29
> Capture errors on google client instantiation

- assets/src/block-editor/ImagePlaceholderIcon/ImagePlaceholderIcon.js
- assets/src/block-editor/URLInput/URLInput.js
- assets/src/block-editor/URLValidationMessage/URLValidationMessage.js
No ticket needed.
Create block-editor directory which will be included all components (from [here](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/tree/main/assets/src/components)) used by the editor. 
This PR replicates a similar structure of what [WordPress has already](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor).
This is a (partial) preparation before moving all blocks from the plugin to the theme.
> Idea: Create block-editor directory for components

- assets/src/functions/hydrateBlock.js
No ticket needed.
This is a preparation before including most of our blocks, from the plugin into the theme.
For now we're including the `hydrateBlock.js` file. We'll be including the rest of the files on demand.
> Maintenance: Add functions directory from plugin into the theme

- index.php
- page-templates/evergreen.php
- search.php
- single-campaign.php
- single-p4_action.php
- src/MediaArchive/ApiClient.php
- src/Post.php
- src/Search.php
Ref: [reset() - Array must be passed by reference](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/305/?query=is%3Aunresolved++url%3A%22https%3A%2F%2Fwww-dev.greenpeace.org%3A80%2Ftest-pandora%2F%2A%22&referrer=issue-stream&statsPeriod=14d&stream_index=0)
Ref: [Undefined array key `ch`](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/292/?query=is%3Aunresolved++url%3A%22https%3A%2F%2Fwww-dev.greenpeace.org%3A80%2Ftest-pandora%2F%2A%22&referrer=issue-stream&statsPeriod=14d&stream_index=1)
Ref: [Undefined array key `orderby`](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/368/?query=is%3Aunresolved&referrer=issue-stream&stream_index=2)
Ref: [foreach argument must be of type array|object](https://sentry.greenpeace.org/organizations/greenp …
> Fix warnings on PHP8

- assets/src/scss/layout/_breadcrumbs.scss
- category.php
- src/Context.php
- tag.php
- taxonomy.php
- templates/tag.twig
- templates/taxonomy.twig
See [PLANET-7276](https://jira.greenpeace.org/browse/PLANET-7276)
- Add a link to the "News & Stories" page as defined in `Settings > Reading > Posts page`.
- This should be applied in Category, Tag and Post Type listing pages.
- Add link following the [design mockups](https://www.figma.com/file/9NtbY8n3at8uOEJTsLrETb/P4-Design-System?type=design&node-id=4276-5015&mode=design&t=7AuHHMgJ8pgw8EKX-0)
You can test the new link on the following listing pages:
- [Post Type](https://www-dev.greenpeace.org/test-oberon/press/)
- [Tag](https://www-dev.greenpeace.org/test-oberon/tag/renewables/)
- [Category](https://www-dev.greenpeace.org/test-oberon/category/energy/)
> PLANET-7276 Add a 'back to News & stories' link to listing pages

- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Accordion/AccordionEditorScript.js
- assets/src/blocks/Accordion/AccordionFrontend.js
- assets/src/blocks/Accordion/AccordionScript.js
- assets/src/scss/blocks/Accordion/AccordionEditorStyle.scss
- assets/src/scss/blocks/Accordion/AccordionStyle.scss
- assets/src/scss/editorStyle.scss
- assets/src/scss/style.scss
- src/Blocks/Accordion.php
- src/Loader.php
- webpack.config.js
Ref: [PLANET-7300](https://jira.greenpeace.org/browse/PLANET-7300)
[Demo page](https://www-dev.greenpeace.org/test-phobos/accordion-block-demo-page/)
Move the Accordion block to master-theme
Related to [#1172](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1172)
> PLANET-7300: Move Accordion block into master theme

- assets/src/blocks/Cookies/CookiesBlock.js
- assets/src/blocks/Cookies/CookiesEditor.js
- assets/src/blocks/Cookies/CookiesEditorScript.js
- assets/src/blocks/Cookies/CookiesFieldResetButton.js
- assets/src/blocks/Cookies/CookiesFrontend.js
- assets/src/blocks/Cookies/CookiesScript.js
- assets/src/blocks/Cookies/useCookie.js
- assets/src/blocks/components/FrontendRichText/FrontendRichText.js
- assets/src/scss/blocks.scss
- assets/src/scss/blocks/Cookies/CookiesEditorStyle.scss
- assets/src/scss/blocks/Cookies/CookiesStyle.scss
- assets/src/scss/editorStyle.scss
- assets/src/scss/style.scss
- src/Blocks/Cookies.php
- src/Loader.php
- src/MasterBlocks.php
- webpack.config.js
See [PLANET-7302](https://jira.greenpeace.org/browse/PLANET-7302)
- Move Cookies block code to master theme.
- Migrate any additional dependencies it may need.
- Use the Guestbook block as a guide for the code/folder structure.
- The block should be tied to the Planet 4 Blocks feature flag.
This PR also includes style fixes for the `CookiesFieldResetButton` component, following this [mockup](https://www.figma.com/file/9NtbY8n3at8uOEJTsLrETb/P4-Design-System?type=design&node-id=4843%3A11035&mode=design&t=9qnx7PZ7YsEeosgJ-1). This was forgotten when working on the new identity.
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1169
Both new and existing Cookies blocks should still behave as expected in the editor and in the frontend. On the …
> PLANET-7302 Move Cookies block into master theme

- assets/src/blocks/editorIndex.js
Ref: https://jira.greenpeace.org/browse/PLANET-7345
We should avoid naming confusions to editors since we have already a custom Posts List variation with the same name.
FYI, this this is the [merged WordPress's Posts List variation PR](https://github.com/WordPress/gutenberg/pull/26990).
Make sure that the WP's Posts List variation is not being appeared through the blocks's list also enable `Planet 4 > Beta blocks`
> PLANET-7345: Disable Posts List Query Loop WP variation

- assets/src/block-editor/PostSelector/PostSelector.js
- assets/src/blocks/PostsList/index.js
- src/Blocks/PostsList.php
- src/Loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-7367
> Follow up from [PLANET-7214](https://jira.greenpeace.org/browse/PLANET-7214) to meet feature parity with the Articles block. We need an option for editors to able to select which specific posts they want to be displayed.
- import of component PostSelector from plugin
- use of a custom filter `postIn` and handle of value in hooks
- I tried to use the `include` filter available on rest API, but it generates some issues with various requests (maybe mixing up some cache), coming probably from [this piece of code](https://github.com/WordPress/gutenberg/blob/e2bda4036db44339aa56d0c85fa3d75edd79cd81/packages/core-data/src/queried-data/get-query-parts.js#L82-L91)
- Activate Core blocks and All blocks in _planet4 > Features_
- Add a _Posts …
> PLANET-7367: Add manual override to Posts List block

- composer.json
- composer.lock
- tests/bootstrap.php
Update polyfills to match [WordPress 6.4](https://github.com/WordPress/wordpress-develop/commit/f0d53f8100d5bc274b126995e5f08a509a70d91c)
- update `yoast/phpunit-polyfills` to 1.1.0
- lock `doctrine/instantiator` to 1.5 for php7.4 compatibility
- add  `WP_DEBUG:false` to test to avoid deprecation messages
> Update phpunit polyfills

- assets/src/scss/blocks/CarouselHeader/SidebarSlidesEditor.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7394
Fix image arrow's path
Navigate through [this page](https://www-dev.greenpeace.org/test-atlas/wp-admin/post.php?post=1353&action=edit) and select the CarouselHeader. Arrows should be visible in right panel.
> PLANET-7394: Fix missing up/down arrow icon in CarouselHeader

- assets/src/block-editor/ImageHoverControls/index.js
- assets/src/blocks/TakeActionBoxout/ImagePlaceholder.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
- assets/src/blocks/TakeActionBoxout/deprecated/takeActionBoxoutV1.js
- assets/src/blocks/editorIndex.js
- assets/src/scss/blocks.scss
- assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutEditorStyle.scss
- assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
- assets/src/scss/editorStyle.scss
- src/Blocks/BaseBlock.php
- src/Blocks/TakeActionBoxout.php
- src/Loader.php
- src/MasterBlocks.php
- src/MasterSite.php
- templates/blocks/take-action-boxout.twig
Ref: [PLANET-7306](https://jira.greenpeace.org/browse/PLANET-7306)
Move the Take Action Boxout block into the master-theme. It should have the same behavior as the one from the plugin.
**Related to:**
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1179
Demo page: https://www-dev.greenpeace.org/test-rhea/story/1236/take-action-boxout-block-into-the-master-theme/
> PLANET-7306: Move Take Action Boxout block into master-theme

- src/Blocks/BaseBlock.php
- src/Blocks/Spreadsheet.php
[No ticket needed]
This small change is because to avoid repeated code and easy to maintain. The `REST_NAMESPACE` constant is being used, at least, by two different blocks. These are the Spreadsheet and the Happypoint.
> Maintenance: move REST_NAMESPACE const to BaeBlock PHP class

- assets/src/scss/layout/_wide-blocks.scss
- assets/src/scss/style.scss
[No ticket needed]
Include `.block-wide` and `.alignfull` CSS Classes. It should works when the plugin is disabled.
> Include wide-blocks stylesheet into master theme

- functions.php
Following CPU spike incident.
From https://github.com/stayallive/wp-sentry/#wp_sentry_options
Report only 25% of errors for the time being.
We can probably later refine to modify the rate to specific error types only (cf https://docs.sentry.io/platforms/php/configuration/sampling/ ).
> Lower Sentry sampling rate to 25%

- src/ListingPage.php
Ref: https://sentry.greenpeace.org/organizations/greenpeace-org/issues/868/?query=is%3Aunresolved+release%3Av2.121.0-fix-php8&referrer=issue-stream&statsPeriod=14d&stream_index=1
Fix taxonomy check when page is not relevant
- consult an author page, display page 2 of their list of articles
- this branch should not generate warnings in logs (`npx wp-env logs`)
> Fix warning on articles list on author page

- src/CustomTaxonomy.php
Ref: https://jira.greenpeace.org/browse/PLANET-7404
On local
- `npm run nro:install denmark`
- checkout this branch
- test url `http://www.planet4.test/pressemeddelelse/feed`
- it's sending back a 404
- flush rewrite rules with `npx wp-env run cli wp rewrite flush`
- test the feed url again
- it should send back a feed
- check the rewrite rules with `npx wp-env run cli wp rewrite list`, rules are applied in order, the feed matching rule should be above our individual page type rules
```
| (nyhed|pressemeddelelse|udgivelse)/(feed|rdf|rss | index.php?p4-page-type=$matches[1]&feed=$matches | root         |
| |rss2|atom)/?$                                   | [2]                                              |              |
| nyhed(/page/([0-9]+)?)?/?$                       | …
```
> PLANET-7404: Fix page type feed url matching

- assets/src/js/external_links.js
This should solve the issue seen in the Handbook ideas for the comments link ([PLANET-6081](https://jira.greenpeace.org/browse/PLANET-6081))
On [this page](https://planet4.greenpeace.org/idea/have-pages-visible-only-to-people-with-the-link-restricted-access/#comments) for example you can see that the comments link has the external link icon, and I'm guessing it's because it doesn't have a `href`:
> PLANET-6081 Remove external link icon when no href

- assets/src/js/Components/ArchivePicker/ArchivePickerToolbar.js
- assets/src/js/media_archive_editor_view.js
- src/MediaArchive/UiIntegration.php
**Ref: [PLANET-7411](https://jira.greenpeace.org/browse/PLANET-7411)**
**Testing:**
_Media Archive_ should now be named _Greenpeace Media_ in both the Dashboard and Editor view
> PLANET-7411 Change name of Media Archive to Greenpeace Media

- assets/src/blocks/ActionsList/index.js
Move layout declaration to post-template
- `displayLayout` was [removed from core/query attributes](https://github.com/WordPress/gutenberg/pull/49050/files#diff-47c277e0638989855123b829b2f5044edb47fe394770f2fea4f0775c0b944936)
- grid layout is handled by core/post-template
> PLANET-7238: Fix core/query layout for WP6.4

- tests/e2e/gravity-forms.spec.js
- tests/e2e/tools/lib/gravity-forms.js
See [PLANET-7319](https://jira.greenpeace.org/browse/PLANET-7319)
**Steps**
1. Login to the Admin Panel.
2. Create a new Form:
- First Name (single line text input)
- Last Name (single line text input)
- Email (email field)
- Submit button
3. Go to Form Settings on the Hubspot section.
4. Create a new Feed:
- Lead Status: New
- Lifecycle Stage: Lead
- Map contact fields.
5. Save the Feed.
6. Verify the new Feed has "Active" state.
> PLANET-7319 Add a Gravity Forms e2e test for Hubspot feeds

- src/GravityFormsExtensions.php
See [PLANET-7405](https://jira.greenpeace.org/browse/PLANET-7405)
It seems that we no longer need custom code for this, it works as expected without it! I'm guessing it was fixed by a Gravity Forms upgrade at some point 🤔 
I have set up the Hubspot GF add-on on the neptune test instance, and created a form with a Hubspot feed, called `Duplication test form`. On [this page](https://www-dev.greenpeace.org/test-neptune/wp-admin/admin.php?page=gf_edit_forms) you can duplicate the form, and then make sure that the feed has been duplicated too. It should be independent of the initial feed, meaning deleting one doesn't affect the other.
> PLANET-7405 Remove GF feed duplication custom code

- single.php
- templates/base.twig
See [PLANET-7425](https://jira.greenpeace.org/browse/PLANET-7425)
This is to be used in ArticlesFrontend to retrieve the right content
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1186
Both in Pages and Posts, the `ignore_categories` attribute should now work as expected!
> PLANET-7425 Add post categories to body dataset

- assets/src/block-editor/NavigationType/NavigationType.js
- assets/src/block-editor/Sidebar/ActionSidebar.js
- assets/src/block-editor/Sidebar/AnalyticsTrackingSidebar.js
- assets/src/block-editor/Sidebar/CampaignThemeSidebar.js
- assets/src/block-editor/Sidebar/LocalThemeSettings.js
- assets/src/block-editor/Sidebar/PageHeaderSidebar.js
- assets/src/block-editor/Sidebar/PostParentLink.js
- assets/src/block-editor/Sidebar/SearchEngineOptimizationsSidebar.js
- assets/src/block-editor/Sidebar/ThemeSettings.js
- assets/src/block-editor/fromThemeOptions/fromThemeOptions.js
- assets/src/block-editor/saveMetaToPreview.js
- assets/src/block-editor/setupCustomSidebar.js
- assets/src/theme/p4ServerThemes.js
Ref. https://jira.greenpeace.org/browse/PLANET-7379 
Move Analytics Tracking, SEO, Action, Campaign Theme, Page Header(atm I moved all fields, afterward we will keep only "hide page title field") sidebar fields to master theme.
> Planet 7379 Move remaining sidebar fields to Master theme

- assets/src/js/cookies.js
- templates/blocks/google_tag_manager.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7409
> Two new parameters need to be implemented on the Consent Mode script: 
> 
>     ad_user_data 
>     ad_personalization 
>  The new parameters should be set using the **same value as the ad_storage parameter**. 
> 
>  In the scripts that execute the consent default, the following instruction should be added: 
> 
>  gtag('set', 'url_passthrough', true); 
>  gtag('set', 'ads_data_redaction', true); 
> 
>  The url_passthrough parameter should always be set to true and is only set when the script that executes the consent default is run. 
>     The ads_data_redaction parameter should be set according to the following logic: 
>       - true when ad_storage is set to denied. 
>       - false when ad_storage is set to granted.
> PLANET-7409: Implement new parameters on Google Consent Mode

- single.php
- src/Context.php
- src/Post.php
- templates/blocks/google_tag_manager.twig
- templates/single.twig
- templates/tease-author.twig
- templates/tease-taxonomy-action.twig
- templates/tease-taxonomy-post.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7426
Requires: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1189
> dataLayer variable for reading_time for all Posts, in milliseconds
> Add the dataLayer variable regardless on whether it's being displayed in the frontend
A variable `reading_time` is added to `dataLayer` as reading time of the displayed post, in milliseconds. This appears even if the post type is not configured for Reading time display. 
- `Post::reading_time()` now returns time in seconds
- `Post::reading_time_for_display()` returns rounded time in minute or null, taking taxonomy configuration into account
> PLANET-7426: Add reading_time datalayer variable

- assets/src/block-editor/PostSelector/PostSelector.js
- assets/src/block-editor/QueryLoopBlockExtension/index.js
- assets/src/blocks/ActionsList/index.js
- assets/src/blocks/PostsList/index.js
- assets/src/editorIndex.js
- src/Blocks/QueryLoopExtension.php
- src/Loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-7415
Requires: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1192
> Follow the work of [PLANET-7367](https://jira.greenpeace.org/browse/PLANET-7367) and replicate the "Manual Override".
- Add an Actions List block to a page
- Override the post list with specific Actions pages
- Check backend and frontend display
> PLANET-7415: Add manual override to Actions list block

- assets/src/scss/pages/post/_article-content.scss
See [PLANET-7444](https://jira.greenpeace.org/browse/PLANET-7444)
This code has been moved to `Image.scss` in the plugin so that it works for all post types
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1194
I've added the various Image alignments on the following:
- [Page](https://www-dev.greenpeace.org/test-pandora/page-with-images/)
- [Post](https://www-dev.greenpeace.org/test-pandora/story/1273/post-with-images/)
- [Action](https://www-dev.greenpeace.org/test-pandora/petitions/action-with-images/)
> PLANET-7444 Remove unnecessary code for image alignment

- assets/src/block-editor/Sidebar/PageHeaderSidebar.js
- page-templates/sitemap.php
- src/Migrations/M028MovePageHeaderSideBarOptions.php
- src/Migrator.php
**Ref: [PLANET-7348](https://jira.greenpeace.org/browse/PLANET-7348)**
**Testing**
You can compare certain pages on the test instance to those of the [DefaultContent](https://www-dev.greenpeace.org/defaultcontent/) instance to see the changes
For example: 
- [Privacy and cookies](https://www-dev.greenpeace.org/defaultcontent/privacy-and-cookies/) (Default Content Instance)
- [Privacy and cookies](https://www-dev.greenpeace.org/test-oberon/privacy-and-cookies/) (Test instance)
> PLANET-7348 Migrate Page Header options to Page Header block pattern

- src/Migrations/M028MovePageHeaderSideBarOptions.php
Ref: https://jira.greenpeace.org/browse/PLANET-7348
Cf. https://developer.wordpress.org/reference/functions/wp_update_post/#parameters
Update function expects array data to be escaped. We're using the same `wp_slash` used by [the update function](https://developer.wordpress.org/reference/functions/wp_update_post/#source) on object.
> PLANET-7348: Escape migrated post content on update

- assets/src/blocks/CarouselHeader/StaticCaption.js
Ref. https://jira.greenpeace.org/browse/PLANET-7447
**Issue reproduced here -**
https://www-dev.greenpeace.org/test-titan/test-html-entites-on-carousel-header/
**Issue fixed here-**
https://www-dev.greenpeace.org/test-neptune/test-html-entites-on-carousel-header/
> PLANET-7447 Unescape HTML entities in Carousel header title

- assets/src/blocks/PostsList/index.js
- assets/src/scss/blocks/ActionsList.scss
- assets/src/scss/blocks/PostsList.scss
- assets/src/scss/editorOverrides.scss
- assets/src/scss/layout/_query-loop-overrides.scss
See [PLANET-7417](https://jira.greenpeace.org/browse/PLANET-7417)
Following a conversation with Houssam, instead of a carousel in smaller screens we will keep a grid there too, with 2 items per row on tablets and 1 item per row on mobiles.
In this PR I also moved some CSS around, to make sure that everything specific to the Actions List or Posts List blocks are in their respective files.
You can make sure all the layouts look and behave as expected for both list blocks:
- [Posts List](https://www-dev.greenpeace.org/test-sinope/posts-lists/)
- [Actions List](https://www-dev.greenpeace.org/test-sinope/actions-lists/)
Make sure to test in all screen sizes 🙂
> PLANET-7417 Add grid layout to Posts List block

- src/ElasticSearch.php
Ref: https://jira.greenpeace.org/browse/PLANET-7443
Meta `ep_exclude_from_search` is not used on ajax search query, as our search is considered "in admin".
Fix by forcing meta usage.
As for other EP issues, our ajax requests for search are considered "in admin" (passing through admin-ajax.php, setting WP_ADMIN const to true), and so trigger some specific behaviors from EP. Here, it sets the filter `ep_bypass_exclusion_from_search` to `true` (cf [elasticpress source](https://10up.github.io/ElasticPress/includes_classes_Feature_Search_Search.php.html#line733))
On a local instance using Brasil db, 
- search for `obrigado`
- scroll down to trigger an ajax request for the next 5 results
- without this fix, you should see Thank you pages for petitions (`Proteja os oceanos - Obrigado` for …
> PLANET-7443: Fix Exclude from search EP functionality

- src/Blocks/BaseBlock.php
This is needed for the [Social Media block](https://github.com/greenpeace/planet4-master-theme/blob/eef1d17d1dad3693c6d4b609e78921896cf58730/src/Blocks/SocialMedia.php#L131) but we forgot to add it. I found this issue while checking [Sentry](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/1621/?environment=development&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=0).
> Add missing is_rest_request function to BaseBlock class

- assets/src/scss/layout/navbar/_search.scss
It shouldn't be white but stay grey in all screen sizes, otherwise we don't see it
You can compare the 2 versions on test instances, by typing in the navbar search input in large screens:
- [broken](https://www-dev.greenpeace.org/test-rhea/)
- [fixed](https://www-dev.greenpeace.org/test-pandora/)
> Fix clear search button in large screens

- assets/src/blocks/ActionsList/index.js
- assets/src/blocks/PostsList/index.js
- src/Blocks/QueryLoopExtension.php
Ref: https://jira.greenpeace.org/browse/PLANET-7448
> We should find a way to exclude password-protected content from the Query Loop block.
- Insert Actions or Posts list block in a page
- Check which posts are included;
- edit one of them to add a password ("quick edit" from the list of pages/actions)
- on this branch, those password-protected posts should not appear in the blocks anymore (after reload), in the editor and on the frontend
> PLANET-7448: Exclude password-protected content from Action/Post list block

- author.php
- src/AuthorPage.php
- src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-7431
> The author listing pages show all posts published by the Editor (as per the author dropdown) even though they are not the Author (as per the author override field)
The `author.php` page tries to edit the Main query, which has already been processed.  
Moving code to a hook on `pre_get_posts` instead will work the expected way.
With `international` DB:
- Check the author page `author/angelo-louw/`
- The page should only list articles with this author as author, _not editor_
- Compare with the current prod page https://www.greenpeace.org/international/author/angelo-louw/
> PLANET-7431: Author profile page returns all posts by Editor

- assets/src/block-templates/edit.js
- assets/src/block-templates/main-theme-url.js
- assets/src/block-templates/register.js
- assets/src/block-templates/save.js
- assets/src/block-templates/side-image-with-text-and-cta/block.json
- assets/src/block-templates/side-image-with-text-and-cta/index.js
- assets/src/block-templates/side-image-with-text-and-cta/template.js
- assets/src/block-templates/template-list.js
- assets/src/editorIndex.js
- src/Loader.php
- src/Patterns/BlockPattern.php
- src/Patterns/SideImageWithTextAndCta.php
**Description: [PLANET-7400](https://jira.greenpeace.org/browse/PLANET-7400)**
Testing: 
If you comment out this [code](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/classes/class-loader.php#L184) and [this](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/editorIndex.js#L52) in the blocks repo locally, you should still see the _Side Image with Text_ Pattern in the editor
> PLANET-7400 Move Side image with text and CTA block pattern into master theme

- theme.json
See [PLANET-7457](https://jira.greenpeace.org/browse/PLANET-7457)
This was confusing for our Actions List and Posts List blocks, I've discussed it with Nikos and it's fine to remove it for all Query Loop blocks since editors don't use them yet. Maybe in the future Gutenberg offers a more granular way of configuring these options per variation.
The `Layout` section should no longer be in the sidebar when adding a Posts List or Actions List block.
> PLANET-7457 Remove Layout sidebar section in Query Loop block

- src/MasterSite.php
- src/Migrations/M028MovePageHeaderSideBarOptions.php
Catch "Title is required" errors
Catch WPML missing translations errors
Using `switzerland` DB
- run `npx wp-env run cli wp p4-run-activator`
- patch M028 should run without failing (some warnings may appear)
- some warnings should appear
- some messages 'Error on page xxx' should appear
> Fix migration to avoid failing on post update errors

- assets/src/blocks/Media/MediaBlock.js
- assets/src/blocks/SocialMedia/SocialMediaBlock.js
- assets/src/blocks/Submenu/SubmenuBlock.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
- assets/src/blocks/Timeline/TimelineBlock.js
See [PLANET-7492](https://jira.greenpeace.org/browse/PLANET-7492)
The blocks registered via the `editorIndex` file were sometimes registered twice:
The console warnings should no longer be there when opening the editor. There is still one for a block pattern being registered twice, but Osong is looking into it since he's working on moving another pattern at the moment.
> PLANET-7492 Make sure blocks are not registered twice

- assets/src/scss/blocks/ENForm/ENFormEditorStyle.scss
- assets/src/scss/blocks/ENForm/components/_enform-full-width-bg.scss
- assets/src/scss/blocks/ENForm/components/_enform-full-width.scss
- assets/src/scss/blocks/ENForm/components/_enform.scss
The full width version of the block (without background image) should have a green background, see [Slack thread](https://greenpeace-gpi.slack.com/archives/G015K63081W/p1712740351855869)
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1200
On the jupiter instance you can activate the ["all blocks" feature](https://www-dev.greenpeace.org/test-jupiter/wp-admin/admin.php?page=planet4_settings_features), and then use [this page](https://www-dev.greenpeace.org/test-jupiter/just-an-enform/) to test the theme version of the block.
> Fix ENForm background color

- assets/src/block-templates/issues/block.json
- assets/src/block-templates/issues/index.js
- assets/src/block-templates/issues/template.js
- assets/src/block-templates/register.js
- assets/src/block-templates/template-list.js
- src/Patterns/BlockPattern.php
- src/Patterns/Issues.php
Description: [PLANET-7397](https://jira.greenpeace.org/browse/PLANET-7397)
Testing:
If you comment out this [code](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/classes/class-loader.php#L184) and [this](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/editorIndex.js#L52) in the blocks repo locally, you should still see the Issues Pattern in the editor
> PLANET-7397 Move Issues block pattern into master theme

- src/MasterSite.php
- src/Migrations/M017NewIAToggle.php
- src/Migrations/M025CreateDefaultPostsPage.php
- tests/bootstrap.php
- tests/e2e/comments.spec.js
- tests/e2e/gallery.spec.js
- tests/e2e/gravity-forms.spec.js
- tests/e2e/navigation-bar.spec.js
- tests/e2e/password-protected-content.spec.js
- tests/e2e/search.spec.js
- tests/e2e/special-pages.spec.js
- tests/e2e/tools/lib/editor.js
- tests/e2e/tools/lib/post.js
- tests/p4-testcase.php
- tests/test-action-type-custom-taxonomy.php
- tests/test-category-page.php
- tests/test-custom-permalinks.php
- tests/test-custom-taxonomy.php
- tests/test-open-graph.php
See [PLANET-7344](https://jira.greenpeace.org/browse/PLANET-7344)
I didn't add a WP alert similar to what we do [here](https://github.com/greenpeace/planet4-master-theme/blob/main/src/MasterSite.php#L430) for the title, because I couldn't find a way to properly check whether or not a featured image was set at this point, so the alert was always shown no matter what. From what I've tested the check from the plugin is enough to disable the update/publish button when no image is set, only issue then is that there is no explanation when it's an update but that's also the case for the title 🤷‍♀️ 
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1190
You should no longer be able to publish or update a Page/Post/Action without setting a featured image or adding …
> PLANET-7344 Make featured image mandatory for publishing

- assets/src/scss/blocks/PostsList.scss
- assets/src/scss/layout/_query-loop-overrides.scss
See [PLANET-7458](https://jira.greenpeace.org/browse/PLANET-7458)
It seems removing the `flex` display does the trick
Add a Posts List or Actions List to a page with the carousel layout, then in the frontend you can manually add `dir="rtl"` to the html element. On `main` branch the block should be blank but on this branch it should display as expected.
On the janus instance I've created [this page](https://www-dev.greenpeace.org/test-janus/the-list-blocks/) with both blocks that you can check as well.
> PLANET-7458 Fix Actions List and Posts List carousel layout in RTL sites

- assets/src/blocks/Timeline/TimelineEditorScript.js
- assets/src/functions/isLodash.js
Ref. https://jira.greenpeace.org/browse/PLANET-7175
The error was caused by conflicts between the underscore and lodash libraries.
**Testing:**
- The issue can be reproduced on [test-jupiter](https://www-dev.greenpeace.org/test-jupiter/wp-admin/post-new.php) instance as below -
https://github.com/greenpeace/planet4-master-theme/assets/5357471/54ead07b-830b-44dd-9768-97604c0b6116
- The same issue should not reproduce on [test-iocaste](https://www-dev.greenpeace.org/test-iocaste/wp-admin/post-new.php) instance.
**Note:** A similar fix needs to be added in the blocks plugin as well, or it can be tested by disabling the blocks plugin.
> PLANET-7175 Fix timeline block editor error

- assets/src/blocks/PostsList/index.js
- assets/src/scss/blocks/PostsList.scss
- src/MasterBlocks.php
See [PLANET-7491](https://jira.greenpeace.org/browse/PLANET-7491)
This is to replace the load more functionality that we have in the Articles block
Either on local or on the [venus test instance](https://www-dev.greenpeace.org/test-venus/), you can add a Posts List block to a page and make sure that the `See all stories` link behaves as expected in all screen sizes.
Make sure to also test the use case where the [News & Stories page](https://www-dev.greenpeace.org/test-venus/wp-admin/options-reading.php) is not set, in that case the new link should not be added to the block (this will only be true for new blocks, existing ones will not be updated).
> PLANET-7491 Add see all link to Posts List block

- composer.json
- composer.lock
- functions.php
- src/AnalyticsValues.php
- src/Blocks/ENForm.php
- src/Campaigns.php
- src/CloudflarePurger.php
- src/CustomTaxonomy.php
- src/GravityFormsExtensions.php
- src/Importer.php
- src/ListingPage.php
- src/Loader.php
- src/MasterBlocks.php
- src/MasterSite.php
- src/Post.php
- src/Post/ReadingTimeCalculator.php
- src/Search.php
- src/Settings.php
- src/Settings/Features.php
- src/Sitemap.php
- tests/test-category-page.php
- tests/test-open-graph.php
Ref: https://jira.greenpeace.org/browse/PLANET-7390
Requires: https://github.com/greenpeace/planet4-base/pull/291
Requires: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1195
- clarify autoload logic
- require timber/timber for php unit tests
- fix syntax following composer update of phpcs rules
- _planet4-develop_ branch for tests: `update/timber-composer-7390`
- fully deployed on [test-leda](https://www-dev.greenpeace.org/test-leda/)
> PLANET-7390: Require Timber as composer package

- src/MasterSite.php
See [PLANET-7199](https://jira.greenpeace.org/browse/PLANET-7199)
They would sometimes appear in two separate lines, because the previous implementation added a new `figcaption` element with the credits
You can compare the possible caption/credits combinations on these 2 pages:
- [Broken](https://www-dev.greenpeace.org/test-rhea/images/)
- [Fixed](https://www-dev.greenpeace.org/test-jupiter/images/)
> PLANET-7199 Fix Image block caption/credits

- src/MasterBlocks.php
- templates/block_templates/enform/enform_post.twig
See [Slack thread](https://greenpeace-gpi.slack.com/archives/C016H6ELXAL/p1713776950660969)
This is to avoid registering the same function twice
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1204
> Rename object_to_array function

- admin/css/archive-picker.css
- assets/src/js/Components/ArchivePicker/MultiSearchOption.js
Ref. https://jira.greenpeace.org/browse/PLANET-7490
**Task:**
1. Change the search limit from 6 to 8 IDs/keywords on the Greenpeace Media in the backend.
2. Adjust the form input width accordingly to make sure IDs/keywords are displayed in one line.
**Testing:**
- The Greenpeace Media search should now allow to search an 8 keywords.
You can test it on local or [test-oberon](https://www-dev.greenpeace.org/test-oberon/wp-admin/upload.php?page=media-picker) instance
> PLANET-7490 Update search limit from 6 to 8 on Greenpeace Media

- src/MasterBlocks.php
This will fix the warning issue ['The block "planet4-block-templates/***" is registered with an invalid category "planet4-block-templates"'](https://github.com/greenpeace/planet4-master-theme/pull/2258#pullrequestreview-2016559047).
> Adding a new planet4 category

- assets/src/block-variations/index.js
- assets/src/editorIndex.js
- assets/src/scss/editorStyle.scss
- assets/src/scss/style.scss
- assets/src/scss/variations/stretched-link/edit.scss
- assets/src/scss/variations/stretched-link/index.scss
No ticket needed.
[Stretched link variations styles](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/tree/9cd9a3cfe4f8b401b2fddd2fe40fcebb51610f0f/assets/src/variations/stretched-link) and [block variation in JS](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/e980c81583a3ffdf32ad86d718e0e6495caa1d9e/assets/src/editorIndex.js#L37-L50) are Required in master theme.
Also required by:
- https://github.com/greenpeace/planet4-master-theme/pull/2258
- https://github.com/greenpeace/planet4-master-theme/pull/2259
> Add stretched link variations from plugin

- src/MasterSite.php
- src/Settings.php
- templates/base.twig
- templates/blocks/google_tag_manager.twig
Ref: https://github.com/greenpeace/planet4/issues/187
Adds an additional setting in the Analytics section of P4 settings for a custom domain name to load Tag Manager scripts from. The domain is then used in two places where the tag manager scripts are loaded. When the setting is left empty, the default domain of Tag Manager is used.
> Add setting for custom Tag Manager scripts URL

- admin/css/dashboard.css
Since we have automatic updates off, this message may be confusing for website admins.
- Currently we do get this message even on local env as there is an update available for GF (see screenshot below).
- Switching to this branch, the message should no longer be visible.
> Hide GravityForms update message

- assets/src/block-templates/reality-check/block.json
- assets/src/block-templates/reality-check/index.js
- assets/src/block-templates/reality-check/template.js
- assets/src/block-templates/template-list.js
- src/Patterns/BlockPattern.php
- src/Patterns/RealityCheck.php
Ref: https://jira.greenpeace.org/browse/PLANET-7399
**Testing:** 
If you comment out this [code](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/classes/class-loader.php#L184) and [this](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/editorIndex.js#L52) in the blocks repo locally, you should still see the Issues Pattern in the editor
> PLANET-7399 Move Reality Check block pattern into master theme

- assets/src/block-templates/quick-links/block.json
- assets/src/block-templates/quick-links/index.js
- assets/src/block-templates/quick-links/template.js
- assets/src/block-templates/template-list.js
- src/Patterns/BlockPattern.php
- src/Patterns/QuickLinks.php
Ref:  https://jira.greenpeace.org/browse/PLANET-7398
**Testing**
If you comment out this [code](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/classes/class-loader.php#L184) and [this](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/editorIndex.js#L52) in the blocks repo locally, you should still see the Issues Pattern in the editor
> PLANET-7398 Move Quick Links block pattern into master theme

- assets/src/blocks/Submenu/getHeadingsFromDom.js
The h2 of the submenu block has ancestors that match :not(.submenu-block), that's why it was included in the results. By only looking for direct ancestors that match :not(.submenu-block) it is excluded as intended.
Ref: https://jira.greenpeace.org/browse/PLANET-7503
> PLANET-7503: Fix selector to exclude submenu header in submenu block

- src/Sendgrid.php
Filter name: planet4_sendgrid_sender
Ref. https://jira.greenpeace.org/browse/PLANET-7366
**Usage:**
```
// The filter callback function.
function update_planet4_sendgrid_sender( $sender ) {
// (maybe) change $sender.
return $sender;
}
add_filter( 'planet4_sendgrid_sender', 'update_planet4_sendgrid_sender', 10, 1 );
```
[Documentation link](https://github.com/greenpeace/planet4-docs/blob/master/docs/tech/hooks.md)
> PLANET-7366 Add filter hook for overriding Sendgrid from address

- assets/src/block-templates/deep-dive/block.json
- assets/src/block-templates/deep-dive/index.js
- assets/src/block-templates/deep-dive/template.js
- assets/src/block-templates/template-list.js
- assets/src/scss/editorOverrides.scss
- src/Patterns/BlockPattern.php
- src/Patterns/DeepDive.php
Ref: https://jira.greenpeace.org/browse/PLANET-7395
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1202
- https://github.com/greenpeace/planet4-master-theme/pull/2269
- https://github.com/greenpeace/planet4-master-theme/pull/2270
- https://github.com/greenpeace/planet4-master-theme/pull/2285
[Demo page](https://www-dev.greenpeace.org/test-janus/deep-dive-block-demo-page/)
Move Deep Dive block into the theme
- Create new core overrides folder and files. These are moved from the plugin
- Make small improvments on the above mentioned files
- Move image's SASS `mixins` to the right place
- Create a new page
- Edit that page
- Click on "+" and click on "Patterns" tab
- The Deep Dive block should be visible on that list
> PLANET-7395: Move Deep Dive block pattern into master theme

- assets/src/block-templates/highlighted-cta/block.json
- assets/src/block-templates/highlighted-cta/index.js
- assets/src/block-templates/highlighted-cta/template.js
- assets/src/block-templates/template-list.js
- src/Patterns/BlockPattern.php
- src/Patterns/HighlightedCta.php
Ref: https://jira.greenpeace.org/browse/PLANET-7396
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1203
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1205
- https://github.com/greenpeace/planet4-master-theme/pull/2269
- https://github.com/greenpeace/planet4-master-theme/pull/2270
- https://github.com/greenpeace/planet4-master-theme/pull/2285
Demo page: https://www-dev.greenpeace.org/test-pluto/highlighted-cta-demo-page/
Move HighlightedCTA block into the theme
- Create a new page
- Edit that page
- Click on "+" and click on "Patterns" tab
- The HighlightedCTA block should be visible on that list
In addition to this, make sure the block is properly rendered within the highlighted
> PLANET-7396: Move Highlighted CTA block pattern into master theme

- assets/src/block-editor/Sidebar/AnalyticsTrackingSidebar.js
Ref: https://jira.greenpeace.org/browse/PLANET-7516
When testing WordPress 6.5 the AnalyticsTrackingSidebar stopped working.
I noticed that the problem comes after adding the analytics-values Entity but not sure exactly why this happens. Unfortunately, there is no recent updates of the addEntities function.
Currently we add the analytics-values entity like this
```
dispatch('core').addEntities([{
baseURL: '/planet4/v1/analytics-values',
kind: 'planet4/v1',
name: 'analytics-values',
label: 'Analytics and tracking values',
}]);
```
And getting the value
```
const options = useSelect(select => {
return select('core').getEntityRecords('planet4/v1', 'analytics-values', {id: postId});
});
```
Finally, the endpoint GET http://www.planet4.test/wp-json/planet4/v1/analytics-values?id=:ID is …
> PLANET-7516: Fix Analytics Tracking Sidebar component

- templates/burger-menu-items.twig
- templates/burger-menu.twig
- templates/desktop-menu.twig
- templates/footer.twig
- templates/navigation-bar.twig
- templates/navigation-bar_min.twig
- templates/navigation-submenu.twig
Comes from https://greenpeace-gpi.slack.com/archives/C0160MX64AG/p1715929906416189
It depends on "Open in a new tab" option
- Go to /menus
- Choose the main navigation
- Edit any sub item by selecting "Open in a new tab"
- Then save
- Test the menu from the site
> Add alt attribute to nav-items

- admin/css/archive-picker.css
- assets/src/js/Components/ArchivePicker/ArchivePickerToolbar.js
See [PLANET-7505](https://jira.greenpeace.org/browse/PLANET-7505)
Either on local or on the [neptune instance](https://www-dev.greenpeace.org/test-neptune/wp-admin/upload.php?page=media-picker), go to the Greenpeace Library and make sure that the search form looks good in all screen sizes. Please test as many scenarios as possible (open sidebar, up to 8 keywords, length of the keywords...)
> PLANET-7505 Adjust Greenpeace Media search UX

- src/Controllers/Menu/EnformPostController.php
- src/MasterSite.php
Ref. https://jira.greenpeace.org/browse/PLANET-7533
This PR will fix below Function param Type error -
> Fatal error: Uncaught TypeError: P4\MasterTheme\MasterSite::add_meta_box_search(): Argument #2 ($post) must be of type WP_Post, WP_Comment given, called in /var/www/html/wp-includes/class-wp-hook.php on line 324 and defined in /var/www/html/wp-content/themes/planet4-master-theme/src/MasterSite.php:972 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(324): P4\MasterTheme\MasterSite->add_meta_box_search('comment', Object(WP_Comment)) #1 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #2 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /var/www/html/wp-admin/edit-form-comment.php(257): do_action('add_meta_boxes', …
> PLANET-7533 Fix Type error in function param

- assets/src/scss/pages/search/_search-bar.scss
Just changing its left/right position to work for RTL languages.
---
I deployed the fix on a dev site:
[Production](https://www.greenpeace.org/mena/ar/?s=climate&orderby=_score) vs [Development](https://www-dev.greenpeace.org/mena/ar/?s=climate&orderby=_score)
> Fix search clear button rtl position

- assets/src/blocks/ActionCustomButtonText/edit.js
- assets/src/blocks/ActionCustomButtonText/index.js
- assets/src/blocks/ActionsList/index.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/editorIndex.js
- assets/src/js/actions_list_clickable_cards.js
- assets/src/scss/blocks/ActionsList.scss
- src/Blocks/ActionButtonText.php
- src/Loader.php
See [PLANET-7369](https://jira.greenpeace.org/browse/PLANET-7369)
You can add an Actions List block on local or check [this one](https://www-dev.greenpeace.org/test-venus/petitions/just-an-actions-list/) on the venus test instance. The button texts should be reflected according to the Actions' settings.
> PLANET-7369 Use custom button text setting in Actions List block

- admin/css/archive-picker.css
- assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
- assets/src/blocks/CarouselHeader/CarouselHeaderEditor.js
- assets/src/blocks/CarouselHeader/EditableBackground.js
- assets/src/js/Components/ArchivePicker/ArchivePicker.js
- assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
- src/Blocks/CarouselHeader.php
Ref: https://jira.greenpeace.org/browse/PLANET-7263
**Testing:** 
- Added option to use _Greenpeace Media_ to upload images for the `core/media-text` block.
- All blocks using `core/image` or `core/media-text` for images now have access to the Greenpeace Media
- `planet4-blocks/carousel-header` also has access to the Greenpeace Media.
> PLANET-7263 Media Archive: add in editor option for P4 blocks

- src/Context.php
**Ref: https://jira.greenpeace.org/browse/PLANET-7480**
**Testting:**
Pages with the Query Loop block should now have a Page header on the frontend
> PLANET-7480 Stop hiding page header when Query Loop block is used

- templates/blocks/share_buttons.twig
- tests/e2e/gravity-forms.spec.js
See [PLANET-7536](https://jira.greenpeace.org/browse/PLANET-7536)
This was requested via [Slack](https://greenpeace.slack.com/archives/C0151L0KKNX/p1717068747633409), we mentioned it in the past but didn't implement it even though it should be doable.
There should now be a WhatsApp share text in the following scenarios:
- [Gravity Forms with a share text](https://www-dev.greenpeace.org/test-nix/gravity-forms-sharing/)
- [Post with OG description](https://www-dev.greenpeace.org/test-nix/press/1113/duis-posuere-6/)
In other situations there will still be no text added to the share link.
> PLANET-7536 Add share text to WhatsApp share button

- assets/src/blocks/ENForm/ShareButtons.js
- templates/blocks/share_buttons.twig
See [Slack](https://greenpeace.slack.com/archives/C0151L0KKNX/p1716900694930299)
X made this change since tweets are now called posts. As far as I understood no other changes are necessary?
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1212
> Change tweet to post

- src/MasterSite.php
**Ref: https://jira.greenpeace.org/browse/PLANET-7535**
**Testing:** 
On local or assigned test-instance, when image captions is edited, credits should still be visible.
This handles two scenarios as implemented.
- Edit an image in the Media Library. Then add it in the post. The caption should be the new one you just edited.
- Edit an image directly in the editor. Then the caption displayed should be the one you just edited in the post regardless of what's stored in the Media Library.
> PLANET-7535 Credit is removed when caption is edited

- src/Commands/SaveCloudflareKey.php
We construct the hostname to use for the Cloudflare API based on the domain name. But our code doesn't work with GPAP domain name because they have one dot more.
Adjusted the relevant code to have a more dynamic way of slicing the domain and work for both cases.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7537
> PLANET-7537 Fix slice offset on Cloudflare hostname

- src/MasterSite.php
**Ref: https://jira.greenpeace.org/browse/PLANET-7524**
**Testing:**
Pages that have the exclude from search option enabled now have the meta tag added to the head.
> PLANET-7524 Add noindex meta tag on pages that are excluded from search

- src/Patterns/BlankPage.php
- src/Patterns/BlockPattern.php
- src/Patterns/DeepDive.php
- src/Patterns/HighlightedCta.php
- src/Patterns/Issues.php
- src/Patterns/QuickLinks.php
- src/Patterns/RealityCheck.php
- src/Patterns/SideImageWithTextAndCta.php
See [PLANET-7561](https://jira.greenpeace.org/browse/PLANET-7561)
It used to be in the plugin, see [related PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1217)
Either on local or on the [umbriel test instance](https://www-dev.greenpeace.org/test-umbriel/), you should be able to add a Blank Page pattern just like before.
> PLANET-7561 Move Blank Page pattern to the theme

- assets/src/blocks/ActionsList/index.js
- assets/src/blocks/PostsList/index.js
- assets/src/js/app.js
- assets/src/js/query-no-posts.js
- assets/src/js/query_loop_carousel.js
**Ref: https://jira.greenpeace.org/browse/PLANET-7531**
**Testing:** 
I added the `core/query-no-results` block to the Posts Lists and Actions List blocks. This gives Editors the freedom to add text or other blocks to display in case the category used to filter the posts returns no posts.
I also added a function to run in the front end to remove the text or block added by the `core/query-no-results` in case the title and description of the Posts/Actions List block are not set.
You can test this locally or on the assigned instance.
> PLANET-7531 Posts/Actions blocks: Show message when no posts found

- assets/src/blocks/Counter/CounterEditor.js
Ref: https://jira.greenpeace.org/browse/PLANET-7497
This PR updates texts on the Counter Block. Additionally, the class name of the last text `div` was changed to follow the design of the rest of the blocks.
**NOTE:** Our codebase has two Counter blocks, one in the theme and another in the plugins. I've applied the changes to the one in the plugins. Please, let me know if the code in the theme must also be updated.
> PLANET-7497: Backend Text Changes on Counter Block

- assets/src/js/cookies.js
- src/GravityFormsExtensions.php
- src/MasterSite.php
- src/Settings.php
- templates/blocks/google_tag_manager.twig
The hashed `gp_user_id` is saved to dataLayer and a cookie also called `gp_user_id`. In order to respect user consent and flexibility for different privacy laws, additional settings for default values for Google Consent Mode are also added.
Ref: [Please add a url to the ticket this change is addressing.
](https://github.com/greenpeace/planet4/issues/189)
Instructions for testing:
- It's best to delete all cookies and not click anything in the cookie box before starting.
- In WP Admin go to _Planet4_ -> _Cookies_ and make sure _Enable Google Consent Mode_ is activated.
- Test the 4 following settings if the default values are set correctly in dataLayer (note that these can be overwritten from Tag Manager, so it's best to block it for this part of the testing)
- Submit a form that contains …
> Generate and save a hashed gp_user_id on form submissions

- admin/css/archive-picker.css
- assets/src/js/Components/ArchivePicker/MultiSearchOption.js
See [PLANET-7543](https://jira.greenpeace.org/browse/PLANET-7543)
**Note:** the spinner is different from the one in the ticket's screenshot, but this one is probably the newest WP one and it has been approved by the design team.
You can go to Greenpeace Media either on local or on the [jupiter instance](https://www-dev.greenpeace.org/test-jupiter/wp-admin/upload.php?page=media-picker). When you search for a term then the spinner should now appear next to the search input on mobile, and next to the Search button in bigger screens.
> PLANET-7543 Add spinner to Greenpeace Media when searching for images

- assets/src/scss/blocks/Accordion/AccordionStyle.scss
Ref: https://jira.greenpeace.org/browse/PLANET-7515
This PR introduces the following changes on mobile to the Accordion Block:
- The line height of the accordion header was increased to 20px.
- The CTA buttons were left aligned.
<hr>
**Before:**
<hr>
**After:**
> PLANET-7515: Accordion block design fixes on mobile

- src/BlockReportSearch/Block/BlockUsage.php
- src/BlockReportSearch/Block/BlockUsageApi.php
- src/BlockReportSearch/Block/BlockUsageTable.php
- src/BlockReportSearch/Block/Query.php
- src/BlockReportSearch/Block/Query/Parameters.php
- src/BlockReportSearch/Block/Sql/Like.php
- src/BlockReportSearch/Block/Sql/Regex.php
- src/BlockReportSearch/Block/Sql/SqlQuery.php
- src/BlockReportSearch/BlockSearch.php
- src/BlockReportSearch/Pattern/ContentStructure.php
- src/BlockReportSearch/Pattern/PatternData.php
- src/BlockReportSearch/Pattern/PatternUsage.php
- src/BlockReportSearch/Pattern/PatternUsageApi.php
- src/BlockReportSearch/Pattern/PatternUsageTable.php
- src/BlockReportSearch/Pattern/Query/Parameters.php
- src/BlockReportSearch/PatternSearch.php
- src/BlockReportSearch/RowActions.php
- src/Commands/DuplicatedPostmeta.php
- src/Controllers/Menu/BlocksReportController.php
- src/Controllers/Menu/BlocksUsageController.php
- src/Controllers/Menu/ClassicBlocksUsage.php
- src/Controllers/Menu/PostmetaCheckController.php
- src/Controllers/Menu/ReusableBlocksController.php
- src/Loader.php
- src/Migrations/M009PopulateCookiesFields.php
- templates/duplicate-postmeta-report.twig
Ref. https://jira.greenpeace.org/browse/PLANET-7527
> Requirements
> 
>     Migrate Blocks Report code to master theme.
>     That should also include classic blocks report functionality.
>     Verify that the API endpoints also work with the plugin de-activated.
The following folder name is changed during the migration to the master theme:
[classes/search](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/tree/main/classes/search) => [src/BlockReportSearch ](https://github.com/greenpeace/planet4-master-theme/tree/PLANET-7527-move-block-report/src/BlockReportSearch)
**Testing:**
- You can test this [PR](https://github.com/greenpeace/planet4-master-theme/pull/2303) along with blocks repo [PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1215) on Local …
> PLANET-7527 Move blocks report into master theme

- assets/src/block-templates/high-level-topic/block.json
- assets/src/block-templates/high-level-topic/index.js
- assets/src/block-templates/high-level-topic/template.js
- assets/src/block-templates/template-list.js
- assets/src/block-templates/templates/gravity-form-with-text.js
- src/Patterns/BlockPattern.php
- src/Patterns/HighLevelTopic.php
See [PLANET-7552](https://jira.greenpeace.org/browse/PLANET-7552)
We also remove it from the plugin: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1223
> PLANET-7552 Move High Level Topic block pattern layout into master theme

- archive-p4_action.php
- author.php
- index.php
- src/ListingPage.php
- tag.php
- taxonomy.php
- templates/burger-menu-items.twig
- templates/burger-menu.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7365
Remove duplicated, unused and obsolete code related to listing pages
Clean up NROs code to make that nothing will be broken after we merge the current PR
- https://github.com/greenpeace/planet4-child-theme-hongkong/pull/32
- https://github.com/greenpeace/planet4-child-theme-korea/pull/21
- https://github.com/greenpeace/planet4-child-theme-taiwan/pull/30
- https://github.com/greenpeace/gpea-planet8-child-theme/pull/83
> PLANET-7365: Clean up Listing page code

- assets/src/block-templates/homepage/block.json
- assets/src/block-templates/homepage/index.js
- assets/src/block-templates/homepage/template.js
- assets/src/block-templates/template-list.js
- assets/src/scss/blocks.scss
- assets/src/scss/blocks/WideBlocks.scss
- assets/src/scss/blocks/core-overrides/BlockSpacing.scss
- assets/src/scss/blocks/core-overrides/Heading.scss
- assets/src/scss/blocks/core-overrides/HeadingEditor.scss
- assets/src/scss/blocks/core-overrides/Image.scss
- assets/src/scss/blocks/core-overrides/Separator.scss
- assets/src/scss/blocks/core-overrides/Table.scss
- assets/src/scss/blocks/core-overrides/_columns.scss
- assets/src/scss/blocks/core-overrides/_media-text.scss
- src/Patterns/BlockPattern.php
- src/Patterns/Homepage.php
Ref. https://jira.greenpeace.org/browse/PLANET-7553
The homepage block pattern layout moves to the theme from the blocks plugin 
[Related PR: ](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1220)
> PLANET-7553 Move Homepage block pattern layout into master theme

- assets/src/blocks/Submenu/SubmenuEditor.js
Ref https://jira.greenpeace.org/browse/PLANET-7496
<hr>
This PR copies the changes applied to [this PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1219) to not lose them once the block is removed from the plugin or the plugin is disabled.
> PLANET-7496: Backend Text Changes on Submenu Block

- assets/src/blocks/Happypoint/HappypointEditor.js
Ref https://jira.greenpeace.org/browse/PLANET-7500
<hr>
This PR copies the changes applied to [this PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1218) to not lose them once the block is removed from the plugin or the plugin is disabled.
> PLANET-7500: Backend text changes on Happypoint block

- assets/src/frontendIndex.js
Ref: https://jira.greenpeace.org/browse/PLANET-7565
<hr>
After upgrading WordPress to its LTS version ([6.6.1 of 23 July, 2024](https://wordpress.org/download/releases/)) the following errors were found:
1. `Planet 4 Columns` block is not rendered in the front.
2. `Happypoint` block is not rendered in the front.
3. `Submenu` block is not rendered in the front.
4. `Articles` block is not rendered in the front.
5. `Covers` block is not rendered in the front.
6. All the patterns that include the previously mentioned blocks are also affected.
The browser console showed the following error message:
After research, I found that [removing some polyfills in WordPress 6.6](https://github.com/WordPress/wordpress-develop/commit/f525e665b6ea6e88289d82cad5fc1dfac57db109) caused the …
> PLANET-7565: Explicitly import "regenerator-runtime"

- assets/src/block-templates/get-informed/block.json
- assets/src/block-templates/get-informed/index.js
- assets/src/block-templates/get-informed/template.js
- assets/src/block-templates/template-list.js
- src/Patterns/BlockPattern.php
- src/Patterns/GetInformed.php
Ref: https://jira.greenpeace.org/browse/PLANET-7551
Include all related files
Related PRs
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1224
Check it out this [demo page](https://www-dev.greenpeace.org/test-titan/getinformed-demo-page/) which is using the [titan](https://github.com/greenpeace/planet4-test-titan/blob/main/composer-local.json#L6-L7) dev instance for testing. 
Also disabled the P4 Gutenberg plugin from [here](https://www-dev.greenpeace.org/test-titan/wp-admin/plugins.php?plugin_status=all&paged=1&s).
> PLANET-7551: Move GetInformed pattern block to theme

- assets/src/block-editor/Sidebar/ActionSidebar.js
- assets/src/block-editor/Sidebar/AnalyticsTrackingSidebar.js
- assets/src/block-editor/Sidebar/CampaignSidebar.js
- assets/src/block-editor/Sidebar/OpenGraphSidebar.js
- assets/src/block-editor/Sidebar/PageHeaderSidebar.js
- assets/src/block-editor/Sidebar/SearchEngineOptimizationsSidebar.js
- assets/src/blocks/ActionsList/index.js
Ref: https://jira.greenpeace.org/browse/PLANET-7565
<hr>
This PR replaces the `PluginDocumentSettingPanel` component of being imported from `@wordpress/edit-post` with `@wordpress/editor` according to the changes introduced by WordPress 6.6 and adds the missing `name` attribute to the `ActionsList`file.
> PLANET-7565: Fix warnings in WordPress 6.6.x

- tests/e2e/tools/lib/editor.js
- tests/e2e/tools/lib/post.js
Ref: https://jira.greenpeace.org/browse/PLANET-7565
<hr>
This PR fixes the failing automated tests after upgrading WordPress to its LTS version ([6.6.1 of 23 July, 2024](https://wordpress.org/download/releases/)). 
It also adds some missing JSDocs.
<hr>
**TESTING:**
Use the Gutenberg instance: https://www-dev.greenpeace.org/gutenberg/ (it is already using WordPress v6.6.1)
>  PLANET-7565: Fix tests broken by WordPress v6.6.x

- single-campaign.php
- src/Loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-7540
This PR reverts the changes introduced [here](https://github.com/greenpeace/planet4-master-theme/commit/acbc3400e8794fdcb4275fba86a2b830e36af5ee#diff-3163ac23cdbb746a9b9bf8dc0a052b7e6e46ac6a40c1c635b61f6bbae7102d20L143) since the problem with previews being saved and deleted multiple times was [fixed by WordPress](https://core.trac.wordpress.org/ticket/49532).
I checked queries using the Query Monitor plugin, the API requests in the Network tab of the browser console, and the records in the `wp_posts` database table, and the preview posts seem to behave correctly.
> PLANET-7540: Clean up auto-save revisions fix

- assets/src/block-templates/campaign/block.json
- assets/src/block-templates/campaign/index.js
- assets/src/block-templates/campaign/template.js
- assets/src/block-templates/template-list.js
- src/Patterns/BlockPattern.php
- src/Patterns/Campaign.php
Ref: https://jira.greenpeace.org/browse/PLANET-7549
Include all related files
Related PRs
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1225
Check it out this [demo page](https://www-dev.greenpeace.org/test-venus/block-campaign-demo-page-2/) which is using the [venus](https://github.com/greenpeace/planet4-test-titan/blob/main/composer-local.json#L6-L7) dev instance for testing. 
Also disabled the P4 Gutenberg plugin from [here](https://www-dev.greenpeace.org/test-titan/wp-admin/plugins.php?plugin_status=all&paged=1&s).
> PLANET-7549: Move Campaign pattern block to theme

- tests/e2e/greenpeace-media.spec.js
- tests/e2e/tools/lib/media-library.js
See [PLANET-7362](https://jira.greenpeace.org/browse/PLANET-7362)
**Test Steps**
1. Login to the Admin Panel.
2. Navigate to Media > Greenpeace Media.
3. Search for a term (eg. "Rainbow Warrior").
4. Pick the first image and import to the Library.
5. Assert that after some time the Processing... message is replaced with a link to the imported image.
6. Search for an image identifier (eg. GP0STXWME) and assert there is one result displayed.
7. Append one more image identified (eg. GP0STXWZH) and assert that now are two images displayed.
8. Click on "Bulk Select" and select both images.
9. Click on "Bulk Upload".
10. Assert that after some time the Processing 2 images message is hidden and the search box is shown again.
11. Remove the imported images from the Library.
> PLANET-7362 Write a Greenpeace Media e2e test for importing images

- assets/src/blocks/ActionCustomButtonText/edit.js
`useEntityProp` is from `wp.coreData` and not `wp.data`
> Fix Action Button Text

- assets/src/editorIndex.js
- src/Loader.php
- src/MasterBlocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-7576
Move Planet4 beta blocks category from plugin to theme. This category should be added after we move blcosk from plugin to theme
You can validate that the category is shown when click on "+" within the assigned [demo page](https://www-dev.greenpeace.org/test-pandora/planet-4-blocks-beta/).
> PLANET-7576: Move Planet4 blocks (beta) category

- src/AuthorPage.php
See [PLANET-7557](https://jira.greenpeace.org/browse/PLANET-7557)
We were overriding the 'paged' query attribute
- [Broken version](https://www-dev.greenpeace.org/test-venus/author/mleray/) 
- [Fixed version](https://www-dev.greenpeace.org/test-jupiter/author/mleray/)
> PLANET-7557 Fix author page pagination

- assets/src/blocks/Gallery/GalleryEditor.js
Ref: https://jira.greenpeace.org/browse/PLANET-7499 
This PR updates the backend text of the Gallery block according to [this design](https://www.figma.com/design/5qO8DT0C7r7z2zNtxpOpdH/Gallery-Block?node-id=1-569&t=OT5MAuRfEZaOGfHz-0).
> PLANET-7499: Apply backend text changes on Gallery block

- tests/e2e/greenpeace-media.spec.js
The Greenpeace Media (OrangeLogic) APIs are currently down, temporarily skipping the media spec to bypass this check
> Skip Media spec test

- assets/src/block-templates/action/block.json
- assets/src/block-templates/action/index.js
- assets/src/block-templates/action/template.js
- assets/src/block-templates/template-list.js
- src/Patterns/Action.php
- src/Patterns/BlockPattern.php
Ref: https://jira.greenpeace.org/browse/PLANET-7548
Include all related files
Related PRs
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1227
Check it out this [demo page](https://www-dev.greenpeace.org/test-pluto/take-pattern-block-demo-page/) which is using the assigned dev instance for testing. 
Also disabled the P4 Gutenberg plugin from [here](https://www-dev.greenpeace.org/test-pluto/wp-admin/plugins.php?plugin_status=all&paged=1&s).
> PLANET-7548: Move Action pattern block to theme

- tests/e2e/greenpeace-media.spec.js
Previously skipped since the GP Media Library was down for a couple of days
Here is the [code](https://github.com/greenpeace/planet4-master-theme/commit/552837e45445964ae861cd9fcfb9fe4594840952#diff-9e4f3da89e97d282f270086927e379ce93af2a6172b7535a86489bf4ca3007d6R11-R13) to revert.
> Revert Greenpeace Media specs

- assets/src/scss/blocks/ActionsList.scss
- assets/src/scss/blocks/Gallery/styles/GalleryCarousel.scss
- assets/src/scss/blocks/PageHeader.scss
- assets/src/scss/blocks/PostsList.scss
- assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutEditorStyle.scss
- assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
- assets/src/scss/layout/_featured-action.scss
- assets/src/scss/pages/_listing-page.scss
- assets/src/scss/pages/post/_article-content.scss
Otherwise we get warnings, this was discussed on [Slack](https://greenpeace-gpi.slack.com/archives/C0160MX64AG/p1725356677015349)
I've also removed the comment lines around the `-webkit-box-orient` attribute, I'm guessing they were added to these files in the plugin but they seem unnecessary here in the theme.
> Add line-clamp CSS attribute

- assets/src/block-editor/QueryLoopBlockExtension/index.js
- assets/src/blocks/Accordion/AccordionEditor.js
- assets/src/blocks/Accordion/AccordionEditorScript.js
- assets/src/blocks/ActionsList/index.js
- assets/src/blocks/CarouselHeader/CarouselHeaderBlock.js
- assets/src/blocks/CarouselHeader/Sidebar.js
- assets/src/blocks/Columns/ColumnsBlock.js
- assets/src/blocks/Columns/ColumnsEditor.js
- assets/src/blocks/Cookies/CookiesBlock.js
- assets/src/blocks/Cookies/CookiesEditor.js
- assets/src/blocks/Counter/CounterBlock.js
- assets/src/blocks/Counter/CounterEditor.js
- assets/src/blocks/ENForm/ENFormBlock.js
- assets/src/blocks/ENForm/ENFormSettings.js
- assets/src/blocks/Happypoint/HappypointBlock.js
- assets/src/blocks/Happypoint/HappypointEditor.js
- assets/src/blocks/PostsList/index.js
- assets/src/blocks/SocialMedia/SocialMediaBlock.js
- assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
- assets/src/blocks/Spreadsheet/SpreadsheetBlock.js
- assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
- assets/src/blocks/Submenu/SubmenuBlock.js
- assets/src/blocks/Submenu/SubmenuEditor.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/blocks/Timeline/TimelineBlock.js
- assets/src/blocks/Timeline/TimelineEditorScript.js
Ref: https://jira.greenpeace.org/browse/PLANET-7220
<hr>
Based on [this mockup](https://www.figma.com/design/87AqKGnduB2Uq5fVkIcdcg/Handbook-Links-in-Backend?node-id=1-437&node-type=FRAME&t=bzJp6zu3cilsg1wU-0), this PR adds a description to some of the blocks in the P4 master theme and an additional collapsible panel body in the editor with a link to the P4 Handbook.
<hr>
**RELATED PR:**
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1237
<hr>
**TESTING LINK:**
https://www-dev.greenpeace.org/test-pandora/wp-admin/post.php?post=1437&action=edit
> PLANET-7220: Add definitions to blocks settings 

- assets/src/js/gravityforms-client-side.js
- src/GravityFormsExtensions.php
See [PLANET-7454](https://jira.greenpeace.org/browse/PLANET-7454)
We want them to be available before form submission
You can make sure that the dataLayer new values are correctly added on any page with a Gravity Forms form, such as [this one](https://www-dev.greenpeace.org/test-pluto/gravity-forms-test/)
> PLANET-7454 Implement GF variables in page load

- src/BlockSettings.php
- src/Loader.php
https://jira.greenpeace.org/browse/PLANET-7615
<hr>
This PR moves to the master theme [the logic related to the post types filter](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/v1.95.0/planet4-gutenberg-blocks.php#L321).
<hr>
**NOTES:**
1. As I am not yet completely aware of the theme repo architecture, I've created for this task a new class ("BlockSettings") which is called from the Loader file. If this is not correct, please let me know.
2. While the comments in the code point out that post types pages, actions, and campaigns allow all blocks, in the code that is not correct: pages miss the "sub-page" block. Is this something to fix?
<hr>
**RELATED PR:**
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1243
> PLANET-7615: Add block post type filter

- assets/src/scss/base/_typography.scss
- assets/src/scss/blocks/core-overrides/Image.scss
- assets/src/scss/blocks/core-overrides/Table.scss
- assets/src/scss/core-overrides/_image.scss
- assets/src/scss/pages/post/_article-content.scss
See [PLANET-7617](https://jira.greenpeace.org/browse/PLANET-7617)
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1245
I've added multiple blocks with captions on [this page](https://www-dev.greenpeace.org/test-venus/so-many-captions/), all should now look the same!
> PLANET-7617 Apply caption styles to all figcaption elements

- assets/src/scss/blocks/ActionsList/ActionsListStyle.scss
Ref: https://greenpeace-gpi.slack.com/archives/C0160MX64AG/p1726049842778739
<hr>
- This PR limits the number of lines of the Actions List's titles to 2.
- This PR aligns the position of the Read More button of the Actions List block according to this mockup:
<hr>
**COMPARISON:**
Main branch:
This branch:
> Align the Read More button in the Actions List block

- templates/burger-menu-items.twig
- templates/footer.twig
- templates/navigation-submenu.twig
This can happen if some pages used in the navigation have special characters in their title
You can check the first submenu item under `Take Action` on the following test instances:
- [Broken](https://www-dev.greenpeace.org/test-rhea)
- [Fixed](https://www-dev.greenpeace.org/test-venus)
> Fix special characters in submenu navigation and in footer

- assets/src/scss/components/_share-buttons.scss
We removed the background color for other share buttons already but forgot this one
You need to test this on mobile/tablet since the native share button doesn't show otherwise.
**Before the fix:**
**After the fix:**
> Remove native share button background

- assets/src/scss/layout/_gravity-forms.scss
See [PLANET-7568](https://jira.greenpeace.org/browse/PLANET-7568)
These are really small changes in buttons alignment and margins
You can test the fix with any form using a multi-file upload field, such as [this one](https://www-dev.greenpeace.org/test-venus/gf-multi-file-upload/)
- **Broken version:**
- **Fixed version:**
> PLANET-7568 Fix styles for the Gravity Forms multiple file upload

- src/GravityFormsExtensions.php
Ref: https://jira.greenpeace.org/browse/PLANET-7598
<hr>
This PR attempts to increment Pixel Counter's counters when submitting a Gravity Form that includes the `p4_gf_counter` field.
<hr>
**TESTING:**
- Login to the Pixel Counter website: https://counter.greenpeace.org/login  
- Go to the list of counters: https://counter.greenpeace.org/list 
- Locate the counter named `testcounter`
- Take note of the current count number in the Counter column.
- Go to the [form settings page](https://www-dev.greenpeace.org/test-iocaste/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=settings&id=1) and check that the field Global Counter ID is `testcounter`
- Visit this page: https://www-dev.greenpeace.org/test-iocaste/form-test-page/
- Fill out and submit the form.
- Go back …
> PLANET-7598: Form Builder - Add a petition counter id field

- src/BlockReportSearch/Block/BlockUsageTable.php
- src/BlockReportSearch/Pattern/PatternUsageTable.php
- src/BlockReportSearch/RowActions.php
See [PLANET-7597](https://jira.greenpeace.org/browse/PLANET-7597)
If this implementation was working in the plugin, it's weird that it no longer works in the theme. Maybe WordPress changed something in `WP_List_Table`.
**Note:** this is a bit of a messy fix, so any feedback is welcome!
- In the [broken version](https://www-dev.greenpeace.org/test-pluto/wp-admin/admin.php?page=plugin_blocks_report&group=post_id), there is no link in the "title" column and the row actions links are not the page edit url, they just reload the page:
- In the [fixed version](https://www-dev.greenpeace.org/test-nix/wp-admin/admin.php?page=plugin_blocks_report&group=post_id), both of these issues are no longer present:
> PLANET-7597 Fix Block Usage Report 'group by post id' links'

- templates/sitemap.twig
This can happen if some pages or categories have special characters in their title
[Broken version](https://www-dev.greenpeace.org/test-rhea/sitemap/):
[Fixed version](https://www-dev.greenpeace.org/test-iocaste/sitemap/):
> Fix special characters in sitemap links

- src/GravityFormsExtensions.php
Ref: https://sentry.greenpeace.org/organizations/greenpeace-org/issues/1964/?project=2
<hr>
**DESCRIPTION:** 
This PR fixes the following Sentry warning: `Warning: Undefined array key "p4_gf_counter"`
> Fix new Sentry warning

- assets/src/scss/base/_mixins.scss
- assets/src/scss/core-overrides/embed.scss
- assets/src/scss/style.scss
This PR re-adds the styles removed [here](https://github.com/greenpeace/planet4-master-theme/pull/2357/files) from the `Media.scss` file.
By removing the `Media.scss` file many embed elements (such as Youtube or Vimeo iframes) lost their styles, especially the full-width property.
Additionally, the scss code was refactored to avoid as much duplicate code as possible.
- Example without styles: https://www-dev.greenpeace.org/gutenberg/media-block-test-page/
- Example with styles: https://www-dev.greenpeace.org/test-iocaste/media-block-test-page/
> Add styles to embed elements

- admin/js/options.js
- assets/src/blocks/Cookies/CookiesFrontend.js
- src/Settings.php
See [PLANET-7607](https://jira.greenpeace.org/browse/PLANET-7607)
It doesn't always work depending on analytical cookies settings, because the capabilities object is not defined
Before this fix, when enabling the analytical cookies but not filling the corresponding text fields, the block would not work properly in the frontend. You can check the following instances to test:
- [Broken version](https://www-dev.greenpeace.org/test-pluto/privacy-and-cookies/)
- [Fixed version](https://www-dev.greenpeace.org/test-nix/privacy-and-cookies/)
> PLANET-7607 Fix Cookies block frontend bug

- assets/src/scss/variations/stretched-link/index.scss
This PR fixes an error in the Homepage template when a user hovers over one of the images.
When that happens, the hover effect instead of zooming in on the hovered image, zooms in all of them.
<hr>
**LINKS:**
- Page with error: https://www.greenpeace.org/nl/
- Page without the error: https://www-dev.greenpeace.org/test-pluto/test-page/
<hr>
**RELATED PR:**
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1252
> Fix zoom on hover in the home template

- assets/src/blocks/ENForm/ShareButtons.js
- src/GravityFormsExtensions.php
- templates/blocks/share_buttons.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7575
- Rename `uaevent` to `page_shared` (see the **Update** section)
- Add new `channel` 
Check it out the shared demo pages and test if the values are properly fired.
- [Post page](https://www-dev.greenpeace.org/test-atlas/story/1445/test-demo-page/)
- [GF demo page](https://www-dev.greenpeace.org/test-atlas/datalayer-values-demo-page/)
We will need to [keep both events](https://github.com/greenpeace/planet4-master-theme/pull/2351/commits/4b9d36f7a9ebda35dd35269d660b8ebbbc3901ea) (for now) until the data team make the changes on GTM
> PLANET-7575: Rename social media events

- assets/src/scss/editorOverrides.scss
See [PLANET-7636](https://jira.greenpeace.org/browse/PLANET-7636)
Make sure all labels in the editor sidebar are no longer in uppercase, and all look the same. Please test all post types since they have different sidebar fields.
> PLANET-7636 Remove editor sidebar labels uppercase

- tests/e2e/gravity-forms.spec.js
- tests/e2e/tools/lib/gravity-forms.js
See [PLANET-7638](https://jira.greenpeace.org/browse/PLANET-7638) & [PLANET-7639](https://jira.greenpeace.org/browse/PLANET-7639)
Until now we only had an e2e test for the text confirmation type.
> PLANET-7638 Add e2e tests for GF redirect and page confirmation types

- single.php
- templates/blocks/google_tag_manager.twig
See [PLANET-7605](https://jira.greenpeace.org/browse/PLANET-7605)
This needs to be standardised for better reporting.
**Requirements:**
- Implement a `page_date` dataLayer variable in page load with the value standardised in the ISO format "YYYY-MM-DDTHH:MM:SS" in UTC.
- Add this new variable on Posts post type existing dataLayer array.
You can make sure that the new dataLayer variable is present for any Post from the phobos test instance, such as [this one](https://www-dev.greenpeace.org/test-phobos/press/1113/duis-posuere-6/).
> PLANET-7605 Implement page_date dataLayer variable for Posts

- assets/src/blocks/CarouselHeader/StaticCaption.js
- src/MasterSite.php
**Ref: https://jira.greenpeace.org/browse/PLANET-7637**
**Testing:**
When uploading images through the _Upload Tab_ in the pop up, there is no validation for images so non-supported images get uploaded but don't show up. With this fix there is an error messages that prompts the user of the image type being uploaded. Also the block validation error no longer exists for the _Carousel Header_ block.
_To test the Image Validation_
- In the editor add the image block.
- Choose the media library
- Go to the upload tab and click to upload an image.
- Only supported images(png, jpg, gif and ico) are allowed to be uploaded, other image types throw and error.
To test the Carousel Block Validation, try editing a page like the Homepage that already has the Carousel block. The validation error should …
> PLANET-7637 Planet 4 Bug Report: Gallery Block - Upload image issue

- admin/css/archive-picker.css
- assets/src/js/Components/ArchivePicker/SingleSidebar.js
- src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-7643
<hr>
This PR fetches restrictions from GP Media API and shows them on the import sidebar before importing the file and also on the Media Library while browsing the media file.
> PLANET-7643: Media Library - Show restrictions on imported media

- assets/src/scss/blocks/core-overrides/Embed.scss
Ref: 
- https://github.com/greenpeace/planet4-master-theme/pull/2399#pullrequestreview-2354346162
- https://greenpeace-gpi.slack.com/archives/G015K63081W/p1729519727583989
<hr>
This PR makes the SoundCloud embed elements full-width in order to match them with the rest of the embed elements (Youtube, mp3 files, etc.)
<hr>
**TESTING:**
- Fixed page: https://www-dev.greenpeace.org/test-jupiter/soundcloud-test-page/
- Page with issues: https://www-dev.greenpeace.org/gutenberg/soundcloud-test-page/
> Make SoundCloud embed full width

- assets/src/scss/pages/post/_article-content.scss
See latest comments on [PLANET-7563](https://jira.greenpeace.org/browse/PLANET-7563)
This was only working for other post types
On [this post](https://www-dev.greenpeace.org/test-deimos/press/1109/duis-posuere-4/) for example, the list link should now have the same styles as our other links.
> PLANET-7563 Apply New Link Style to lists in Posts

- assets/src/js/app.js
- assets/src/js/remove_related_section_no_posts.js
- assets/src/scss/pages/post/_post.scss
- functions.php
- single.php
- tests/e2e/blocks/related-articles.spec.js
**Ref: https://jira.greenpeace.org/browse/PLANET-7592**
**Testing:**
On local or test instance, the "_Related Articles_" section is now rendered using the Query loop block.
UI wise, it still should be similar.
> PLANET-7592 Re-implement related articles with Query Loop block

- tag.php
This is a revert of fc35da662402012b2d67ae0266ac5aac1321a49b
It seems that `get_post` returns a specific post even the argument passed as id is an empty string.
- While on `main` branch:
- Go to a tag and make sure it doesn't have a "Redirect Page" value (see screenshot)
- Visit that tag page on the frontend, and instead of the tag listing page you should see a specific post
- Switch to this branch:
- Refresh the above tag and you should see the regular tag listing page
> Fix tag page when redirection is not set

- src/Exporter.php
We are injecting an Import button, in order to guide people on import media files while on Media Library. But currently that button show up everywhere, on all post types.
This small change makes the button visible only in the Media Library.
- Ensure the "Import Greenpeace Media" button works the same as before
- It should no longer appear on Posts and Pages
> Show media import button only on Media Library

- templates/footer.twig
This will some NROs to add a custom block on top of the footer on all pages without the need to override the entire footer template.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7666
> PLANET-7666 Add template include for extra footer block

- assets/src/blocks/SocialMedia/SocialMediaBlock.js
- assets/src/blocks/SocialMedia/SocialMediaConstants.js
- assets/src/blocks/SocialMedia/SocialMediaEditorScript.js
- src/Blocks/SocialMedia.php
- src/Migrations/M033MigrateSocialMediaTwitterBlockToEmbedBlock.php
- src/Migrations/Utils/Constants.php
- src/Migrations/Utils/Functions.php
- src/Migrator.php
- templates/blocks/social-media.twig
See [PLANET-7523](https://jira.greenpeace.org/browse/PLANET-7523)
This also includes cleaning up the code of all previous Twitter/X customisations since we will now use the Embed block for these instead. The corresponding migration is included in this PR too.
**Note:** it seems X urls were not working anyways 😬 see [here](https://www-dev.greenpeace.org/gutenberg/twitter-x-embeds/) for example
**For the block changes:**
Make sure the block is now called `Meta` and it has no more mentions of Twitter/X in its options.
**For the migration:**
1. Run this PR in your local environment.
2. Add a Meta block to a page using a Twitter/X post url ([example](https://x.com/Greenpeace/status/1842512562383913248)), it won't embed the block anymore because of this PR's changes but it's good enough to test …
> PLANET-7523 Remove Twitter from Social Media block and rename it Meta

- assets/src/scss/layout/_navbar.scss
- templates/burger-menu-items.twig
- templates/navigation-submenu.twig
See [PLANET-7618](https://jira.greenpeace.org/browse/PLANET-7618)
This can happen in edge cases where a page used in the navigation is renamed with a longer title
On the [titan instance](https://www-dev.greenpeace.org/test-titan/) in the navigation under `The issues we work on` I've added a page with a really long title. It should be cut off after 2 lines for both mobile and desktop.
> PLANET-7618 Make sure nav links don't exceed 2 lines

- assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutEditorStyle.scss
See [PLANET-7672](https://jira.greenpeace.org/browse/PLANET-7672)
This editor style was overridden by the frontend styles for the block. 
Before these changes this is what a custom boxout looks like in the editor: 
After these changes it should look as expected.
> PLANET-7672 Update TAB custom image width in the editor

- assets/src/scss/blocks/PostsList/PostsListStyle.scss
- assets/src/scss/pages/post/_post.scss
- functions.php
See [PLANET-7670](https://jira.greenpeace.org/browse/PLANET-7670)
In this PR I've also "fixed" the indentation for the Related Posts implementation to make it easier to read. And I've removed the `lock` attributes since this block is not available in the editor but only rendered in the frontend.
On the telesto instance, I've updated the "Duis Posuere 6" post with author override `Another author`. On [this post](https://www-dev.greenpeace.org/test-telesto/press/1111/duis-posuere-5/) for example, the Related Posts should show the author override for Duis Posuere 6.
> PLANET-7670 Show author override in Related Posts

- functions.php
- src/Api/SocialMedia.php
We forgot it when moving this block to the theme. The oEmbed is still not working (see [PLANET-7654](https://jira.greenpeace.org/browse/PLANET-7654)) but at least now everything related to this block will be in the theme. 
Although the Instagram one now shows an error message 😅 [example](https://www-dev.greenpeace.org/test-phobos/oembeds/)
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1264
> Add Social Media block API endpoint

- assets/src/block-editor/TagSelector/index.js
Ref: https://jira.greenpeace.org/browse/PLANET-7674
The issue has been reported by [GPUS](https://greenpeace-gpi.slack.com/archives/C07J7BB7NL9/p1732215809593329).
Remove per_page parameter
- Create a new page
- Insert a Covers block into the page
- Set any Tag from settings panel
- https://developer.wordpress.org/block-editor/reference-guides/data/data-core/#getentityrecords
- https://developer.wordpress.org/block-editor/reference-guides/data/data-core/
- https://developer.wordpress.org/rest-api/reference/
> PLANET-7674: Fix tags list

- assets/src/js/app.js
- assets/src/js/country_selector.js
- assets/src/scss/layout/_country-selector.scss
- templates/footer.twig
- templates/footer_country_selector.twig
- templates/footer_social_media.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7135
[Demo page](https://www-dev.greenpeace.org/test-jupiter)
- Fixed the issue but also Improved SEO on the country selector component. 
- Additionally, I've also Implemented a new script which is in charge to add/remove dynamically the `tabindex` attribute depending on the country selector state (`open|close`).
1. Scroll down to the footer
2. Click on it footer
3. Then press the `Tab` key.
Within the previous behavior ([see the international dev site](https://www-dev.greenpeace.org/international/)),  the end-user is not able to navigate within page's links NOR social links.
Within the current fix, the user can navigate through ALL the footer's links, including sub-links, even if the list is opened or closed. …
> PLANET-7135: Fix country selector tab index

- src/Commands/SaveCloudflareKey.php
We made a change to accommodate for domains with more parts (like `.org.au`), but that broke `ummah4earth.org` because they don't have `www` in their hostname.
Since we practically only want to remove `www`, this simplifies that part of the code to avoid complicated conditional logic for all use cases.
It's hard to test directly with Cloudflare, but I moved the code to a different file and use php cli to test out the logic with the different use cases.
> Simplify CF zone code to only remove www. from hostname

- assets/src/scss/pages/_author.scss
- assets/src/scss/pages/post/_author-block.scss
- templates/author.twig
- templates/blocks/author_profile.twig
We are currently using [the_author_meta](https://developer.wordpress.org/reference/functions/the_author_meta/).
But the function doesn't return a string, which is what [wpautop](https://developer.wordpress.org/reference/functions/wpautop/) expects. This also triggers the following warning locally:
```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/wp-includes/formatting.php on line 449
```
Instead, we should use [get_the_author_meta](https://developer.wordpress.org/reference/functions/get_the_author_meta/) as it's also mentioned in the documentation of `the_author_meta`:
>NOTE: Use `get_the_author_meta()` if you need to return (and do something with) the field, rather than just display it.
This also fixes bug …
> PLANET-7482 Use proper function for displaying author bio

- assets/src/block-editor/PostSelector/index.js
- assets/src/blocks/ActionsList/index.js
- src/MasterBlocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-7677
In preparation of https://jira.greenpeace.org/browse/PLANET-7657
Remove appearences of p4ge_vars to avoid conflicts whenever the plugin is disabled.
> PLANET-7677: Consolidate parent act page injected to window p4_vars

- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
Ref: https://jira.greenpeace.org/browse/PLANET-7662
The `Select Take Action Page` is now rendered based on IA.
[Demo page](https://www-dev.greenpeace.org/test-tavros/act/test-tab-demo-page/) 
- Go to Planet 4 > Navigation and see if new IA feature is enabled
- Create a new page and include a Take Action Boxout block
- If the new IA feature is disabled the list should render only pages that its parents are the same as the one defined trough `/wp-admin/admin.php?page=planet4_settings_navigation`.
- If the new IA feature is enabled the list should include not  only the previous ones but also `p4_action` pages
<!-- Ref: Please add a url to the ticket this change is addressing.
> PLANET-7662: Fix action pages dropdown

- assets/src/scss/blocks/core-overrides/Embed.scss
---
Ref:  Ref: https://jira.greenpeace.org/browse/PLANET-7688
1.  Create a new page and add the Embed block with a Spotify URL
2.  The shouldn't be any huge space anymore between the block and the captions
3.  Compare this [page](https://www-dev.greenpeace.org/test-umbriel/testing-spotify-fix/) with fix, to this [page](https://www.greenpeace.org/international/audio-series/) with bug.
> PLANET-7688 Fixed huge space between Spotify embed and captions

- assets/src/scss/layout/_query-loop-overrides.scss
See [PLANET-7694](https://jira.greenpeace.org/browse/PLANET-7694)
These were an issue only in Posts. I know that the ticket also mentions the arrows and indicators showing even when there are not enough items to scroll, but I think I'll handle that in a different PR. These CSS-only changes are quick fixes and more urgent. 
- [Broken version](https://www-dev.greenpeace.org/test-rhea/press/1113/duis-posuere-6/)
- [Fixed version](https://www-dev.greenpeace.org/test-telesto/press/1113/duis-posuere-6/)
> PLANET-7694 Fix design issues in Posts List with carousel style

- assets/src/scss/layout/_forms.scss
The issue is happening on ginput_container selector. It's been reported [on Slack](https://greenpeace.slack.com/archives/C0151L0KKNX/p1734035633880299).
> Follow up GF checkbox styles issue

- assets/src/block-templates/action/block.json
- assets/src/block-templates/campaign/block.json
- assets/src/block-templates/deep-dive-topic/block.json
- assets/src/block-templates/deep-dive/block.json
- assets/src/block-templates/get-informed/block.json
- assets/src/block-templates/high-level-topic/block.json
- assets/src/block-templates/highlighted-cta/block.json
- assets/src/block-templates/homepage/block.json
- assets/src/block-templates/issues/block.json
- assets/src/block-templates/page-header/block.json
- assets/src/block-templates/quick-links/block.json
- assets/src/block-templates/reality-check/block.json
- assets/src/block-templates/side-image-with-text-and-cta/block.json
- assets/src/block-templates/take-action/block.json
See [PLANET-7201](https://jira.greenpeace.org/browse/PLANET-7201). This has been available since WP 6.3, see [docs](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-api-versions/). I don't see any difference 🤷‍♀️
> Update apiVersion for our blocks to 3

- assets/src/scss/layout/_page-header.scss
Follow up with Houssam, we need to set the page header title `font-weight` to `regular` by default.
---
Ref:  #2432 
Go to the assigned instance https://www-dev.greenpeace.org/test-jupiter/get-informed/
> Fix page header title font-weight

- assets/src/js/listing_pages.js
- assets/src/scss/pages/_listing-page.scss
- functions.php
- src/ListingPage.php
- templates/listing-page-filters.twig
See [PLANET-7671](https://jira.greenpeace.org/browse/PLANET-7671)
This is in addition to the previously added category filter
**Note:** for the mobile version we don't use the modal in the end.
You can check out the new filter and "Apply" button on the [News & Stories page](https://www-dev.greenpeace.org/test-leda/news-stories/) from the leda test instance or on local. Make sure to test several filter combinations and also all screen sizes.
> PLANET-7671 Add post type filter to News & Stories page

- assets/src/blocks/ActionsList/index.js
- assets/src/blocks/PostsList/index.js
- assets/src/editorIndex.js
- tests/e2e/navigation-bar.spec.js
- tests/e2e/tools/lib/post.js
See [PLANET-7656](https://jira.greenpeace.org/browse/PLANET-7656)
**Related PRs:**
- https://github.com/greenpeace/planet4-base/pull/320
- https://github.com/greenpeace/planet4-develop/pull/47
**Changes made for the upgrade:**
- The core Posts List variation of the Query Loop block [has been removed](https://github.com/WordPress/gutenberg/pull/63404) so we don't need to unregister it anymore
- Some e2e tests were failing
- The Posts List and Actions List block no longer had the controls to set how many items to display, the offset and max number of pages... These [have been moved to the sidebar](https://github.com/WordPress/gutenberg/pull/58207) and we need to add them to the `allowedControls`.
**Things I noticed but don't need changes or I'm not sure they are problematic:**
- WordPress …
> PLANET-7656 Prepare for WordPress 6.7 upgrade

- exporter-helper.php
- src/BlockSettings.php
- src/Importer.php
See [PLANET-7635](https://jira.greenpeace.org/browse/PLANET-7635)
These blocks are `SubPages`, `ShareButtons`, and `SocialMediaCards`. We won't move them from the plugin to the theme.
> Remove beta blocks that we won't migrate

- assets/src/blocks/Covers/CoversCarouselLayout.js
By removing this attr the Carousel stops sliding crazily
---
Ref: https://jira.greenpeace.org/browse/PLANET-7729?
1. Create a new page
2. Add the Covers block into that
3. Preview the page and then the Covers Block might work normally
> PLANET-7729: Fix Carousel interval issue

- assets/src/scss/blocks/Covers/layouts/CoversCarouselLayout.scss
The carousel indicator numbers are visible and might be hidde and it is happening only in Chrome.
---
Ref: 
1. Go to the assigned [demo page](https://www-dev.greenpeace.org/test-phoebe/fix-covers-block-layout-issue/)
3. Check if the carousel indicator numbers are hidden
4. Ideally confirm on Chrome but could be great if there is another browser to test. Besides Chrome, I've also tested on FF and Safari.
> Fix <ol> selector issue

- src/Post.php
---
Ref: https://jira.greenpeace.org/browse/PLANET-7730
Inspect pages in the Navigation Bar Menu and the links should work as expected even on sites with WPML
Can also test on mena [dev-site](https://www-dev.greenpeace.org/mena/en/act/)
> PLANET-7730 Fix bottom navigation block issue

- src/BlockReportSearch/Block/BlockUsageTable.php
This is a temporary fix to solve the issue mentioned by Kelli in the ticket [PLANET-7489](https://jira.greenpeace.org/browse/PLANET-7489).
This PR adds an additional column to the Blocks Report page only once the P4 Columns block is selected, to show the number of columns for each block. If more than 4 columns were added to the block (the maximum allowed) a warning message is shown.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7489 
1. Go to the Blocks Report page (`/wp-admin/admin.php?page=plugin_blocks_report`)
2. Filter only P4 Columns block.
3. Check the Columns table's column.
4. Check if there are blocks using more than 4 columns. If so, a warning should be shown. If not, create a new page, add the following block code and check the report again:
``` 
```
> PLANET-7489: Check number of columns in the P4 columns block

- src/MasterSite.php
- src/Migrations/M038RemoveCustomSiteIcon.php
- src/Migrator.php
See [PLANET-7647](https://jira.greenpeace.org/browse/PLANET-7647)
We remove the option to customize it in the site identity settings, and we need to run a migration to remove existing values
**1. Setting removal**
If you go to `Appearance > Customize > Site Identity` you should no longer be able to change the site icon.
Before the removal you would see this:
**2. Migration script**
You can run it on local with `npx wp-env run cli wp p4-run-activator`
Before the migration, we had a custom site icon:
After the migration, you should now see the default site icon:
> PLANET-7647 Enforce consistency on default favicon

- tests/e2e/blocks/audio-video.spec.js
See [PLANET-7633](https://jira.greenpeace.org/browse/PLANET-7633)
> PLANET-7633 Add e2e tests for Audio and Video blocks

- admin/css/options.css
- src/GravityFormsExtensions.php
- src/Migrations/M039EnableNewSocialSharePlatforms.php
- src/Migrator.php
- src/Post.php
- src/Settings.php
- templates/blocks/header.twig
- templates/blocks/share_buttons.twig
- templates/single-attachment.twig
- templates/single.twig
See [PLANET-7681](https://jira.greenpeace.org/browse/PLANET-7681)
- Label: "Choose social sharing options"
- This should be a multiple selection option field (checkboxes), showing the 4 sharing options we already have (WhatsApp, Facebook, X, Email).
- Remove the current customization menu
- Native share should still be displayed in mobile
- We can keep the text fields for custom share url/text
- To test the migration on local, you can run `npx wp-env run cli wp p4-run-activator` and the new settings should all be checked by default. You can run `npm run db:reset` beforehand if necessary.
- To test the new settings, either on local or on the test instance in `Planet 4 > Social` you can try (un)checking the various social media sharing options. Then you can make sure that …
> PLANET-7681 Make existing social share buttons configurable

- tests/e2e/blocks/posts-list.spec.js
See [PLANET-7732](https://jira.greenpeace.org/browse/PLANET-7732)
**Test Steps**
1. Login to the Admin Panel.
2. Create a new Page.
3. Add a Posts List block:
- Pick the List layout _-> not necessary since it's the default_
- Increase the Posts per page value to 4
- Filter posts by category "Energy"
- Change block title to "Related Stories"
4. Publish the page.
5. Navigate to the frontend view of that Page and verify that all of the above properties are working as expected:
- Block title
- All posts are from the "Energy" category
- Assess list layout
- There are 4 posts displayed
> PLANET-7732 Add an e2e test for the Posts List block (list layout)

- assets/src/js/google_tag_manager.js
- src/EnqueueController.php
---
Ref: https://jira.greenpeace.org/browse/PLANET-7436
1. Locally use an NRO with GTM
2. On the search page when you search a term, the number of search results from the query is added to the DLV
3. You can also test on the Belgium dev [instance](https://www-dev.greenpeace.org/belgium/fr/).
> PLANET-7436 Added search_results to DLV

- assets/src/editorIndex.js
Move editor behavior-related scripts outside wp.domReady() function
---
Ref: [PLANET-7754](https://jira.greenpeace.org/browse/PLANET-7754)
- The issue is reproducible on the latest code from the master theme's main branch.
- To test the fix, check out this branch, build the assets, and verify the changes.
- You can also check the issue on the [test-rhea](https://www-dev.greenpeace.org/test-rhea/wp-admin/post.php?post=1113&action=edit) instance.
- The fix can be tested on the [test-nix](https://www-dev.greenpeace.org/test-nix/wp-admin/post.php?post=260&action=edit) instance.
> PLANET-7754 Fix P4 sidebar panel disappear issue

- assets/src/js/listing_pages.js
- src/ListingPage.php
- templates/listing-page.twig
See [PLANET-7706](https://jira.greenpeace.org/browse/PLANET-7706)
You can check this new behaviour (with pagination) on the titan instance:
- in a normal listing page ([example](https://www-dev.greenpeace.org/test-titan/press/))
- in the [News & Stories page](https://www-dev.greenpeace.org/test-titan/news-stories/) (for this one make sure the filtering also still works as expected)
> PLANET-7706 Keep News & Stories page layout when reloading/filtering

- src/Migrations/M040ReplaceSpecialCharactersInPostsContent.php
- src/Migrator.php
This PR replaces the special characters `u003c`, `u003e`,  and `u0022` in the content of the posts that were affected by previous migrations, for example [here](https://www.greenpeace.org/sweden/klimat/#vad-du-kan-gora).
---
1. Run this PR in your local environment.
2. Add the following text (it contains wrong markups) to a new post or page (or edit an existing one): `This should be replaced: u003cau003eu0022testu0022u003c/au003e, but this should NOT: \u003ca\u003e\u0022test\u0022\u003c/a\u003e` 
4. Run the migrator command: `npx wp-env run cli wp p4-run-activator`
5. Check whether the migration worked as expected and the special characters were fixed.
6. To reset the environment database back to the latest default content and repeat the tests, run: `npm run db:reset`
> Replace special characters in the content of the posts

- templates/countries.json
Ref: https://jira.greenpeace.org/browse/PLANET-7761
1. There should be a new link for Portugal in the footer country selector
> PLANET-7761 Add new Portugal website to NRO footer selector

- assets/src/scss/components/_skip-links.scss
---
Ref: https://jira.greenpeace.org/browse/PLANET-7715
1. On assigned instance or locally, tabbing through the page, skip links are more visible with a white background.
> PLANET-7715 Made skip links more visible

- src/GravityFormsExtensions.php
Fixes sending formSubmission events when using redirect confirmations in GravityForms. 
The new [JS file that contains Tag Manager code](https://github.com/greenpeace/planet4-master-theme/blob/695451aee431d4058de99e48ae006f4c0a9d0245/assets/src/js/google_tag_manager.js#L5)  for Tag Manager since [PLANET-7625](https://jira.greenpeace.org/browse/PLANET-7625) initialized `google_tag_value` inside a conditional. It was a global variable in the Twig template that was used before that change.
The [script that sends formSubmission events before redirecting](https://github.com/greenpeace/planet4-master-theme/blob/695451aee431d4058de99e48ae006f4c0a9d0245/src/GravityFormsExtensions.php#L875-L911) was still referencing `google_tag_value` as a global variable and stopped working. 
The new version now …
> Fix formSubmission event for GravityForms redirect confirmations

- functions.php
- src/Api/Tracking.php
This endpoint it's going to be implemented within [this spreedsheet](https://docs.google.com/spreadsheets/d/1uAmZLIWYsxrBByqbhoF_vVtSM7WGebYWIc0xftPRPwE/edit?gid=1046330328#gid=1046330328).
- Added the `last_days` param wich returns the last N days. By default is set to `30`
- Added the `full` param wich returns also metadata for logins. By default is set `false`
Example of response (requires auth)
```shell
curl -X GET -G \
'https://www-dev.greenpeace.org/test-jupiter/wp-json/planet4/v1/tracking' \
-d last_days=365 \
-d full=true
```
```json
{
"logins": {
"data": [
{
"display_name": "Dan Tovbein - P4 team",
"login_date": "2025-02-13 09:33:44"
},
{
"display_name": "Nikos",
"login_date": "2025-02-13 10:14:58"
},
{
"display_name": "Foppe Pieters - P4 team",
"login_date": "2024-02-26 …
```
> PLANET-7612: Track user logins

- admin/js/media_replacer.js
- src/MediaReplacer.php
This PR implements a new feature to replace images in Google Cloud Storage through the WP Stateless plugin. Also, the PR creates the image thumbnails using PHP native functions since, for unknown reasons, the ones created by WordPress are not uploaded to Google Cloud Storage. Even if that happened, the new thumbnails might differ in size from the originals, so the file names and their URLs would differ, making the replacement feature unusable.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7645
**Testing note:** for local testing, go to [the Gutenberg instance](https://www-dev.greenpeace.org/gutenberg/wp-admin/) and copy the WP Stateless configuration from Media > Stateless settings.
1. Go to the Media Library and upload a new image.
2. Go to Google Cloud Storage ([Gutenberg …
>  PLANET-7645: Implement image replacement feature

- admin/css/options.css
- templates/blocks/favicon.twig
- templates/html-header.twig
Ref: https://jira.greenpeace.org/browse/PLANET-7647
---
Follow up from https://github.com/greenpeace/planet4-master-theme/pull/2507, there is one more additional option besides the one we disabled.
I couldn't find a hook for this one, so at least we can hide it in css for now to avoid confusion.
Also split up the favicon code in a new partial template, in case some NROs want to override it in their child theme.
1. Swithing to this branch should hide the site icon option in _Settings > General_
> PLANET-7647 Hide site icon setting

- assets/src/scss/layout/_country-selector.scss
- templates/footer_country_selector.twig
See [PLANET-7703](https://jira.greenpeace.org/browse/PLANET-7703)
This commit also adds a visually hidden span for better accessibility.
Either on local or on the [titan instance](https://www-dev.greenpeace.org/test-titan/), make sure that the close button now has a visible focus state when navigating with tabs. Note that on local you will need to clear the Timber cache (`npx wp-env run cli wp timber clear_cache`) to test this.
> PLANET-7703 Fix country selector close button focus ring

- assets/src/scss/blocks/core-overrides/MediaText.scss
See [PLANET-7744](https://jira.greenpeace.org/browse/PLANET-7744)
Otherwise the content is impossible to read. I also made some design changes following Houssam's recommendations.
Make sure to check all screen sizes in the following pages:
- [Broken](https://www-dev.greenpeace.org/test-rhea/media-text-tests/)
- [Fixed](https://www-dev.greenpeace.org/test-neptune/media-text-tests/)
Please also make sure that the Page Header pattern still look fine, for example on [this page](https://www-dev.greenpeace.org/test-neptune/take-action/)
> PLANET-7744 Fix Media & Text padding in large screens

- src/GravityFormsExtensions.php
- src/Migrations/M032MigrateSplit2ColumnBlock.php
- tag.php
Ref. https://jira.greenpeace.org/browse/PLANET-7714
Fix below type errors
[Sentry error](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/3170/?alert_rule_id=4&alert_type=issue&notification_uuid=3dec6f65-2502-47ef-bf97-eb595ac45369&project=2&referrer=slack)
```
TypeError
P4\MasterTheme\GravityFormsExtensions::p4_client_side_gravityforms_prefill(): Argument #1 ($form) must be of type array, bool given, called in /app/source/public/wp-includes/class-wp-hook.php on line 326
```
~~[Sentry Error](https://sentry.greenpeace.org/organizations/greenpeace-org/issues/2972/events/e9bd5636a5984500be0a9e4528403b6c/)~~
```
TypeError
P4\MasterTheme\Migrations\Utils\Functions::create_media_text_block(): Argument #3 ($img_url) must be of type string, bool given, called in …
```
> PLANET-7714 Fix Sentry errors

- assets/src/js/toggle_comment_submit.js
This PR fixes the error in the `assets/src/js/toggle_comment_submit.js` script when the element `gdpr-comments-checkbox` is not part of the DOM. It also refactors the script for better readability and performance.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7773
1. Visit any post with comments and check that the "Post comment" toggles enable or disable when clicking on the "I agree on providing my name, email and content so that my comment can be stored and displayed in the website." checkbox.
3. Check there is no error in the browser console when comments are not enabled on a post.
> PLANET-7773: Fix error in the `toggleCommentSubmit` script

- assets/src/blocks/Covers/CoversCarouselLayout.js
- assets/src/js/query_loop_carousel.js
- src/MasterSite.php
This is for the Actions List and Covers blocks. This behaviour has been updated in Bootstrap 5.2 ([docs](https://getbootstrap.com/docs/5.2/components/carousel/)). It's been confirmed with the design team that we want to deactivate the autoplay!
On any page with a carousel layout, on `main` branch ([example](https://www-dev.greenpeace.org/test-rhea/actions-list/)) it has autoplay but on this branch it shouldn't ([example](https://www-dev.greenpeace.org/test-janus/actions-list/)).
> Remove carousel autoplay

- assets/src/scss/base/_mixins.scss
- assets/src/scss/base/_typography.scss
- assets/src/scss/layout/_country-selector.scss
- assets/src/scss/layout/_forms.scss
- assets/src/scss/layout/_navbar.scss
- assets/src/scss/layout/navbar/_search.scss
This removes some duplicate code and makes it easier to add new focus states in the future
All elements should still have the correct focus styles.
> Add mixin for focus styles

- src/Api/Tracking.php
The current implementation will retrieve the total of posts that have been created during the last N days.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7613
Navigate through this [sheet](https://docs.google.com/spreadsheets/d/1uAmZLIWYsxrBByqbhoF_vVtSM7WGebYWIc0xftPRPwE/edit?gid=636537247#gid=636537247) > Tracking and then click on top nav Planet 4 > Tracking. The total column related to content created should be updated.
⚠️  Once this PR is merged, we'll need to update this sheet with all NROs and remove the assigned instance.
> PLANET-7613: Track content created

- assets/src/block-editor/QueryLoopBlockExtension/index.js
See [PLANET-7780](https://jira.greenpeace.org/browse/PLANET-7780). It used to be the Articles block link. We'll need to do the same thing for the Actions List once the page is created in the Handbook.
> PLANET-7780 Update Posts List block Handbook link

- tag.php
Follow up from 580fa49e23ee51f9239a025dc5965073dc42f0ed
Tried a different way of making the redirect work, while keeping Sentry happy.
---
1. Currently if you pick a page as a redirect while editing a Tag it doens't work in the frontend
2. In this branch the redirect works just fine
> Fix tag redirect functionality

- assets/src/scss/blocks/PageHeader.scss
See [PLANET-7769](https://jira.greenpeace.org/browse/PLANET-7769). We can use padding instead. This was causing issues with other background colors.
- [Broken](https://www-dev.greenpeace.org/test-rhea/take-action/)
- [Fixed](https://www-dev.greenpeace.org/test-janus/take-action/)
> PLANET-7769 Remove PageHeader box-shadow

- assets/src/block-editor/Sidebar/ActionSidebar.js
- src/ActionPage.php
- src/Blocks/ActionButtonText.php
- src/Settings.php
This PR introduces an `aria-label` attribute to the Actions CTA to be read by screen readers. 
The text of the attribute can be edited from the sidebar of the Actions post type editor.
Also, some texts have been adjusted.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7702
1. Go to the editor of an Action post.
2. Check the new field ("Add descriptive text for screen readers...") exists in the sidebar.
3. Add text to the field and save the changes.
4. Visit a page containing an Actions List block with the Action edited in the previous steps.
5. Check that the CTA of that action in the Actions List block contains an `aria-label` attribute with the value added in step 3 (i.e., the Oceans action in [this page](https://www-dev.greenpeace.org/test-neptune/actions-list-test-page/)).
6. …
> PLANET-7702: Add Actions List Block CTA text for Screen Reader

- assets/src/js/accessible_nav_menu.js
- assets/src/scss/layout/_navbar.scss
- assets/src/scss/layout/navbar/_burger-menu.scss
- assets/src/scss/layout/navbar/mobile.scss
- templates/burger-menu.twig
This PR improves the accessibility of the mobile navigation menu by introducing these changes:
- When the hamburger menu is open, tabbing makes the close button reachable.
- A keyboard trap is added to the navigation menu when the hamburger menu is open.
- A focus ring is added to the reset button of the search field.
- The focus rings are no longer cut off.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7756 
1. Run this PR locally or in the dev instance.
2. Check the mobile version.
3. Check that the mobile navigation menu accomplishes the requirements of the Jira ticket.
> PLANET-7756: Navigation Menu: fix accessibility issues on mobile

- assets/src/scss/layout/_navbar.scss
- templates/desktop-menu.twig
This PR fixes the following issues:
- When clicking on the main navigation dropdown items, the arrow suddenly appears.
- On the Donate button, the arrow is always there over the text.
Video reference: [2025-03-10 14-18-39.mp4](https://jira.greenpeace.org/secure/attachment/39410/39410_2025-03-10+14-18-39.mp4)
---
Ref: https://jira.greenpeace.org/browse/PLANET-7783
1. Go to the test instance: https://www-dev.greenpeace.org/test-tavros/ 
2. Check the arrow in the Donate button. It should not overlap the button label.
3. Click on the submenu links of any menu item with children (except the Donate button). The arrow should not appear.
> PLANET-7783: Fixed issue with the main navigation arrows

- assets/src/scss/layout/_forms.scss
- assets/src/scss/pages/post/_comments-block.scss
- assets/src/scss/pages/post/_comments-form.scss
See [PLANET-7782](https://jira.greenpeace.org/browse/PLANET-7782). The new style is applied to links within comments, and also to the Reply button.
See [PLANET-7738](https://jira.greenpeace.org/browse/PLANET-7738). 
- In RTL sites, the "cancel reply" link is missing spacing
- When the logged in user has a long name, in some screen sizes the "Logged in as..." message overlaps with the "cancel reply" link
You can check the changes on [this post](https://www-dev.greenpeace.org/test-jupiter/press/1109/duis-posuere-4) for example.
> PLANET-7782 & PLANET-7738 Improve comments form

- assets/src/blocks/TakeActionBoxout/HeadingFontSizes.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutBlock.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutEditor.js
- assets/src/blocks/TakeActionBoxout/TakeActionBoxoutFrontend.js
- assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
- src/Blocks/TakeActionBoxout.php
- templates/blocks/take-action-boxout.twig
See [PLANET-7603](https://jira.greenpeace.org/browse/PLANET-7603)
- Heading Sizes: The title should be able to be adjusted with the following options:
- **Desktop XXL, XL, & L**
- XL: 28px/1.75rem
- L: 22px/1.1375rem
- M: 20px/1.25rem - default
- S: 18px/1.125rem
- **Mobile M&S**
- XL: 22px/1.1375rem
- L: 20px/1.25rem
- M: 18px/1.125rem - default
- S: 16px/1rem
- Default Setting: The default title size will be set to Heading M.
- Use design tokens for font sizes
- Ideally use rem points for font sizes
[FontSizePicker documentation
](https://developer.wordpress.org/block-editor/reference-guides/components/font-size-picker/)
You can test all the new variations on [this post](https://www-dev.greenpeace.org/test-sinope/press/1113/duis-posuere-6/) for example (different font …
> PLANET-7603 Add an option to change TAB heading size 

- assets/src/blocks/TableOfContents/TableOfContentsBlock.js
- assets/src/blocks/TableOfContents/TableOfContentsEditor.js
- src/Blocks/TableOfContents.php
See [PLANET-7752](https://jira.greenpeace.org/browse/PLANET-7752). This should not affect existing blocks
Either on local or on the [janus test instance](https://www-dev.greenpeace.org/test-janus/), add a new Table Of Contents block to a page and make sure the level's "Link" option is checked by default. If you add an extra level, you should see the "Link" option checked there too.
> PLANET-7752 Make Table Of Contents content links by default

- assets/src/scss/base/_colors.scss
- assets/src/scss/components/_share-buttons.scss
- src/GravityFormsExtensions.php
- src/Post.php
- src/Settings.php
- templates/blocks/share_buttons.twig
Ref. https://jira.greenpeace.org/browse/PLANET-7749
- Add Bluesky as an option to Planet 4 > Social > Social sharing options (not enabled by default)
- Add Bluesky as an option on Forms sharing settings
- Use Bluesky's compose url to generate the sharing action
- We already have the Bluesky icon in our svg sprite so we can use the twig tag we have, same as we do for [Whatsapp](https://github.com/greenpeace/planet4-master-theme/blob/v1.308.0/templates/blocks/share_buttons.twig#L46). We can use #1185fe as the svg [fill color](https://github.com/greenpeace/planet4-master-theme/blob/c31f6667ff235855b2ac33759f6a35fe76659833/assets/src/scss/base/_colors.scss#L2).
1. Login to the [test instance](https://www-dev.greenpeace.org/test-titan/wp-admin/) or test it on your local environment.
2. …
> PLANET-7749 Add Bluesky share button

- templates/listing-page.twig
This PR adds text to be read by screen readers to the layout toggle button.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7716
1. Visit a page that uses a layout toggle button (ie https://www-dev.greenpeace.org/test-umbriel/tag/consumption/).
2. Reach the button by using only the keyboard.
3. Once the button is focused, the screen reader must read "Switch to grid view" or "Switch to list view".
4. Press "Enter" or "Space" and check that the button works as expected.
> PLANET-7716: Make the layout toggle button operable by screen readers

- src/EnqueueController.php
This PR fixes the error with the Google Consent Mode value not being passed correctly to Google Tag Manager.
---
Ref: https://greenpeace.slack.com/archives/C014UMRC4AJ/p1742291992761149
1. Go to the admin panel > Planet 4 > Cookies (`/admin.php?page=planet4_settings_cookies_text`)
2. Check or uncheck the "Enable Google Consent Mode" option and save the changes.
3. Go to the front and review the `googleTagManagerData.cookies_enable_google_consent_mode` global variable in the browser console. Its value should be `on` or `null` based on the selection in step 3.
> Fix error with GTM and Google Consent Mode

- functions.php
As it currently gets the pod hostname it's harder to filter and merge pods from the same deployment. So tried to get the useful part of the hostname. Which is just one word for most instances, but may be two for some (eg. test instances).
Also increases a bit the events sample rate.
---
_This is based on [wp-sentry filter](https://github.com/stayallive/wp-sentry/blob/master/README.md#wp_sentry_options) to set options for Sentry_
1. You should already be able to filter issues on Sentry using the filter `server_name is test-venus` in the Custom Search bar
> Set server_name tag for Sentry logging

- .circleci/config.yml
- package-lock.json
- package.json
Ref: https://jira.greenpeace.org/browse/PLANET-7707
Upgrade to Node v20
- https://github.com/greenpeace/planet4-base/pull/322
- https://github.com/greenpeace/planet4-circleci/pull/74
- https://github.com/greenpeace/planet4-develop/pull/52. This PR can wait after me we update the theme and base repos.
> PLANET-7707: Upgrade to NodeJS v20

- assets/src/scss/pages/search/_sort-filter.scss
- templates/base.twig
- templates/search.twig
- templates/search/action_types.twig
- templates/search/categories.twig
- templates/search/content_types.twig
- templates/search/post_types.twig
See [PLANET-7718](https://jira.greenpeace.org/browse/PLANET-7718)
- Use `<section>` or `<aside>` HTML tags for Filters
- ~Use `<form>` for the Search Input.~ (already implemented)
You can test all of these changes on the oberon instance [Search page](https://www-dev.greenpeace.org/test-oberon/?s=&orderby=_score).
> PLANET-7718 Improve search page accessibility

- assets/src/scss/blocks/PageHeader.scss
See [PLANET-7546](https://jira.greenpeace.org/browse/PLANET-7546)
Add a Page Header pattern to a page with a very long title, on desktop/tablet it should be cut off after 3 lines but on mobile the limit should now be 5 lines. You can also just check [this page](https://www-dev.greenpeace.org/test-proteus/act/).
> PLANET-7546 Increase Page Header title limit on mobile

- src/MasterSite.php
Ref. https://jira.greenpeace.org/browse/PLANET-7793
In the media library, the missing image URL is:
https://storage.googleapis.com/planet4-aotearoa-stateless-develop/2025/04/bb77ca80-event-pic.jpeg
However, the image is actually saved in the Stateless bucket at:
https://storage.googleapis.com/planet4-aotearoa-stateless-develop/2025/03/bb77ca80-event-pic.jpeg
This suggests that if Stateless Storage is using server time (UTC) while WordPress is using Auckland time (UTC+12/13), the month may roll over differently. As a result, uploads might be placed in a different month folder in the Stateless bucket than what WordPress expects.
In this PR, we force WordPress to use UTC date for upload paths, ensuring consistency and preventing missing media library images.
We don't have an exact scenario …
> PLANET-7793 Force WP to use UTC date for upload paths

- assets/src/blocks/Columns/EditableColumns.js
- assets/src/scss/components/_buttons.scss
- assets/src/scss/editorOverrides.scss
See [PLANET-7483](https://jira.greenpeace.org/browse/PLANET-7483)
I've also added a small fix for the P4 Columns block, to show the correct button classes in the editor for the Tasks style. And I updated the secondary buttons' background to be white instead of slightly transparent, because it looked ugly in case a background is added:
Please test all Button styles (primary, secondary, transparent, donate)! In all screen sizes they should still look good. You can do this on local or use [this page](https://www-dev.greenpeace.org/test-janus/button-tests/) I created.
> PLANET-7483 Use padding instead of line height for buttons

- assets/src/scss/layout/navbar/_site-logo.scss
This PR aligns the main logo with the left margin of the website content.
Additionally, it moves a line of CSS code to avoid repeating a media query.
**BEFORE:**
**NOW:**
---
Ref: https://greenpeace-gpi.slack.com/archives/G015K63081W/p1743580344148979
> Align main Greenpeace logo

- .circleci/config.yml
- .stylelintrc
- assets/src/scss/base/_icons.scss
- assets/src/scss/base/_typography.scss
- assets/src/scss/blocks.scss
- assets/src/scss/blocks/Accordion/AccordionStyle.scss
- assets/src/scss/blocks/Columns/ColumnsStyle.scss
- assets/src/scss/blocks/PostsList/PostsListStyle.scss
- assets/src/scss/blocks/TopicLink/TopicLinkStyle.scss
- assets/src/scss/blocks/core-overrides/Heading.scss
- assets/src/scss/layout/_navbar.scss
- assets/src/scss/layout/navbar/_burger-menu.scss
- assets/src/scss/layout/navbar/languages.scss
- assets/src/scss/pages/_listing-page.scss
- assets/src/scss/pages/post/_author-block.scss
- assets/src/scss/vendors/photoswipe/main.scss
- assets/src/scss/vendors/photoswipe/p4-skin.scss
- package-lock.json
- package.json
It looks like our `stylelint` config was not working lately. For the version of stylelint we use (`14.16.1`) we also need to use `postcss-scss` for support SASS.
So what this PR does:
- Adds postcss on the stylelint configuration
- Fixes minor styling issues accumulated overtime in scss code
---
1. On the main branch run: `npx stylelint "assets/src/scss/**/*.scss"` You should get multiple warnings about `Unknown word  CssSyntaxError` and suggestion for using `postcss-scss`.
2. Switch to this branch and run: `npm run install`
3. Then re-run `npx stylelint "assets/src/scss/**/*.scss"`
4. Everything should work fine
> Add scss support for stylelint

- src/MasterSite.php
Ref. https://jira.greenpeace.org/browse/PLANET-7659
- You can test this fix on a local environment or a [test instance](https://www-dev.greenpeace.org/test-venus/wp-admin/upload.php?item=771).
- Navigate to WP Admin → Media Library → View Image.
- If the image is imported from Greenpeace Media Library and has a restriction, the restriction field should be visible.
- If the image does not have a restriction, the restriction field should be hidden (previously, an empty input field was displayed).
> PLANET-7659 Hide empty restrictions text field in media library

- src/EnqueueController.php
This PR adds the value of `cf_local_project` to the `googleTagManagerData` global variable, which is missing.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7796
1. Edit an existing page or post, or create a new one.
2. In the page/post settings, go to "Analytics & Tracking"
3. Complete all the fields.
4. Visit the page/post front.
5. In the browser console, check the `googleTagManagerData.cf_local_project` variable. It should match the selection of step 3.
> PLANET-7796: Pass the variable `cf_local_project` to GTM

- src/Blocks/Gallery.php
This PR limits the number of images shown by the lightbox carousel of the block "Gallery" with style "3 columns".
Without this implementation, When we create a Gallery block with the 3 Columns style, even if more images are selected in the backend only 3 will show in the frontend. However, when clicking on one of these images to open the Lightbox, all images show there which is confusing.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7101
1. Check the testing page: https://www-dev.greenpeace.org/test-neptune/planet-7101/
2. Check that all the galleries are working as expected. Each gallery contains the same 6 images.
3. Check that the gallery using the "3 columns" style shows only the corresponding 3 images when the lightbox carousel is opened.
> PLANET-7101: Lightbox shows all images for Gallery 3 columns style

- assets/src/js/vwo_smart_code.js
- src/HttpHeaders.php
- src/MasterSite.php
---
This fix removes the `*visualwebsiteoptimizer.com ` subdomain from the CSP headers. This was throwing an error on the console.
Also added a fallback function to queue `vwo_$` requests if they run before the script is loaded.
Now loading the VWO Smart code at the beginning of the head tag.
> Fix VWO script

- src/Blocks/Columns.php
This PR includes in the front the empty columns of the P4 Columns block.
---
Ref: 
- https://jira.greenpeace.org/browse/PLANET-7034
- https://greenpeace-gpi.slack.com/archives/G015K63081W/p1744106076520599
1. Visit https://www-dev.greenpeace.org/test-phoebe/p4-columns-test-page/
2. Check that all the columns of the P4 Columns block are rendered, regardless of whether they have content or not.
> PLANET-7034: Show empty columns in the P4 Columns block

- admin/css/dashboard.css
This PR temporarily hides the Stateless Media notices in the admin area.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7686
Related PR: https://github.com/greenpeace/planet4-base/pull/335
> PLANET-7686: Hide WP-Stateless admin notices

- assets/src/scss/pages/_listing-page.scss
**Before:**
**After:**
Check any listing page, on `main` branch you should see the broken version but on this one it should be fixed. You can also check [this page](https://www-dev.greenpeace.org/test-proteus/press/) from the test instance.
> Fix layout toggle size

- assets/src/js/google_tag_manager.js
- src/EnqueueController.php
- src/MasterSite.php
- src/Migrations/M044SetDefaultUrlPassthroughOption.php
- src/Migrator.php
- src/Settings.php
This PR creates a new setting under `Planet 4 > Cookies` for NROs to set the `url_passthrough` variable.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7791
1. In your local environment, reset the database by running: `npm run db:reset` 
2. In the website editor, go to `Planet 4 > Cookies` and check that the new setting `Consent default: url_passthrough` exists and it's set as `true`
3. Visit the website front and look at the `googleTagManagerData.consent_default_url_passthrough` variable in the browser console. It should be empty.
4. Run the migration script: `npx wp-env run cli wp p4-run-activator`
5. Repeat step 3. Now the value of the variable should be `1`
6. Go to `Planet 4 > Cookies`, change the value of `url_passthrough`, and check in the browser console if the change is …
> PLANET-7791: Create `url_passthrough` setting

- src/Blocks/Gallery.php
Ref: https://jira.greenpeace.org/browse/PLANET-7802
It needs an extra `className` validation to fix:
```
Warning: Undefined array key "className" in /var/www/html/wp-content/themes/planet4-master-theme/src/Blocks/Gallery.php on line 207
```
The PR is related to #2592.
> Fix Gallery warning issue

- assets/src/scss/layout/navbar/mobile.scss
See [PLANET-7803](https://jira.greenpeace.org/browse/PLANET-7803). It was broken when working on accessibility.
Either on local or on the [titan test instance](https://www-dev.greenpeace.org/test-titan/), on mobile/tablet the mobile tabs should again have a height transition when (dis)appearing.
> PLANET-7803 Fix mobile tabs transition

- assets/src/blocks/Spreadsheet/SpreadsheetEditor.js
- assets/src/blocks/Spreadsheet/SpreadsheetFrontend.js
- assets/src/scss/blocks/Spreadsheet.scss
- assets/src/scss/editorOverrides.scss
See [PLANET-6407](https://jira.greenpeace.org/browse/PLANET-6407).
This PR also includes a quick fix to remove an ugly padding in the sidebar settings:
**Before**
**After**
Add a Spreadsheet block to a page, in the frontend you should now see the sorting indicators and they should rotate when you click on them. You can use [this sheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vSbOPA0YEfvAYEKO2KguU_A1vIaIeJVJp1eC4zu9lrWpMRtJX0NiYC0iZwalvI3BUkOQSKYEaQwrt7Q/pubhtml) for testing purposes. Alternatively you can check out [this Post](https://www-dev.greenpeace.org/test-janus/press/1113/duis-posuere-6/) from the test instance.
> PLANET-6407 Fix Spreadsheet block indicators

- functions.php
In some cases the pods hostname has more parts that expected. Adjusted the relevant code for simplicity and not relying on number of hostname parts.
> Adjust Sentry server name to work in all cases

- assets/src/scss/blocks/TakeActionBoxout/TakeActionBoxoutStyle.scss
Ref: [PLANET-7801](https://jira.greenpeace.org/browse/PLANET-7801)
On local, add a Take Action Boxout block to a page or a post, enable the `Make block stick to the bottom of the page on mobile` setting in the sidebar. Alternatively you can check out [this page](https://www-dev.greenpeace.org/test-venus/about-us-2/) and [this post](https://www-dev.greenpeace.org/test-venus/press/1113/duis-posuere-6/) I made on the test instance.
In the frontend on mobile and tablets you should see the block stick to the bottom of the page, without any extra margin.
> PLANET-7801 Remove unwanted margin bottom in sticky Take Action Boxout

- assets/src/scss/base/_body.scss
- assets/src/scss/layout/_page-header.scss
- assets/src/scss/pages/_page.scss
- templates/base.twig
- templates/navigation-bar.twig
See [PLANET-7650](https://jira.greenpeace.org/browse/PLANET-7650). This was due to the presence of a `clearfix` div between the content and the header.
Please make sure that the spacing looks good in all screen sizes in the following examples:
- [News & Stories page](https://www-dev.greenpeace.org/test-jupiter/news-stories/)
- [Listing page](https://www-dev.greenpeace.org/test-jupiter/category/energy/)
- [Post](https://www-dev.greenpeace.org/test-jupiter/press/1113/duis-posuere-6/)
- [Page with title](https://www-dev.greenpeace.org/test-jupiter/get-informed/energy/)
- [Page with hidden title](https://www-dev.greenpeace.org/test-jupiter/get-informed/nature/)
> PLANET-7650 Fix News & Stories top spacing on mobile

- assets/src/scss/variations/stretched-link/edit.scss
- assets/src/scss/variations/stretched-link/index.scss
See [PLANET-7776](https://jira.greenpeace.org/browse/PLANET-7776). We added our usual link styles by mistake.
You can check out the changes on [this page](https://www-dev.greenpeace.org/test-pluto/patterns/) that I made for UAT, both in the editor and in the frontend.
> PLANET-7776 Remove link styles from Quick Links & Deep Dive patterns

- assets/src/block-editor/setupTaxonomyBreadcrumbBlock.js
- assets/src/blocks/ActionsList/index.js
- functions.php
- src/Api/QueryLoopExtension.php
- src/Blocks/QueryLoopExtension.php
- src/Loader.php
The ActionsList block might render the same content as the Covers block.
[Demo page as a reference](https://www-dev.greenpeace.org/test-pandora/support-to-ta-pages-demo-page/)
Also play around with [this page](https://www-dev.greenpeace.org/test-pandora/take-action/page-with-act-parent/) and change its parent to `Act` or `Take Action`. The block should follows the expected behavior.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7657
1. Create a new page
2. Add two blocks: ActionsList and Cover which will be needed to compare content
Then check:
1. it's disabled, we should only fetch children pages of the page that is assigned as "Act Page" (same as the current Covers block).
2. If it's enabled, we should fetch Actions (we already do that) but also the children pages of the page that …
> PLANET-7657: Add support for Take Action pages

- templates/single.twig
Revert fix added earlier in [PR#2616](https://github.com/greenpeace/planet4-master-theme/pull/2616#discussion_r2074790055)
Ref: 
https://jira.greenpeace.org/browse/PLANET-7432
- Edit a post and update the Author Override setting.
- Check the frontend — the default avatar image should no longer appear alongside the author name.
[Before this fix eg.](https://www-dev.greenpeace.org/test-titan/press/1113/duis-posuere-6/)
[After this fix eg.](https://www-dev.greenpeace.org/test-proteus/press/1113/duis-posuere-6/)
> PLANET-7432 Revert fix added for missing default avatar for author override

- assets/src/blocks/Accordion/AccordionEditor.js
Otherwise it's not convenient to add links there. This was requested by Quentin to facilitate Handbook updates!
You should now see the link option in the Accordion tab content:
> Allow links in Accordion content

- tests/e2e/blocks/audio-video.spec.js
- tests/e2e/blocks/posts-list.spec.js
- tests/e2e/blocks/spreadsheet.spec.js
- tests/e2e/comments.spec.js
- tests/e2e/navigation-bar.spec.js
- tests/e2e/password-protected-content.spec.js
- tests/e2e/related-posts.spec.js
- tests/e2e/search.spec.js
- tests/e2e/special-pages.spec.js
- tests/e2e/tools/lib/editor.js
Loads of copy has been changed with WordPress 6.8.1, this is why tests are failing in [this PR](https://github.com/greenpeace/planet4-develop/pull/57). 
- `Toggle block inserter` => `Block Inserter`
- `Search for blocks and patterns` => `Search` (using placeholder selector instead of label, which wasn't strict enough)
- `Posts per page` => `Items per page`
- In `ColorPalette` (used in our Spreadsheet block) the aria-label no longer contains `Color:` but just the color name
- `<p>...</p>` => `<p>...</p>` because otherwise for some reason it was interpreted as code in the frontend:
```
Error: expect.toBeVisible: Error: strict mode violation: getByText('This is a paragraph.') resolved to 2 elements:
1) <p>This is a paragraph.</p> aka getByText('This is a paragraph.', { exact: true })
2) …
```
> Fix e2e tests for WordPress 6.8.1

- src/Loader.php
See [PLANET-7792](https://jira.greenpeace.org/browse/PLANET-7792). We forgot to move them before deactivating the plugin 😬 
You should now see the patterns properly categorised in the editor:
> PLANET-7792 Register block pattern categories

- src/Blocks/QueryLoopExtension.php
---
**Ref: https://jira.greenpeace.org/browse/PLANET-7811**
You can compare the this [page](https://www-dev.greenpeace.ch/de/ueber-uns/#jahresbericht) on dev site, with same [page](https://www.greenpeace.ch/de/ueber-uns/#jahresbericht) on the production site to see how the changes fix the issue.
We are simply removing the sticky posts from showing up when manual override is used.
> PLANET-7811 Fix Posts List Block manual override

- assets/src/block-editor/TermSelector/index.js
Without this it wasn't possible to add new tags via the editor:
It's probably related to the WordPress upgrade? Or it's been broken for a while 😬 
Try adding new tags to a Post or Page via the editor sidebar. On `main` branch it won't work, but on this branch it will be possible.
> Fix TermSelector findTerm function

- src/GravityFormsExtensions.php
This PR fixes the issue with the Entry Date in the entries page of Gravity Forms:
---
1. Check the form entries on any dev site of an NRO ([example](https://www-dev.greenpeace.org/international/wp-admin/admin.php?page=gf_entries&id=67)). The Entry Date should show an error: `There has been a critical error on this website. Please check your site admin email inbox for instructions. If you continue to have problems, please try the support forums.`
2. Check the form entries locally. The Entry Date should show the expected data. If the Entry Date column is not visible, select it by clicking the cog icon at the end of the columns' titles.
> Fix error with Entry Dates in Gravity Forms

- assets/src/block-editor/QueryLoopBlockExtension/index.js
- assets/src/block-editor/setupTaxonomyBreadcrumbBlock.js
- functions.php
- src/MasterBlocks.php
- src/Migrations/M048SetDefaultTaxonomyBreadcrumb.php
- src/Migrator.php
- src/Settings.php
This PR removes the configuration of the Taxonomy Breadcrumbs inner block from the Posts List block and creates a new global setting for it instead.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7808
1. In your local environment, reset the database by running the command `npm run db:reset`
2. Run the migration scripts: `npx wp-env run cli wp p4-run-activator`
3. Check that the Posts List and the Actions List blocks still work as expected.
4. Check that the new Settings exist in the Defaults Content admin page and work as expected: `wp-admin/admin.php?page=planet4_settings_defaults_content`
5. Change the settings and see if it alters the taxonomy of the Posts List and the Actions List blocks as expected. Also check the other instances of the Posts List block, such as listing pages and …
> PLANET-7808: Add a global setting for taxonomy breadcrumb

- src/BlockSettings.php
Ref: [PLANET-7817](https://jira.greenpeace.org/browse/PLANET-7817)
The block should now be available in all post types.
> PLANET-7817 Enable core Cover block

- src/MasterSite.php
Ref https://jira.greenpeace.org/browse/PLANET-7810
- We are calling the __() function (for translations) too early, likely during theme class instantiation — before the init action. Since translation functions like __() rely on the translation system being loaded, this is what's triggering:
```Notice: Function _load_textdomain_just_in_time was called incorrectly...```
- The correct way to load translations now(as of WP 6.7+) is to load translations using the init hook.
1. Switch to the `main` branch locally, and ensure that `WP_DEBUG` is enabled.
2. Visit any page of the Planet4 local website.
3. You should see a PHP Notice similar to the one below in the logs:
```PHP Notice:  Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the planet4-master-theme …
```
> PLANET-7810 Fix notice(Theme translations are loaded too early)

- admin/css/archive-picker.css
- assets/src/js/Components/ArchivePicker/ArchivePicker.js
- assets/src/js/Components/ArchivePicker/blockUpdateFunctions.js
---
**Ref: https://jira.greenpeace.org/browse/PLANET-7840**
GP Media is now enabled for the Cover block. For testing, make sure to enable all blocks in _Planet4 -> Features_, then on the editor, you can add the Cover block and use the GP Media tab to add and update the images.
> PLANET-7840 Enabled Greenpeace Media on Cover block

- src/MasterSite.php
From wp6.7 the translation files path location change to 'wp-content/languages/themes/' for now we have keep language files in theme language folder and use load_textdomain() to load translations
---
[Ref: ](https://wordpress.org/support/topic/translations-are-no-longer-loading-from-the-theme-folder/#post-18132409)
TBD
> Replace a fallback solution for loading a language files

- src/Blocks/QueryLoopExtension.php
This PR removes from the `QueryLoopExtension` class a piece of code that was calling a non-existent variable.
It also adds an extra check to ensure that the variable `$query['post__in']` is set before being manipulated.
---
Ref: https://jira.greenpeace.org/browse/PLANET-7848
In your local environment or the test instance, check both in the editor and the front-end that:
1. Query Loop blocks (existing and newly added) only query published posts (no draft, private, or password-protected) and exclude the current post.
2. Posts List blocks (existing and newly added) only query published posts (no draft, private, or password-protected) and exclude the current post.
3. Actions List blocks (existing and newly added) only query published posts (no draft, private, or password-protected) and …
> PLANET-7848: Fix the error "undefined array key `post__in`"

- assets/src/block-editor/Sidebar/ActionSidebar.js
- src/ActionPage.php
- src/Features/ActionOptions.php
- src/Features/ActionsTaskType.php
- src/Settings/Features.php
This will allow to editor to set the action page as In Real Life or Online.
Also it will used by the Resistance Hub campaign page.
Related PRs:
- #2670 
- Full implementation #2656 
---
Ref: [PLANET-7828](https://jira.greenpeace.org/browse/PLANET-7828)
1. Go to [`Planet 4/Features`](https://www-dev.greenpeace.org/test-venus/wp-admin/admin.php?page=planet4_settings_features) and enable `Action Options`
2. If it's enabled, the can create or edit any Action page and set the Task Type of right panel
> PLANET-7828: Add Task Type field

- assets/src/block-editor/Sidebar/ActionSidebar.js
- assets/src/block-editor/SidebarFields/DatePickerSidebarField.js
- src/ActionPage.php
- src/Features/ActionsDeadline.php
- src/Settings/Features.php
This will allow editors to set the Deadline field on Actions It works only if Actions Options is enabled from P4 Features.
- Blocked by #2669 
- Full implementation #2656 
---
Ref: https://jira.greenpeace.org/browse/PLANET-7841
1. Go to Planet 4/Features and enable Action Options
2. If it's enabled, the can create or edit any Action page and set the Deadline from right panel
> PLANET-7841: Add Action Deadline field

- src/Migrations/M046MigrateArticlesBlockToPostsListBlock.php
- src/Migrations/M049MigrateCoversBlockToActionsListBlock.php
- src/Migrations/Utils/Functions.php
This PR enables migration scripts to log the errors during the migration process, making them accessible from the recently introduced "Data Migration" page in the admin area. It also logs the errors of migrations `M046MigrateArticlesBlockToPostsListBlock` and `M049MigrateCoversBlockToActionsListBlock` 
--- 
1. Follow the testing steps mentioned here: https://github.com/greenpeace/planet4-master-theme/pull/2676 
2. Go to the Data Migration admin page: `/wp-admin/admin.php?page=planet4_migration_status` 
3. Check that errors were logged in the "Logs" column.
> Log errors during the migration process

- admin/js/media_replacer.js
- src/Loader.php
- src/MediaReplacer.php
This PR adds the following fixes and improvements to the `MediaReplacer` class:
- Removes the `nocache` URL parameter which produces no benefit and could cause issues on page reload.
- Loads the class only in the admin area.
- Calls the `ud_get_stateless_media` function only once.
- Gets the name of the replaced file correctly, including the year and month as part of it.
- Gets the image width and height from the file name as an extra precaution.
- Reduces the file cache.
---
1. Log in to the test instance: https://www-dev.greenpeace.org/test-venus/wp-admin/
2. Go to the Media Library: https://www-dev.greenpeace.org/test-venus/wp-admin/upload.php
3. Select an already existing image.
4. Replace it by clicking on the Replace Media button.
5. Wait for the page to reload and the message "File …
> Fixes in the `MediaReplacer` class

- assets/src/block-editor/QueryLoopBlockExtension/index.js
**Ref:** [PLANET-7857](https://jira.greenpeace.org/browse/PLANET-7857)
**Related PR:** https://github.com/greenpeace/planet4-master-theme/pull/2677 (migration script for existing blocks)
On local or on the test instance, add a Posts List block to a page and update the taxonomy filters in the sidebar. After doing so, check in the editor that the corresponding "see all" link has been updated, save the page and make sure that the custom link also shows in the frontend.
> PLANET-7857 Adjust See All link based on taxonomy filters

- src/MasterSite.php
Revert "PLANET-7793 Force WP to use UTC date for upload paths PR 2582"
Since we've found that this fix does not affect the upload directory path and the issue was resolved by updating the ACL settings on the Stateless bucket, we can safely revert these changes.
> PLANET-7793 Revert fix added in 2582 PR

- src/AttachmentsController.php
This would result in issues when using the images afterwards
Ref: [PLANET-7872](https://jira.greenpeace.org/browse/PLANET-7872)
Try uploading an image to the Media Library, without this fix it won't have dimensions but on this branch they should be added as expected.
For example you can use the [image](https://www.greenpeace.org/luxembourg/wp-admin/upload.php?item=25132) cited by GP Luxembourg in the ticket.
> PLANET-7872 Fix missing image dimensions in Library upload

- index.php
- page-templates/evergreen.php
- page.php
- single-campaign.php
- single-p4_action.php
- single.php
- src/BlockSettings.php
Ref: [PLANET-7829](https://jira.greenpeace.org/browse/PLANET-7829)
This feature was added with WordPress 6.3. For it to be rendered in the frontend, we need to use the global WP post ID to construct the Timber post.
You can check out the Footnotes block in the various available post types:
- [Page](https://www-dev.greenpeace.org/test-tavros/about-us-2/)
- [Post](https://www-dev.greenpeace.org/test-tavros/press/1113/duis-posuere-6/)
- [Action](https://www-dev.greenpeace.org/test-tavros/petitions/consectetur-adipiscing/)
- [Campaign](https://www-dev.greenpeace.org/test-tavros/campaign/this-is-a-campaign-for-testing-purposes/)
- [Homepage](https://www-dev.greenpeace.org/test-tavros/)
- [Evergreen page](https://www-dev.greenpeace.org/test-tavros/just-an-evergreen-page/)
> PLANET-7829 Enable Footnotes block

- src/MasterSite.php
- src/MetaboxRegister.php
This is part of our efforts to make this file shorter 🩳 
This box should still be present in the sidebar for Posts and Pages, and work as expected:
> Move metabox search functionalities out of MasterSite.php

- assets/src/js/header.js
- assets/src/js/header/setupCloseNavMenuButton.js
- templates/burger-menu.twig
This allows us to simplify `header.js` and hopefully makes the code easier to maintain. I've removed mentions of the `close-navbar-dropdown` because it seems it's no longer used.
Ref: [PLANET-7849](https://jira.greenpeace.org/browse/PLANET-7849)
I've also removed the Bootstrap attributes on the close nav button, we don't need them since we override the click function. The `aria-expanded` attribute wasn't updated anyways, see following screenshot where the button was open: 
Closing the navigation menu should still work as expected.
[PLANET-7849]: https://greenpeace-planet4.atlassian.net/browse/PLANET-7849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move close nav element functionality to separate file

- assets/src/js/header.js
- assets/src/js/header/setupMobileTabsMenuScroll.js
This allows us to simplify `header.js` and hopefully makes the code easier to maintain. I've also created a constant to be used for the `mobile-menu-hidden` class.
Ref: [PLANET-7849](https://jira.greenpeace.org/browse/PLANET-7849)
The mobile tabs should still behave as expected.
[PLANET-7849]: https://greenpeace-planet4.atlassian.net/browse/PLANET-7849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move mobile tabs behaviour to separate file

- assets/src/scss/pages/_listing-page.scss
- index.php
- page-templates/evergreen.php
- page.php
- single-campaign.php
- single-p4_action.php
- single.php
This PR fixes the blank page issue when no posts are found.
Additionally, it aligns the "Apply" button of the "News & Stories" page on desktop.
---
Ref: https://greenpeace-gpi.slack.com/archives/C0160MX64AG/p1753350675224669
1. Go to the "News & Stories" page.
2. Select a combination of filters that return no posts.
3. Click on the "Apply" button.
4. Check the page after being reloaded: it should be rendered as expected and show the message "No posts found!"
> Fix blank page when no posts are found

- assets/src/scss/pages/post/_comments-form.scss
- src/CommentFormCustomizer.php
- src/Loader.php
- src/MasterSite.php
As part of our effort to reduce the size of the `MasterSite` class, this PR moves from it all functions related to the comment forms into a new class called `CommentFormCustomizer`
---
Ref: https://greenpeace-gpi.slack.com/archives/C0160MX64AG/p1751531019331059 
1. Go to a post that contains a comment form.
2. Check in the form that the checkbox and its label contain the expected custom classes.
3. Check in the form that the website field was removed.
>  Reduce the length of the `MasterSite` class II

- functions.php
This wasn't working properly
Ref: [PLANET-7890](https://greenpeace-planet4.atlassian.net/browse/PLANET-7890)
- [Broken](https://www-dev.greenpeace.org/test-rhea/wp-admin/post.php?post=1147&action=edit)
- [Fixed](https://www-dev.greenpeace.org/test-venus/wp-admin/post.php?post=1147&action=edit)
[PLANET-7890]: https://greenpeace-planet4.atlassian.net/browse/PLANET-7890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PLANET-7890 Fix backend link to settings for News Stories page

- assets/src/js/header.js
- assets/src/js/header/setupNavMenu.js
This allows us to simplify `header.js`.
Ref: [PLANET-7849](https://greenpeace-planet4.atlassian.net/browse/PLANET-7849)
Toggling nav elements should still behave as expected.
[PLANET-7849]: https://greenpeace-planet4.atlassian.net/browse/PLANET-7849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PLANET-7849 Move toggleNavElement function to separate file

- src/Migrations/M055AddDefaultSiteIcon.php
- src/Migrator.php
---
Ref: https://greenpeace-planet4.atlassian.net/browse/PLANET-7770
1. On test instance, the Dashboard should now have the same favicon as on the frontend
2. Locally, run migration and test the same icon is used in Dashboard as on frontend favicons
3. Also because embed use this icon as a default, we should now have the G icon on embeds and not the WP default.
> PLANET-7770 Added default site icon

- assets/src/js/resistance-hub-campaign.js
- assets/src/scss/pages/_resistance-hub-campaign.scss
- single-p4_action-resistance_hub.php
- src/Blocks/TakeActionBoxout.php
- src/Features/ActionsTaskType.php
- src/Features/ActionsUserPersonalization.php
- src/Settings/Features.php
- templates/blocks/take-action-boxout.twig
Ref: [PLANET-7882](https://greenpeace-planet4.atlassian.net/browse/PLANET-7882)
**Requirements:**
- Label: Actions User Personalization
- Description: Shows Actions as completed if the user has visited them already
- Make sure it's clear these new features are only applied to the Resistance Hub template.
You can use [this page](https://www-dev.greenpeace.org/test-phoebe/petitions/resistance-hub/) I created for UAT in order to test the new functionality.
[PLANET-7882]: https://greenpeace-planet4.atlassian.net/browse/PLANET-7882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PLANET-7882 Mark Action as completed based on user interaction

- src/CronJob.php
- src/Loader.php
- src/Search/ElasticSearch.php
Add a cron job for full ES sync
---
[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/2713)
Ref: https://greenpeace-planet4.atlassian.net/browse/PLANET-7821
**Note:**: Please connect to local elastic search container using `npm run elastic:activate` cmd.
We don’t have specific steps to reproduce this issue, but we can simulate it by adding the following code to the `functions.php` file. To trigger the code execution, you’ll need to run an ElasticPress sync(`npx wp-env run cli wp elasticpress sync --setup --yes --force`):
```
add_filter( 'ep_post_mapping', function( $mapping ) {
$mapping['mappings']['properties']['post_date'] = [
'type' => 'text'
];
return $mapping;
} );
```
To check the mapping locally, run the following command:
`npx wp-env run cli wp elasticpress …
> Planet 7821 full es sync

- assets/src/block-templates/quick-links/template.js
- assets/src/scss/base/_mixins.scss
- assets/src/scss/blocks/core-overrides/Columns.scss
- assets/src/scss/layout/_wide-blocks.scss
- src/Migrations/M056UpdateQuickLinksClassName.php
- src/Migrations/Utils/Constants.php
- src/Migrator.php
Ref: https://greenpeace-planet4.atlassian.net/browse/PLANET-7608
The currently layout displays the items fine, however, some times the users don't understand if there are more quick links availble to scroll within small screens. The idea is to display at least a tiny part of the last item visible on viewport to let them know that there are more items available to see.
Convert block to wide and remove the grey spaces in both sides.
Demo page: https://www-dev.greenpeace.org/test-pandora/quick-links-demo/
https://github.com/user-attachments/assets/c99d1f22-3887-4c8d-b7f4-5a43cc1cdf6a
---
Ref: https://jira.greenpeace.org/browse/PLANET-7608
Use small sizes `< 576px` (mobile recommended).
> PLANET-7608: Fix Quick Links layout issues on small screens

- assets/src/block-editor/QueryLoopBlockExtension/index.js
- assets/src/blocks/ActionsList/index.js
- assets/src/js/actions_list_clickable_cards.js
- assets/src/js/actions_list_load_more.js
- assets/src/js/app.js
- assets/src/scss/blocks/ActionsList/ActionsListEditorStyle.scss
- assets/src/scss/blocks/ActionsList/ActionsListStyle.scss
- assets/src/scss/components/_buttons.scss
- src/Blocks/QueryLoopExtension.php
- src/Migrations/M057ActionsListBlockLoadMore.php
- src/Migrations/Utils/Functions.php
- src/Migrator.php
Ref: [PLANET-7865](https://greenpeace-planet4.atlassian.net/browse/PLANET-7865)
You can test the functionality on [this page](https://www-dev.greenpeace.org/test-janus/actions-list-test/) for example.
For the migration, on local you can use the [Take Action page](http://www.planet4.test/take-action/) which already has an Actions List. At first it shouldn't have the load more button, but when running `npx wp-env run cli wp p4-run-activator` you should see it (maybe only when inspecting, it's hidden if there are less than 6 items in the block).
To reset your local content you can use `npm run db:reset`
[PLANET-7865]: https://greenpeace-planet4.atlassian.net/browse/PLANET-7865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PLANET-7865 Enable Load More functionality in Actions List

- src/Blocks/QueryLoopExtension.php
This PR fixes the bug that prevents the manual override feature not to working as expected in the Posts List block.
The problem was the early return of the query parameters on line 90 of the `src/Blocks/QueryLoopExtension.php` file.
---
Ref: https://greenpeace-planet4.atlassian.net/browse/PLANET-7921
1. Add a Posts List block to a page or post.
2. Add posts to the manual override feature.
3. Check that the block displays the selected posts in the correct order.
4. Check that the current post is not displayed, even if selected from the manual override feature.
5. Check that the rest of the functionalities of the block still work correctly.
6. Check that the Actions List block still works correctly.
> PLANET-7921: Fix bug with the manual override feature in the Posts List block

- src/GravityFormsExtensions.php
Ref. https://greenpeace-planet4.atlassian.net/browse/PLANET-7904
The `gform_pre_render` filter throughs a TypeError due to strict return type of array, now we make it array|bool (use php Union type)
> TypeError
> P4\MasterTheme\GravityFormsExtensions::p4_client_side_gravityforms_prefill(): Return value must be of type array, bool returned
> PLANET-7904 Fix Sentry TypeError in GF form filter

- tests/e2e/search.spec.js
Search test is failing even now that Elasticsearch is back on test instances (see screenshot from the report below). Looking at the test code, it looks like we are testing for the tag name twice, but the first time we are looking at the wrong place.
Not sure why it used to work before. Maybe something changed because if [this commit](https://github.com/greenpeace/planet4-master-theme/commit/56f4f2834a185fc80f428fef089e7db3ed315975#diff-3a54bde3f5a7b056c7bb6cfd1a84b704e2412d26ae66ea39e0de84e7f6783737)?
> Fix search e2e test

- admin/css/options.css
As we are planning on using a newer version of ElasticSearch, this hides the version notice to avoid confusion for admins.
Used the data selector, as the css classes have very generic names.
---
1. Test any dev to see the notice that is visible on admin panel by Elasticpress
2. In this branch, the notice should no longer be visible
> Hide ElasticPress version notice

- assets/src/blocks/components/Lightbox/setupLightboxForImages.js
This PR fixes the images not using their largest size when expanded by the lightbox, but the one selected by the editor.
---
Ref: https://greenpeace-planet4.atlassian.net/browse/PLANET-7649
1. In a post or page, add the following blocks: Image (with caption), Image (without caption), Media Text, and Paragraph (or you can also use [this page](https://www-dev.greenpeace.org/test-atlas/test-page/)).
2. Add images to all the blocks mentioned in step 1. In the case of the Paragraph block, add an inline image.
3. Change the size of the image and use one different to of "full" or "original".
4. In the front, click on every image. The lightbox should be fired, and the image should expand to full size regardless of the size chosen on step 3.
5. Also check that the Gallery blocks keep working …
> PLANET-7649: Fix lightbox not using largest image

- admin/css/gravity-forms-admin.css
- src/GravityFormsExtensions.php
This PR hides the "Attachments" option (see below) in the Gravity Form's notification settings.
As it was mentioned [here](https://greenpeace-planet4.atlassian.net/browse/PLANET-7460?focusedCommentId=25642), there's an incompatibility between that option and the WP-Stateless plugin, so the decision to remove the option was made. 
I could not find any filter to properly remove it, so the change applied to this PR relies on CSS.
---
Ref: https://greenpeace-planet4.atlassian.net/browse/PLANET-7460
1. Go to Gravity Form's notification settings.
2. Check that the "Attachments" option is no longer visible.
> PLANET-7460: Hide GF notification checkbox for attachments
