greenpeace/planet4-master-theme

search.php, templates/navigation-bar.twig, templates/search.twig, templates/tease-post.twig, templates/tease-search.twig, templates/tease.twig
Initial version of the P4 Search Results page. It is using SearchWP plugin's search under the hood. (Sorting by most recent is not completed). Added simple markup to resemble the final design. Replaced Timber's get_preview() deprecated function calls with preview(). Truncated preview down to 25 words.
=> Feature/937: Search sort

functions.php, search.php, templates/navigation-bar.twig, templates/search.twig
Fix issue with Timber and SearchWP not collaborating well when we provided parameter to Timber's get_posts() function. Now Most Recent sorting includes attachments as well. Also, fixed issue with displaying max 10 results. Also, added pagination as a temp solution until we add lazy loading.
=> Feature/1428 Search attachments

functions.php
Just changing the wording here, as "Post Type" is an existing WordPress term and could cause confusion and 'P4' was an unnecessary qualification. We talked about Presentation Type and Content Type but settled on Page Type for least conflict across editorial terms.
=> Changed post-type to page-type

templates/blocks/header.twig, templates/tag.twig
Fix Header Block disparity so that description text does not spread across page width. Also, fixed small issue where the Separator bullet between Issue and Campaign links appeared even if there were no Campaign links. Adjusted Campaign page markup to be similar to presentation layer markup and remove unecessary classes and aligned its header to start at the same height as the other pages headers.
=> Presentation templates disparities

classes/class-p4-search.php, functions.php, search.php, templates/navigation-bar.twig, templates/search.twig
Fix multiple bugs on search filtering. Bug that was not returning attachments (Documents) when searching for everything. Bug that was not allowing correct filtering by Content Type when we searched for everything. Bug that did not allow multiple Page type filters. Bug that did not allow multiple Content Type filters. Changed implementation so that we can search for everything (with or without filters applied) by not entering anything at all( /?s= ),instead of entering the space character. Made it so that when we search for everything then the 'Most relevant' sort option gets disabled. Page title changes depending on searching for everything or not.
=> Search page bug fixes.

classes/class-p4-search.php, templates/navigation-bar.twig, templates/search.twig
Display correctly the search input inside both search fields and in the page title as well, when it contains special characters.
The get_search_query() escapes the search input value by default but I still escape the variable that contains it on output (just to be sure in case someone else changes what this variable contains)
=> 1575 search fixes - Spreadsheet issue 129

classes/class-p4-search.php, templates/search.twig
Temporarily remove the Source selection buttons (This site, Archive) in search page. When removed the search input takes up the rest of the space.
=> 1575 search fixes - Spreadsheet issue 114

functions.php
Check that orderby URL param is actually set before applying the ORDER BY clause, so that it will not cause a wrong SQL clause and so that search links can work without orderby param included in the link (e.g. 404 search form).
=> 1575 search fixes - Spreadsheet issue 156

classes/class-p4-search.php
Make sure that we add results to Issues filter item that belong to one of the Issues children categories. Increase POSTS_LIMIT to 300 to mitigate issue with different types of Posts being left out due to big number of PDF documents.
=> 1575 search fixes - Spreadsheet issues 139, 142

tag.php
Update Campaign page code so that it can correctly auto-generate the Happy Point block now that it is updated with EN mailing list.
The web editors need to set the background image for the Happy Point block, located within the Tag page itself inside the WP admin panel.
=> Campaign page update - Spreadsheet issue 165

page-templates/evergreen.php, page.php, templates/blocks/header.twig
Update Breadcrumbs to display multiple Issue categories (Take Action, Evergreen pages) instead of displaying only the first one.
=> 1635 breadcrumb update

templates/blocks/author_profile.twig
Timber uses default wordpress value (96px) for avatar url creation.
Changed to 294px to look closer to the design.
[Issue 1651](https://jira.greenpeace.org/browse/PLANET-1651)
=> Changed avatar size used in author_profile template.

functions.php
Comment out tags_support_query for now as it seems we don't need it.
If no issue comes up in the next days, I will remove it completely.
[Issue 1455](https://jira.greenpeace.org/browse/PLANET-1455)
=> Comment out tags_support_query for the time being.

templates/single.twig
Per [this comment](https://jira.greenpeace.org/browse/PLANET-1581?focusedCommentId=60973&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-60973) the Take Action card on Posts shows the slug instead of the name. This commit fixes that.
=> Show tag name instead of slug

functions.php, partials/tags_box.php
Add functions to disallow creation of tags to all roles besides administrator.
- Remove default wordpress selection box for all roles besides administrator.
- Add checkboxes list for selecting post's / page's tags for all roles besides administrator.
- Add hook to prevent creation of tags for all roles besides administrator.
[Issue 1690](https://jira.greenpeace.org/browse/PLANET-1690)
=> Disallow creation of tags to all roles besides administrator

assets/js/search.js, classes/class-p4-search.php
Fix bug due to js variable ajaxurl being defined by WP only in the backend. In the frontend we need to define it ouselves.
=> 1649 search optimize

assets/admin/js/edit_post.js, functions.php
Add change event listener for categories selection box.
Select the relevant p4-page-type if the category that is selected it is also a p4-page-type.
[Issue 1642](https://jira.greenpeace.org/browse/PLANET-1642)
=> Add js file for edit post admin page

functions.php
Remove obsolete tags_support_query function, since it does not affect functionality.
Related to PR #212
=> Remove obsolete tags_support_query function.

assets/scss/common/_page-header.scss, assets/scss/common/_skewed-overlay.scss
Not sure why we had `max-height` on `.skewed-overlay` since we have `height: 100%`. This caused the gradients to stop on very [long pages](https://dev.p4.greenpeace.org/international/explore/about/worldwide/).
=> [PLANET-1780] Expand page backgrounds to full width and height

assets/scss/pages/post/_article-content.scss
It's hard to have perfect iframe height for the entire mobile breakpoint. I optimized it for `320px` and `360px` that most smartphones use.
=> [PLANET 1722] Use smaller height on iframes on mobile

assets/js/custom.js
Since we allow editors to add the cover card as a post element anywhere in the post we need to make sure we only float the cards that are added as block on the sidebar.
=> [PLANET-1581] Float only action cards on sidebar

assets/scss/common/_covers.scss
Minor change to fix vertical spacing and to make sure that covers styling is not overridden by `.post-content h2`.
=> [PLANET-1802] Fix vertical spacing on Posts

assets/scss/common/_campaign-thumbnail-block.scss
Centering the campaign image for mobile screen size instead of showing
just the top.
=> Bug fix PLANET-1740

composer.json
I updated Timber locally and I didn't noticed anything weird
=> [PLANET-1807] Update timber-library to 1.7.0

assets/admin/js/edit_post.js, assets/admin/js/planet4_settings.js, classes/class-p4-settings.php, functions.php
- Add planet4 settings js. 
- Add fields in planet4 settings page for mapping p4 page types to wordpress categories.
- Change save_post hook to assign the proper p4 page type to the post according to the mapping.
- In edit post page only one of the mapped categories can be chosen and p4-page-type will be changed according to the mapping.
[Issue 1642](https://jira.greenpeace.org/browse/PLANET-1642)
=> [PLANET-1642] Map p4 page types to categories

assets/scss/pages/post/_article-content.scss
We have some rare cases where content may exist outside any markup. See the text below the first image [here](https://dev.p4.greenpeace.org/international/issues/ships/11635/charting-a-plastic-free-future-in-taiwan/). This minor fix ensures that at least the typography rules are correct.
=> [PLANET-1707] Enforce typography styling on bare content

functions.php
Removed default p4 page type terms from master theme.
I will move them to content default repo to run only on a new site installation.
[Issue 1871](https://jira.greenpeace.org/browse/PLANET-1871)
=> [PLANET-1871] Remove default p4 page type terms

templates/base.twig
This adds the ability to child-theme developers to add a sidebar. Since `sidebar.twig` is emtpy on master-theme this adds no extra markup to our default template.
=> Add support for sidebar

classes/class-p4-search.php
Fix the way we check if a search result is an Action page, by comparing it's parent with the selected Act page inside P4 Settings.
=> Planet4-1896 search action pages results

assets/js/main.js, tag.php
Fix Covers block Load more functionality. Reveal 3 or 2 more covers (depending on device) each time user clicks on Load more button. Display 6 covers on page load inside Campaign page.
=> PLANET-1875 fix covers load more

assets/scss/common/_covers.scss
Fix number of take action covers displayed on page load on M screens when 'Show 3 covers' option in Covers block is selected.
PS. I am entering your territory here. Looks like it works but if this is not correct then feel free to take over the issue.
=> PLANET-1928 fix covers m screens

assets/scss/common/_covers.scss
Ticket [link](https://jira.greenpeace.org/browse/PLANET-1704) 
As per feedback from the design team changing the width of the button from `90%` to `92%`.
cc: @tolen
=> PLANET 1704 Fixing alignment of button on small screen size.

assets/js/partials/carousel.js, functions.php
Change carousel header js to use current loaded image from srcset for img tags.
Add event listeners to change css background images in a carousel header block as window is resized.
Change retina-large image size not to crop images.
[Issue 1926](https://jira.greenpeace.org/browse/PLANET-1926)
=> PLANET-1926 Carousel header responsive images

assets/admin/js/edit_post.js, functions.php
Automatically set as featured image of a Post the first image found within the Post's content. Allow Editors to override this by setting manually another featured image of their choosing.
=> PLANET-1823 auto set featured image

classes/class-p4-custom-taxonomy.php
The issue was if no taxonomy is assigned to page/post, it will take first page type taxonomy as default. Here now, we have added condition for post type check, which solved an issue for new records. We need to find a solution for already added pages with default page_type.
=> PLANET-1954 Fix issue of page type auto assigned to post_type PAGE

classes/class-p4-post.php, page-templates/evergreen.php, page.php, single.php, templates/blocks/header.twig, templates/evergreen.twig, templates/single.twig
Implement smarter logic for loading navigation links of Issue pages that are relevant to current P4_Post (page, post, evergreen) categories. Moved logic inside P4_Post class from where it can be accessed by all pages.
- This way we no longer need to match Category Names with Issue page names. -
=> PLANET-1963 smarter post breadcrumps

templates/html-header.twig
Changed viewport device width to `320px` as per suggestions [here](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/UsingtheViewport/UsingtheViewport.html) & [here](https://jira.greenpeace.org/browse/PLANET-1956?focusedCommentId=62705&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-62705).
[ref1](https://www.quirksmode.org/mobile/viewports2.html), [ref2](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) for extra dose of viewports; mind-boggling stuff ahead.
=> Bug/1956 iPhone breakpoint

classes/class-p4-custom-taxonomy.php
Since we removed categories - p4-page-types mapping, users should be able to select the p4-page-type when they edit a post.
Related to this [PR 368](https://github.com/greenpeace/planet4-master-theme/pull/368)
=> PLANET-1975 Reintroduce code that saves p4-page-type from edit post requests.

assets/scss/common/_footer.scss
So the site need to meet all the readability standards. The existing two links in the footer to "Otherwise Stated" and "CC-BY International License" are currently in #86EEE7 which when used on such small type on a background colour of #1E5F65 fails to pass WCAG AAA standard. So we have to change the link colour to white #FFFFFF which has an underline that switches on on mouse hover.
=> PLANET-1708 Footer: change background and link color

assets/scss/common/_happy-point-block.scss
I moved the default fallback image to plugin-blocks, since we no longer use `background-image` for the happy-point.
See greenpeace/planet4-plugin-blocks#255
=> Remove happy-point default background

assets/scss/common/_happy-point-block.scss
Related to https://github.com/greenpeace/planet4-plugin-blocks/pull/256
[Issue 1936](https://jira.greenpeace.org/browse/PLANET-1936)
=> PLANET-1936 Allow happy point img to use container's full space for s & m sizes.

assets/js/partials/pubslider.js, assets/scss/common/_content-four-column.scss
A minor modification to make sure the block expands on full page width when we have less than 4 columns.
=> PLANET-1987 - Make Content Four Column block responsive

assets/js/partials/pubslider.js, assets/scss/common/_content-four-column.scss
If I got the [design request](https://jira.greenpeace.org/browse/PLANET-1916) right, we only need slickify slider behavior on Small screens. We currently also had it running for Medium devices causing some problems.
I also added visibility css options for Medium devices that didn't exist.
=> PLANET-1916 - Fix M devices visibility issues on Four Column Block

assets/scss/pages/post/_comments-form.scss
There is a conflict with bootstrap's own placeholder styling than require this to be more explicit.
=> PLANET-1709 - Make placeholder css more explicit

classes/class-p4-search.php, search.php
Adjust filters to work with ES.
Fixed Content Type -> Page filter to not include Action Pages in its results.
Fixed Content Type -> Document filter to include only P4_Search::DOCUMENT_TYPES in its results. Still, the Document filter counter needs adjustment to include only the defined mime types.
Fixed a bug where Pages where as counted into Category filters counters, while only Posts should have the p4-page-type taxonomy.
Fixed a php notice.
=> PLANET4-2028 adjust search filtering

assets/js/partials/happy_point.js
Refactoring happy point asynchronous load so we don't rely on scroll position, but on whether the happy point is inside the user's viewport.
=> PLANET-2037 - Refactor Happy Point ifeame to load only when visible

assets/js/partials/post_action.js
The bug seems reproducible only on Chrome. I refactored the relevant code to use the more reliable `addEventListener`.
=> PLANET-2091 - Refactor and simplify action card scroll code

assets/scss/common/_navbar.scss, templates/navigation-bar.twig
This removes custom hard-coded class names for the nav items, that we don't use anyway.
Adds a raw filter, which should be safe for item titles. in order to render language flag image.
The current language won't be displayed at all, so in a bilingual scenario we would only have one flag there.
=> PLANET-2146 - Adjust navbar to fit a Language selector flag

templates/navigation-bar.twig
I removed hard-coded class names from nav links on e87304b9a5a57c4fa4de194ff98e8a8acd43c68e, since it's not easy to have those along with language switcher. But these are used as selectors on selenium tests. So I'm adding `item.class` so we can add these classes back through the admin.
=> Add class name on nav links

assets/scss/common/_submenu.scss
Altered `z-index` in order for the Sidebar to be above the content but not above the navigation bar.
=> PLANET-2127 - Add z-index to Submenu Sidebar

templates/blocks/share_buttons.twig, templates/html-header.twig
It seems that `title` is already escaped so we were double escaping some characters. So for instance instead of displaying the apostrophe sign as `&#8220;` we display it as `&amp;#8220;`, and Facebook can't render them properly.
Also twig seems to escapes variables inside the ternary operator, so I used a more classic syntax.
That's not easy to test locally with Facebook's opengraph debug tool. I'll need to re-check once this is live on stage.
=> PLANET-2179 - Avoid double escaping opengraph titles

functions.php
According to bootstrap documentation, umd version of popper js should be used along with it.
Current version throws an error in production.
=> Use umd version of popper js

assets/scss/common/_navbar.scss
This fixes the fact that WPML is injecting some custom css that overrides the visibility of current.
=> PLANET-2146 - Make sure current language is always displayed

assets/js/partials/cookies.js, assets/js/partials/happy_point.js, assets/scss/common/_cookies.scss, assets/scss/style.scss, classes/class-p4-cookies.php, classes/class-p4-settings.php, functions.php
[Issue 2240](https://jira.greenpeace.org/browse/PLANET-2240)
- Prevent happy point iframe loading if cookie policy is not accepted.
- Prevents google tag manager js embed if cookie policy is not accepted.
- Remove iframes/embeds from post content (could be changed to remove only iframes/embeds that come from specific urls).
- Set google login plugin cookie only in wp-login page.
- Set cookie expire time to 1 year.
=> PLANET-2240 Prevent cookies setting

assets/scss/common/_carousel.scss
This is a minor css fix needed by greenpeace/planet4-plugin-blocks#288
=> PLANET-1719 - Lift Carousel controls close to the top

classes/class-p4-image-compression.php, functions.php
https://greenpeace.github.io/planet4-imagestest-results/
The solution applied in the 6th image produces much better quality than P4 currently produces
and at the same time -47% size on retina-large images, -38% size on large images and -17% on medium images (on large and medium images results about the size of the 2 tested images are conflicting though).
```
Resize: Lanczos
Sharpening: unsharpMask( Radius 1, Sigma 0.45, Amount 3, Threshold 0 )
Compression: Interlace_Plane
Quality: 60
```
=> PLANET-2347 Imagestest

classes/class-p4-sitemap.php, single.php
[Related PR](https://github.com/greenpeace/planet4-plugin-blocks/pull/293)
The `get_home_url()` function consider current page language in base url.
([Reference](https://wpml.org/wpml-hook/wpml_home_url/))
=> PLANET-2372 Consider current language in search page url

classes/class-p4-cookies.php
Move priority & no of args outside callback array.
[Issue 2394](https://jira.greenpeace.org/browse/PLANET-2394)
=> PLANET-2394 Fix google login cookie hook.

templates/tease-search.twig
Use wp_get_attachment_url in search results for documents to allow wp-stateless run it's hooks
=> PLANET-1977 Fix documents urls in search results

assets/scss/common/_carousel-header.scss, assets/scss/common/_content-four-column.scss, assets/scss/common/_covers.scss, assets/scss/common/_navbar.scss, assets/scss/common/_page-header.scss, assets/scss/pages/_take-action.scss, assets/scss/pages/post/_article-content.scss, assets/scss/pages/post/post.scss, assets/scss/pages/search/_search.scss, assets/scss/partials/_typography.scss, assets/scss/style.scss
Since we use Roboto on specific elements (headings, captions, buttons, etc) this PR switches the default font to Lora to make sure all text elements are displayed properly.
=> PLANET-2377 - Use Lora as the default font

classes/class-p4-settings.php
The text is not used anywhere at this stage. We want to add the setting in the first release, ask all NROs to fill it in, and actually use it on the next release, so that we make sure that there is no point where the button text is empty. 
(Currently the button text is using the language files)
=> PLANET-2473 Added setting for donate text in p4settings

.gitignore, README.md, backstop.js, gulpfile.js, package.json, yarn.lock
Although this doesn't includes specific tests, it's related to frontend testing. Check README additions on how this works. Bellow I attach a few screenshots of an example report and the diff visualizations.
=> PLANET-2525 - Add BackstopJS for visual regression testing

tag.php
Change tag_id attribute to tags for articles block in tag page.
This should be merged together with
https://github.com/greenpeace/planet4-plugin-blocks/pull/300
=> PLANET-2412 Change tag_id attribute to tags for articles block in tag page

templates/html-header.twig
We currently load the happy point iframe asynchronously when the block gets visible to the user. This is just a minor trick that instruct the browser to do dns resolving beforehand making the iframe to load a bit faster.
=> Add dns-prefetch for happy point iframe

templates/tease-search.twig
Fix issue that caused the last search result item to auto-open when its Excerpt had less that 25 words. Also, fixes an older issue when a search result item that followed an item with less that 25 words in its Excerpt, had smaller thumbnail image and mis-aligned excerpt.
This was caused by Timber's read more functionality causing Twig's truncate filter to break html.
There is a twig extension of this filter (truncate_html) that is safe for html in cases like this, but no need since we can fix it this way.
=> PLANET-2532 fix search item auto-opening

classes/class-p4-post.php, templates/tease-author.twig
Author page should not include posts with author override. I added a function to use as a filter. Not sure if that's the more efficient way :)
The change on the template is just a wrap around and `if not (post.get_author_override)`.
=> PLANEt-2368 - Hide posts with override from Author's page

composer.json
I removed Timber from all child themes, and now we can safely upgrade.
=> PLANET-2729 - Timber v1.8.1

classes/class-p4-sitemap.php
URL before -
https://master.k8s.p4.greenpeace.org/luxembourg/fr//?s=&orderby=post_date&f[ptype][Arbeitsplatz%20Greenpeace]=70
URL after -
https://master.k8s.p4.greenpeace.org/luxembourg/fr/?s=&orderby=post_date&f[ptype][Arbeitsplatz%20Greenpeace]=70
(Remove extra slash[/] appended in url for multilingual sites)
=> PLANET-2758 Fix search page URL on a sitemap for multilanguage sites

classes/class-p4-custom-taxonomy.php, classes/class-p4-sitemap.php, single.php, taxonomy.php, templates/page_type.twig, templates/single.twig, templates/tease-author.twig, templates/tease-page-type.twig
Please read the issue for context: https://jira.greenpeace.org/browse/PLANET-2614
Added a `page_type` slug parameter to the custom taxonomy's `register_taxonomy` method.
Using `taxonomy.php` as a catcher for taxonomies requests using the default behavior of WP template hierarchy.
I changed the Page Type slug from most pages from being a filter url to a pure slug except for the search page, where the slug simulates a click in the "Page Type" checkbox.
Let me know what you think!
=> PLANET-2614: Refined results page

templates/single.twig
The "Comments" counter for articles was not translated.
Ref: https://jira.greenpeace.org/browse/PLANET-2726?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
=> PLANET-2726: Translate hardcoded Comments word.

assets/js/author.js, author.php, templates/author.twig, templates/tease-author.twig
Starting this PR to polish & finish our method to get posts for [Author](https://jira.greenpeace.org/browse/PLANET-2637) and [Page Type](https://jira.greenpeace.org/browse/PLANET-2822) pages.
I noticed we could be using the search class, but the `get_paged_posts` method is tied to the `search` pages templates. Maybe if we could separate the core functionality from the render, we could benefit from using the search logic already implemented in the search class, which looks more robust  in terms of validation, sanitization and caching. But maybe that's out of the scope of this issue.
=> PLANET-2637: Author Profile: missing posts

templates/blocks/site_logo.twig, templates/navigation-bar.twig
Since we have our first request from an NRO for custom logo, I splitted the logo image to a new block template so we can easily override it from child themes.
=> PLANET-2824 - Break logo image to a new block template

gulpfile.js
This will allow us to run gulp for both `master-theme` and and `plugin-blocks`.
=> PLANET-2892 - Add port to livereload

assets/js/load_more.js, taxonomy.php, templates/author.twig, templates/page_type.twig, templates/tease-page-type.twig
Fix class name collision with Load more button of Blocks. Master Theme should use load-more-mt. Small improvements in js. Now can use the data-content attribute to indicate where the response should be appended to. Registered couple strings for translation.
=> PLANET-2822 fix name collision

author.php, templates/tease-author.twig
Remove overridden posts from Author page. This happened because we were using TimberPost instead of P4_Post. TimberPost does not have post.get_author_override nor post.author.is_fake
=> PLANET-2637 authorpage remove overridden posts

templates/html-header.twig
This PR would fix the fact that the `favicon.ico` file is 404 not found.
Opening this link https://www.greenpeace.org/international/ and checking in console, the favicon is 404 and as  fallback the website keep loading another favicon that i may suppose it's in the wordpress root directory not in the theme directory. (don't know if wanted actually)
Shortly, the website is looking for https://www.greenpeace.org/international/favicon.ico constantly but that file doesn't exist.
Actually, i tried some of the context vars but i could have made something wrong there, so researching i found this issue explained https://github.com/timber/timber/issues/113
Finally `href="{{ theme.uri }}favicon.ico` seems to fix all of this, as it will surely point to the file path  on any page url.
I couldn't try …
=> fixing 404 http error - favicon.ico not found 

taxonomy.php
We were not filtering for page type!
Ref: https://jira.greenpeace.org/browse/PLANET-2931
Note: I'm using the shorthand method, which is based on the `slug` field, I don't know if this could cause any side effects, I don't foresee any.
Otherwise, we could do a `term_id`-based query using:
```
'tax_query' => [
[
'taxonomy' => 'p4-page-type',
'field' => 'term_id',
'terms' => $context['page_type']->term_id
]
],
```
=> PLANET-2931: #360374 Page Type page: showing wrong content

templates/tease-author.twig, templates/tease-page-type.twig
Use post_excerpt in page_type author templates.
Made it consistent with tease articles block template.
=> PLANET-2915 Fix post excerpt/preview in page_type and author templates

assets/js/load_more.js
Notes:
Switched from 'click' to 'mousedown touchstart' to prevent the 'focus()' event from happening, as I tried a few ways of blurring the element (jQuery, vanilla, document.activeElement) and none seemed to work right.
We could also remove `:focus` from the CSS class, but I'm not sure if that's what we want here, as the button classes are too generic (`btn-secondary`, etc).
Ref: https://jira.greenpeace.org/browse/PLANET-2927
=> PLANET-2927: Author Profile page: Load More button is wrong colour

sidebar.php
Ref: https://jira.greenpeace.org/browse/PLANET-2574
Ok, this is a long shot but here it goes: I don't have a local working Handbook DB for testing, so I just did some research on the surface, but my spider sense is telling me this could be the cause of the sidebar issue.
Looks like the `ip-tag` (IdeaPush tag) templates include `sidebar.php` in the render pipeline, which is a surprisingly old file:
IdeaPush includes it by calling: 
This is an example page: https://planet4.greenpeace.org/ip-tag/contribution/
Removing the file causes this error: 
```
Notice: Theme without sidebar.php is deprecated since version 3.0.0 with no alternative available. Please include a sidebar.php template in your theme. in /app/source/public/wp-includes/functions.php on line 3984
```
So, keeping the file but …
=> PLANET-2574: IdeaPush with broken sidebar

templates/author.twig, templates/taxonomy.twig
Ref: https://jira.greenpeace.org/browse/PLANET-2926 and https://jira.greenpeace.org/browse/PLANET-2930
Fixed the bootstrap grid classes on the Load More wrapper.
=> PLANET-2926: Load More button is wrong size

package.json, yarn.lock
Currently on `develop` the yarn install fails because flatmap-stream [has been removed from npm](https://www.npmjs.com/package/flatmap-stream).
gulp-livereload 4.0.1 [pins event-stream to 3.3.4](https://github.com/vohof/gulp-livereload/pull/140) which predates the flatmap-stream security vulnerability.
=> Upgrade gulp-livereload to avoid flatmap issue

templates/tease-author.twig, templates/tease-search.twig, templates/tease-taxonomy-post.twig
Truncate and excerpt are pretty identical, but excerpt uses [wp_trim_words](https://developer.wordpress.org/reference/functions/wp_trim_words/) which splits the content for character based languages correctly.
=> PLANET-3004 Fix truncate post excerpt for character based languages

classes/class-p4-post-report-controller.php, functions.php, languages/planet4-master-theme-backend.pot, languages/planet4-master-theme.pot, templates/404.twig, templates/blocks/share_buttons.twig, templates/comment_form/author_field.twig, templates/comment_form/comment_field.twig, templates/comment_form/email_field.twig, templates/comment_form/submit_button.twig, templates/comments_section.twig, templates/navigation-bar.twig, templates/search.twig, templates/single.twig, templates/tease-taxonomy-post.twig
- Add master-theme's textdomains to strings without textdomain.
- Apply workaround for translate functions inside twig files. Extracted stings inside html attributes into twig variables.
https://wordpress.org/support/topic/timbertwig-compatibility/
- Update pot templates.
With these changes, it is safe to use loco-translate for pot templates generation.
=> PLANET-3007 Add missing translatable strings

assets/scss/layout/_footer.scss
Switched the footer icons spacing from `space-evenly` to `space-between`, it is slightly different, just a few pixels, but it's more consistent with MS Edge, it looks the same in all browsers.
Ref: https://jira.greenpeace.org/browse/PLANET-3013
=> PLANET-3013: Social icons not aligned properly on Windows

.circleci/config.yml, composer.json, tests/bootstrap.php, tests/p4-testcase.php
A followup for #673 
- Install repo's dependencies in circleci
- Use repo's phpcs version
Thoughts/Questions:
Phpunit version should be defined by repo's dependencies and not in ci config (leaving it as it is now for the moment)
Do we need the multi-site testing?
=> Update circleci config

templates/author.twig
In order to get to translate the author bio, I had to:
- Install and activate WPML's **String Translation** plugin. 
- Add authors as translatable strings in WPML's **String Translation** config:
- Scan the template for translatable strings, this should collect the authors strings for translation:
- Go back to **String Translation** and edit the corresponding author bios:
- In order for the language switcher to show, the author must have written posts in both languages. Heads up: if YOU translate a post to test this, remember to change the post's author to the corresponding author, otherwise, the translated post will belong to "admin", your user (this made me lose quite a bit of time...)
So, it's a very small change in the template, but quite a big process for the editors, I guess we …
=> PLANET-2767: enable bilingual author profiles

classes/class-p4-custom-taxonomy.php
Ref: https://jira.greenpeace.org/browse/PLANET-2841
I did some research on how to remove the taxonomy name (`page_type`) from the URL without breaking other pages, to turn this URLs:
`https://www.greenpeace.org/international/page_type/story/`
Into: 
`https://www.greenpeace.org/international/story/`
The challenge is: avoid breaking other pages and let Wordpress know what are we referring to when the taxonomy name is not present in the URL: is it a page? a post? a page_type?.
I came up with this solution so far.
Do you see any possible side effects with this changes? 
Ping @kirdia , as I think you know more about these topics and it looks like you authored the current permalink / rewrite functions.
=> PLANET-2841: #358171 - Refined Results: wrong URL path

.circleci/config.yml
Utilise the planet4-base-fork codeception tests. 
- Build a docker-compose planet4 environment
- Run the tests against it
- Upload the artifacts. 
(Will change circleCI settings to run only on PRs)
=> Run codeception tests on builds

classes/class-p4-custom-taxonomy.php
Add a filter for root_rewrite_rules to add p4 taxonomy terms rewrite rules.
It is triggered when flushing rules (`flush_rewrite_rules()` or `wp rewrite flush`)
This way when changing permalink structure or when rewrite rules are flushed the p4 terms rewrite rules will be always added to the rules.
This will work when NROs update their permalink structure, despite if they use p4 page type permastruct 
in their permalink structure (like `/%p4_page_type%/%post_id%/%postname%/`)
[https://www.greenpeace.org/international/story/](https://www.greenpeace.org/international/story/)
A post-deploy flush rewrite rules will be needed though.
=> PLANET-2841 Add filter for root_rewrite_rules to add taxonomy terms in rewrite rules

assets/js/search.js, classes/class-p4-master-site.php, classes/class-p4-search.php, templates/search.twig
* Change default weight for Action Pages and simple Pages so that they always rank higher than other search results.
* Fix issue so that both ways (SearchWP/ES) function properly (left/right click), so that we can compare results more easily.
Note: As it is currently, default search (left click) still works with SearchWP
=> PLANET-3180 es search update

classes/class-p4-campaigns.php, tag.php
In order to keep the slug unchanged, instead of redirecting the Tag page fetches and renders the custom page content.
Ref: https://jira.greenpeace.org/browse/PLANET-3172
=> PLANET-3172 - Tags: Add option for a custom page redirection

templates/single.twig
`.cleafix` comes from [Bootstrap](https://getbootstrap.com/docs/4.2/utilities/clearfix/) and adds an `::after` element to make prevent problems with floating items at the end of post content.
Ref: https://jira.greenpeace.org/browse/PLANET-3190
=> PLANET-3190 - Posts: Add clearfix hack for clearing floating items

classes/class-p4-campaigns.php
A minor fix to allow validation to allow zero value selection. This means that by selecting "Select Page" (`value=0`) you can disable the redirection.
=> PLANET-3172 - Tag redirection: Fix validation to allow zero value selection

assets/js/search.js, classes/class-p4-search.php, templates/search.twig
Ref: https://jira.greenpeace.org/browse/PLANET-2364
Note: as we don't have lazy loading for all types of search, I consider this to be a temporary solution until we fix the TODO's in the current search code. That said, it works!.
=> PLANET-2364: Search: Don't display 'Show 5 more' button when there are less than 5 results

classes/class-p4-master-site.php, classes/class-p4-taxonomy-campaign.php
Make sure post cache is cleared after each update. Clear Timber's cache as well to avoid cache issue with rendering block changes.
The cache issue appeared in WP Pages and within blocks (for example, in an auto-generated campaign page https://release.k8s.p4.greenpeace.org/greece/tag/theseis-ergasias/).
Not sure if this will fix the issue (since I can not reproduce it locally) but it seems that there is a correlation with Timber caching since Timber caching uses different expiration time for anonymous and logged in users (which is something that was reported).
=> PLANET-2981 cache page issue

templates/blocks/header.twig
Original Ticket(planet-3256) Comment:
Checkbox added to header to choose whether to open header link in new tab or not.
Ticket requested to add checkbox alongside Header Button Title but that wasn't feasible so it was added below.
Ref: https://jira.greenpeace.org/browse/PLANET-3256
=> Planet-3256-fix: Removed test code in header.twig for planet-3256

classes/class-p4-master-site.php, page.php, templates/html-header.twig
- Added new option(block) on P4 pages backend for campaign fields
- All fields are optional (no mandatory validation)
- The dataLayer push code is added in HTML `<head>` before GTM code
- The old dataLayer push code is removed from EN form block in separate PR
=> PLANET-3324 Move campaign fields (dataLayer) to the P4 page backend

functions.php
Sets `Timber::$cache` to the inverse of `WP_DEBUG`
Enables Timber .twig > .php blob template caching for all non-development environments.
See: https://github.com/greenpeace/planet4-docker/blob/master/src/planet-4-151612/wordpress/wp-config.php.tmpl#L60
If APP_ENV matches `develop` then WP_DEBUG is true, therefore template caching is disabled and edits _should_ be immediately visible without cache clear.
=> PLANET-3419 - Enable Timber template caching

classes/class-p4-post-campaign.php
As per product owners requirements, the campaigns functionality should be hidden until it is ready to be delivered.
=> PLANET-3425 Hide the campaigns menu item until it is ready to be shown

classes/class-p4-master-site.php, single-campaign.php
**Task -**
- Add datalayer fields on add/edit campaign page [on right sidebar] (backend)
- Apply require validation on Campaign name, Basket name and Scope fields (Applicable on campaign page only and not for default wp pages)
- Add dataLayer push event on frontend campaign page
[JIRA 3396](https://jira.greenpeace.org/browse/PLANET-3396)
=> PLANET-3396 CPP - Add DataLayer fields on campaign page

classes/class-p4-sitemap.php
'orderby' and 'order' was missing from 'About Greenpeace' Column
=> PLANET-3433 Sitemap - Alphabetical order

classes/class-p4-dev-report.php, functions.php
This creates a new settings page, that only shows the p4 dev releated data if the relevant wp option exists (needs the [PR in base-fork](https://github.com/greenpeace/planet4-base-fork/pull/29) to have been merged, and run on deploys for the report to show)
The report can be seen at the [koyansync](https://k8s.p4.greenpeace.org/koyansync/wp-admin/options-general.php?page=planet4_dev_report) site
=> PLANET-3498 Show dev report of what repos/tags/branches are used

assets/js/posts_report.js
Use wp api load promise to wait for wp backbone js client to load, before initializing post report backbone views/collections.
=> PLANET-2402 Use wp api load promise to initiliaze post report js

.circleci/config.yml
Add a config entry to automate the test of the master theme in RIPS.
Ref: https://jira.greenpeace.org/browse/PLANET-2668
See the related PR on the p4-builder repo: https://github.com/greenpeace/planet4-builder/pull/27
=> PLANET-2668: Automate testing of new versions of plugins using RIPPs on the cloud

classes/class-p4-campaign-importer.php, exporter-helper.php, exporter.php, exporter_helper.php, functions.php
[JIRA 2658](https://jira.greenpeace.org/browse/PLANET-2658)
On export of campaign, export all attachment data in XML file.
On campaign import, import attachments and update all source image ids with newly imported attachment ids in post content.
The `planet-2658` branch is pinned to `koyansync` and `campaign` instances.
Example -
Exported campaign from `campaigns` instance :
https://k8s.p4.greenpeace.org/campaigns/campaign/test-campaign-export/
Imported campaign on `koyansync` instance:
https://k8s.p4.greenpeace.org/koyansync/campaign/test-campaign-export/
=> Planet 2658 Campaign Export and Import with attachments

page.php, single-campaign.php, templates/html-header.twig
https://jira.greenpeace.org/browse/PLANET-3320
As @sagarsdeshmukh  pointed out in this PR: https://github.com/greenpeace/planet4-master-theme/pull/794 , we don't need to render this field on the load event, only after form submission, thus I'm removing the rendering part from the code.
=> PLANET-3320: Add a new dataLayer field (Goal) on Form Block backend

classes/class-p4-elasticsearch.php, classes/class-p4-search.php, templates/search.twig
- Task
Added default case to all switch statements. Invalid filters, content types now will throw an exception whose message will be displayed.
- Fix
Included campaign Page results under the Pages filter.
- Optimizations
Made small optimization by avoiding unnecessary calls to get_the_category function for attachments.
Removed reduntant call to get_option.
=> PLANET-3519 switch default

templates/comment.twig
Since the comment.author.name returns always the original author we change it to use the field comment_author instead of comment.author.name
=> PLANET-3293 Use the field comment_author instead of comment.author.name

templates/child_comments.twig
As in https://github.com/greenpeace/planet4-master-theme/pull/805 , show the correct author for comments that have been reattributed. Previous fix was doing only first level comments. This one does all the other levels (that use a different twig template)
=> PLANET-3293 show correct author for replied reatributed comments

classes/class-p4-custom-taxonomy.php
This will add an additional column to the posts list that contains the post type, like the second last column in the screenshot:
Clicking the post type will filter the list. 
Related Wordpress documentation is here:
https://codex.wordpress.org/Function_Reference/register_taxonomy#Arguments
=> PLANET-3583 - Added show_admin_column argument to page-type taxonomy

classes/class-p4-master-site.php
Filter youtube.com domain for oembeds to youtube-nocookie.com
Use embed_oembed_html filter to cover for cached oembeds also (which WordPress stores in db)
https://developer.wordpress.org/reference/hooks/embed_oembed_html/
save_post hook won't work entirely, because it breaks post preview
=> PLANET-3619 Add filter for embed_oembed_html

page.php, single.php, templates/single-page.twig, templates/single-password.twig
Changed the login URL for password protected posts and pages to use wp_login_url() instead of Timber's site.link.
[site.link](https://timber.github.io/docs/reference/timber-site/#link) points to the home page and with WPML installed, that includes for example /en/ for the language. Using it to generate the login URL won't work in those cases and leads to a 404 error.
[wp_login_url()](https://codex.wordpress.org/Function_Reference/wp_login_url) returns the URL of the login page and is more reliable in special cases like this one.
=> PLANET-3812: Fixed login URL for password protected pages

.circleci/config.yml
Use current production version php 7.2 for unit tests builds
=> Use php 7.2 for unit tests builds

classes/class-p4-master-site.php, classes/class-p4-post-campaign.php
[JIRA 3748](https://jira.greenpeace.org/browse/PLANET-3748)
- Add Campaigner role with capabilities (Add, Edit, delete, publish campaigns etc.)
- Add Campaigner capabilities to view, add post, delete(own posts), edit(own post)
- Sort user roles alphabetically
The overview of campaigner permission are [here](https://docs.google.com/spreadsheets/d/1ZGfb6jF0WVClrrk7ftXH9vMUkq2U1cpbim59eiYfibo/edit#gid=120062525 ) .
=> PLANET-3748 CPP - Add 'Campaigner' role and its capabilities

classes/class-p4-master-site.php
I had to add a filter to allow the `object-position` property, otherwise, `wp_kses` would still remove the `style` attribute even if it's defined as an allowed attribute in the `set_custom_allowed_attributes` filter.
Ref: https://jira.greenpeace.org/browse/PLANET-3781
=> PLANET-3781: Gallery Block: Grid style focus point not working when used in Posts

classes/class-p4-custom-taxonomy.php
It is needed for gutenberg blocks to be able to query the taxonomy's terms.
=> Allow p4 custom taxonomy to be queried by rest api requests

classes/class-p4-campaigns.php, classes/class-p4-search.php
Temporary solution for excluding the auto generated tag pages from the search results (not optimal solution).
Note: _- In order for this to work the Tag pages need to get Updated once after this is merged in -_
Note 2: _Added a small change to avoid possible php error_
**Better solution**
I found the direct Elasticsearch curl request that is required for this but I could not translate it correctly into EP query arguments so I opened an [issue/question](https://github.com/10up/ElasticPress/issues/1437) in the EP repo.
If we can make it work this way it will be better because we will not need the extra SQL query that is included in this PR.
**Optimal solution**
Best way is to exclude them from being indexed in the first place but I have not managed to make this work with the latest EP …
=> PLANET-3857 search exclude tag pages

classes/class-p4-master-site.php
We prematurely added Bootstrap to the admin side to render the Gutenberg blocks correctly, but it breaks some styles on the admin (see screenshot).
We'll remove it for now and probably add a custom Bootstrap build.
=> Remove bootstrap styles from admin side for now.

templates/tease-search.twig
- Changed header length check and concatenation to still allow rendering of normal characters
=> PLANET-3932 Search: Media Results not accommodating special characters

templates/footer_min.twig
As noticed by Kelli, we need to remove the "All rights reserved" text from the minimal footer.
(no ticket yet)
=> (No ticket yet): Minimal footer copyright fix

classes/class-p4-campaigns.php, classes/class-p4-search.php
Hello all,
this is my first PR as a contributor :)
I received a [response](https://github.com/10up/ElasticPress/issues/1437#issuecomment-523669618) from the EP guys and this is a better way to exclude the auto-generated tag pages (without the need of an extra db query).
_Note 1: Tried also the non-indexing solution that was proposed in the response but it did not work for me.
Note 2: (I am not sure of the contributing process, so let me know if I should change something)._
=> search exclude tag pages improved

.circleci/config.yml, gulpfile.js
Double asterisk patterns need double quotes to work properly.
=> Fix stylelint and eslint paths

classes/class-p4-post-campaign.php
The 'select icon' dropdown field is change to text field. The style-guide repo is not available on staging/production and we already use class names of svg files in our P4 footer social menus, therefore the icon field is change to text field.
[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/894)
=> PLANET-4034 Make icon field text from selectbox

classes/class-p4-post-campaign.php
Ref: https://jira.greenpeace.org/browse/PLANET-4039
- Editors to be able to create/edit/delete all campaign pages
- Authors to be able to create/edit/delete only my own campaign pages
- Contributors simliar to Authors, but not able to publish
=> PLANET-4039 Adjust campaign roles for editors and authors

classes/class-p4-campaign-importer.php
Add filter function for wp_import_post_data_processed (wordpress importer) to set campaign posts as draft during import.
=> PLANET-4081 Set imported campaign posts as draft

templates/html-header.twig
Ref: https://jira.greenpeace.org/browse/PLANET-4166
Markup on this field is useless and it creates problem since it's escaped to html entities.
=> PLANET-4166 Strip html markup from Open Graph description field

classes/class-p4-metabox-register.php, single-campaign.php, templates/base.twig
Ref: https://jira.greenpeace.org/browse/PLANET-4241
Add the option to hide page title for editors, same as regular pages.
This fixes the current bug, that we completely hide the header.
=> PLANET-4241 - CPP: Use same page header options as regular pages

single.php
- Auto generated code was using post id of post page rather than selected id of take action page.
- Changed to use selected take action page id.
=> PLANET-4311 Take action boxout: added by TA page selector in posts showing wrong content

tag.php
Fix old Content Four Columns block => Cover block
Issue link -
https://k8s.p4.greenpeace.org/denmark/tag/landbrug/
expected behaviour link - 
https://www.greenpeace.org/denmark/tag/landbrug/
The fix is tested on local with `Denmark` production DB.
On my local I don't have images, but fix confirm with post title and desc.
=> PLANET-4295 Fix cover block gutenberg conversion for old CFC block

classes/class-p4-master-site.php
Test with more content if this solves the issue.
Ref: https://jira.greenpeace.org/browse/PLANET-4305
I think WP by default also adds `wpautop` to excerpts, we could mimic this by adding the same filter to the `the_excerpt` hook, but we are using the `excerpt` filter from Timber which is an alias of `wp_trim_words`, it trims words, strips tags, and removes line-breaks internally, so it makes no difference.
Some notes:
https://wpquark.com/kb/misc/wordpress/fixing-themes-custom-wpautop-priority/
=> PLANET-4305: Enable wpautop as Wordpress did before Gutenberg.

classes/class-p4-master-site.php
We don't seem to need that after the Gutenberg switch, and it also raises some exceptions.
```
Uncaught exception 'Error' with message 'Class 'Shortcode_UI' not found' in /app/source/public/wp-content/themes/planet4-master-theme/classes/class-p4-master-site.php:645
```
=> Remove obsolete admin action

classes/class-p4-master-site.php
[JIRA 4389](https://jira.greenpeace.org/browse/PLANET-4389)
- Add “Credit” custom media metadata fields
-  Remove `action_page_media_buttons ` function as it's not in use anymore
- Add visibility to  `login_redirect`, `add_login_logo_url ` and `add_login_logo_url_title ` function
- Remove `post_gallery ` filter function (In Gutenberg editor, we don't have classic image Gallery feature)
- Remove `img_caption_shortcode`  filter, added new `p4_core_image_block_render` function to append image credit field with image caption on core/image Gutenberg block
=> PLANET-4389 Add “Credit” custom media metadata fields

assets/src/scss/base/_body.scss
We no longer need this, since we are creating separate builds for editor and frontend. This is making these styles less explicit and easier to override on child themes.
=> Remove wp-admin exclusion from body css

templates/blocks/author_profile.twig, templates/single.twig
This PR moves the conditional check if a author is set to the author_profile.
This way child-themes are able to easily override the author_profile and set their own logic.
GPNL wants to be able to set a default author block in some cases.
Moving the logic to the block itself instead of the single.twig makes sure we don't override too much unnecessarily.
=> Move conditional into author_profile

templates/single.twig
The class `.article-listing` was renamed in this PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/commit/89c21883121fa4044cdf22f70f72760aa681792f#diff-7e3188835fafb9e447ab7a0fe44be0a0R122
This renames an occurrence of it in the `master-theme`.
=> [No ticket number] Missing class rename fix

classes/class-p4-campaign-importer.php, exporter-helper.php
- Fix special char issue in campaign export/import functionality.
- The EN form background image not exported properly, added small fix in regular exp. to fix this issue.
Example :
Campaign exported from `staging` -
https://release.k8s.p4.greenpeace.org/international/campaign/campaign-page-demo-plastics/
Campaign imported on `sagardev` instance (current PR branch is pinned on sagardev instance) -
https://k8s.p4.greenpeace.org/sagardev/?post_type=campaign&p=27747&preview=true
The EN form bg image issue tested by exporting from sagardev instance and imported on staging.
https://k8s.p4.greenpeace.org/sagardev/campaign/test-en-form/
https://release.k8s.p4.greenpeace.org/international/?post_type=campaign&p=27806&preview=true
=> PLANET-4456 Fix special chars in campaign import

classes/class-p4-master-site.php
[JIRA 4510](https://jira.greenpeace.org/browse/PLANET-4510)
Fixed PHP notice -
`Notice: Undefined index: id in /app/source/public/wp-content/themes/planet4-master-theme/classes/class-p4-master-site.php on line 858`
=> PLANET-4510 Fix PHP notice

assets/src/scss/base/_body.scss
Removing this generic rule as it is too broad, if something comes up we'll deal with that case with something more specific.
Ref: https://jira.greenpeace.org/browse/PLANET-4454
=> PLANET-4454: Posts: Anchor link extends beyond the body column

classes/class-p4-search.php
Currently the field configuration of elasticpress is not used to
determine which fields to search in. No fields were passed causing it to
default to title, description and excerpt. I added these same fields
manually and also the author display name.
=> PLANET-4515 Specify search fields including author

classes/class-p4-activator.php
This enables them to change the author from the document sidebar. By
default wordpress doesn't require this permission, however the Wordfence
plugin adds a check on this.
This does mean that editors are able to access the `users` menu item and see (but not edit) users of all roles. I asked Gabor in the ticket if this is an issue for us.
=> PLANET-4429 Give `list_users` capability to editors

assets/src/scss/pages/search/_search.scss, templates/search.twig
This branch is based on: https://github.com/greenpeace/planet4-master-theme/pull/972
The task was to move the "Include Archive" switch below the button in mobile. 
Ref: https://jira.greenpeace.org/browse/PLANET-4595
=> PLANET-4595: Archive - Implement command to include archived content in search results (incl. mobile)

assets/src/scss/pages/post/_author-block.scss, templates/blocks/author_profile.twig
[JIRA 4157](https://jira.greenpeace.org/browse/PLANET-4157)
- The `wp_trim_words()` function is localized. For languages that count ‘words’ by the individual character (such as East Asian languages), the `num_words` argument will apply to the number of individual characters
- The `wp_is_mobile()` function is used to apply `author_bio_word_limit` as per device size
=> PLANET-4157 Fix author bio block readmore link

campaign_themes/antarctic.json, campaign_themes/arctic.json, campaign_themes/climate.json, campaign_themes/default.json, campaign_themes/forest.json, campaign_themes/oceans.json, campaign_themes/oil.json, campaign_themes/plastic.json, classes/class-p4-campaign-importer.php, classes/class-p4-post-campaign.php, single-campaign.php, templates/css-variables.twig, templates/html-header.twig
* Use `register_post_meta` to add campaign fields instead of cmb2. The
editor interface for these fields will be added to
planet4-plugin-gutenberg-blocks in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/190
* Move allowed values to json files. These are fetched by the frontend
to populate the values of the editor. Initially all files contain the
same values as were available for all templates in the code.
* Use a wrapper function `P4_Post_Campaign::campaign_field()` to add
these fields for convenience, as they all share some args.
* Create a list of CSS variables. Ultimately these should be used as
actual css variables, however as a first step use these in a twig
template that only adds the rule if a variable is set. This intermediary
step is because a bigger change …
=> PLANET-4603 Register campaign fields instead of metaboxes

classes/class-p4-post-campaign.php, single-campaign.php
... of post meta fields, which is not very well. This can definitely be
cleaned up later.
Context:
- When you create a new post there will be no entries in the db for the meta fields, until they are set.
- However when in the editor you use the API `dispatch( 'core/editor' ).editPost( { meta: { [ metaKey ]: value } } )`, wordpress will actually create a key for all registered meta fields, however it doesn't use the default value specified in `register_post_meta`. Instead the entries will have an empty value.
- So I moved all the defaults into the code where they are used, which is manageable as they're mostly used in a single place, but does involve a lot of checks.
=> PLANET-4603 Dealing with how WP deals with default values

classes/class-p4-post-campaign.php
* I thought it wasn't needed previous commit, but it is: with no selection
no css rule is added, which is not the same as choosing "campaign" that
only works if a css rule is set.
* Also compare campaign_logo_color against 'dark' so that 'light' is used
as default.
=> PLANET-4603 Readd campaign font map

assets/src/js/load_more.js, assets/src/js/search.js
Updates the lazy-loaded images when clicking "Load More" or scrolling to see more results.
=> [No issue]: Hotfix - Load More in search page

classes/class-p4-campaign-importer.php, classes/class-p4-post-campaign.php, classes/class-p4-settings.php
* Add configuration toggle for whether campaign styles should be
excluded on import.
* Move campaign fields to a constant so that it can be used in the
filter on import.
* Make sure that old `_campaign_page_template` is only used if the new
one isn't set.
ref. https://jira.greenpeace.org/browse/PLANET-4742
=> PLANET-4742 Provide option to exclude campaign style on import

assets/src/js/cookies.js, templates/cookies.twig
Ref: https://jira.greenpeace.org/browse/PLANET-4740
Styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/37
Blocks Plugin PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/215
Note: this also removes a vestigial animation, which made sense when the cookie bar was not fixed but not anymore.
=> PLANET-4740: CSS: Remove :not(#hidecookie) rule

README.md, author.php, classes/class-p4-campaign-exporter.php, classes/class-p4-campaigns.php, classes/class-p4-custom-taxonomy.php, classes/class-p4-master-site.php, classes/class-p4-post-campaign.php, classes/class-p4-post-report-controller.php, classes/class-p4-post.php, classes/class-p4-search.php, classes/class-p4-settings.php, composer.json, composer.lock, exporter-helper.php, exporter.php, page-templates/evergreen.php, page-templates/sitemap.php, page.php, partials/tags-box.php, phpcs.xml.dist, posts-report.php, search.php, single-campaign.php, single.php, tag.php, tests/bootstrap.php, tests/p4-testcase.php, tests/test-custom-permalinks.php, tests/test-p4-master-theme.php
Sync phpcs configuration with blocks-plugins,
Fix PHPCS errors
[JIRA 4626](https://jira.greenpeace.org/browse/PLANET-4626)
=> PLANET-4626 Update composer dev dependencies to match blocks-plugins,

classes/class-p4-campaign-importer.php, classes/class-p4-post-campaign.php, exporter.php
for certain post_meta keys of the attachment post type. Though a single
value is ever used, due to a bug multiple values are stored containing
mostly the same data. In some cases this was adding up to 70MB to the
size of the export XML.
https://jira.greenpeace.org/browse/PLANET-4773
=> PLANET-4773 Use single meta value instead of all

classes/class-p4-master-site.php
[JIRA](https://jira.greenpeace.org/browse/PLANET-4759)
- To fix spreadsheet search bar and column sorting issue, allowed HTML input tag in Post content
eg. https://k8s.p4.greenpeace.org/test-atlas/story/691/test-spreadsheet-block-on-post/
=> PLANET-4759 Fix spreadsheet block search bar, column sorting issue

classes/class-p4-post-campaign.php, single-campaign.php, templates/base.twig, templates/single-campaign.twig
This required me to change the permalink settings to "post name" instead of the custom structure, else campaigns with a parent would navigate to `/parent-slug/own-slug` but that page would give a 404. So if you run locally you will need to do that as well. For now that is probably breaking other aspects of the site, though I didn't run into them yet.
=> PLANET-4712 Multi page campaigns

templates/blocks/header.twig
The tags and share buttons were being shown under the top nav bar,
making them hardly visible and impossible to click.
Don't include these elements if the page title is hidden.
This is a temporary fix while we await the design of where the share
buttons should be if the page title is hidden.
=> PLANET-4741 Do not show tags/share buttons if title is hidden

classes/class-p4-loader.php, single-campaign.php
* Due to a bug in wordpress the autosave record gets created and deleted
many times when clicking preview without changes to revisioned
attributes. Add a filter so that the autosave record is only ever
deleted if the post is permanently deleted.
=> PLANET-3427 Prevent wordpress autosave recreation

campaign_themes/antarctic.json, campaign_themes/arctic.json, campaign_themes/climate.json, campaign_themes/default.json, campaign_themes/forest.json, campaign_themes/oceans.json, campaign_themes/oil.json, campaign_themes/plastic.json
UAT Passed.
This is just for setting the default font on the JSON files.
Ref: https://jira.greenpeace.org/browse/PLANET-4750
Blocks counterpart: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/230
=> PLANET-4750: Campaigns customiser - Adjust Header primary font options

classes/class-p4-master-site.php
The LazyLoading script was not loaded on the editor side so some calls to it were triggering a JS error.
Ref: https://jira.greenpeace.org/browse/PLANET-4845
=> PLANET-4845: JS Error: Unable to edit background image in pages

classes/class-p4-post-campaign.php
Restoring the body font logic and replacing a call to `wp_safe_remote_get` to `file_get_contents`.
=> Hotfix: Restore old body font logic in a method.

assets/src/scss/pages/_page.scss
This just adjusts the base font size for the `.page-template` class (present in pages and campaigns) in XL screens.
=> [No issue]: Font size for XL screens in pages.

templates/blocks/author_profile.twig
- Only shorten and add 'read more' to author bio if it's too long
- Trying to find strpos at an offset greater than the string threw an error.
Ref: https://jira.greenpeace.org/browse/PLANET-4779
=> PLANET-4779 Planet 4 Bug Report: Author bio: Not visible on Post

assets/src/js/search.js, classes/class-p4-elasticsearch.php, classes/class-p4-loader.php, classes/class-p4-master-site.php, classes/class-p4-post-archive.php, classes/class-p4-search.php, classes/class-p4-settings.php, functions.php, templates/search.twig, templates/tease-search.twig
NOTE TO REVIEWER:
This is a pretty big PR, but most of the changes are in `classes/class-p4-search.php`. I suggest first going through the other files, as those are easier to understand in isolation, and then proceed to `classes/class-p4-search.php`.
I removed the caching of search results, as that was mainly for reducing the footprint of loading all results in memory, which is not needed anymore as aggregations are used instead of looping through all posts to get the totals data.
* Add custom post type for archive.
* Setup search for that post type.
* Make decay params configurable (mainly for making it easier to find good values for these during development, but maybe we can preserve these for NROs to configure).
* Add settings for including archived content for logged in users only,
or …
=> PLANET-4827 Archive as a post type

assets/src/scss/pages/_404.scss, assets/src/scss/pages/_evergreen.scss, assets/src/scss/pages/post/_comments-block.scss, assets/src/scss/pages/post/_post.scss, assets/src/scss/pages/search/_filter-modal.scss, assets/src/scss/pages/search/_filter-sidebar.scss, assets/src/scss/pages/search/_search-bar.scss, campaign_themes/antarctic.json, campaign_themes/arctic.json, campaign_themes/climate.json, campaign_themes/forest.json, campaign_themes/oceans.json, campaign_themes/oil.json, campaign_themes/plastic.json
Note: this is based on PLANET-4919, since the names of the color values in the JSON files changed.
UAT Passed.
Ref: https://jira.greenpeace.org/browse/PLANET-4887
Blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/252
Styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/45
=> PLANET-4887: Text that is #000000 should be #1A1A1A

classes/class-p4-elasticsearch.php, classes/class-p4-search.php, templates/tease-search.twig
* Put the document type filter on all queries, by making it an OR query:
either the post type is something else than attachment, or the mime type
is one of the supported types. Remove previous filters that were in
multiple places as the new filter can be used on any result set.
* Don't show numbers lower than 0 for calculated page amount. We
subtract the Act pages from this as they have their own metric, however
in some cases the counts are not reliable and we might end up below 0.
Probably we want to replace this calculation with an aggregation that
already subtracts the Act pages.
=> PLANET-4975 Fix document type filtering and page count

templates/blocks/author_profile.twig
- Reduced the char limit for the author bio block to 180 for all screens
Ref: https://jira.greenpeace.org/browse/PLANET-4723
=> PLANET-4723 Author bio block is missing "Read more" link when too long - broken for M screens

assets/src/js/search.js, classes/class-p4-master-site.php, classes/class-p4-search.php, templates/tease-search.twig
Changed the `button` tag for post type into an `a` tag in the Search page.
While doing this, I found a weird thing about the `search.js` script, it was triggering a 404 locally. It looks like it's loaded from the search class here: https://github.com/greenpeace/planet4-master-theme/blob/master/classes/class-p4-search.php#L1097 (which actually does nothing, because the `setupSearch` function is never invoked) but also built in: https://github.com/greenpeace/planet4-master-theme/blob/master/assets/src/js/app.js
So I removed the script being loaded from the Search class, and moved the `localizations` variables to the place where we enqueue `index.js`, the main script.
=> PLANET-4937: Search results post type should use an a tag instead of a button that behaves like an a tag

classes/class-p4-search.php
* If you don't it will default to 'post-thumbnail', which interestingly
is a size that does not exist by default, only 'thumb' and 'thumbnail'
do. 'post-thumbnail' exists only after `set_post_thumbnail_size` is
called. Since WordPress can't map it to a size when calling
`get_the_post_thumbnail_url`, the thumbnail was using the full size by
default.
=> PLANET-5048 Explicitly pass thumbnail size

classes/class-p4-master-site.php
* Else they will be stripped by `kses`. This is a temporary solution as
clearly we don't want to have to add each variable we want to use here
as well. Perhaps we should not be stripping attributes that were not
added by the user somehow?
=> PLANET-5037 Add css variable to allow properties

classes/class-p4-elasticsearch.php
* Since the `??` operator is right-associative, this fallback was not
working as intended without parentheses. Because the functions (left
hand of `??`) are already there in all cases, the custom weighting on
the right hand was never used.
=> PLANET-4955 Fix ES custom weighting not being applied.

classes/class-p4-campaign-importer.php
[JIRA 4774](https://jira.greenpeace.org/browse/PLANET-4774)
- The [WP-Importer](https://wordpress.org/plugins/wordpress-importer/) plugin has a bug, if post already exists, it skip the post from import but [imports post_meta data](https://github.com/WordPress/wordpress-importer/blob/master/src/class-wp-import.php#L898).
Fix - 
- Added a `wp_import_post_meta` filter to skip duplicate post_meta from import.
=> PLANET-4774 Campaign Import - Skip duplicate post_meta import

assets/src/js/pdf_icon.js
- Changed pdf_icon.js to apply icon link class if .pdf appears anywhere in link, as opposed to only at the end
=> PLANET-4926 PDF icon not shown in CTA when URL includes GA UTM code

classes/class-p4-elasticsearch.php
see https://jira.greenpeace.org/browse/PLANET-5032
* There is already a WP filter in `class-p4-search.php` that adds the
same ES filter. Moreover, the removed one added it on `post_type`
instead of `post_type.raw`. This caused page filter to break if the
ElasticPress language is something else than English. No idea why it did work for English.
=> PLANET-5032 Remove duplicate ES filter on post type

classes/class-p4-settings.php
Ref: https://jira.greenpeace.org/browse/PLANET-2209
Added a success notification message after saving P4 settings.
Go to `/wp-admin` Settings > Planet4, and save the form.  
If no problem occurs, a message "Settings saved." appears, as it does in Settings > General.
I followed the same method used in [General Settings code](https://github.com/WordPress/WordPress/blob/57fb3c6cf016678ab38d7a636b8df41fa2d955f1/wp-admin/options.php#L313), and put it in an [after_save](https://github.com/CMB2/CMB2/blob/af56b9eb227a3db9694510ca21bf9e9058e640f0/includes/CMB2.php#L854) hook of CMB2. Also parameterized the ID of the metabox, so that the hook doesn't break if we change it. I need somebody to tell me how wrong I am 😨 
I have used the domain `planet4-master-theme-backend` for the string `Settings …
=> PLANET-2209 Add success notification on P4 settings saved

assets/src/scss/pages/search/_search-results.scss
See https://jira.greenpeace.org/browse/PLANET-5034
According to [w3schools](https://www.w3schools.com/cssref/css3_pr_word-break.asp) the description for `keep-all` value is `Word breaks should not be used for Chinese/Japanese/Korean (CJK) text. Non-CJK text behavior is the same as value "normal"`
=> PLANET-5034 Fix Japanese search results button label overflow

assets/src/js/external_links.js
For external links we usually show an svg icon, but for the Take Action card (https://jira.greenpeace.org/browse/PLANET-5060) and for the Take Action boxout (https://jira.greenpeace.org/browse/PLANET-5126) it doesn't fit the design.
Also, we usually open external links in a new tab, but Take Action cards always open in the same page, and for the Take Action boxouts it's a setting (open in new tab or not) that is taken care of in this file.
=> PLANET-5060 Remove external links features for Take Action card links

templates/tease-search.twig
In https://github.com/greenpeace/planet4-master-theme/pull/1107 we made it already populate the link before the template, so we can use that instead.
=> PLANET-5145 Get p4 post type link from attribute in template

classes/class-p4-master-site.php, tests/test-p4-master-site.php
Ref: https://jira.greenpeace.org/browse/PLANET-5128
Wordpress 5.5 will add the `loading` attribute for all images by default. We will have to check if this does not break our own implementation on browsers that support it (and see if we want to migrate to it ? Browser support might not be good enough).
- Implementation in browsers: https://caniuse.com/#feat=loading-lazy-attr
- Announcement: https://make.wordpress.org/core/2020/01/29/lazy-loading-images-in-wordpress-core/
- Changes on `core`: https://core.trac.wordpress.org/changeset/47554
The approach I took follows function [`wp_make_content_images_responsive`](https://github.com/WordPress/WordPress/blob/5.4-branch/wp-includes/media.php#L1490) that adds `srcset` and `sizes` attributes to all wp images in content. This `scrset` attribute …
=> PLANET-5128: Expand images lazy-loading on Image block

templates/tease-search.twig
[Jira issue](https://jira.greenpeace.org/browse/PLANET-5057) 
While the generated excerpt is 30 words, and everywhere else in the app we show 30 words, in the search we were limiting it via twig to 25 words. This change raises the twig limit to the standard 30 words
=> PLANET-5057 . Make search excerpt to be 30 words as documented

classes/class-p4-master-site.php
This lib wasn't available on cdnjs when we included it. It was just recently added to cdnjs. So this a small change, just to avoid resolving/requesting one more domain and instead use the same CDN as the rest of the frontend libraries.
=> Switch css-vars-ponyfill CDN to cdnjs

classes/class-p4-campaign-exporter.php, classes/class-p4-campaign-importer.php, classes/class-p4-campaigns.php, classes/class-p4-control-panel.php, classes/class-p4-cookies.php, classes/class-p4-custom-taxonomy.php, classes/class-p4-dev-report.php, classes/class-p4-elasticsearch.php, classes/class-p4-image-compression.php, classes/class-p4-post-campaign.php, classes/class-p4-post-report-controller.php, classes/class-p4-post.php, classes/class-p4-search.php, classes/class-p4-settings.php, classes/class-p4-sitemap.php, classes/class-p4-taxonomy-campaign.php, classes/class-p4-user.php
Ref: https://jira.greenpeace.org/browse/PLANET-5099
Deployed on test instance, though it fails when trying to run the `01-run-p4-activator.sh`: https://circleci.com/gh/greenpeace/planet4-test-uranus/90
This doesn't seem related to the changes in this PR though, as running the test instance with `master` of master-theme and otherwise the same setup runs into the same error.
https://circleci.com/gh/greenpeace/planet4-test-uranus/94
Not sure what's going on over there, it is looking for the class in `classes/class-p4mt\p4-activator.php`, even though the `p4mt` string is only present in `@package` annotations in our code.
=> PLANET-5099 Remove class_exists_checks

author.php, category.php, classes/class-p4-loader.php, classes/class-p4-master-site.php, single-campaign.php, single.php, taxonomy.php, tests/test-p4-master-theme.php
Ref: https://jira.greenpeace.org/browse/PLANET-5099
So that we don't miss any when changing file names/structure.
Tested here: https://github.com/greenpeace/planet4-test-uranus/blob/6e76e4316e8f34f751a1b2013c6b518348fedaf8/composer-local.json
=> PLANET-5099 Use ::class references instead of strings

classes/class-p4-activator.php, classes/class-p4-campaigner.php, classes/class-p4-loader.php
* The usage of `wp eval` in planet4-docker-compose makes it hard to
provide backwards compatibility for P4_Activator when we move to psr-4,
so provide a WP CLI command instead.
PR for the post deploy task in base-fork: https://github.com/greenpeace/planet4-master-theme/pull/1125
Also cleaned up role registration a bit: 
* There were 2 separate calls outside of the functions per role which also added some capabilities, while there was no reason for them to be separate so I added them with the rest.
* Create a map with all roles and their capabilities, which is less noisy to watch than a `add_cap` call inside of separate functions + mandatory docblock ...
* Made functions static so we don't need to create pointless instances.
Deployed here …
=> PLANET-5099 Add a command as alternative for eval

assets/src/js/enhancedDonateButton.js
The button was being cloned multiple times, this to ensure we only clone it if it's not already there.
Ref: https://jira.greenpeace.org/browse/PLANET-5203?
=> PLANET-5203: Enhanced mobile donate button causing a few problems

classes/class-p4-campaigns.php, classes/class-p4-control-panel.php, classes/class-p4-loader.php, classes/class-p4-master-site.php, classes/class-p4-post-campaign.php, classes/class-p4-post-report-controller.php
Ref: https://jira.greenpeace.org/browse/PLANET-5186
Linked: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/302
Script version is not automatically updated when we make changes, which leads to cache problems if we forget it.
Switch enqueue/register scripts from hardcoded version to `filectime`.
Versions were found with regex `[0-9]{1,2}\.[0-9]{1,2}`, and by looking at `wp_enqueue_style` and `wp_enqueue_script` usage.
_I didn't write a specific larger function for this, because at this point I would prefer to create a new class that could be used in other repos and would have the paths needed and version function for each equivalent wordpress enqueue/register functions; and I'm not doing that because we currently are in a namespace refactoring + another large …
=> PLANET-5186: Switch script version to filectime

classes/class-p4-master-site.php
Ref: https://jira.greenpeace.org/browse/PLANET-4818
PoC for a single informative message from Planet4 team on the dashboard.
The ticket didn't say too much about specific functionalities, so this was extrapolated.
The message:
- is in HTML format
- is integrated by a developer  
- appears only on the dashboard
- is dismissible, at a user level
- once dismissed, doesn't reappear until a new release is pushed
and:
- only one Planet4 message can appear at the same time
- Fetching a message from a document
We could think about fetching the message from a distant document, it raises the problems of formatting and control of that document.
- Adding a permanent widget, with a Planet4 newsfeed
This would require a newsfeed; I don't know if the widget would always appear on top, I think the user …
=> PLANET-4818: PoC for a dashboard P4 message

assets/src/scss/bootstrap-build.scss
Ref: https://jira.greenpeace.org/browse/PLANET-4536
This is pretty straightforward, just removing parts of Bootstrap we are not using. 
Actually not removing, just commenting them out to keep a reference of what a complete build looks like in case we do want to use any of that in the future.
The Backstop tests look good: 
https://193-238904235-gh.circle-artifacts.com/0/app/backstop_data/html_report/index.html
Test instance here:
https://k8s.p4.greenpeace.org/test-mars/
=> PLANET-4536: Perf: Reduce unused dependencies from bootstrap in code

assets/src/scss/pages/post/_article-content.scss
These font sizes are overriding the consistent typography rules newly introduced with https://jira.greenpeace.org/browse/PLANET-5080, so they need to be removed. Otherwise, we get font inconsistencies (for example lists having bigger font size than paragraphs in the handbook).
=> Fix typography in article content

templates/blocks/header.twig, templates/single.twig
Related to [JIRA 5201](https://jira.greenpeace.org/browse/PLANET-5201)
Task -
- Add data attributes on page/post header taxonomy(category and tags) and CTA button element as per JIRA ticket details.
Testing -
- Check the page/post header category, tags and CTA button html element for analytics data attributes values.
- The changes are pinned on [test-venus](https://k8s.p4.greenpeace.org/test-venus/) instance for testing.
=> PLANET-5201 Add data attributes on page header

functions.php, src/Settings.php
* That way we're sure it's loaded and doesn't depend on the autoloader
loading the Settings class.
Sentry error: https://sentry.greenpeace.org/greenpeace/planet4/issues/1624/?query=is%3Aunresolved
ref: https://jira.greenpeace.org/browse/PLANET-5099
=> PLANET-5099 Move function to functions

TESTING.md
A few fixes on documentation:
- Specified how to run tests _in a container_, as running it on a machine would imply listing many dependencies.
- Specified svn installation, it is not in php-fpm container natively. Another solution would be to add subversion to the container repo.
- Specified a mysql user `root` able to create a database, user `planet4` is not allowed to do that.
Any reason why we are sticking to PHPUnit 6 ?
=> Fix test documentation

exporter-helper.php, functions.php, src/Search.php
While I was debugging why my previous suggested solution didn't work, I stumbled on this other filter that allows us to exclude unwanted attachments from the list of ids that ElasticPress will sync, before it starts looping through these. The benefit is that way it will also show correct numbers in the UI and can prevent issues caused by the number not corresponding to the actual posts being synced.
Unfortunately this was not solvable by adding more args, as WP query args don't support the kind of complex or condition we need (either not post_type attachment or having one of the wanted mime types), so instead I had to first fetch all unwanted ids. It needs to be done with raw SQL, as regular query with args was not returning attachments with no post_parent.
The additional query shouldn't …
=> PLANET-4987 Exclude unwanted attachments from EP

single.php
Ref: https://jira.greenpeace.org/browse/PLANET-5306
> According to the single post template, the post type should be displayed with tags before the post title; it doesn't appear anymore
The fix is just an `array_map( 'reset', array )` changed to a more fitting `reset( array )`.  In the best case, `get_the_terms()` returns `WP_Term[]`, and according to the [previous version](https://github.com/greenpeace/planet4-master-theme/blame/a678ed1ce57368d170d8d14f14bf61a4acf706ad/single.php#L46) of the code, we are just using the first one of the terms given.
The problem occurs on single post pages; display any post that has a post type, you should get something like this :
_Post type is not displayed, and notices are generated by PHP in dev mode._
_Post type PRESS RELEASE is displayed, no notice …
=> PLANET-5306: Display post type above post title

phpcs.xml.dist, src/Activator.php, src/AnalyticsValues.php, src/CampaignExporter.php, src/CampaignImporter.php, src/Campaigner.php, src/Campaigns.php, src/Context.php, src/ControlPanel.php, src/Cookies.php, src/CustomTaxonomy.php, src/DevReport.php, src/ElasticSearch.php, src/ImageCompression.php, src/Loader.php, src/MasterSite.php, src/MetaboxRegister.php, src/Post.php, src/PostArchive.php, src/PostCampaign.php, src/PostReportController.php, src/Search.php, src/Settings.php, src/Sitemap.php, src/Smartsheet.php, src/SmartsheetClient.php, src/TaxonomyCampaign.php, src/User.php
* Exclude file comment rule for all files in /src, as all of them are
classes which already have a comment before the declaration. The file
comment also required an `@package` tag, which is redundant if the class
is in a namespace.
* Remove file comment from all classes.
* Import namespace Timber instead of the User class in that namespace so
we don't need to add an alias.
=> Refactor: remove file comment in /src/*

src/MasterSite.php, src/Settings.php, tests/test-p4-master-site.php
Ref.
[JIRA 5142](https://jira.greenpeace.org/browse/PLANET-5142)
https://developers.cloudflare.com/images/responsive
- Add a twig filter which returns cloudflare ready(cloudflare optimized) image url
- Add P4 setting to toggle the cloudflare image url functionality
- Option added in P4 setting to try different `options` values from [cloudflare](https://developers.cloudflare.com/images/about) (`https://zone/cdn-cgi/image/options/source-image`) [This field is intended for testing purpose only, we will remove it once finish with testing]
Related PR: [#321](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/321)
=> PLANET-5142 Add Cloudflare's Image Optimization url twig filter(cf_img_url)

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5319
Sentry: https://sentry.greenpeace.org/greenpeace/planet4/issues/1665/
This bug currently blocks the edition of the homepage on GP Denmark.
> Argument 1 passed to P4\MasterTheme\MasterSite::P4\MasterTheme\{closure}() must be of the type string, null given
Fixes an error generated when one of the parameters used by the filter `cf_img_url` is null.  
I couldn't reproduce the bug naturally, it seems to happen on a particular state on the carousel that I can't create through the editor.
The fix allows for null values in the twig filter and handle them by returning them right away.
**To reproduce the bug**, I edited [`wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/blocks/class-carouselheader.php#L131`](https://github.com/greenpeace/ …
=> PLANET-5319: Fix cf_img_url error on image srcset null

src/DevReport.php, src/Settings.php
Group the Planet4 settings into groups.
Note: The page that had nothing to do with the settings (dev report), has not been touched. The links here are just links towards the existing pages
Edit: Removed the media library and planet4-dev-report links (There is MR on the media library plugin directly but it should be merged AFTER this one)
Note2: The Media library MR has to be merged AFTER this has gone to production
=> PLANET4-5222 P4 settings grouped and divided to subpages

src/DevReport.php, src/Settings.php
We roll back this feature yesterday, because it resulted in options being blank at the backend (see screenshot below). I re-picked the initial commits and added one more just to preserve the original options key and use a new slug variable to make sure the menu opens in the first subpage.
=> PLANET-5222 P4 settings grouped and divided to subpages

templates/base.twig
When converting some blocks to WYSIWYG, for example the Articles block, we need to have the post type easily accessible in the frontend. Therefore it makes sense to add it as a data-attribute on the body element 🙂
=> PLANET-4801 Add post-type data-attribute to body element

functions.php
Previously planet4-base-fork ran the Activator class by running `wp
eval` with an instantiation of the old class name. We added a command
inside WP instead to avoid eval, but if anyone has a localdev setup with
the old version of base-fork still running this command, it will cause
localdev to break in a confusing way, taking a lot of people's time
debugging it. We can easily still make it work by moving the aliases to
before the first usage of any of the classes.
=> Load aliases before using a class

src/Loader.php, src/MetaboxRegister.php
Ref: https://jira.greenpeace.org/browse/PLANET-4808
Related to: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/358
Doc: https://github.com/CMB2/CMB2/wiki/REST-API#registered-rest-fields
In order to get full functionalities for the [WYSIWYG version of the Split Two Columns block](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/358), I need those fields to appear in the rest api response giving a list of pages.  
The loading of MetaboxRegister is based on `wp_is_json_request()`, which needs a header `Http-Accept` or `Content-Type` with `application/json` if you want to test this. 
I also tried to base this solution on the constant `REST_REQUEST`, but it is defined far too late in the process.
Request a list of pages from the rest api.
```console
> curl …
```
=> PLANET-4808: Display of cmb2 fields in rest api response

src/Activator.php, src/Exception/MigrationFailed.php, src/Migration.php, src/MigrationLog.php, src/Migrations/M001EnableEnFormFeature.php, src/Migrations/MigrationRecord.php, src/Migrator.php
* MigrationRecord holds the data of a particular run of a migration
script.
* Move migration logic into it's own class.
* Throw a specific exception.
=> PLANET-5292 create record, move to separate class

assets/src/js/external_links.js
Excludes links that contain href="javascript:[...]" from being treated as external links.
Fixes greenpeace/planet4#78
=> PLANET-5444 Add exception in external links script

src/Exception/SqlInIsEmpty.php, src/Search.php, src/SqlParameters.php, tests/SqlParameters.php
* Sql query parameters need to be be passed separately to $wpdb->prepare
and the values need to be in the same order as the placeholders in the
query. This makes the code hard to read and prone to bugs if a mistake
in the position is made. The class introduced here solves this problem
by allowing to specify these values in the query, where it will echo
back a placeholder and keep track of all values in the order they were
passed in. This ensure that the order will be the same, and that the
values can be seen in the position they will be used.
=> Class to facilitate parameterized queries

assets/src/scss/bootstrap-build.scss
* These were removed, but turns out that they're needed anyway in a few
places.
We may want to check the other parts to in a later PR, this one just re-adds the ones which we know already are needed.
Ref: https://jira.greenpeace.org/browse/PLANET-5363, also fixes https://jira.greenpeace.org/browse/PLANET-5475
@comzeradd `_cards.scss` is indeed used by the columns block, though at first glance it looks like it's barely actually using it. Most of the rules of those classes are overridden. Probably best for now to re-add it, but maybe afterwards we can add those few rules it does use to our css and drop the dependency.
Test instance:
- search page: https://k8s.p4.greenpeace.org/test-mars/?s=test&orderby=_score
- page with a columns task style block (accordion only on mobile): …
=> PLANET-5363 Re-add bootstrap card and transitions

.circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5275
Ref: https://github.com/greenpeace/planet4/issues/73
Requires: https://github.com/greenpeace/planet4-base-fork/pull/91 (pa11y configuration)  
Requires: https://github.com/greenpeace/planet4-docker-compose/pull/52 (targets for pa11y installation and run)
A report generated by circle-ci is visible there https://9211-80401279-gh.circle-artifacts.com/0/planet4-docker-compose/artifacts/pa11y/index.html
=> PLANET-5275: Running accessibility report with pa11y

src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-5515
Deployed on my test instance. eg. https://k8s.p4.greenpeace.org/nikosdev/?s=blahblah&orderby=_score
The above page returns 0 zero results, with the normal search template. But the http status header is `404`.
This can be tested putting that url at [httpstatus](https://httpstatus.io/) or looking at web console.
=> PLANET-5515 When 0 search results set 204 http header

.circleci/config.yml, composer.json
Ref: https://jira.greenpeace.org/browse/PLANET-5484
=> Planet 5484 create zip on tag

src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-5526
- Revert of https://github.com/greenpeace/planet4-master-theme/pull/1183  
Code `204` seem to block any content, returning an empty page (it does so locally and in production)
- Call `wp_no_robots()` to add relevant meta tag
It adds a meta tag `robots` with `noindex,follow`. Search engines will [concatenate multiple directives](https://webmasters.googleblog.com/2007/03/using-robots-meta-tag.html) and follow the most restrictive directive if some are conflicting.
There were other possible solutions:
- Add condition to template `html-header.twig` to replace the existing meta robots there.
- Add an http header `X-Robot-Tag` with the same content.
For a search giving 0 result (page `/?s=averyuniquesearch` for example), an html tag `<meta …
=> PLANET-5526: Add noindex meta tag for no results search page

.circleci/config.yml
* It's not counting for Github anyway, and we know it will fail each
time. So making it pass each time allows us to see whether the other
jobs have passed in the GitHub UI (PRs, next to commits, the icon of the browser tab...).
=> Pass test regardless of result

templates/html-header.twig
Ref: https://jira.greenpeace.org/browse/PLANET-5563
* The fonts were loaded to late, causing the browser to not render text
until the files are loaded. To mitigate this adds a preload tag for
these fonts, which makes them more likely to be loaded in time.
* Add the fonts in the head so they're next to the preload tag.
* Add `&display=swap` to the fonts url, which will cause the browser to
render the text with a local font while the url is not yet loaded.
Deployed on cidev instance. 
https://www.greenpeace.org/cidev/publication/260/mauris-quis-dictum-magna/
related styleguide PR to remove font loading from files:
https://github.com/greenpeace/planet4-styleguide/pull/77
=> PLANET-5563 Preload fonts and set swap display

src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-5515
Ref: https://jira.greenpeace.org/browse/PLANET-5526
Demo for custom header added to a search page with no result.  
It is live on [rhea](https://k8s.p4.greenpeace.org/test-rhea/)
```sh
$> curl -IXGET "https://k8s.p4.greenpeace.org/test-rhea/?s=averyuniquetitle" 
HTTP/2 200 
content-type: text/html; charset=UTF-8
date: Thu, 08 Oct 2020 12:05:02 GMT
link: <https://k8s.p4.greenpeace.org/test-rhea/wp-json/>; rel="https://api.w.org/"
p4-search: no-results
server: openresty
set-cookie: wordpress_google_apps_login=d114e606af1acbb3dd77e5245929e4bd; path=/; secure; HttpOnly
vary: Accept-Encoding
vary: Accept-Encoding
x-cache: BYPASS
x-cache-2: BYPASS
x-content-type-options: nosniff
x-elasticpress-query: true
x-frame-options: SAMEORIGIN …
```
=> Custom header on search with no result

templates/single.twig, templates/tease-taxonomy-post.twig
[JIRA 5373](https://jira.greenpeace.org/browse/PLANET-5373)
Related PR: [#403](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/403)
=> PLANET-5373 Remove the "by" string in post details page and taxonomy details page

.circleci/config.yml
* Due to an issue the assets are not building for the tag. This is a
quick fix to allow tests to pass again while we further check the issue.
=> Manually specify master for other repo

author.php, templates/blocks/author_profile.twig
Rel. to [JIRA 5388](https://jira.greenpeace.org/browse/PLANET-5516)
- Fix author bio translation on Post
- Fix author page meta data & social share button which were showing english author bio on non english author page
eg. https://k8s.p4.greenpeace.org/test-nix/fr/story/43917/quest-ce-que-le-lorem-ipsum-fr/
=> PLANET-5388 Fix author bio translation on Post and Author page

single.php
[JIRA 5388](https://jira.greenpeace.org/browse/PLANET-5388)
- Pass post tags and categories in articles block attributes.
These changes are part of [PR #412](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/412)
=> PLANET-5388 PLANET-5388 Fix related articles issue on Post

src/Cookies.php
* This filter is needed to prevent the cookie from being set anywhere
but the login page. If you don't add the filter then the cookie is
always set.
* The checks were in place to prevent other things from setting cookies.
Those things are not there anymore, so we don't need the checks.
Ref: https://jira.greenpeace.org/browse/PLANET-5605
deployed on https://k8s.p4.greenpeace.org/test-iocaste/
=> Always add apps login filter

assets/src/scss/pages/search/_filter-sidebar.scss, assets/src/scss/pages/search/_search-bar.scss, src/MasterSite.php, src/Search.php, templates/author.twig, templates/blocks/header.twig, templates/cookies.twig, templates/search.twig, templates/taxonomy.twig, templates/tease-search.twig
See https://jira.greenpeace.org/browse/PLANET-5501
In order to follow the new "capitalized" buttons, we need to update some default texts:
- Donate button default text: from `DONATE` to `Donate`
- Cookies button text: from `GOT IT!` to `Got it!`
- Search "load more" button text: from `SHOW %s MORE RESULTS` to `Show %s more results`
I also did a bit of clean up:
- Remove `btn-medium` class as it just duplicates the "regular" button styles
- Remove `source_selection` and `btn-secondary` from search bar (no longer relevant)
- [styleguide](https://github.com/greenpeace/planet4-styleguide/pull/80)
- [gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/413)
=> Planet 5501 - Consistent styles for buttons

.circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5221
Allow acceptance tests (and a11y tests) to run on forks.
This involved the following changes:
- Remove `org-global` context 
- Remove `activate-gcloud-account.sh`, which depended on the context and was needed only for `make`
- Replace `make` with `make ci`, as `make` pushes the images for which the gcloud account activation is needed, but these images are only used in the job itself, we don't need to push them
- Create a local `contrib` branch after checking out forks. A branch with the same name exists on the repo itself. Composer checks the branches on our GitHub repo, if the branch exists only in the local repository, then composer fails because it doesn't check there. However in the end composer will still use the local branch if it …
=> PLANET-5221 Checkout code for forks, instead of composer

admin/css/picker.css, assets/src/js/Components/ArchivePicker.js, assets/src/js/Components/archivePicker/ArchivePickerList.js, assets/src/js/Components/archivePicker/MultiSidebar.js, assets/src/js/Components/archivePicker/SingleSidebar.js, src/ImageArchive/UiIntegration.php
See https://jira.greenpeace.org/browse/PLANET-5481
You can see the improved UI version [here](https://www-dev.greenpeace.org/test-iocaste/wp-admin/admin.php?page=gpi-image-picker)!
=> Planet 5481 - Improve Image Archive UI

templates/base.twig
* Similarly to how .skip-links was already set up, we can add the
backtop markup here and hide it. That way it's already directly under
the body, and we don't need to dynamically append it. Since the click
handler is very short we can directly include it here for simplicity.
=> PLANET-4811 Add backtop markup to base template

assets/src/scss/pages/search/_filter-sidebar.scss, assets/src/scss/pages/search/_search-bar.scss
See https://jira.greenpeace.org/browse/PLANET-5606
In addition to centering the icons, in the comments of the ticket there was also a request to add a 4px margin between the icons and the text.
- Broken version: go to [this page](https://www-dev.greenpeace.org/test-jupiter/?s=&orderby=_score) and check the alignment of the icons in the search button and in the filters button (mobile & tablet only)
- Fixed version: go to [this page](https://www-dev.greenpeace.org/test-phoebe/?s=&orderby=_score) and check the alignment of the icons in the search button and in the filters button (mobile & tablet only)
**Note**: on tablets for the search button we need to remove the 4px margin, because otherwise the button is not wide enough and spreads onto 2 lines
=> PLANET-5606 Center search buttons svg icons

templates/blocks/meta_fields.twig
[JIRA 5660](https://jira.greenpeace.org/browse/PLANET-5660)
The URL encoding function was added on twitter card title during fixing the [PLANET-5441 ](https://jira.greenpeace.org/browse/PLANET-5441)ticket, but it breaks the twitter cards view and display encoded text as it is.
=> PLANET-5660 Revert twitter card title url encoding

src/MasterSite.php
[JIRA 5460](https://jira.greenpeace.org/browse/PLANET-5460)
The branch is pin on [planet-test-nix](https://www-dev.greenpeace.org/test-nix/wp-admin/post-new.php?post_type=page) test instance for testing.
=> PLANET-5460 Disable Wordpress(wp5.5) Blocks Directory feature

admin/css/login.css
When updating the button styles to make them more consistent with [PLANET-5501](https://jira.greenpeace.org/browse/PLANET-5501) and then [PLANET-5644](https://jira.greenpeace.org/browse/PLANET-5644), we forgot this button in the admin login page 😬 I've also added hover and active styles.
=> No ticket - Update admin login button styles

functions.php
Ref: https://jira.greenpeace.org/browse/PLANET-5619
* Remove any actions that would trigger a full purge.
* Remove settings page. 1) from the menu 2) because removing from menu
still leaves the page accessible, add a function to the same action with
a higher priority.
Deploying it now on a test instances without the CF plugin first as we'll probably do that for prod too.
I'm currently verifying if the plugin will function correctly by just putting the right credentials into `wp_options` (likely it will).
=> PLANET-5619 Restrict CF plugin

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5503
* Hammer is only used by a block which also performs this enqueue. (We do need to check if none of the NRO code relies on it being there.)
* Slick is added as a dependency by the blocks plugin, but the only usage it has is currently not working. So we can remove both CSS and JS files of it until we have fixed the usage. We need to merge https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/434 first for that, to remove the dependency. (currently causes failing tests anyway)
=> PLANET-5503 Remove hammer and slick CSS and JS resources

.stylelintrc
Forgot to include this in the previous PR, like in the blocks plugin https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/410/files#diff-a3f38f2cae79a3819f93ff1a9d4cd281cbe8f95696e14a29864f08796d3dc568R67
=> Add custom selector config

templates/google-fonts.twig, templates/html-header.twig
Quick win is to combine both requests, which should produce the same result.
~~I'm still sorting out whether we need the `?subset=latin-ext` query parameter, which was only on one of the two fonts.~~ It's ignored for most browsers, they get all subsets anyway as they're able to figure out which one they need to fetch. But for browsers without that capability it is still needed, Google fonts then will only serve the subset. see https://github.com/google/fonts/issues/113
=> Combine g fonts

src/MasterSite.php
[JIRA 5055](https://jira.greenpeace.org/browse/PLANET-5055)
The [ElasticPress v3.5](https://github.com/10up/ElasticPress/releases) version includes a revamp of the search algorithm, which probably breaks the backwards compatibility. 
After discussion with @Inwerpsel , we agree on to pin the EP search algorithm to older version (v3.4) and we will test & evaluate the new algorithm changes in separate ticket.
Related PR # [102](https://github.com/greenpeace/planet4-base-fork/pull/102)
=> PLANET-5055 Pinned the ElasticPress Search algorithm to v3.4

assets/src/scss/pages/search/_search-results.scss, templates/tease-search.twig
Ref: https://jira.greenpeace.org/browse/PLANET-5585
Ref: https://jira.greenpeace.org/browse/PLANET-4374
> Background images for Take Action pages on search results are pixelated and make the text hard to read
This PR makes the actions in a search result look like the other results.  
It also fixes general search results layout.
- Suppression of some exception rules and markup specific to action results.  
- Added a margin-top to the button so it's not stuck under the text.
- Fixed some margins, paddings, width and markup so that it fits the layout given in https://jira.greenpeace.org/browse/PLANET-4374
- Run a search on Content type `Action` : https://www-dev.greenpeace.org/test-uranus/?s=&orderby=_score&f[ctype][Action]=0
- Results should fit [the …
=> PLANET-5585: Normalize action search results appearance with other results

src/Loader.php
The Cloudflare plugin uses this key from the db. We'll put it in wp-config during deploy (https://github.com/greenpeace/planet4-builder/pull/62 https://github.com/greenpeace/planet4-helm-wordpress/pull/13/files), so that it can be put into the db in a post deploy script (https://github.com/greenpeace/planet4-base-fork/pull/104/files) which uses the command introduced in this PR.
=> PLANET-5619 Command to update CF key from config

assets/src/js/external_links.js, assets/src/scss/pages/post/_article-content.scss
See https://jira.greenpeace.org/browse/PLANET-5325
- **Remove external link markup**: we don't want to show the external link markup in Take Action covers, including Take Action boxouts. In order to achieve this, we need to update the selector as Take Action boxouts are only in posts (that don't have the `page-template` class).
- **Update post content z-index value**: this is to prevent the Take Action boxout going under the author block and comment form on mobile (scrolling version)
Related gutenberg-blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/364
=> PLANET-5325 Take Action boxout A/B test

templates/google-fonts.twig, templates/html-header.twig
* This line break caused an issue with Cloudflare's APO, which inlines
Google Fonts for better performance. They clearly didn't expect a
newline in there and did a bad request to Google resulting in a 400.
Cloudflare then proceeded to include that 400 response in the page, as
though it was the expected styles. This meant a html document was inside
of a style tag in the head, breaking the site very badly.
* Remove preload as APO doesn't remove it when inlining the google fonts
response.
=> Remove preload and line break in href

templates/html-header.twig
Turns out the line break was not the culprit. Instead APO is not handling google fonts links that specify multiple fonts in a single request correctly. We can split these up as they will be inlined anyway, instead of waiting for their fix.
=> Split fonts as CF crashes on combined url

src/MasterSite.php, src/Search.php, templates/search.twig
[JIRA 4861](https://jira.greenpeace.org/browse/PLANET-4861)
Tasks : 
- Added a new sort option called "Oldest"
- Renamed option "Most recent" as "Newest"
- Make new sort option translatable
- Make sure that archived content should be sorted
Testing :
- Open [P4 search page](https://www.planet4.test/?s=&orderby=_score)
- Toggle between new sort options in "Sort by" dropdown
- The content will be sort as per newly added sort options( Oldest = Sort by post_date ASC, Newest = Sort by post_date DESC)
- To test the archived content, make sure the "Include archived content in search for" setting is enabled from backend(Admin >> Planet4 >> Search content)
=> PLANET-4861 Adjust search sorting options

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5773
> it seems as though CSL iframes work fine on page but not on posts.
[ControlShiftLabs iframe script](https://support.controlshiftlabs.com/hc/en-us/articles/204104308-Embeddable-Petition-Signature-Forms) relies on attributes `id` and `data-petition-url` to insert its form, as seen in its minified version: `function loadIframe(){var e=document.getElementById("controlsfhift-embed-sign-form-script")`.
We [filter a post content](https://github.com/greenpeace/planet4-master-theme/blob/700bf73ff32d472f578556491459c22599379a04/templates/single.twig#L95) before display in a certain way, that is [not applied to pages](https://github.com/greenpeace/planet4-master-theme/blob/700bf73ff32d472f578556491459c22599379a04/templates/page.twig#L5), and …
=> PLANET-5773: CSL iframe not loading on posts

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5781
> change the message in the P4 message board to advertise the holiday party
Update of message and increment of message version to trigger reappearance of the dashboard message for every user.
The revert of this message for [5782](https://jira.greenpeace.org/browse/PLANET-5782) won't need a version increment, as it should stay hidden for people who discarded it before.
=> PLANET-5781: Update the P4 message board with the Holiday party

src/MasterSite.php
Ref: [JIRA 5162](https://jira.greenpeace.org/browse/PLANET-5162)
---
**Issue :**
- The RSS feed not showing the author override value in place of author name (`dc:creator`) in RSS feed.
**Testing:**
- Add post with author override value
- After checkout of this branch goto RSS feed link(https://www.planet4.test/feed/)
- The post feed will show the author override value at author name
=> PLANET-5162 Fix author override value in RSS feed

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5395
> ~Due to a bug in the ElasticPress plugin~ we're not able to save EP settings. There seems to be a missing html attribute that is used to send the update request.
Our html tag filter overwrites the elasticpress plugin own filters (and any other :grimacing:).
The tag attribute filter is too widely applied, and should only concern `post` content.
`MasterSite::set_custom_allowed_attributes_filter` only concerns `post` context. It is mainly used with the `wp_kses_post()` function.
- Passing `context` parameter to our filter
- Limiting filter to `post` context (ElasticPress uses its own context `ep-html`)
Test ElasticPress dashboard before and after fix:
- enable/disable radio boxes are mutually exclusive (can't check both at the same time) …
=> PLANET-5395: Some ElasticPress settings can not be saved

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5387
---
Added author filter to ensure the users with campaigner role are included in dropdown
=> PLANET-5387 Campaigner User Role missing from Author dropdown field

author.php, category.php, src/Search.php, taxonomy.php
[JIRA 5726](https://jira.greenpeace.org/browse/PLANET-5726)
**Task** -
- Hide password protected content from post listing pages like taxonomy, author, p4 post type pages etc
- Hide password protected content from search result page
**Blocker** -
- ~~The elasticPress plugin won’t provide option/support to hide password protected content from search result(quite surprising)~~
I found some discussion and open PR which offer the solution , but it will take time to get approval and merging -
- https://github.com/10up/ElasticPress/pull/1789
- https://github.com/10up/ElasticPress/pull/1913
~~Till the time we could consider some temporary solution-~~
- ~~We already have a meta field check which skip the posts from search result ( `p4_do_not_index` [meta …
=> PLANET-5726 Hide password protected content on post listing & search page

src/MetaboxRegister.php, src/Post.php, tests/test-open-graph.php
Ref: [JIRA 5774](https://jira.greenpeace.org/browse/PLANET-5774)
---
**Task:**
- Strip OG description field data
- Replace the OG description field type in backend from TinyMEC to textarea
- Update open graph unit test for strip tags
**Testing:**
- Login to [nix-test](https://www-dev.greenpeace.org/test-nix/admin) instance
- Add/edit page/post/campaign, the OG description field on page will display as textarea
- Check OG description field in page source, if the existing content have a html tags in description field, that will be strip before display on frontend.
eg. https://www-dev.greenpeace.org/test-nix/campaign/beskidt-palmeolie-truer-regnskoven/
Related PR : https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/466
=> PLANET-5774 Replace OG description field type from wysiwyg to textarea, strip OG desc

src/MasterSite.php
We need to add `rel=0` query parameter to the iframe url. This is done in the same way as the youtube-nocookie, on the embed html response.
For now this uses a somewhat shaky method of adding this, by relying on the `feature=oembed`query parameter being there. Checking if there is a better way, but I guess there's no risk proceeding with this in the meanwhile if it turns out to be tricky?
Ref: https://jira.greenpeace.org/browse/PLANET-5386
=> PLANET-5386 Force only related videos of channel

assets/src/js/app.js, assets/src/js/img_align.js
Ref: https://jira.greenpeace.org/browse/PLANET-5759
---
This one seems unused. `wp-caption` was probably a default WP class in the pro-Gutenberg era.
=> PLANET-5759 Remove unused img_align script

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5654
`register_block_type('core/image')` is called twice, first by WP, then by us to add a render callback. This triggers an error WP >= 5.5.
Fix by hooking to the `register_block_type_args` which allows to modify block type args at register, including `render_callback`.
~The fix also works for WP < 5.5~ <sub>no it does not</sub> 
Added a version compare to use this fix only on versions >= 5.5
The render callback we add is used to add credits to images caption.
- Add an image in a post. The image has to have something in the _Credit_ field of the Attachment details.
- The credit appears at the end of the image caption on the frontend.
=> PLANET-5654: WP_Block_Type_Registry::register was called incorrectly

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5782
> Once the Holiday party is over (December 18th), we should put back the original message  (well, slightly adjusted)
Made the message time dependent, as we might not deploy anything during the holidays.
You can play with the `over_date` locally to see the dashboard message change, if `over_date` is in the past.
- Before `over_date`: Party message
- Starting on `over_date`: Regular slack message
=> PLANET-5782: Restore the P4 message board after the Holiday party announcement

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5782
Removing holiday party message.
Message version is not incremented so that people who dismissed it previously won't see it again.
=> PLANET-5782: Restore the P4 message board

src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-5680
---
Changed function to static function to fix calling non static function error
=> PLANET-5680 fix static call to search function

.circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5434
php-8 job is not added yet, but since we already switched to 7.3 no need to test for a previous version.
=> PLANET-5434 Remove php-7.2

composer.json, composer.lock
Ref: https://jira.greenpeace.org/browse/PLANET-5434
---
Tests were failing with:
> Error: Class 'Timber' not found
Since we don't build the entire app for these tests, Timber was missing (it's on the base repo). Not sure how these were actually working before 🤔
=> Add Timber library for unit tests

assets/src/scss/vendors/_gtm.scss, src/MasterSite.php, src/Settings.php, templates/html-header.twig
* The toggle controlled whether to hide everything before the test is
applied, which harmed performance.
* Instead provide an option for a selector that will be hidden before
the test is ready.
* Always run the snippet since we're not hiding anything unless
specifically configured.
* Rename `.async-hide` class to something more accurate.
* Provide `.ab-hide` class which will be hidden while loading.
Ref: https://jira.greenpeace.org/browse/PLANET-5820
Tested and UAT approved on https://www-dev.greenpeace.org/test-deimos . It's set up there with the take action boxout selector, and Julia confirmed that the tests ran succesfully.
=> PLANET-5820 Anti flicker selector insteadof toggle

templates/base.twig
Google expects this to be the first item after `<body>`
=> Move GTM noscript higher on body

src/Settings.php
Ref: https://jira.greenpeace.org/browse/PLANET-5820
This should have been removed in the previous PR, but was overlooked.
=> Remove anti-flicker snippet setting

.circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5685
To get reliable performance test results we need to run Lighthouse we need to deploy the code to a test instance, since these have the same setup (Cloudflare) as production. Automatically deploying each commit to a branch of an open PR allows this, and additionally helps ensuring our test instances are always on the latest version of the code.
=> PLANET-5685 Add auto test instance booking and deploy, use test instance for lighthouse check

.circleci/config.yml
Ref: https://jira.greenpeace.org/browse/PLANET-5883
Currently merge commit workflows are failling because they can't find a test instance to deploy to. Trying out if we can re-use the instance of the branch that was merged by the merge commit.
Uses newer version of builder to put the test instance to `dev-master` and remove the `repositories` entry. Currently this only works as intended if the test instance has only one of 2 repos on it. If a version for the other one is pinned then the master workflow will run against that version.
Well, in a way we want both to happen, but can't have both. Since the other PR is not merged, it makes sense to keep it on the instance, as it might get further commits or get tested after merging the other reop. But we also want to run the master workflow …
=> PLANET-5883 Use merged PR's instance for merge commit workflow

.circleci/config.yml, src/Commands.php, src/Commands/CloudflarePurge.php, src/Commands/Command.php, src/Commands/RunActivator.php, src/Commands/SaveCloudflareKey.php, src/Features.php, src/Loader.php
Ref: https://jira.greenpeace.org/browse/PLANET-5870
Adding this as a command first so that we can make it a post-deploy step for test instances. We can start that way and observe if purging all html on each deployment causes any issues. Then we can set it up for a few production NROs and see how it goes. If it doesn't cause issues (e.g. Cloudflare deciding to evict us from cache more frequently once they pick up these entries usually don't live long), we could do this for all sites on each deploy.
I added a feature flag for this, so that we're not blocked to use it on production by needing more code changes. Tested off and on behavior on https://app.circleci.com/pipelines/github/greenpeace/planet4-test-janus/37/workflows/a3b88549-3fb8-4d73-926b-2e42e61b34ad/jobs/199
=> PLANET-5870: Cache clear command

assets/src/scss/pages/_404.scss, assets/src/scss/pages/post/_author-block.scss, assets/src/scss/pages/search/_filter-sidebar.scss, assets/src/scss/pages/search/_suggested-terms.scss
See https://jira.greenpeace.org/browse/PLANET-5842
- ~~#63bbfd = $blue-60~~
- ~~($grey-60) = $shadow-color~~
- ~~#f6f4e7 = $single-bg~~
- ~~#aed4c7 = $active~~
- ~~#b0d4c8 = $body-bg~~
- ~~#a7e021 = $inch-worm~~
- ~~#e51538 = $crimson~~
- ~~#5c1f10 = $brown-header~~
- ~~#003300 = $green~~
- ~~#264042 = $darkb-blue-text~~
- ~~#004d53 = $heading~~
- ~~#115247 = $search-text-color~~
- ~~#186a70 = $genoa~~
- ~~#017e7a = $percentage-text~~
- #418482 = $faded-jade => actually used in search page for search bar border, will be replaced in https://jira.greenpeace.org/browse/PLANET-5843
- ~~#22938d = $blue-elm~~
- ~~#67b2af = $light-blue~~
- ~~#1bb6d6 = $java~~
- ~~#007799 = $allports~~
- ~~#152340 = (none)~~
- ~~#152431 = $article-heading-color~~
- ~~#1b4a1b = $green-80~~
- ~~#a7a7a7 = …
=> PLANET-5842 Remove unused colors

assets/src/scss/pages/_page.scss, templates/page.twig, templates/single-page.twig
Ref: https://jira.greenpeace.org/browse/PLANET-5939
On a campaign page with title hidden and no subtitle or description, the text is on top of the page and gets hidden by the navbar.
The div `.page-header` has a padding that largely compensate the navbar height, but it is not always visible. When the title is hidden (option "Hide page title" in Campaign and Page) and there's no subtitle or description, it shrinks as `.page-header-hidden` and the main container has no padding-top.  
The padding has to be precise, so that when we add an EN form as first block, it doesn't look weird or has no white empty bar at the top.
The problem also exists on Pages. Solution has to be tested on:
| | Page type | Title visible* | First block |
| --- | --- | --- | --- |
| Minimal navigation |
| | Campaign | …
=> PLANET-5939: Campaign text hidden by navbar

assets/src/js/enhancedDonateButton.js
Ref: [JIRA 5752](https://jira.greenpeace.org/browse/PLANET-5752)
---
**Testing steps:**
- Go to WP admin and enable the "Show donate button below mobile navigation bar" setting from **Planet 4 >> Donate button**
- Test the feature in mobile and desktop screen
- The functionality should work as it is after removing the jQuery
=> PLANET-5752 Remove jQuery from enhancedDonateButton.js

assets/src/js/app.js, assets/src/js/cssvarsponyfill.js, src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5850
After doing some testing I noticed that the ponyfill has a large impact on performance. I don't know yet exactly what causes this impact, it could be the additional domain for a blocking resource, or the ponyfill might interfere with render by accessing style attributes. Normally it should not have to do anything for browsers that do support CSS variables, but maybe just checking for support affects page load.
I [temporarily put a commit on this branch](https://github.com/greenpeace/planet4-master-theme/commit/77faaca03c024f9f80b747d8fca8453efe0b8d12) that has a toggle for the removal so I could test both scenarios. The difference for the test instance was quite massive, without the ponyfill it was getting just under 70, with the …
=> PLANET-5850 Remove CSS vars ponyfill

assets/src/scss/pages/_page.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5939
Goes with: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/501
Last fix https://github.com/greenpeace/planet4-master-theme/pull/1293 introduced a change that separated image from navbar on campaigns relying on an image as first block.
_Expected layout:_
_Layout after https://github.com/greenpeace/planet4-master-theme/pull/1293_
This is because some campaigns have a fixed margin applied to header (solved in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/501), and image blocks also have a fixed margin.
Add a specific margin for first image block, like we previously gave to the first paragraph.
=> PLANET-5939: Image as first block separated from navbar

.circleci/config.yml
Removing the python call, since the script is executable and already configured to use python3
=> Use python3 for book-instance

templates/blocks/google_tag_manager.twig, templates/html-header.twig
Ref: https://jira.greenpeace.org/browse/PLANET-5844
This just moves the GTM code into its own template because it sparks no joy in html-header, but on its own, it does. ✨ 
Then we can continue with this PR: https://github.com/greenpeace/planet4-master-theme/pull/1307
---
=> PLANET-5844: Investigate using Google Optimize with optimize.js

.circleci/config.yml
stylelint needs a double-quoted path, otherwise it doesn't make a recursive lookup.
Counterpart of greenpeace/planet4-plugin-gutenberg-blocks#510. In this case no scss code needed fixing.
=> Fix stylelint recursive path

.stylelintrc, assets/src/scss/style.scss, package-lock.json, package.json, src/Features.php, src/MasterSite.php, src/Migrations/M002EnableLazyYoutube.php, src/Migrator.php, webpack.config.js
* Add a way to force feature settings using query string. Can be used to
alternate lighthouse tests between both versions so that both are
affected about equally by the run conditions.
* Use srcdoc with an image using YouTube's url schema to avoid loading
the massive player on page load.
Ref: https://jira.greenpeace.org/browse/PLANET-5959
---
=> PLANET-5959 Add lazy youtube loading

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5964
---
This also makes us use jquery 3 instead of 1 on the front end, and consequently we won't be loading jquery-migrate. Add the blocks index script as a dependency so that jquery doesn't block it. That script is rendering a large portion of the page.
=> PLANET-5964: make depend on blocks

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5971
---
* By not making jquery depend on it when logged in, since in that case
WordPress enqueues jquery in the head.
=> PLANET-5971 Fix blocks js loading when logged in

.stylelintrc, package-lock.json, package.json
Ref: no ticket, just a bump to match the same bump in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/495
---
This bumps dashdash to the latest version, which supports a shorthand to generate variable names from the selector.
```
.foo-bar {
_-- {
color: green;
background-color: yellow;
}
}
```
produces the same result as
```
.foo-bar {
--foo-bar-- {
color: green;
background-color: yellow;
}
}
```
which is the same as
```
.foo-bar {
color: var(--foo-bar--color, green);
background-color: var(--foo-bar--background-color, yellow);
}
```
=> Bump dashdash, whitelist shorthand

assets/src/scss/bootstrap-build.scss, package-lock.json, package.json, templates/blocks/share_buttons.twig, templates/footer.twig, templates/footer_min.twig, templates/tease-author.twig, templates/tease-search.twig, templates/tease-taxonomy-post.twig
Ref: https://jira.greenpeace.org/browse/PLANET-5906
Migrate to Bootstrap 5.
Changes:
* [_media.scss](https://github.com/twbs/bootstrap/blob/v4.6.0/scss/_media.scss) no longer exists, but it can be replaced with the `d-flex` utility.
* `sr-only` is now `visually-hidden`
Also check the [styleguide PR](https://github.com/greenpeace/planet4-styleguide/pull/98) and the [blocks PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/505).
---
=> PLANET-5906: Migrate to Bootstrap 5

.circleci/config.yml
Since we renamed repo name and default branch, this currently breaks tests.
=> Fix base branch and name

assets/src/scss/pages/post/_author-block.scss
See [PLANET-5035](https://jira.greenpeace.org/browse/PLANET-5035): this is an old ticket that was closed but apparently the issue comes back from time to time in very specific cases (probably due to the author image dimensions?) This fix should solve it for good. 😬
=> PLANET-5035 Make sure author image is full height

.circleci/config.yml
a11y tests are currently failing because of some changes in our docker-compose configuration.
We are planning to run those tests on live test instances, and this job is consuming resources while failing systematically. It's better to comment this out for now and work next on moving it to run on the test instance.
Related: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/517
=> Comment a11y test out until we make them run on test instances

assets/src/scss/pages/post/_article-content.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5990
---
On images this has no effect, since they already have `max-width`,
but other elements can expand outside of the post container when floating.
> _[Test post](https://www-dev.greenpeace.org/test-proteus/story/1007/social-media-test/)_
Required for greenpeace/planet4-plugin-gutenberg-blocks#524
=> PLANET-5990 Restrict max-width on floated elements

assets/src/scss/pages/_page.scss, page.php, single-campaign.php, single.php, src/Post.php, templates/single-page.twig, templates/single-password.twig
Ref: [JIRA 5748](https://jira.greenpeace.org/browse/PLANET-5748)
---
**Testing steps:**
- Add a page with password protected visibility
- Go to the page on frontend, add wrong password
- It should show wrong password message
**Summary:**
Here I didn’t find a better way than the below one -
- When visitor open a password protected page, check if page url have  a unique hash token? If no add one in URL and redirect to url with hash token
- This token is use to uniquely identify visitor, store and access old cookie password hash from transient cache
In wordpress core, the latest entered password is stored as a secure hash in a cookie named 'wp-postpass_' . COOKIEHASH.
When the password form is called, that cookie has been validated internally by WordPress.
The form validation flow is as per …
=> PLANET-5748 Add password validation message on password protected page

assets/src/scss/pages/search/_filter-sidebar.scss, templates/search.twig
When updating the button styles for [PLANET-5501](https://jira.greenpeace.org/browse/PLANET-5501) we forgot the one to clear search filters 😬 We probably missed it because it didn't have the `btn` class so I added it, which also avoids some duplicate code
You can see the updated button [here](https://www-dev.greenpeace.org/test-umbriel/?s=&orderby=_score&f%5Bcat%5D%5BNature%5D=3) for instance
=> PLANET-5501 Update clear search filters button styles

.circleci/config.yml, bin/install-wp-tests.sh
Ref: 
---
Our tests are running against the latest version of WP, not against the one we use in production. This came up by a new issue in 5.7 that broke a test.
Could need more changes than just the WP version since it's still failing.
=> test against version we use

.stylelintrc, assets/src/scss/pages/post/_author-block.scss, assets/src/scss/pages/post/_post.scss
Ref: no ticket for now
---
Since we use autoprefixer, we can use a stylelintrule to detect any prefixes in our source that would be added during build anyway. This adds the rule and fixes violations, except `-webkit-box-orient` which is buggy.
=> Prevent unneeded prefixes, we autoprefix

assets/src/scss/pages/post/_article-content.scss
See https://jira.greenpeace.org/browse/PLANET-5848
- [Old version](https://www-dev.greenpeace.org/test-jupiter/explore/ships/arctic-sunrise/) with the blue caption overlay
- [New version](https://www-dev.greenpeace.org/test-tavros/explore/ships/arctic-sunrise/) with the regular caption styles
=> PLANET-5848 Remove blue caption from classic editor images

assets/src/scss/editorOverrides.scss, assets/src/scss/editorStyle.scss, src/MasterSite.php, webpack.config.js
---
Needs to be merged together with https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/533
This moves in all parts of the editor styles that are not relevant to the blocks in the blocks plugin. After this there will be more parts of the styleguide that can be moved into master theme.
=> PLANET-5983: Move in editorStyle from blocks plugin

assets/src/js/header.js, assets/src/scss/pages/_404.scss, assets/src/scss/pages/_page.scss, assets/src/scss/pages/search/_filter-sidebar.scss, assets/src/scss/pages/search/_search-results.scss, assets/src/scss/pages/search/_sort-filter.scss, src/MasterSite.php, templates/author.twig, templates/navigation-bar.twig, templates/search.twig, templates/taxonomy.twig, templates/tease-search.twig
See https://jira.greenpeace.org/browse/PLANET-5981
Changes made to comply with the [migration doc](https://getbootstrap.com/docs/5.0/migration/):
- Rename all Bootstrap attributes' prefixes from `data-` to `data-bs-`
- Rename `float-right` to `float-end`
- Add `form-select` to select components instead of `form-control` (which now has the `appearance: none;` hiding the select's arrow)
- Remove `mr-sm-2` class
- Rename `text-right` to `text-end`
- Update page-template width for xxl screens (new breakpoint added as of Bootstrap 5)
- Remove `screen-reader-text` class to use Bootstrap's `visually-hidden` instead
- Add `align-items-start` class to search results
- Fix search for rtl direction
You can check the changes on [this test instance](https://www-dev.greenpeace.org/test-janus/), …
=> PLANET-5981 Updates for Bootstrap 5

src/PostCampaign.php
Ref: https://jira.greenpeace.org/browse/PLANET-6015
---
The block editor validation relied on reading the meta from the input field that is separate from the other data flow in the editor. This adds it to the "campaign fields", which results in it being registered for the API so it can be used in the editor.
This PR needs to be merged before the tests on https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/537 can pass. Adding just the field here should only mean it is registered for the REST API so that it's returned by `wp.data.select('core/editor').getEditedPostAttribute('meta')`. So this seems a safe change.
=> PLANET-6015: add field here so it can be used in editor

functions.php
Ref: https://jira.greenpeace.org/browse/PLANET-6021
---
We already watch for new releases, so this notice only causes confusion to users.
To test: confirm that the notice is not shown at the top of every admin page.
=> PLANET-6021 Hide core upgrade notice

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6028
---
We didn't define this earlier but it didn't cause any issues. However since last deploy the Japanese child theme is now loading bootstrap after the master theme CSS, which changes the order of CSS and so causes most `a` tags to be underlined (and likely more issues). Could be it was already loading like this before but it only started causing issues with Bootstrap 5 upgrade.
=> PLANET-6028 explicitly define bootstrap as dep of parent-style

.gitmodules, assets/src/scss/pages/_page.scss, assets/src/scss/styleguide/src/base/_body.scss, assets/src/scss/styleguide/src/base/_colors.scss, assets/src/scss/styleguide/src/base/_fonts.scss, assets/src/scss/styleguide/src/base/_functions.scss, assets/src/scss/styleguide/src/base/_icons.scss, assets/src/scss/styleguide/src/base/_mixins.scss, assets/src/scss/styleguide/src/base/_rtl.scss, assets/src/scss/styleguide/src/base/_shame.scss, assets/src/scss/styleguide/src/base/_typography.scss, assets/src/scss/styleguide/src/base/_variables.scss, assets/src/scss/styleguide/src/components/_blockquote.scss, assets/src/scss/styleguide/src/components/_buttons.scss, assets/src/scss/styleguide/src/components/_share-buttons.scss, assets/src/scss/styleguide/src/components/_skip-links.scss, assets/src/scss/styleguide/src/components/_spinner.scss, assets/src/scss/styleguide/src/components/_tweet-block.scss, assets/src/scss/styleguide/src/layout/_blocks.scss, assets/src/scss/styleguide/src/layout/_breadcrumbs.scss, assets/src/scss/styleguide/src/layout/_cookies.scss, assets/src/scss/styleguide/src/layout/_footer.scss, assets/src/scss/styleguide/src/layout/_forms.scss, assets/src/scss/styleguide/src/layout/_navbar.scss, assets/src/scss/styleguide/src/layout/_page-header.scss, assets/src/scss/styleguide/src/layout/_page-section.scss, assets/src/scss/styleguide/src/layout/_skewed-overlay.scss, assets/src/scss/styleguide/src/layout/_tables.scss
---
This should move in the entire styleguide repo (except parts only relevant to the styleguide repo itself). It's moved to the location it already was in the theme.
Other repos that used the styleguide can be switched to use master theme as a submodule instead after this PR is merged.
I also needed to fix some code style issues in the styleguide, and also one in master theme before I could make the test pass. These are the commits starting from https://github.com/greenpeace/planet4-master-theme/pull/1344/commits/b489975a0008c90871f8562c92212a891a63b987
=> PLANET-5983: Move in styleguide

assets/src/js/external_links.js
See https://jira.greenpeace.org/browse/PLANET-6004
You can see the fixed links & buttons on [this page](https://www-dev.greenpeace.org/test-leda/links-and-buttons-with-icons/) for example.
Note: the issue with the width of the secondary buttons will be solved as part of [PLANET-5980](https://jira.greenpeace.org/browse/PLANET-5980).
- [styleguide](https://github.com/greenpeace/planet4-styleguide/pull/107)
- [blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/531)
=> PLANET-6004 Fix pdf link icon (hover) colors

assets/src/scss/editorOverrides.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6035
---
We made a fix for `iframe` heights a while back which worked, but in 5.5 or 5.6 a change was done (possibly to address the same issue) that together with our fix causes the iframe in the embed block to have no height. I couldn't reproduce the original issue (that youtube videos overlap the next block in the editor) after removing the CSS, so I guess it's fixed in core.
Tested on https://www-dev.greenpeace.org/test-pandora/wp-admin/post.php?post=29036&action=edit
original issue: https://jira.greenpeace.org/browse/PLANET-5344
PR (same code was previously in blocks): https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/361
=> PLANET-6035 Restore embed block iframe heights

src/MasterSite.php
This update is to match the changes in the blocks plugin repo, see:
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/508/files#diff-4baaf0cfa9f65dafcc2bed33ae43cbc221e00364aaa33ec6b6c71b49e56ea5c0R402
Ref: https://jira.greenpeace.org/browse/PLANET-4535
---
=> PLANET-4535: Match change in plugin's script handle

assets/src/scss/styleguide/src/layout/_skewed-overlay.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5622
This recreates the original styleguide PR since the styleguide was moved to the master theme: https://github.com/greenpeace/planet4-styleguide/pull/90
(previously approved by @mleray)
=> PLANET-5622: Skewed overlay changes position when page length changes

assets/src/scss/pages/_page.scss, assets/src/scss/styleguide/src/layout/_forms.scss, templates/single-page.twig, templates/single-password.twig
See https://jira.greenpeace.org/browse/PLANET-5984
- Fix required radio/checkbox validation
- Update radio/checkbox color in EN form full-width style for better readability
- Move input error styles to the styleguide
Changes can be tested on [this page](https://www-dev.greenpeace.org/test-venus/required-inputs/) (password is "password")
- [blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/520)
=> PLANET-5984 Move input error styles to _forms.scss

templates/countries.json
This came as a request from GP Nordic. It turns out we had it wrong all along.
=> Fix Finland localized name

assets/src/scss/pages/search/_search-results.scss, templates/tease-search.twig
See https://jira.greenpeace.org/browse/PLANET-6043
We added this fix to the [search page results](https://github.com/greenpeace/planet4-master-theme/blob/master/templates/tease-search.twig#L19) when upgrading to Bootstrap 5, but forgot to update the other templates that feature search results. 
There is already a [PR open](https://github.com/greenpeace/planet4-master-theme/pull/1353) for that issue using the new BS 5 classes, but this PR gives another solution without using the BS 5 classes, which avoids some duplication 🙂
=> PLANET-6043 Fix search pages image aspect ratios

package-lock.json, package.json, webpack.config.js
---
The previous version of this plugin didn't account for [multiple entrypoints](https://github.com/greenpeace/planet4-master-theme/blob/0c65cee3a83bc760e21a59fed9f6583f7304b4cb/webpack.config.js#L16-L19). To resolve this the new version now writes to a separate key per entrypoint.
The plugin to combine these and write the file is now also included. Before this was in both repos using this package.
This also disables extracting the variables from the source SCSS files. Nothing was done with the result yet, and probably the same can be achieved directly in the postcss plugin by ensuring the rules source is properly set.
This also makes it use [Greenpeace's fork](https://github.com/greenpeace/planet4-postcss-css-variables) and npm …
=> PLANET-5983: Properly extract vars from multiple files

assets/src/scss/styleguide/src/base/_icons.scss, tests/acceptance/CustomTaxonomyPageCept.php
Ref: https://jira.greenpeace.org/browse/PLANET-6053
---
`inline-block` forces links with long text to try to fit on the same line causing weird white space on paragraphs.
Not sure why we had that initially. It looks these were added when we removed `jQuery` from the js part of these links.
=> PLANET-6053 Remove inline-block from icon links to properly wrap

assets/src/scss/base/_body.scss, assets/src/scss/base/_typography.scss, assets/src/scss/components/_buttons.scss, assets/src/scss/layout/_breadcrumbs.scss, assets/src/scss/layout/_footer.scss, assets/src/scss/layout/_navbar.scss, assets/src/scss/layout/_skewed-overlay.scss, package-lock.json, package.json, src/PostCampaign.php, webpack.config.js
---
Easiest to review with whitespace changes hidden: https://github.com/greenpeace/planet4-master-theme/pull/1325/files?diff=split&w=1
Current proposed migration path:
* Add all variables needed to recreate the campaign themes (CSS overrides living under https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/tree/d90243cf861c5e5909db59c546516bc6f58315cb/assets/src/styles/campaigns, as well as the sidebar options.
* Recreate the themes (either by adding a JSON/CSS file for each one in our code, or by allowing themes to be created and saved in the database without code change)
* Switch all existing campaigns to use these instead of the CSS overrides.
* Remove the old override based code.
In this PR (might split up further):
* Add …
=> PLANET-5983: Add variables

assets/src/scss/layout/_navbar.scss
See https://jira.greenpeace.org/browse/PLANET-6062
You'll need to resize your screen, for me on Chrome I could see the issue at 768px width.
- Broken: 
- Fixed:
=> PLANET-6062 Hide Menu text when main menu is open on small screens

assets/src/scss/base/_icons.scss, src/PostCampaign.php
---
I forgot to update the name fallbacks for campaigns before merging. Also made it a bit more manageable.
How to test: Create a campaign and use the sidebar options. Each of them should result in the expected property being applied.
=> PLANET-6082 Fix incorrect old name migration

src/Features.php, tag.php
Ref: https://jira.greenpeace.org/browse/PLANET-5523
---
This adds the feature toggle for beta blocks used in by the plugin.
Also makes `tag.php` use a string literal instead of the class constant from the other repo, to avoid hassle when we change the old version name to `OldCovers`.
=> PLANET-5523 Add Beta Blocks option

templates/author.twig, templates/taxonomy.twig
Related to: https://jira.greenpeace.org/browse/PLANET-5981
"Load More" button doesn't work on author and taxonomy pages.
Data attribute `data-bs-content` in templates is not the one expected by the `load_more.js` script; the "Load More" button does a request but doesn't display anything.
This reverts the data-content attribute changes from https://github.com/greenpeace/planet4-master-theme/pull/1323 
You can check the issue on this page https://www.greenpeace.org/international/story/ - the "Load More" button doesn't display more stories, despite sending a GET request and getting a response. You can make it work by changing the `data-bs-content` attribute to `data-content`.  
Locally:
- Create a few posts (use the clone function, quick edit to change title and publish)
- For convenience …
=> Fix "Load more" function on author and taxonomy

src/Features.php
Ref: https://jira.greenpeace.org/browse/PLANET-6087
---
Now that we moved out blocks that were already used in production from the beta category, it will be hidden behind this toggle from now on. So we can refer to it in the help text.
https://www-dev.greenpeace.org/test-pluto/wp-admin/admin.php?page=planet4_settings_features
=> PLANET-6087 Refer to beta category in help

assets/src/js/load_more.js, assets/src/scss/components/_buttons.scss
This replaces all jquery references in the component to using
raw DOM APIs instead. Note that this uses the `fetch` api,
which may not be available in older browsers. I am not sure
if we need to support browsers that do not have fetch in it.
Fixes https://github.com/greenpeace/planet4/issues/134
Please let me know a good way to test this out.
=> Remove jquery from load_more component

src/HttpHeaders.php, src/Loader.php
Ref: https://github.com/greenpeace/planet4/issues/132
Adds an HTTP Header class that sends two headers by default:
`Content-Security-Policy: frame-ancestors 'self'`
`X-Frame-Options: SAMEORIGIN`
In addition, it contains a filter hook to allow modification of the allowed frame ancestors list in the `Content-Security-Policy` header. In practice, the filter can be used to whitelist domains of 3rd party websites to embed Planet4 content.
When the filter is used to add allowed frame ancestors, the `X-Frame-Options` header is not sent. 
This PR is intended to replace sending of the `X-Frame-Options: SAMEORIGIN` header [directly from NGINX](https://github.com/greenpeace/planet4-docker/blob/develop/src/planet-4-151612/openresty/etc/nginx/conf.d/security.conf#L8). The config for NGINX has to be …
=> PLANET-5897: Add HTTP Header class that sends CSP and X-Frame headers

single-campaign.php, templates/head/google_fonts.twig, templates/html-header.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6080
---
These fonts were loaded with an `import` in the stylesheet, which is being removed in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/556. This PR adds them to the HTML so that Cloudflare APO can optimize them.
Both should be merged at the same time. This one should go first so we don't end up in a state where there are no fonts.
I moved the new code and existing fonts into a new template part.
=> PLANET-6080 Add fonts in HTML head for campaigns

src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-6019
Related to: https://github.com/greenpeace/planet4-docker-compose/pull/85
On local instance, Elasticsearch container is disabled by default.
Elasticpress throws some exceptions when it is activated (no server to connect to), and once deactivated the Search functionality throws some more.
This fixes exceptions thrown when Elasticpress plugin is disabled, and keeps some links working in the result page.
- Disable Elasticpress 
`docker-compose exec php-fpm wp plugin deactivate elasticpress`
- Go to a search page
- on `master` branch, you should get an error 
- on this branch, the page appears and result links are valid
=> PLANET-6019: Verify Elasticpress activation before adding filters

package-lock.json, package.json, webpack.config.js
* It's not needed anymore. The same info can be extracted at runtime
fast enough, which is a lot easier to work with. Besides the plugin had
multiple serious issues. It always added a fallback with no option to
disable that. It also for some reason split combined selectors, which
did quite increase the size of the CSS.
Ref: https://jira.greenpeace.org/browse/PLANET-6129
=> PLANET-6129 Remove variable collect script

templates/base.twig
See https://jira.greenpeace.org/browse/PLANET-6002
Go to a long page with a Submenu block (for example Copyright or maybe Privacy) and make sure that the button doesn't appear when you scroll down.
- https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/584
=> PLANET-6002 Remove Submenu back to top button

assets/src/scss/editorOverrides.scss, assets/src/scss/layout/_page-header.scss, src/PostCampaign.php, templates/css-variables.twig, templates/html-header.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6136
---
This branch ended up with various small things. I didn't split them up yet because for now it seems manageable to review. But I can still split it if that works better for the reviewer.
- Add the theme to the campaigns listing and allow sorting on it. See screenshot
- Fix fallbacks in editor styles
- Add a "data-base" attribute so that we can use it to create a namespace in localstorage.
- If a campaign has a new theme selected, it will grab it from the options. Not intended to be used in production, but it shouldn't affect any live content so we can merge it. On production you're not able to select a new theme for a campaign.
- If the stripping `-new` from the theme name results in one of the legacy themes, it will still use the …
=> PLANET-6136 Prepare test instance for themes review

assets/src/scss/layout/_page-section.scss, single-campaign.php, src/MasterSite.php, templates/head/google_fonts.twig, templates/html-header.twig
---
While adding variables to the blocks CSS I find that some need more variables in master theme.
We also need to include the custom fonts for the default theme as well.
Also included a commit to use an existing variable in the twig template instead of a constant. These don't throw errors when undefined.
=> PLANET-5983 Ensure theme fonts are loaded, add page section header variables

.circleci/config.yml, composer.json, composer.lock
Ref: https://jira.greenpeace.org/browse/PLANET-6020
---
This just update the github-archive plugin to the version that works with `composer2`. I also adjusted the builder branches to pick composer2, for all the other repos (plugin, base, builder). I will remove those after the review. There is one test failing, but it doesn't seem related to this 🤔
=> PLANET-6020 Upgrade github-archive-installer to support composer 2

src/PostCampaign.php
The incorrect name caused the sidebar settings to not work for the
plastic theme.
Ref: https://jira.greenpeace.org/browse/PLANET-6136
=> Correct "plastics" to "plastic"

.circleci/config.yml
That would allow us to use the [artifacts](https://getcomposer.org/doc/05-repositories.md#artifact) type on the base repo and get rid of the plugin (in a next step).
Also did some CI cosmetic changes for consistency with other repos.
This doesn't affect existing workflow, since it just adds one more line in `composer.json`. 
The best way is to test locally the two extra commands and verify. Replace `${CIRCLE_TAG}` with a version number.
```
wget https://raw.githubusercontent.com/greenpeace/planet4-master-theme/master/composer.json
cat composer.json | jq --arg version ${CIRCLE_TAG} '. + {version: $version}' > tmp.json
cp -f tmp.json composer.json
tail composer.json
```
The version field should be there as the last key.
=> Inject version key in composer file on zip creation

src/MasterSite.php, templates/head/hubspot.twig, templates/html-header.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6155
---
Ensure that the `revokeCookieConsent` is the first thing on the _hsp queue.
Luckily, this seems to work even if requiring consent is not enabled for the policy. Even though HubSpot documentation doesn't explicitly mention that revoking is supported in this case, it seems safe enough to do since it's unlikely that they would alter this behavior.
=> PLANET-6155 Prevent HubSpot cookies being set if user didn't consent

composer.json, composer.lock
To make it work with both Composer 1 and 2. Note that it won't fully work with Composer 2 since we still have another issue to solve relating to zip downloads.
Same PR for plugin: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/605
=> Bump github-archive-installer to 1.3.2

src/MasterSite.php
Set wp-editor in the 'Text' mode by default (Temporary fix till the WP release a core fix for https://core.trac.wordpress.org/ticket/52050)
Ref: [JIRA 6060](https://jira.greenpeace.org/browse/PLANET-6060)
---
When we switch from text to visual, the wp-editor(tinyMCE) works fine, though its not a perfect fix but a quick win over adding a whole new plugin.
eg. https://www-dev.greenpeace.org/sagardev/wp-admin/post-new.php?post_type=page
=> PLANET-6060 Fix wp-editor issue

assets/src/scss/layout/_breadcrumbs.scss, templates/blocks/header.twig, templates/single.twig, templates/tease-author.twig, templates/tease-search.twig, templates/tease-taxonomy-post.twig
Ref: 1/2 of https://github.com/greenpeace/planet4/issues/114
Sibling PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/560
This will remove the bullet applied via css `content: "\2022";` as there is not a clean way to hide the bullet from the screenreader when the bullet is added through css like this.
After taking a quick look, and noticing that we are updating a file that seems more general than the component we are touching (`_breadcrumbs.scss`) I am a little worried that this might break other functionality by hiding bullets in other places of the website. I would definitely like some 👀 on this PR with that in mind. Thank you ❤️ 
---
=> remove bullet from breadcrumbs styling

assets/src/js/app.js, assets/src/js/global.js, category.php, src/MasterSite.php, taxonomy.php, templates/blocks/image.twig, templates/tease-author.twig, templates/tease-taxonomy-post.twig
Removed global.js file and added title attribute in twig file & in PHP file by altering original output
Ref: [JIRA 5757](https://jira.greenpeace.org/browse/PLANET-5757)
---
**Testing steps:**
- Add native image block on page/post/campaign and test the frontend page the image has a title attribute
- The same fix is added for some other pages like author profile page, search, taxonomy page etc.
=> PLANET-5757 jQuery: remove jQuery from global.js

templates/navigation-bar.twig, templates/navigation-bar_min.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6192
---
Fix: 
- After the WPML plugin upgrade the, menubar language title is appended with newline char (Thanks @lithrel ), added a trim function to fix the issue.
=> PLANET-6192 Fix WPML language switcher issue

assets/src/scss/pages/post/_article-content.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6197
On posts (only), twitter embed is larger than a regular mobile width (<500px).
The current rule only applies to posts, and only to twitter.
Twitter embeds on pages, and instagram embeds on posts/pages, follow different rules and fit properly.
Some other embeds are also too large on 320px width, because of a general rule of width:330px in gutenberg blocks, fixed in this commit https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/compare/planet-6197 . Embeds usually have their own min-width included in their containers or frames (250px for twitter, 200px for reddit, etc.).
The test instance has commits of both theme and plugin. 
Removing the rule fixes the issue.
I created a page with multiple embed there …
=> PLANET-6197: Fix Twitter embed width on mobile screen

templates/blocks/share_buttons.twig
Fix Twitter share text. Add a comma before via '@Greenpeace'
Ref: https://jira.greenpeace.org/browse/PLANET-6152
---
**Testing**
Go to any post and click on Twitter Share Button. You will be redirected to Twitter, then, a popup with this text modification would be shown.
=> PLANET-6152 Fix Twitter share text. Add a comma before via '@greenpeace'

assets/src/scss/layout/_navbar.scss
Before this modification, the main logo was fitted the entire width of the main Header. In consequence, It has been caused an strange behaviour for users that accidentally clicked on the Header, outside the logo, and being redirected to the index page.
Ref: https://jira.greenpeace.org/browse/PLANET-6130
=> PLANET-6130: Fix Mobile logo width

assets/src/scss/pages/post/_article-content.scss
Ref: https://jira.greenpeace.org/browse/PLANET-5003
> When using lists `<ul><ol>` in Pages, for both Default and Evergreen templates, there appears to be additional spacing below the list. Additionally, there is no spacing within the list itself. The expected behaviour would be what appears on Posts.
Removes list container padding and margin to replace them with a different margin scheme applied on list items, fixing inter-block margin (no)collapse issues and post/page differences.
See plugin PR on same branch name for more details https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/617
=> PLANET-5003: Fix inconsistencies in lists

src/MigrationLog.php, src/Migrations/M003UpdateArticlesBlockAttribute.php, src/Migrator.php
Ref: [JIRA 6040](https://jira.greenpeace.org/browse/PLANET-6040)
---
Follow up PR from [#546](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/546)
**Tasks:**
- Add migration script which update articles description field in block inner HTML and place it after article_heading and before article_count
- Fix Fatal error, Warning in Migration script
**Testing:** 
- First reproduce a "Block validation failed" error (The issue is reproducible by creating a new page/campaign with articles block with description field, refresh page and try to edit it.)
- On local development env, connect to php container by `make php-shell`
- Run migration script - `wp p4-run-activator`
- Check the page revision, it looks like -
- The migration logs are also logged  into `planet4_migrations` …
=> Planet 6040 Update articles block attribute

assets/src/js/external_links.js
I tackled this modification to be ensure that external links, the ones that were set by the block, would always have set the defined target value. If not, just keep the default.
Linked PR https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/624
Ref: https://jira.greenpeace.org/browse/PLANET-6124
---
=> PLANET-6124: Change the way of setting the target to links when are externals

src/Campaigner.php
Allows to read, write and delete them.
Ref: https://jira.greenpeace.org/browse/PLANET-6238
---
=> PLANET-6238 Add private campaigns caps for editor role

composer.json, composer.lock, functions.php, src/Features.php, src/Notifications/MrkDwnField.php, src/Notifications/Slack.php, src/Settings.php
Ref: https://jira.greenpeace.org/browse/PLANET-6237
---
Add our own super lightweight implementation of a Slack message carrier to the notifications plugin.
Stores the webhook in a WP option (maybe we can find a better menu location, though the features section is already a place where we put early stuff).
The code that adds Slack only runs on a hook provided by the plugin, so should be safe to merge before we add the plugin. We'll initially set it up for GPI only as a pilot.
The current code was already quite extensively tested, see https://greenpeace-gpi.slack.com/archives/C022728TVT9 . The latest messages in the channel look a bit off, but that's just because of how the notification is set up. We can add a webhook and a test channel webhook to the GPI dev site, it can be used by Kelli …
=> PLANET-6237 Slack notifications

.circleci/config.yml
To make the CI config more readable, moving the PR check into its own
script in the circleci container.
Same for the `requests_oauthlib`. It's now already installed.
Has to be merged after greenpeace/planet4-circleci#53
=> Move PR check in a script

.circleci/config.yml
Ref: 
This PR was in draft because I wanted to split out the `ci` target, however this requires changes to the makefile. We can merge this part already to split it a bit and remove some duplications.
=> Do ci setup in separate job step

page.php, single-campaign.php, single.php, src/Context.php, templates/blocks/share_buttons.twig, templates/single.twig
The Social Media share message should include the current page URL with the additional UTM parameters below (based on the [Global UTM Standards](https://app.gitbook.com/@greenpeace/s/insights/global-property/standards/utm-conventions))
Ref: https://jira.greenpeace.org/browse/PLANET-6083
=> PLANET-6083: Add UTM Parameters to share buttons

.circleci/config.yml
Without quotes this probably only passes the first string before a
space, and it's not able to pick up merge commits anymore. As a result
test instances are not being reset to master after merging.
Same PR for the plugin https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/638
Ref: 
---
=> Add quotes, message contains spaces

src/PostCampaign.php
* By putting "--" in front. New themes currently define them with "--", previously it was adding it without resulting in double definition.
* Remove "footer_color" as that one doesn't come from meta, set right name directly.
* Add some explanatory comments.
To reproduce the issue this fixes on `master`: create a new version of a theme (say `climate-new`). This allows you to use the same sidebar settings as the old `climate` theme. Set the navigation background color using the sidebar. After saving, you'll notice on the public URL of the page that it includes `--top-navigation--background` twice. Also if you're on Chrome, inspect the top navigation and click on the CSS variable to navigate to the defintion. Chrome points you to the first one, while it's actually using the last one (this …
=> Ensure migrated old vars override new themes

campaign_themes/climate.json, campaign_themes/plastic.json
This was added to production content before we removed the option, and that content is still using it. If the option is not there, it's
impossible to put the color back using the UI once it's unset or switched to another color. (You can use the console to set it with `wp.data.dispatch('core/editor').setEditedPostAttribute( {meta: {campaign_nav_color: any_value})`)
This is needed now because we want to test switching content to the new version of Plastics theme, and when a theme is switched, it unsets all values on a post that are not allowed in the theme.
I also added the same fix for the Climate theme.
=> Re-add GP green for plastics and climate nav color

templates/blocks/share_buttons.twig
URL encode Twitter share description text to avoid text break
Ref: [JIRA 6318](https://jira.greenpeace.org/browse/PLANET-6318)
---
Testing :
- Go to https://www-dev.greenpeace.org/test-titan/test-twitter-post-share-option/
- Remove the `display:none` style from div having class "thankyou"
- Check the Twitter share and Email share option, It should not break the text because of special chars(like '#' ) in description text.
=> PLANET-6318 Fix Twitter share description issue

assets/src/scss/campaigns/_campaign_cookies.scss, assets/src/scss/layout/_cookies-new.scss, assets/src/scss/layout/_cookies.scss, assets/src/scss/style.scss
See https://jira.greenpeace.org/browse/PLANET-6336
On local you can add `new-design` to the [class in cookies.twig](https://github.com/greenpeace/planet4-master-theme/blob/master/templates/cookies.twig#L2) and replace `btn-secondary` with `btn-primary` in the button classes in the same file. That should be enough to see the new design, if you remove all cookies from storage (or uncheck the necessary cookies in the Privacy page) 🙂 
**Note**: for the A/B test these changes are applied by Optimize.
=> PLANET-6336 Implement new Cookies banner design

src/Settings.php
The "Enable Analytical Cookies" checkbox is added under Planet4 > Cookies Text setting
Ref: [JIRA 6253](https://jira.greenpeace.org/browse/PLANET-6253)
---
- The "Enable Analytical Cookies" checkbox is added under Planet4 > Cookies Text setting
=> PLANET-6253 Add analytical cookies setting in Planet4 settings

.circleci/config.yml, src/Commands/CloudflarePurge.php
Ref: https://jira.greenpeace.org/browse/PLANET-6306
Add PHP 7.4 job on Circleci
Fix [deprecated usage](https://www.php.net/implode#refsect1-function.implode-changelog) of `implode`
=> PLANET-6306: Run tests on PHP 7.4

assets/src/scss/base/_colors.scss, assets/src/scss/pages/post/_comments-block.scss, assets/src/scss/pages/post/_comments-form.scss, single.php, src/MasterSite.php, templates/child_comments.twig, templates/comment.twig, templates/comment_form/author_field.twig, templates/comment_form/comment_field.twig, templates/comment_form/email_field.twig, templates/comment_form/submit_button.twig, templates/comments_section.twig
See the [ticket](https://jira.greenpeace.org/browse/PLANET-6071) and the [designs](https://www.figma.com/file/tdt8olZ6RS4bTMqbo2cvCU/Post-page-V1?node-id=629%3A981)
This PR also includes a fix for the "Cookies opt-in" checkbox (Settings > Discussion > `Show comments cookies opt-in checkbox, allowing comment author cookies to be set`) which previously didn't work properly and wasn't styled. 
You can see the new designs either on local or on the [jupiter](https://www-dev.greenpeace.org/test-jupiter/) test instance, on any post. There are a few scenarios to test in addition to the comments and the basic comment form in all screen sizes:
- The "Cookies opt-in" checkbox: if that option is enabled in the backend, users that are not logged in should see the option in the comment form to save …
=> PLANET-6071 Implement new comments form

src/PostCampaign.php
* The logo was using the theme name to locate the logo file, and this
name changed when we migrated to the new version.
* I just did a quick fix so we can un-break it. I'll do the clean up the
code really needs in a follow up so that these things can't slip through
that easily.
Ref: 
---
=> Fix custom logo on campaign pages 

assets/src/scss/layout/_footer.scss, src/PostCampaign.php, templates/base.twig, templates/footer.twig, themes/climate.json, themes/plastic.json
- Add classnames depending of the `nav_type`.
- If the `nav_type` is not defined, the footer will be rendered as the default one.
- Show or hide the primary and secondary nav through the css and not through the template
- Rename css variables
Demo page: https://www-dev.greenpeace.org/test-rhea/campaign/campaign-for-climate-emergency/
Ref: https://jira.greenpeace.org/browse/PLANET-6189
---
=> Improve and refactor the current Footer version

assets/src/js/app.js, assets/src/js/cookies.js, src/Settings.php
See https://jira.greenpeace.org/browse/PLANET-6223
Go to https://www-dev.greenpeace.org/test-iocaste/privacy/ to test all the possible cookie combinations (also the "Got it!" button from the cookies banner) and check that the correct events are firing.
- [plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/661)
=> PLANET-6223 Implement Google's Consent Mode on Planet 4

src/Features.php, src/MasterSite.php
Add an option to the features menu to enable theme support for the "template editor". Because this feature is not production ready for us (see list of issues below), it's made clear in the description that it's unstable. We can add the option already because internally this feature can be used for prototyping in the Information Architecture workshop.
Blocking issues for production use:
- Everything we add to the template using Twig files (for example meta tags in the head, GTM and Google Analytics tracking code) won't be present in these templates. We would need to add these to the head in another way to support them on custom templates.
- We need documentation and best practices to avoid people building things that are hard to maintain, because of the large amount of flexibility the …
=> Add optional support for "block templates"

assets/src/scss/layout/_cookies-new.scss, assets/src/scss/layout/_cookies.scss
This is to avoid breaking child themes. Initial ticket: [PLANET-6336](https://jira.greenpeace.org/browse/PLANET-6336)
You can test this new setup in the [Optimize experiment](https://optimize.google.com/optimize/home/?authuser=0&hl=en-US#/accounts/4701225997/containers/11070199/experiments/150), it should trigger the changes for the A/B test correctly.
=> Use different class for Cookies A/B test instead of additional one

templates/base.twig
* This caused campaign pages to use the inverse of the navigation
setting for the footer.
Ref: 
---
=> PLANET-6421 Fix inverted logic of minimal footer

package-lock.json, package.json
This was fixed in the package previously, but still needed to be bumped here.
To test, inspect an element that uses variables on any page of the test instance, and control + click on a CSS rule that has a generated variable (in Chrome). This should open the sources panel with the right line for the variable selected.
relevant changes: https://github.com/greenpeace/planet4-dashdash/commit/a265f9d64eaea6e1acbf10c7a0e0fec379e796e3#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R72
Ref:  https://jira.greenpeace.org/browse/PLANET-6225
=> PLANET-6225 Fix source maps for generated CSS variables

assets/src/js/external_links.js, functions.php
* Core did not take the case into account where a background-image is
not only a gradient. As a result gradient + URL combination gets
stripped out.
* Workaround: add filter that checks the remainder of the
$css_test_string. This string is progressively dismantled with stuff
they don't want to perform the check for certain characters on by WP
core. So if we remove a gradient from this and only a comma is left,
it's probably valid CSS.
Ref: https://jira.greenpeace.org/browse/PLANET-6455
TODO:
* ~~There still seems to be an issue with the scrolling script which I didn't have locally but is persistent on the test instance. We can merge this PR already but that issue might need to be fixed to fully use it as a reusable block.~~ It was just in the other repo, so created a PR there as well to …
=> PLANET-6455 Add filter to catch core bug removing gradients

assets/src/scss/pages/search/_search-results.scss
See https://jira.greenpeace.org/browse/PLANET-5799
When working on this ticket, it seems that some occurrences of the search results component were not properly updated, for instance the press releases or stories pages.
Make sure the title links behave as expected in the fixed version (in the broken one, they become blue on hover):
- [Broken](https://www-dev.greenpeace.org/test-uranus/story/)
- [Fixed](https://www-dev.greenpeace.org/test-jupiter/story/)
=> PLANET-5799 Align search results title color with design system

src/Cloudflare.php, src/CloudflarePurger.php, src/Commands/CloudflarePurge.php, src/Features.php, src/Settings.php
Necessary for https://jira.greenpeace.org/browse/PLANET-6257
Since the new designs hidden behind toggle features change some markup of the frontend,
we have to purge the relevant Cloudflare cache when we switch those features.
- Toggle is now only for Country Selector, as it can be released by itself
- Extract Cloudflare purge execution from command
- Run purge on Country Selector feature toggle
Purge command should still work as expected
```console
> wp p4-cf-purge --urls='https://planet4.test/'
About to purge 1 urls.
Chunk 0: ok
> wp p4-cf-purge --all
About to purge 1402 urls.
Chunk 0: ok
...
Chunk 46: ok
```
=> PLANET-6257: Trigger Clouflare purge on feature toggle

assets/src/scss/base/_colors.scss
See https://jira.greenpeace.org/browse/PLANET-6006
The changes requested for this ticket made this color redundant, so we can remove it 🎉 
Related PR: [plugin-gutenberg-blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/711)
You can test the new Gallery carousel in all screen sizes on [this page](https://www-dev.greenpeace.org/test-atlas/act/sail-aboard-a-greenpeace-ship/) for example, or you can simply add one to a page on local 🙂
=> PLANET-6006 Remove Gallery carousel indicator active color

assets/src/scss/base/_typography.scss, assets/src/scss/components/_buttons.scss, assets/src/scss/components/_share-buttons.scss, assets/src/scss/layout/_navbar.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6008
---
This PR also includes a fix for the regular link focus state, making it also use `outline` instead of `border` to avoid changing the layout dimensions.
The PR adds the same outline as links to buttons, and removes all the other `:focus` styles, which were always the same as the hover styles.
Still investigating:
- (Probably a separate ticket/PR) We don't have a ticket for adding the focus state around images that are a link, however it could be an improvement to include those. If you check an articles block and focus through its links, it's odd to have no indication of where your tab landed for the image only. Check video below.
- ~~The current navigation background makes the focus color almost invisible around the donate button. For …
=> PLANET-6008 Button and link focus outline

.circleci/config.yml
We need that in order to run acceptance tests on production pipelines.
To verify check [this production pipeline](https://app.circleci.com/pipelines/github/greenpeace/planet4-base/1239/workflows/b244446a-2d89-4460-a821-9c403d885f7c/jobs/6845):
1. Open the `Run tests` job.
2. Check lines 5-6. `rsync` syncs nothing because the `tests/` folder is missing.
=> Keep tests folder on zip creation

assets/src/scss/layout/_breadcrumbs.scss
This was removed in a previous commit causing tags to be too close to each other (eg. in the Articles block).
According to the [Design System](https://p4-designsystem.greenpeace.org/05f6e9516/v/15009/p/835f95-post-page/i/40590918), these still need some space in between.
=> Fix space between breadcrumb tags

assets/src/scss/editorOverrides.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6430
A CSS definition from [bootstrap on class `.btn`](https://github.com/twbs/bootstrap-sass/blob/b34765d8a6aa775816c59012b2d6b30c4c66a8e9/assets/stylesheets/bootstrap/_buttons.scss#L21) prevents CTA button from being editable on Safari.
You need __Safari on MacOS__ to test this issue.
Has to be tested with https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/725
- Edit a page, add a Carousel header, try to edit the CTA button text:
- On main branch, clicking on the CTA button doesn't have any effect,
- With this branch, a click makes a caret appear and text is editable.
=> PLANET-6430: Carousel Header - CTA button is not editable in Safari

assets/src/scss/base/_mixins.scss, assets/src/scss/base/_variables.scss, assets/src/scss/pages/_page.scss, assets/src/scss/pages/post/_post.scss, assets/src/scss/vendors/_bootstrap.scss, webpack.config.js
See [PLANET-6091](https://jira.greenpeace.org/browse/PLANET-6091)
This commit also creates the corresponding mixin for easier CSS rules.
We also need to update: 
- The donation pages: [PR](https://github.com/greenpeace/planet4-en-petitions/pull/8)
- Some blocks (CarouselHeader, Columns, Gallery) content width: [PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/716)
You can test the changes on this [test instance](https://www-dev.greenpeace.org/test-jupiter/) or on local.
=> PLANET-6091 Add new XXL breakpoint

src/MetaboxRegister.php, src/Migrations/M005TurnBoxoutSettingIntoBlock.php, src/Migrator.php
Remove the field for the Take Action Boxout and convert existing usages of the field to have the block at the end of the post content.
This should also make it easier to see the actual usage of the block (which is quite a lot).
To test: You can run the migration locally. To run it multiple times you need to remove the migration record, or temporarily exclude [the check](https://github.com/greenpeace/planet4-master-theme/blob/0dbbaa694102bc517d3690389f24afcc54e01fc0/src/MigrationLog.php#L43-L46) for this particular script in code.
You can also check the [workflows of this test instance](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-mars?branch=main).
Ref: https://jira.greenpeace.org/browse/PLANET-6450
=> Convert Take Action Boxout setting to blocks, and remove field

assets/src/scss/base/_colors.scss, assets/src/scss/base/_palette.scss, assets/src/scss/editorStyle.scss, assets/src/scss/style.scss
The classes for the palette were being duplicated by every entry point that included it, because it looked as though the file only contained SASS variable definitions.
I moved those to a separate file which is imported only in the front end and editor style entry points.
This needs to be bumped in the plugin as submodule.
=> Move palette classes to separate file

src/MasterSite.php, src/PublicAssets.php
Prioritize master-theme styles enqueue, so that the cascading order is stable.
Action `wp_enqueue_scripts` is used without any priority, and because the child-theme `functions.php` file is loaded before the master-theme one, its styles are enqueued before any style it does not declare as a dependency.
Adding a priority 0 to master-theme enqueue fixes the issue.
_Before fix, the child theme css loads before the country-selector one, which can lead to overwriting child theme rules_
_After fix, the country-selector style loads with master-theme main style file_
edit: Adding a priority < 10 makes some unit tests fail (`Trying to get property 'queue' of non-object` on global `$wp_styles` in function `wp_maybe_inline_styles()`), so we keep the default priority for now and will ask child themes …
=> Load master-theme partial styles before any child-theme

src/Commands.php, src/Commands/FixOrphans.php
The [command used to fix post authors](https://github.com/greenpeace/planet4-builder/blob/main/src/bin/sync_to_test_site.sh#L95-L97) during data sync takes a ridiculous amount of time. (approx 1.7sec per post, more than 20 min for 800 posts)
It makes some data sync fail: https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora/209/workflows/6d9e5226-aada-47f3-aa55-45b96820a1cb/jobs/1108
Some others take 40 minutes: https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora/152/workflows/4096c607-bc6c-48b7-bda8-aa84c5ee3ed9/jobs/773
Using a simple batch request and bypassing other update ripples should only take a few seconds in total.
=> Faster update command for data sync to test instances

assets/src/scss/layout/_footer.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6486
---
This way hover works again, as defined in `_footer-social-media`. We could remove this whole block, but maybe some campaign themes are using this to override colors.
=> Fix footer icons to inherit hover color

assets/src/scss/pages/_page.scss, assets/src/scss/pages/post/_post.scss, templates/author.twig, templates/evergreen.twig, templates/page.twig, templates/single-campaign.twig, templates/single-page.twig, templates/tag.twig, templates/taxonomy.twig
We have some content width/padding issues in pages on mobile, which are due to our blocks having the `container` class but not the "non-blocks" items (paragraphs for example). Also because of this we had to manually add the page width to the `page-template` element, which doesn't make sense since we use the same ones as Bootstrap anyway so we might as well use that directly 🙂 So a solution would be to remove the `container` class from the blocks (except full-width ones) (done in [this PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/737)) and add it to the `page-template` div instead.
You can see the new layout in this [test instance](https://www-dev.greenpeace.org/test-uranus), everything should look pretty much the same except with a bit less padding than before on …
=> Add container class to page-template elements

assets/src/js/external_links.js, assets/src/scss/layout/_tables.scss, assets/src/scss/pages/_evergreen.scss, assets/src/scss/pages/_page.scss, templates/author.twig, templates/evergreen.twig, templates/page.twig, templates/single-campaign.twig, templates/single-page.twig, templates/tag.twig, templates/taxonomy.twig
Ref: https://jira.greenpeace.org/browse/PLANET-5321
---
Although we use this in many places, it seems the more sane option to replace this one instead of "hacking" WP's default Page post type body classes array. It's also consistent with Post post type, where we use `.post-content` for the same purpose.
No visual change should be noticeable in the frontend. Surprisingly even the visual regression tests in this PR [passed](https://1658-251234573-gh.circle-artifacts.com/0/app/backstop_data/html_report/index.html).
=> Replace page-template with page-content as its main class

src/MasterSite.php, templates/navigation-bar-new.twig
A variable `languages` used in the new navbar template is overwriting another one already used in the current template, which triggers a Twig error on local environment for multilingual sites ( cf https://app.circleci.com/pipelines/github/greenpeace/planet4-docker-compose/787/workflows/5864e815-50ec-47b6-b7bc-df3d98065ba3/jobs/2009 )
This variable is used by the current code and other NRO templates overrides, so we're keeping the variable as it is and renaming the new one as ~`languages_list`~ `site_languages`.
Building a new multilingual site should show a twig error on the homepage
```shell
> git clone git@github.com:greenpeace/planet4-docker-compose.git pdc-fixnavbartpl
> cd pdc-fixnavbartpl
> NRO_NAME=greenland NRO_DB_VERSION=latest make nro-from-release
```
_(Any asset error is …
=> Fix template error on navbar with multilingual site

src/MasterSite.php, src/PublicAssets.php
`master-theme` styles are loaded after `child-theme` styles in some situations.
This leads to style overrides in an unexpected order.
Follows: https://github.com/greenpeace/planet4-master-theme/pull/1525
Mostly changing a default priority, and moving some enqueue code to skip it if the right file is not there.
- Ensure master-theme styles are enqueued before any child-theme style, by adding priority 0.
Most child-themes are enqueuing their styles with priority 99, but some have no priority or priority 10, which interferes with our default priority.
- Fix unit tests by dropping style enqueue if the main style is not built.
Unit tests are currently testing some frontend features and trigger styles inclusion, but they run without assets built. This way of testing triggers errors down the …
=> Fix main & partial styles enqueue order

assets/src/scss/layout/_country-selector.scss
Since interpolation already happens within the sass function
this creates some undesired effects. We can only multiple it
to change its sign.
=> Fix negative spacing interpolation

src/MasterSite.php, src/PublicAssets.php
Separate css and js enqueue so that js doesn't change priority.
Changing js priority leads to a frontend error with `wp` object undefined with a logged in user. The wp object exists in the console, but is apparently loaded too late.
This change is currently integrated on Pandora through https://github.com/greenpeace/planet4-master-theme/pull/1542/files#diff-d5a71432d6e94abc1260a448df306d8dfc76d15fa4047646a4d133c38cc131d7 , where the error was present before deployment.
=> Restore js enqueue order

assets/src/scss/layout/_country-selector.scss, templates/footer_country_selector.twig
Adjusted the markup to avoid a white space being rendered on both sides of the text. It makes the code slightly less readable, but we avoid having the underline decoration overflow on hover (check the screenshot below).
To compensate for the loss of the white space, added a bit more margin to the two icons.
=> Country Selector: Remove white space from button

assets/src/scss/base/_variables.scss, assets/src/scss/layout/_country-selector.scss, assets/src/scss/layout/navbar/_search.scss
* The previous form of the code let the front end perform calculations
which can just as well be done compile time. Since these variables are
used very frequently, this probably has a significant (though still relatively small) impact.
[PR to bump these changes in the plugin](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/749).
=> Avoid performing calculations at runtime in CSS

src/Features.php
* This solves the chicken and egg problem of a child theme needing to do
adjustments to work with a feature.
* (not included yet) We may want to visualize whether a filter exists on the options page,
and show the toggle as disabled, using the value of the filter.
A child theme would adjust their code to the new version and include the following PHP in their `functions.php`, or anywhere else that's loaded before the feature is checked for activity.
```php
add_filter( 'planet4_feature__new_design_navigation_bar`, '__return_true' );
add_filter( 'planet4_feature__new_design_country_selector`, '__return_true' );
```
=> Allow setting features with a filter

assets/src/js/header.js, assets/src/scss/layout/_navbar.scss, assets/src/scss/layout/navbar/_search.scss, src/MasterSite.php
In Planet 4 > Donate button we can set a fixed position for the donate button
This situation doesn't exist in the new navbar, and if active the button appears at the bottom of the page. We're hiding this button on the new style, and will remove the option from the scripts and backend after the transition.
Search field is not hidden when a user clicks anywhere else on the page after opening it.
This comes from a double click generated by the `closeInactiveMenus` function, that runs on the 2 toggles.
=> Remove enhanced donate button on new navbar, fix search toggle

templates/blocks/author_profile.twig
See [PLANET-6474](https://jira.greenpeace.org/browse/PLANET-6474)
This space appears when clicking on Show more, when the ellipsis is removed.
- [Broken version](https://www-dev.greenpeace.org/test-venus/story/49932/industrial-agriculture-forest-fires-climate-crisis/)
- [Fixed version](https://www-dev.greenpeace.org/test-atlas/story/49932/industrial-agriculture-forest-fires-climate-crisis/)
=> PLANET-6474 Remove space between truncated bio and remainder

assets/src/scss/editorStyle.scss, src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6538
* The Media block uses another way to get the embed HTML which doesn't
use the filter we added for WP's embed block. As a result it was still
using the default YT player which completely cripples page load
performance.
Earlier we missed the fact that WordPress actually has 2 different filters for embeds. Luckily both have the same signature so it's a really easy fix.
The results speak for themselves on a page that has only the Media block with a YouTube video.
Without fix: https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww-dev.greenpeace.org%2Ftest-mars%2Fonly-yt-video%2F
With fix: https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww-dev.greenpeace.org%2Ftest-pluto%2Fonly-yt-video%2F
Failing acceptance test should be fixed by …
=> Also add lite YouTube player on 2nd oembed filter

functions.php, src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-5968
* WPML creates copies to use in other languages which use the same file.
However they don't copy all meta. As a result the Stateless plugin
doesn't detect it should put the CDN URL.
* Remove action that was only needed to debug this issue.
Tested on the BE site and confirmed that it does create the stateless meta in all cases. I used [this image](https://www-dev.greenpeace.org/belgium/wp-admin/upload.php?item=25838) uploaded to a French post.
Interestingly the bug of the missing media only occurred when you upload an image to a post. Uploading from the media page using "add new" already seemed to create the right WP stateless meta data. Probably the previous filter (which is removed in this PR) only ran in that case.
=> PLANET-5968 Ensure translated media gets Stateless meta

assets/src/js/header.js, templates/navigation-bar-new.twig
See [PLANET-6549](https://jira.greenpeace.org/browse/PLANET-6549).
This was previously wrongly set to the svg icon instead of the actual button. The change of text (from "Open menu" to "Close menu" for example) was not implemented, probably because the button is under the menu when the menu is open so it's not visible to the user... However it's still on the page and accessible, for instance by tab or by changing the `z-index` value, so I've added the behaviour anyway 🙃 
If you check any page with the new navbar and narrow it down to a width < 992px, with the dev tools open you can inspect the hamburger menu button:
- At first you should see on it a ga-action attribute with value "Open Menu"
- When opening the menu this value should change to "Close Menu"
- When closing the menu it should …
=> PLANET-6549 Fix ga-action attribute for navbar hamburger menu

assets/src/js/search.js, search.php, src/ElasticSearch.php, src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-6338
This PR includes:
- Ensure a `function_score` is present, remove the code doubling/nesting this property
- Add a debug function, allows to check the generated Lucene query from given arguments
- Other modifications are inverted conditions to reduce indentation levels, so __hide whitespaces__ during review
Differences between regular request and ajax request in 3 steps, the last step is the query part sent to elastic (doesn't include other props like aggregation, sort, etc.)
1. How it creates or not the `function_score` property in advance
2. How it impacts the query construction
3. What the end result is before being sent to elastic
4. Lucene query
Query `?s=greenpeace+germany&orderby=post_date`
<table> …
=> PLANET-6338: Fix duplicate results in search

assets/src/scss/layout/_navbar.scss, assets/src/scss/layout/navbar/_site-logo.scss
See [PLANET-6548](https://jira.greenpeace.org/browse/PLANET-6548)
The site logo link should be as wide as the logo itself, otherwise it might be confusing for users.
With the new navbar enabled, make sure that the `site-logo` link is always the size of the actual logo, and that it's correctly positioned in all screen sizes within the bar. Also check campaign pages with the minimal navbar, to make sure it also still looks good!
=> PLANET-6548 Fix new navbar site logo link width in small screens

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6466
---
Using native filter hook [pre_comment_user_ip](https://developer.wordpress.org/reference/hooks/pre_comment_user_ip/).
Returning an empty string, same as the plugin we currently use does.
1. De-activate the "GDPR Comments" plugin.
2. Use a private/incognito window (so you are not logged in), visit a post and leave a comment.
3. One the backend in the Comments section you should see the Author's IP address.
4. Switch to this branch, are add one more comment.
5. In the backend there should be no IP address visible for the new comment Author.
6. Re-test that with plugin enabled. No IP either as expected. We can leave the plugin running till we also have [PLANET-6465](https://jira.greenpeace.org/browse/PLANET-6465) in place.
Below a …
=> PLANET-6466 Anonymize Comment Authors IP address

assets/src/scss/layout/_navbar.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6572
---
Switch to using a high number since we want the navbar to be always on top of everything else.
Current code makes Submenu block float over the navbar. To test just use a page with a Submenu block and switch branches.
- [Current behavior](https://www.greenpeace.org/belgium/fr/faq/)
- [This branch](https://www-dev.greenpeace.org/test-nix/explore/)
=> PLANET-6572 Use a high z-index number for navbar

assets/src/scss/editorOverrides.scss
Customizer font is really big since it's inherited from our theme.
Since it's on a sidebar a decreased size makes it a bit easier to read.
Changes:
- Decreases font-size
- Decreases line-height
=> Adjust CSS Customizer typography for readability

src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-6574
* This doesn't seem to do anything anymore, except breaking the media
library because we reduced the check.
The code also has a similar filter in other places which is what is actually used https://github.com/greenpeace/planet4-master-theme/blob/cff56634ca62b529132be26307cdb35190cbbbc4/src/ElasticSearch.php#L246-L269.
=> PLANET-6574 Remove unneeded filter that broke media library

assets/src/scss/layout/navbar/_search.scss
See https://jira.greenpeace.org/browse/PLANET-6542
I couldn't think of a way to achieve this without JS, but maybe there's one? Suggestions welcome 🙃 
On screens > 1200px, the navbar search icon should be disabled if the search input is empty. When typing in the input, the button should no longer be disabled, and when clicking on it the form should be submitted as expected.
=> PLANET-6542 Disable search button when search input is empty

assets/src/js/app.js, assets/src/js/search.js, assets/src/scss/pages/search/_search-results.scss, templates/search.twig, templates/tease-search.twig
See [PLANET-5761](https://jira.greenpeace.org/browse/PLANET-5761)
This is part of a bigger epic to completely remove jQuery from the frontend. For now I haven't touched the AJAX call, since if I understood correctly this part might change soon?
You can test the changes on the [iocaste test instance](https://www-dev.greenpeace.org/test-iocaste/?s=&orderby=_score), make sure that everything behaves as expected:
- Searching specific terms
- Changing the sorting order
- Adding and removing filters (this behaviour should be tested on mobile too, where a modal is used)
- Showing more results (first by scrolling down the page, and then by clicking on the button)
- Clicking on the image or title of a search result to go to the corresponding page
=> PLANET-5761 Remove jQuery from search

templates/single.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6505
* It didn't have the ID which always resulted in the default Gravatar
image.
* Check not needed in the bottom bio because that is not included for
overridden authors.
=> PLANET-6505 Remove author image in case of author override

admin/css/campaign.css, admin/css/options.css, src/Settings.php
Some of our field descriptions are really long that wrap and look unreadable. This minor tweak just uses grid, instead of float, to make them at least align properly.
=> Use grid for Planet 4 admin options

src/Features.php, src/Migrations/M006MoveFeaturesToSeparateOption.php, src/Migrator.php, src/Settings.php
Ref: https://jira.greenpeace.org/browse/PLANET-6536
* This ensures we can make those features non-translatable.
* Include migration script which will run on post-deploy. It's important
that no one touches the settings between releasing the code and running
post-deploy.
* In the feature check, fallback to the old options key if the new one
was not created yet. If someone makes a feature change before this
script runs, their input will be reset.
Should be just 2 steps:
1. After merging this PR (and post-deploy ran) it will already use the new option record when checking features. The code falls back to the old option record as long as the new one wasn't created (short time between deploy and post-deploy).
2. Clean up: Remove the migration script and code fallback. Remove feature settings …
=> PLANET-6536 Move feature settings to a separate WP option

templates/tease-author.twig, templates/tease-taxonomy-post.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6593
---
This includes:
- [Post type](https://www-dev.greenpeace.org/test-venus/story/)
- [Author page](https://www-dev.greenpeace.org/test-venus/author/admin/) (where actually only `Stories` have reading time)
- [Category listing](https://www-dev.greenpeace.org/test-venus/explore/about/)
- [Tag listing](https://www-dev.greenpeace.org/test-venus/tag/fires/)
I was tempted to align all these meta details to use the same markup as the Articles block, but since we are planning on revamping these pages anyway, I kept the scope just on adding the reading time markup.
=> Add reading time to listing pages

src/Features.php, src/MasterSite.php
* To enable on the gutenberg instance, where all blocks are allowed.
I first started setting up a test instance to also have [all blocks allowed + allow block patterns](https://www-dev.greenpeace.org/test-deimos/wp-admin/admin.php?page=planet4_settings_core_blocks). But the Gutenberg instance is on the latest RC of WordPress 5.9, so it also has newly added core block patterns which would be nice to test. It's also nicer to have other team members work with the Gutenberg instance they're more familiar with.
=> Add feature toggle for core block patterns

assets/src/scss/components/_share-buttons.scss
=> Update pseudo selectors for buttons

src/Features.php, src/MasterSite.php
WP_APP_ENV on local environment is "local" by default, so these Feature flags are currently hidden.
Also reworded some help texts to make them more readable.
Switching your local `wp-config.php` and changing `WP_APP_ENV` should reveal or hide these options.
=> Enable experimental features on local environment too

assets/src/scss/layout/_breadcrumbs.scss, templates/single.twig
See [PLANET-6512](https://jira.greenpeace.org/browse/PLANET-6512)
This includes removing the tags and updating the separators between the post type and the categories. It also removes the uppercase style on the post type.
**Note**: these breadcrumbs are used in a few other places, such as the Articles block or some templates (such as the author page), but I think this ticket was only about updating the posts' navigation links. The only change that will be applied everywhere is the uppercase removal, which I think will eventually be completely removed anyway.
You can test the changes on your local on any post, or you can see them on the atlas test instance that has been set up for UAT: for example, you can check out [this post](https://www-dev.greenpeace.org/test-atlas/press-release/49484/r …
=> PLANET-6512 Update post top links

assets/src/js/header.js
Ref: https://jira.greenpeace.org/browse/PLANET-6577
Add a focus listener to the search input field, which fires once per page load.
This also contains a minor clean up to related code.
=> PLANET-6577 Hj search event

tests/acceptance/HomePageCept.php
The report https://2193-89261592-gh.circle-artifacts.com/0/artifacts/codeception/report.html
seems to indicate the page is not finished loading when we try to click on a footer button.
This make the local build pipeline fail https://app.circleci.com/pipelines/github/greenpeace/planet4-docker-compose/840/workflows/989bf053-2865-478c-a26c-9f5098e2801e
Waiting a bit until the button is clickable.
=> Fix HomePage test failure on local build

src/Settings.php
See https://jira.greenpeace.org/browse/PLANET-6603
This is to be used in the Cookies box but also as default values for the Cookies block
Related blocks PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/766
You can check the new settings on local (`Planet 4 > Cookies`), or on the [neptune test instance](https://www-dev.greenpeace.org/test-neptune/wp-admin/admin.php?page=planet4_settings_cookies_text). Then once you set some values there, you can add a Cookies block to a page and see those values appear as default in the various fields.
=> PLANET-6603 Add Cookies text fields to settings

assets/src/scss/layout/_breadcrumbs.scss
The space between tags in the breadscrumbs had been removed by mistake when adding the new separators between categories in post navigation links. 
You can find these tags in several places, the easiest one to check is probably in an Articles block. Make sure the new post navigation links also still look as expected!
=> Fix tags spacing in breadcrumbs

src/Settings.php
Ref: https://jira.greenpeace.org/browse/PLANET-6622
* To make it more clear this label is only used in the country selector.
=> PLANET-6622 Rename navigation title option

functions.php
Ref: https://jira.greenpeace.org/browse/PLANET-6611
Make `post_type` a hidden column by default. The Post Type Switcher plugin doesn't do this, even though it doesn't depend on the column being visible to work.
Showing the column is a bit pointless because all listings only ever have a single post type.
The only advantage of having it a visible column is it allows you to see the different type after switching. But only when using "Quick edit" in the listing view. It's because quick edit doesn't refresh the page but updates in place.
=> PLANET-6611 Hide post type in admin listings

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6614
> it is impossible to set the main tag (and the other page tags) in a custom order, because when there is more than 1 tag upon page save the tags get automatically rearranged in alphabetical order. 
Post tags are not ordered by default, so order is lost on save, and never used on fetch.
Using [`register_taxonomy_args`](https://developer.wordpress.org/reference/functions/register_taxonomy/) hook to
- set `sort` parameter for keeping order when saving post tags
- set `args` parameter for using order when fetching post tags
This configuration forces the use of the DB field `wp_term_relationships.term_order`.
- Edit a new page
- Add tags in a different order than alphabetical (ie `Ocean, Coal, Forest`)
- Clicking on the `Save draft` button …
=> PLANET-6614: Save post tags as ordered

src/ElasticSearch.php, src/Search.php
Ref: https://jira.greenpeace.org/browse/PLANET-6589
Ref: https://jira.greenpeace.org/browse/PLANET-6590
Ref: https://jira.greenpeace.org/browse/PLANET-6588
An empty `act_page` option will result in an empty search term in the post_parent filter.
This empty term raises an ElasticSearch error:
- `QueryShardException[failed to create query`,
- `NumberFormatException[empty String];; java.lang.NumberFormatException: empty String`
Adding conditions on act_page value fixes the referenced issues for the Handbook.
I used the function added last time I had to debug the search functionality, here's a var_dump version :grin: 
```diff
diff --git a/src/ElasticSearch.php b/src/ElasticSearch.php
index e1730393..b383a152 100644
--- a/src/ElasticSearch.php
+++ b/src/ElasticSearch.php
@@ -102,6 +102,15 @@ …
```
=> PLANET-6589: Fix search error when act page not selected

assets/src/js/header.js, assets/src/scss/layout/_navbar.scss, assets/src/scss/layout/_page-header.scss, assets/src/scss/layout/navbar/_search.scss, assets/src/scss/layout/navbar/_site-logo.scss, assets/src/scss/layout/navbar/mobile.scss, assets/src/scss/pages/_page.scss, assets/src/scss/partials/navigation-bar-light.scss, src/MasterSite.php, src/Settings.php, src/Settings/InformationArchitecture.php, templates/navigation-bar-new.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6510
> Navigation Bar: implement a tabs menu on mobile
> The tabs should lead to each parent/category page of the site.
> They should have a selected state on the frontend regardless the level of hierarchy (example: Parent page > sub page).
> To view all items users would be able to swipe horizontally.
> The tabs menu should be sticky at the top and disappear when users start scrolling down the page.
for all Information Architecture options, in _Planet 4 > Information architecture_
Activate this navigation menu:
Menu is visible on `width < 992px`
- Menu height is now 60px on width < 992px, (+50px if tabs menu is enabled)
- Menu links alignement with the Design iteration 2 (underline color, offset and animation, switch from padding to margin …
=> PLANET-6510: Navigation bar - Tabs menu on mobile

src/Features.php
* This way we don't need a branch to allow blocks on the [gutenberg instance](https://github.com/greenpeace/planet4-gutenberg/blob/46c4a5f68e3879c6cac19856819957f300ed066e/composer-local.json#L6), making it much easier to test branches on that instance without having to merge them with the all_blocks branch.
Used in https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/785
=> Add toggle to allow all blocks on development environments

src/Settings.php
Ref: https://jira.greenpeace.org/browse/PLANET-6496
Related to: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/781
Add a setting in _Planet 4 > Defaults content_ to use either iframe or embed code as default HappyPoint form.
Test with https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/781 locally, or [on Pluto](https://www-dev.greenpeace.org/test-pluto/)
This option should make the selected form appear by default on any **new** HappyPoint (if the corresponding form value is also filled in Defaults content) - see [this Jira comment](https://jira.greenpeace.org/browse/PLANET-6496?focusedCommentId=244914&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-244914) for more details.
=> PLANET-6496: HappyPoint global switch and default content

src/Migrations/M008RemoveArticlesDefaultOptions.php, src/Migrator.php, src/Settings.php
Ref: https://jira.greenpeace.org/browse/PLANET-6440
These global settings are confusing for the users as they are not used anymore
- Default title for related articles block
- Default button title for related articles block
- Default Number Of Related Articles
Test the patch locally:
```shell
> docker-compose exec php-fpm wp option get planet4_options | grep article
> docker-compose exec php-fpm wp p4-run-activator
> docker-compose exec php-fpm wp option get planet4_options | grep article
```
=> PLANET-6440: Remove unused related articles settings

tests/acceptance/campaign.feature
Ref: https://jira.greenpeace.org/browse/PLANET-6615
Related to: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/790
Make the Global project field non mandatory to be able to save campaign pages despite issues with the global sheet
=> PLANET-6615: Make Global project field non mandatory

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6480
---
Checking [WP_APP_ENV](https://github.com/greenpeace/planet4-docker/blob/a4d8b32057469834b2798e861e5da1de1f96ce98/src/planet-4-151612/wordpress/wp-config.php.tmpl#L66-L68). If it's production or staging hide the CSS Customizer.
1. Get inside the php container: `make php-shell`
2. Edit `public/wp-config.php`
3. Test with changing `WP_APP_ENV` variable. It should already be there if you have a recent environment. Oherwise you would need to add it /eg. `define( 'WP_APP_ENV', 'local' );`
=> PLANET-6480 Disable CSS Customizer on production

single-p4_action.php, src/ActionPage.php, src/Loader.php, src/Settings/InformationArchitecture.php
**Task:**
- Introduce a new Action page post type with Action Type taxonomy
- Added a Feature flag for Action page type menu in admin
Ref. https://jira.greenpeace.org/browse/PLANET-6515
**Testing:**
- After check out of `PLANET-6515-action-page-type` branch on local dev environment , go to "WP admin >> Planet4 >> Features" setting
- Enable the `Information Architecture >> Enable Action post type` setting
- After enabling the above setting you will able to see the new menu (Actions) in admin sidebar below the Pages menu
- Check the taxonomy available for "Action" page type
- The action pages should use the same layout as pages
=> PLANET-6515 Add new Action page type and Action Type taxonomy

assets/src/scss/layout/navbar/_search.scss
It should adapt to the bigger height of the navbar for screen widths between 992px and 1200px.
You can see the fixed version on the [sinope test instance](https://www-dev.greenpeace.org/test-sinope/) or on local. You can see the broken version on the [GPI site](https://www.greenpeace.org/international/) for example!
=> Fix navbar search position in large screens

src/Migrations/M009PopulateCookiesFields.php, src/Migrator.php
Ref: https://jira.greenpeace.org/browse/PLANET-6644
:warning: **Requires: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/792** :warning:
A patch to gather Cookies block data and populate _Planet 4 > Cookies_ settings with.
Only published pages with a Cookies block are fetched for this operation (no draft, post, etc.).
Test locally by using various NROs and running the patch.
On local test, pay attention to the wpml plugin activation/deactivation, as it can stay active if you switch from a multilingual to a monolingual NRO, in which case the patch wouldn't work.
- Check the current _Planet 4 > Cookies_ settings
- Run patch with `docker-compose exec php-fpm wp p4-run-activator`
- Check again the _Planet 4 > Cookies_ settings, for each language, it should be populate with …
=> PLANET-6644: Set cookies settings from cookies block data

assets/src/js/cookies.js, assets/src/scss/layout/_cookies-settings.scss, assets/src/scss/layout/_cookies.scss, assets/src/scss/style.scss, src/MasterSite.php, src/Settings.php, templates/cookies.twig, templates/cookies/cookies_settings.twig, tests/acceptance/CookiesBannerCept.php
See https://jira.greenpeace.org/browse/PLANET-6075
**Related PR:** [blocks](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/779)
You can see the new Cookies box with settings on the [jupiter test instance](https://www-dev.greenpeace.org/test-jupiter/), please check the design in all screen sizes. You can also change the texts in the settings (`Planet 4 > Cookies`) and make sure that all is updated properly, knowing that leaving a label or description empty will hide them in the box. Also try adding/removing the `Reject all` option (in the same settings section). I'll ping Julia to make sure the analytics part is working as expected and the correct events are fired 🙂
=> PLANET-6075 Add settings to Cookies box

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6648
---
This needed for embedding PDFs with the core File block.
=> PLANET-6648 Add object tag on Posts

assets/src/js/header.js, assets/src/scss/layout/_navbar.scss, assets/src/scss/partials/navigation-bar-light.scss, src/AdminAssets.php, templates/navigation-bar-new.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6509
👉 [Parent PR](https://github.com/greenpeace/planet4-master-theme/pull/1628)
Navigate to the [instance](https://www-dev.greenpeace.org/test-nix/) and play around with the menu.
Also go to:
`Planet4 > Navigation` and change the **Website Navigation Style** to `dark|light`
**What to test**
- Validate the Design iteration2_IA & nav MVP from [here](https://www.figma.com/file/Gn8wyqgto7608rlESePXZE/Foundations-%26-Components?node-id=0%3A103).
- Analytics vars set to the sub-menu items.
**New CSS variables**
```
--submenu-nav-link--color
--submenu-nav-link--hover--color
--submenu-nav-link--font-size
--submenu-nav-link--font-weight
```
=> PLANET-6509: Navigation Bar styling drop-down menus

assets/src/js/menu_editor.js, assets/src/scss/layout/_navbar.scss, src/AdminAssets.php, src/MasterSite.php, src/Settings.php, templates/navigation-bar-new.twig, templates/navigation-submenu.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6579
👉 [Parent PR](https://github.com/greenpeace/planet4-master-theme/pull/1628)
- First, check if the Donate menu has items already added going to `Appearence > Menus`
- Navigate to the [instance](https://www-dev.greenpeace.org/test-rhea/) and play around with the Donate menu.
Also go to:
`Planet4 > Navigation` and change the **Website Navigation Style** to `dark|light`
**What to test**
- Validate the Design iteration2_IA & nav MVP from [here](https://www.figma.com/file/Gn8wyqgto7608rlESePXZE/Foundations-%26-Components?node-id=0%3A103).
- Analytics vars set to the sub-menu items.
=> PLANET-6579: Allow a drop down menu for the Donate button through the Navigation Bar

assets/src/scss/layout/_footer-social-media.scss, templates/footer.twig
See [PLANET-6656](https://jira.greenpeace.org/browse/PLANET-6656)
In the backend it is possible to remove all social media links, in this case we should completely hide the social media part of the footer including the Follow us text.
I've removed all social media links from the [deimos test instance](https://www-dev.greenpeace.org/test-deimos/), with the fix you can see that in the footer the `Follow us` link no longer shows! Before the fix it shows like this:
=> PLANET-6656 Hide Follow us link when no social media links

assets/src/scss/editorStyle.scss, src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6647
> Videos added using the Youtube embed block disappear in the editor.
> The block is still there, but has a height of 0 in Gutenberg as a preview. Videos do show up in the frontend, so it's only the preview and editing that doesn't work.
Gutenberg editor is forcing an iframe for any embed, which doesn't allow for lite-youtube styles to be applied.
Cf. Gutenberg [embed preview component](https://github.com/WordPress/gutenberg/blob/aa05bd47df3247730065b197a170ab84e4c6761f/packages/block-library/src/embed/embed-preview.js#L96) and [sandbox component](https://github.com/WordPress/gutenberg/blob/d5915916abc45e6682f4bdb70888aa41e98aa395/packages/components/src/sandbox/index.js#L94) 
Removing lite-youtube integration in the editor fixes the …
=> PLANET-6647: Youtube Embed - block not showing in the editor

assets/src/scss/pages/_page.scss
See [PLANET-6663](https://jira.greenpeace.org/browse/PLANET-6663)
Before this fix the input would go off-screen in small screen widths:
In your local env, create a password-protected page or post, then check it in a small screen (< 400px). On `master` branch you'll see that the input goes off-screen, whereas on this branch it doesn't.
=> PLANET-6663 Fix password input width on mobile

assets/src/scss/pages/post/_comments-form.scss, single.php, src/Migrations/M010RemoveGdprPluginOptions.php, src/Migrator.php, src/Settings.php, src/Settings/Comments.php, templates/comment_form/submit_button.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6465
> This a follow up from [PLANET-6454](https://jira.greenpeace.org/browse/PLANET-6454) and the fact that the [GDPR Comments](https://wordpress.org/plugins/gdpr-comments/) plugin in not maintained anymore. This ticket is about implementing one of its functions: opt-in checkbox.
This PR 
- adds a checkbox to the comments form, disabling the submit button
- disables the _GDPR Comments_ plugin and removes its options
Settings in _Planet 4 > Comments_
_Checkbox displayed in the comments form_
- Activate the GDPR option in _Planet 4 > Comments_
- Visit a post, check the comments section
- The GDPR checkbox should be unchecked and the submit button disabled
- Check the GDPR checkbox, the submit button is enabled
- Run patch
`docker-compose exec …
=> PLANET-6465: Add opt-in checkbox for submitting the comments form

assets/src/scss/components/_buttons.scss
See [PLANET-6659](https://jira.greenpeace.org/browse/PLANET-6659)
With the upgrade to WP5.9 some of our styles for this button type were overridden in the frontend.
In your local env, add a "File" block to a page and check the option "Show download button" in the sidebar. In the frontend on `master` branch you will see the broken version of that button, but on this branch you should see it styled as a secondary button as expected.
=> PLANET-6659 Fix Download file button styles

assets/src/scss/components/_buttons.scss, assets/src/scss/layout/_cookies-settings.scss, assets/src/scss/layout/_cookies.scss, templates/cookies.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6664
Was needlessly wrapping specific selectors inside the element they happened to be in.
Also duplicate media queries instead of selectors. That way it's always close to the thing it's overriding.
[Hide whitespace changes](https://github.com/greenpeace/planet4-master-theme/pull/1646/files?diff=split&w=1)
It's easier if we merge this simplification first, as it should not change any behavior. After that I'll open a PR to address the button ellipsis issue.
=> Unwrap cookies CSS

src/CustomTaxonomy.php
* Possibly a past rebase mishap. A function with almost the same name
does exist which is in fact used, add_terms_rewrite_rules.
* Also clean up duplicate array key.
The usage was removed in the [PR that added the similarly named function](https://github.com/greenpeace/planet4-master-theme/pull/701/).
=> Remove unused function add_terms_as_rewrite_rules

assets/src/scss/base/_mixins.scss, assets/src/scss/layout/_navbar.scss, assets/src/scss/layout/navbar/_burger-menu.scss, assets/src/scss/layout/navbar/languages.scss, templates/burger-menu-items.twig, templates/burger-menu.twig, templates/navigation-bar-new.twig, templates/navigation-submenu.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6509
👉 [Parent PR](https://github.com/greenpeace/planet4-master-theme/pull/1628)
Go to the [Demo page](https://www-dev.greenpeace.org/test-titan) and play around the main navigation.
**What is done**
- Is changed the way of showing the main navigation on mobile version.
- Isolated markup with own styles
- Refactored code
Navigate to the [instance](https://www-dev.greenpeace.org/test-titan/) and play around with the **mobile menu**.
Also go to:
`Planet4 > Navigation` and change the **Website Navigation Style** to `dark|light`
**What to test**
- Validate the Design iteration2_IA & nav MVP from [here](https://www.figma.com/file/Gn8wyqgto7608rlESePXZE/Foundations-%26-Components?node-id=0%3A103).
- Analytics vars set to the …
=> PLANET-6511: Navigation Bar: implement the new design (mobile)

src/AnalyticsValues.php, src/Commands/CloudflarePurge.php, src/Feature.php, src/Features.php, src/Features/CloudflareDeployPurge.php, src/Features/Dev/AllowAllBlocks.php, src/Features/Dev/BetaBlocks.php, src/Features/Dev/CoreBlockPatterns.php, src/Features/Dev/ThemeEditor.php, src/Features/Dev/WPTemplateEditor.php, src/Features/EngagingNetworks.php, src/Features/GoogleSheetReplacesSmartsheet.php, src/Features/ImageArchive.php, src/Features/LazyYoutubePlayer.php, src/Features/NewDesignCountrySelector.php, src/Features/NewDesignNavigationBar.php, src/Features/PurgeOnFeatureChanges.php, src/ImageArchive/Rest.php, src/ImageArchive/UiIntegration.php, src/MasterSite.php, src/Migrations/M001EnableEnFormFeature.php, src/Migrations/M002EnableLazyYoutube.php, src/PublicAssets.php, src/Settings.php
With more and more features, the previous implementation that contained all feature related data in a single file became hard to manage.
We could further combine effects of each feature inside of the class, such as conditionally loading stylesheets.
This branch should result in the same behavior as `master`. With [one exception](https://github.com/greenpeace/planet4-master-theme/pull/1650/files#diff-ecf1d8c1cedf861e4a52c13d299a24fc41ebadbecc85d321eacbf40b4a3b3799L201-L211): There was 1 feature set up to only be allowed locally, but it's a leftover that we can remove instead. This avoids needing to add local only features support to the class definition.
Needs to be tested together with the [plugin PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/813). You can see the …
=> Use a class per feature

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6583
Ref: https://github.com/WordPress/wordpress-develop/blob/f7d2a2ee9d003633e6c729c0835cd4addd23f9b3/src/wp-includes/class-wp-theme.php#L1470
---
It seems that with 5.9 the template editor is enabled by default if there is a `theme.json` present.
=> Reverse logic on template editor feature

load-class-aliases.php, src/ImageArchive/Rest.php, src/ImageArchive/UiIntegration.php, src/Loader.php, src/Migrations/M006MoveFeaturesToSeparateOption.php, src/Notifications/Slack.php, src/Settings.php, src/Settings/Features.php
* This way we don't have an identifier that is both a class name and a
namespace. This actually caused issues doing this rename, where my IDE
incorrectly changed a few usages of things in the `Features` folder.
As suggested in https://github.com/greenpeace/planet4-master-theme/pull/1650#discussion_r829172374
=> Move Features into Settings\Features

assets/src/scss/base/_colors.scss, assets/src/scss/base/_palette.scss, assets/src/scss/components/_buttons.scss, assets/src/scss/editorOverrides.scss
See [PLANET-6668](https://jira.greenpeace.org/browse/PLANET-6668), the [example page](https://www-dev.greenpeace.org/gutenberg/new-p4-blocks/) and the [designs](https://www.figma.com/file/leueo1LMrlPabJkZYs2NgW/IA%26nav_Final-mockups?node-id=1%3A1650)
This PR includes adding the "Dark Green" color to our palette, and creating the transparent button styles.
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/814
You can test the new pattern on [this page](https://www-dev.greenpeace.org/test-oberon/51007-2/) for example, or on your local.
=> PLANET-6668 Implement Highlighted CTA pattern

assets/src/scss/base/_colors.scss, assets/src/scss/base/_palette.scss
See [PLANET-6668](https://jira.greenpeace.org/browse/PLANET-6668)
Houssam  asked that we replace the previously used dark green color by our existing dark blue, since we'll only start using the dark green in our future new identity. Therefore I've removed it from our color palette for now.
**Related PR**: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/817
=> PLANET-6668 Remove dark green color from our palette

assets/src/scss/components/_buttons.scss
See [PLANET-6696](https://jira.greenpeace.org/browse/PLANET-6696)
This visited color was recently [removed from the generic btn class](https://github.com/greenpeace/planet4-master-theme/commit/c7d37155f9ca66547ef6a3d53ed2db938520c011) but we forgot to add it to the primary class 😬 
On your local, you should see your visited primary buttons with the generic link visited color (purple) on `master` branch, whereas on this branch you should see them with the white color.
=> PLANET-6696 Add white color to visited primary buttons

single.php, src/MetaboxRegister.php, src/Migrations/M011TurnIncludeArticlesSettingIntoBlock.php, src/Migrator.php, templates/single.twig
Ref. https://jira.greenpeace.org/browse/PLANET-6612
- Remove "Include Articles in post" setting from add/edit post
- Remove unused code of TAB setting(https://jira.greenpeace.org/browse/PLANET-6450)
**To test:** You can run the migration locally. To run it multiple times you need to remove the migration record, or temporarily exclude [the check](https://github.com/greenpeace/planet4-master-theme/blob/PLANET-6612-include_articles_migration/src/MigrationLog.php#L44-L46) for this particular script in code.
Related PR: https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/795
=> PLANET-6515 Migrate "Include Articles In Post" setting to a regular Articles block on Post

assets/src/scss/editorOverrides.scss
See [PLANET-6690](https://jira.greenpeace.org/browse/PLANET-6690)
This is only for the Button block, other block overrides will be handled in another PR. 
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/823
You can test this on your local or on the [titan test instance](https://www-dev.greenpeace.org/test-titan/), by adding a Button block in the backend. It should by default have the secondary style, and the only other available style should be `Primary` (`Donate` has been removed from the style picker, all the corresponding classes and styles will be removed later as part of [PLANET-6698](https://jira.greenpeace.org/browse/PLANET-6698)). Please also make sure the buttons are still correctly styled in the frontend too.
=> PLANET-6690 Use secondary style by default on buttons in the editor

theme.json
See [PLANET-6690](https://jira.greenpeace.org/browse/PLANET-6690)
This includes adding our background color options, plus hiding the text color selector and the default WP color palette. The background color can now be changed for the block in the sidebar, in `Color > Background`.
The only thing I'm wondering is how to implement translations for this file, but that can be handled later 🤔 
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/825
You can test the new version of the Table block on your local or on the titan test instance, for example on [this page](https://www-dev.greenpeace.org/test-titan/table-block-tests/) I created with all the possible colors!
=> PLANET-6690 Update Table block settings in theme.json

assets/src/scss/layout/navbar/mobile.scss, assets/src/scss/partials/navigation-bar-light.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6702
Demo page (pending)
[Design](https://www.figma.com/file/Gn8wyqgto7608rlESePXZE/Foundations-%26-Components?node-id=0%3A103)
Message from Mag
> I noticed that the tabs menu on mobile doesn’t have the right color when the menu items are with the default state. They should use this color #6F7376
Also fixed active colors on Light and Dark themes.
=> PLANET-6702: Fix Mobile nav link color

assets/src/js/cookies.js, templates/blocks/google_tag_manager.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6625
> Fix Google's Consent Mode default state. 
> The default state should be included in all pages before the user gives consent/interacts with the cookies box. This means that the default values for 'ad_storage' and 'analytics_storage' should be set to'denied' in all pages until it's explicitly changed by the user. 
Added a `defaultGoogleConsent()` function, and always run either `defaultGoogleConsent` or `updateGoogleConsent` function as long as `ENABLE_GOOGLE_CONSENT_MODE` is activated.
Test was done by UAT. Code is deployed on [Tavros](https://www-dev.greenpeace.org/test-tavros/)
- Activate Google conset mode in _Planet 4 > Analytics_
- Navigate to homepage
- If asked, save cookies preferences and reload page 
- Check the content of …
=> PLANET-6625: Set default consent mode on every page

single.php, src/ActionPage.php, src/Feature.php, src/Features/ActionPostType.php, src/Features/GdprCheckbox.php, src/Features/MobileTabsMenu.php, src/MasterSite.php, src/Migrations/M001EnableEnFormFeature.php, src/Migrations/M002EnableLazyYoutube.php, src/Migrations/M010RemoveGdprPluginOptions.php, src/Settings/Comments.php, src/Settings/InformationArchitecture.php
Ref: https://jira.greenpeace.org/browse/PLANET-6729
I missed this part while rebasing the feature classes introduced in https://github.com/greenpeace/planet4-master-theme/pull/1650.
Create a class combining each feature's info.
I had to preserve `is_active` to avoid chicken and egg situation in the tests, as the plugin also uses it.
I also included a convenience method for enabling, to use in upgrade scripts.
Last minute we added a small improvement to distinguish dev only toggles. Created separate ticket [PLANET-6728](https://jira.greenpeace.org/browse/PLANET-6728) for the release notes.
=> PLANET-6729 Make IA features use feature classes

assets/src/scss/layout/navbar/_search.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6551
Tested on iPad Pro Simulator (xCode)
You'll need to use a real device or an alternative is to use a native simulator (xCode). Validate also on Desktop to check that nothing is broken.
Before:
After:
=> PLANET-6551: Fix navbar issue on ipad pro

assets/src/scss/pages/post/_article-content.scss, assets/src/scss/pages/post/_post.scss, assets/src/scss/post.scss, assets/src/scss/style.scss, src/PublicAssets.php, webpack.config.js
Ref: https://jira.greenpeace.org/browse/PLANET-6730
Easier [with whitespace hidden](https://github.com/greenpeace/planet4-master-theme/pull/1660/files?diff=split&w=1).
Put all CSS that is only needed on posts in a separate entry point. This is then included in the same cases by checking post type before enqueuing (post, attachment, and idea).
TODO:
=> PLANET-6730 Split post css

assets/src/scss/layout/_block-classes.scss, assets/src/scss/style.scss, functions.php, parts/query-grid.html, parts/query-list.html, src/Feature.php, src/Features/Dev/DisableTagRedirectPages.php, src/Features/Dev/ListingPageGridView.php, src/Features/Dev/ListingPagePagination.php, src/Post.php, src/Settings/Features.php, tag.php, templates/tag.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6645
As a first step of using paginated lists, the new list is only added to tag pages.
Define query loop block in HTML and use it to output almost the same markup as our Articles block.
We can gradually rewrite the CSS to make more sense with the core block, but using Article's existing CSS classes makes ensuring the same layout much easier.
I used a few **feature toggles** to aid development (just a few small if-statements really). We can probably remove them before merging.
* [Toggle old server generated pages / paginated list](https://github.com/greenpeace/planet4-master-theme/blob/e1cbd068bb0e5d31cef28f531d1d71885961a7c0/tag.php#L70-L70) (could be useful for releasing)
* [Toggle Grid / …
=> PLANET-6645 Add paginated list on tag pages

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6671
> Nginx: Request Header Or Cookie Too Large
> Editors get this error sometimes. Workaround is to clear their cookies.
It is possible to replicate the issue with a header over 8KB.
We want to understand if some specific cookies are growing over a certain limit. Log to sentry when cookies are over 4KB.
Capture example: https://sentry.greenpeace.org/organizations/greenpeace-org/issues/138/?project=2&query=is%3Aunresolved
I thought about logging only 1 in 2/10 events in case we have a lot, but this situation shouldn't be too common.
=> PLANET-6671: Log cookie issue

assets/src/scss/layout/navbar/_burger-menu.scss, templates/burger-menu-items.twig, templates/burger-menu.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6673 
Cleanup PR after we merged https://github.com/greenpeace/planet4-master-theme/pull/1628
We glossed over some parts of the code to unblock merging the branch. There's a few things that would be nice to address before we need to worry about child theme overrides. Mainly the CSS specificity as overrides would likely copy it.
I'll start with addressing some basic things, like using tabs inside Twig files and indentation. After that we can see if there's more room for improvement, but maybe it's better to merge these already to provide a cleaner basis to work on.
Maybe easier to see the CSS changes [with whitespace hidden](https://github.com/greenpeace/planet4-master-theme/pull/1672/files?diff=split&w=1).
I'm pretty sure that after we make …
=> Clean up burger menu code

assets/src/js/cookies.js
See [PLANET-6705](https://jira.greenpeace.org/browse/PLANET-6705)
After the recent Cookies changes we did, the cookie we set for the last visited NRO is considered as 1st party, so it should be fired right away without waiting for user consent. It should also be updated when switching sites.
On local, you can switch to this branch and open http://www.planet4.test/ in an incognito window, then in the development tools you can check the cookies and you should see the `gp_nro` cookie set right away, along with the `greenpeace` one. On `master` branch you should notice only the `greenpeace` one is set on the first visit.
=> PLANET-6705 Treat gp_nro cookie as 1st party cookie

assets/src/scss/base/_mixins.scss, assets/src/scss/layout/navbar/_burger-menu.scss, templates/burger-menu.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6673
Some further low hanging fruit improvements to the code, mostly making it do the same with less lines of CSS.
I also used `d-lg-none` in favor of CSS rules to hide other elements.
~~Each commit is a separate fix, please refer to the commit messages for more detailed info.~~ I'll probably rebase it as now the latest fix supersedes some of the previous commits.
I ended up using transforms instead for the open and close animation. If you do `translateX(-100%)`, it always uses 100% of the width of that element. Whereas `inset-inline-start` needed CSS per screen size, as % there uses the parent container as a reference.
=> PLANET-6673 Burger menu fixes

templates/navigation-bar-new.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6733
Demo page: https://www-dev.greenpeace.org/test-neptune/
**Solution**
Moved the element outside the main nav desktop element since is not displayed on large screens because of the `ds-lg-none` class.
**Testing**
Go to international dev instance and resize the screen to <992px, then click on the search button. The search form might be visible.
=> PLANET-6733: Nav search form is hidden on large screens

templates/navigation-bar-new.twig
This is a semantic (probably a nice to have) change and opened for suggestions.
Is it not better to use a `<header>` instead of a `<section>` tag? basically because of SEO.
Maybe you implemented it previously for a particular reason.
=> Change <section> to <header> from Header

assets/src/scss/base/_typography.scss
See [PLANET-6734](https://jira.greenpeace.org/browse/PLANET-6734)
We don't want heading links to follow standalone links colors, as you can see in the [design system](https://p4-designsystem.greenpeace.org/05f6e9516/v/0/p/266986-links/t/365cab).
**Related PR:** https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/829
You can test the new heading links on [this page](https://www-dev.greenpeace.org/test-venus/heading-links/) for example, and compare it to [the old version](https://www-dev.greenpeace.org/test-titan/51775-2/). Also make sure that our P4 Columns and Articles blocks still behave as expected too (for instance on the [homepage](https://www-dev.greenpeace.org/test-venus/)).
=> PLANET-6734 Inherit color for heading links

assets/src/scss/layout/navbar/_burger-menu.scss
Follow up on https://github.com/greenpeace/planet4-master-theme/pull/1673 and https://jira.greenpeace.org/browse/PLANET-6673
* This way the off screen element is still not visibile while the screen
size is changing. Opacity has better render performance.
I also added a transition of this opacity for better performance. It should be safe, as it will be below each element unless it has a lower z index.
You can't animate opacity if the element is `display: none`, so I had to move the overlay under all elements with `z-index`. So far this seemed reliable.
https://user-images.githubusercontent.com/7604138/164056181-1f350e07-0425-4596-bc17-6470cde32ddc.mp4
https://user-images.githubusercontent.com/7604138/164056216-f224128b-14e7-4df3-a0f1-f6f93608144d.mp4
=> Use opacity instead of visibility for better performance

templates/burger-menu.twig
Some strings are assigned by using a `"` and it's different than the other template that use `'` for translations.
=> Change quotes to burger menu 18n strings

assets/src/js/header.js, assets/src/scss/pages/_page.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6708
> The mobile tabs menu makes it impossible to see the top part of the first block.
The rule adding a padding to a page without header became irrelevant since divs now exist between section#header and div.page-content
<table>
<tr>
<td>
</td>
<td>
</td></tr></table>
- Fix padding rule to apply to page-content
- Add `passive` option to event listener (Cf. https://www.digitalocean.com/community/tutorials/js-speed-up-scroll-events)
- Fix menu glitch when scrolling up while already at the top of the page (browser sometimes does a down-and-up jump)
Check on [Tavros](https://www-dev.greenpeace.org/test-tavros/)
Locally, 
- Activate the mobile tabs menu (Planet 4 > Information Architecture)
- Get your window to mobile size
- Check a page without …
=> PLANET-6708: Fix page padding with mobile tabs menu

load-class-aliases.php, src/Activator.php, src/Role/Campaigner.php, src/Role/Reviewer.php
Ref: https://jira.greenpeace.org/browse/PLANET-6637
Add user role and capabilites
- Added _Role\Reviewer_ class
- Moved Campaigner to the `Role` namespace
Locally, run `docker-compose exec php-fpm wp p4-run-activator` to create the role.
- Create a private post/page, note the public url
- Create a user with role _Reviewer_
- Log with this user, check the private post/page
- You should be able to read the content
- You don't have access to anything else
- Content is not available when you're not logged in
=> PLANET-6637: Create a Reviewer user role

assets/src/scss/layout/_cookies-settings.scss
See [PLANET-6695](https://jira.greenpeace.org/browse/PLANET-6695)
This fix will not work everywhere, in particular not in MacOS where scroll bars are shown/hidden based on system settings (see screenshot), but it's an easy fix for at least some browsers/OS!
=> PLANET-6695 Always show scroll bar in cookies settings

src/Features/PostPageCategoryLinks.php, src/Post.php, src/Settings/Features.php, src/Settings/InformationArchitecture.php
Investigate whether it's easy to replace the weird logic of which links are shown after the tags, with a simple link to the category page itself.
Note that our category page atm still needs to get pagination and a new listing style. We should also first check the content of these pages, to be sure our new alternative is sufficient.
Since the toggle is only a few lines of code, it's easy to provide already on dev envs.
There's some things an NRO should watch out for when enabling:
* "Uncategorized" is a category, and will be shown as such. Also you need to manually unassign it after assigning an actual category.
* Some categories which didn't have a page will start getting shown. They should maybe be removed if they're not intended to show up. If they can't be removed we could maybe check …
=> Add setting to link to category directly

templates/burger-menu.twig
Show only when it has **more than 1 children**.
Doing this we will avoid to have 2 donate buttons with the same link in the same template, which is not necessary.
This fix comes from this [Slack thread](https://greenpeace.slack.com/archives/C0151L0KKNX/p1650978089768639) and this is a [real example](https://www.greenpeace.org/brasil/).
=> Modify Donate button functionality on Mobile

templates/search.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6652
> - We could re-purpose the filters to follow native taxonomies. So in the end we can have these filters:
>    "Categories" (actual categories)
>    "Tags" (actual tags) leave out for now
>    "Post Types" (eg. Stories, Publications, etc)
>    "Action Types" (eg. Petition, Event)
>    "Content Types" (WP post types. eg. pages, posts, actions, archive, document, etc)
> - Hide taxonomies and post types if there is no content
<table>
<tr>
<td><em>Master branch</em></td>
<td><em>This branch</em></td>
</tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Test on [Phobos](https://www-dev.greenpeace.org/test-phobos)
Locally, run the elastic container and the indexation
```shell
> docker-compose -f docker-compose.full.yml up -d elasticsearch
> …
```
=> PLANET-6552: Fix search filters to follow native taxonomies

src/MasterSite.php
Ref: https://jira.greenpeace.org/browse/PLANET-6671
Cookie content is filtered on the events currently logged.
Trying to log content explicitly to bypass the filter
=> PLANET-6671: Log large cookie content

src/Feature.php, src/Features/ActionPostType.php, src/Features/CloudflareDeployPurge.php, src/Features/Dev/AllowAllBlocks.php, src/Features/Dev/BetaBlocks.php, src/Features/Dev/CoreBlockPatterns.php, src/Features/Dev/DisableTagRedirectPages.php, src/Features/Dev/ListingPagePagination.php, src/Features/Dev/WPTemplateEditor.php, src/Features/DropdownMenu.php, src/Features/EngagingNetworks.php, src/Features/GdprCheckbox.php, src/Features/GoogleSheetReplacesSmartsheet.php, src/Features/ImageArchive.php, src/Features/LazyYoutubePlayer.php, src/Features/MobileTabsMenu.php, src/Features/NewDesignCountrySelector.php, src/Features/NewDesignNavigationBar.php, src/Features/PostPageCategoryLinks.php, src/Features/PurgeOnFeatureChanges.php, src/Settings/Features.php
- Avoid using "Enable" or "Activate" on titles, just on descriptions.
- Use imperative on descriptions.
- Add dev-sites memo on Features descriptions to de-clutter checkbox descriptions.
- Link to certain tickets or design system where applicable.
=> Harmonize Features titles and descriptions

templates/desktop-menu.twig, templates/navigation-bar-new.twig, templates/search-form.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6760
The search box was inadvertently moved to the wrong position when we restored it in a previous bug fix.
I'll start by moving some stuff out of the overly complex navigation bar file, which will already help preventing basic issues like this to slip through. We can merge this already to facilitate work / review of the actual fix.
It's not going to be easy because the navigation bar is now a weird mix of things that are only shown on some screens, and things shown on all screens. We can't just drop it in another place and have it work.
=> PLANET-6760 Prepare to fix search box position

assets/src/js/cookies.js, src/MasterSite.php, templates/blocks/google_tag_manager.twig
Ref: https://jira.greenpeace.org/browse/PLANET-6697
>  “Take a note that Page View event fires on the gtm.js event which fires before the consent event. That's why the first collect? hit doesn't have gcs a parameter and  gid is the same on any page. Let's try to fire event with consent before gtm.js - it should help”
> Can we send the ‘consent’ arguments before the GTM script is loaded? That should fix our last issue. 
Consent should fire before gtm starts.
Sending the consent before gtm starts requires to read cookies early. This involves some code duplication, that we try to keep minimal.
Waiting for UAT on [tavros](https://www-dev.greenpeace.org/test-tavros).
Testing there or locally, the event `defaultConsent` or `updateConsent` triggered on page load should fire before `gtm.start`
=> PLANET-6697: Fire consent before gtm starts

assets/src/scss/layout/_navbar.scss, templates/desktop-menu.twig, templates/navigation-bar-new.twig
[PLANET-6760](https://jira.greenpeace.org/browse/PLANET-6760)
After clearing the ground in https://github.com/greenpeace/planet4-master-theme/pull/1700 and https://github.com/greenpeace/planet4-master-theme/pull/1701, it's now a lot easier to address the position issue.
* By adding a second language switcher, and adjusting CSS slightly to account for new position on desktop. On mobile the new switcher is hidden.
* Seems to need no other changes as on mobile it's a fixed element.
=> PLANET-6760 Restore search bar position

assets/src/scss/layout/navbar/_burger-menu.scss
Ref: https://jira.greenpeace.org/browse/PLANET-6765
We previously missed the RTL version of left for the slide from start effect. As a result the menu was not off screen and covered part of it.
=> PLANET-6765 Fix slide in direction of mobile menu on RTL

assets/src/scss/pages/search/_search-results.scss, templates/tease-author.twig, templates/tease-search.twig, templates/tease-taxonomy-post.twig
See [PLANET-6727](https://jira.greenpeace.org/browse/PLANET-6727)
We want to apply there some of the changes that we recently made for the Articles block, mainly moving the meta information below the excerpt and removing the italic font style.
You can see the changes on the leda test instance, for example:
- [author listing pages](https://www-dev.greenpeace.org/test-leda/author/admin/)
- [search results](https://www-dev.greenpeace.org/test-leda/?s=lorem&orderby=_score)
- [post type listing pages](https://www-dev.greenpeace.org/test-leda/story/)
=> PLANET-6727 Update search results UI

src/CloudflarePurger.php
[PLANET-6770](https://jira.greenpeace.org/browse/PLANET-6770)
* We hit the rate limit and are still sending batches with http URLs.
It's unclear if it would even still send the HTTPS URL.
Tested locally by commenting out [this code](https://github.com/greenpeace/planet4-master-theme/blob/0259049bab34a55957c023b59c0c547e6d0921ff/src/CloudflarePurger.php#L32-L45), so that it also works without having the plugin setup.
=> Ensure unique HTTPS URLs get purged
